# People

Humans are by far the most dominant race in Orbis Astea. Aside from their heads being barely hairy, less muscular and bulkier than orcs, taller but dumber than dwarves, and not quite as agile as elves, humans do not excel in any physical traits over the other races.Their greatest strength, on the other hand, is their ability to adapt to seemingly any situation, or to sacrifice their brothers and sisters until the situation seems suitable. Thus, a human can learn almost anything and is not really physically limited like halflings or goblins. Also, it seems as if a certain indifference to wrong decisions of superiors, as advantageous as the lack of intellect to understand that probably really only each self is the next, as with the smaller and greedier dwarves.

This leads to a situation where humans are "up there" in every field, but are hardly among the best in any field. For the species itself, however, being average seems to pay off. They occupy the largest area, outnumber all other races, and are by far the most powerful race. The latter is hard to take advantage of, however, when you can't let your neighbor's grudge for misdeeds of several centuries rest.

## The history of the race

The history of the people is too diverse to really speak of a racial history. This is mainly due to the enormous heterogeneity between the great societies of Rah Kari, Eldria's and the Empire. For example, the Empire, Rah Kari and Eldria, refer to completely different cultures, although they belong to the same race. The Sea People are described as dreamy and starving people with mental seasickness by the inhabitants of Eldria, while the "free" people of the Skaen are no more than peasants in the freezing fields of the resident warlords.

What is known, however, is that the humans must be one of the older races. The historical records of the dwarves (or their business books), documented over a much longer period of time, point to foreign trade with humans from the beginning. Dwarven scholars, on the other hand, would point out that, on the one hand, villages with a few hundred people is not yet a civilization, and that one rarely maintains business relations with orcs or goblins, if the business partners, eat traders, rob or simply can not write anything down.

## Known cultures of the people

Thus, the inquisitive are left with only a list of "pure" human cultures, or cultures in which humans have a high percentage of the population:

-   The [Empire](#Imperial Empire)
-   The [Rah Kari](#RahKari)
-   The [Principalities of Eldria](#EldriaFaction)
-   The [Skaen](#Skaen)
-   The [Cultists of the Berma Valley](#BermaValley)
-   The [Sea Cultists](#SeaPeople)
-   The [Iron Red Desert](#IronRedDesert)
