# Mongrels

Although it happens only rarely, creatures of different races manage to produce offspring again and again. These children are rarely a reason for joy for the parents, because in most places in Orbis Astea mixed-race families are not very accepted. This is a fact that is difficult to understand, since sexual unions are widely perceived as unproblematic.
Since successful interracial impregnation is less likely than same-race impregnation, the basic number of mixed-bloods is already rather rare. This number is further reduced because many mixed-breed children die as a result of social or physical abuse either by themselves, their parents, or their fellows before they are fully grown.

Not all races are capable of siring half-breeds, for example dwarves and orcs are absolutely unable to breed with other races. Likewise, no half-breeds have been sired that would have been able to reproduce themselves - so the half-breed line always dies with the half-breed itself. Humans and elves seem to be the most compatible, as most half-elves are half-elves.