
# The Elves of Silva Nacia {#SilvaNacia}

## The story of Silva Nacia

The history of the Silva Nacia elves is marked by <font color="green">[uprooting](#uprooting)</font> as much as that of all the wood elves in Orbis Astea. What is special, however, is the status with which they emerged from these wars. Since the enslavement of the elves was abolished one more time, the forest of the faction is considered to be avoided at all costs.

## The Society of Silva Nacia

The elves of the Silva Nacia faction are considered the most arrogant wood elves living in the forests of Orbis Astea.

The highest authority of the social structure is the council. This council is composed of the oldest women of the upper social class of the tribe and occupies the envoy positions of the tribe.

* Envoys of the claws = warriors
* Envoys of the branch = eco-system care (plants, graves, fertilizers)
* Envoy of the Gaze = Scout
* Envoys of the hammer = craftsmen
* Envoy of the paws = animal husbandry
* Envoy of the Magnifying Glass = Research

When a new Envoy is appointed in Silva Nacia, it is the last duty of the old Envoys to write the history of their "reign" on the rock walls under the Sacred Tree using the Luminous Jellyfish Liquid.

Thus, the society is made up of specialized groups who devote themselves only to their field and continue to deepen their knowledge and skills there. However, these positions are not given randomly, nor is any elf born into their position. Unlike what is known from other races and their societies, the offspring of the elves are given the opportunity to get to know each field, so that they can indicate preferences for possible positions. These are also evaluated by the envoys of each realm, resulting in a match between interests and abilities in the allocation of jobs.

Being a branch envoy represents a special honor because they get to directly fulfill the demands of their gods by tending the forests and feeding the gods with the bodies of their tribe members.

## Economic Situation

### The resources of Silva Nacia

## Sociopolitical situation

### Domination system/organization

### The relations of Silva Nacia

## Military of Silva Nacia

A significant advantage, over the other wood elf tribes, are the <font color="green">[plants of the forest ](#SilvaNaciaForest)</font>.

## The religion of Silva Nacia

Like all wood elves, Silva Nacia prays to the forest gods. The special thing, however, is the great tree of life, which is located in the middle of the forest and is the center of faith. The importance of this tree for the elves of Silva Nacia is widely known, which is why there are various defense mechanisms against intruders.  

### Cult of the Dead

The cult of the dead of Silva Nacia is based on the general beliefs of the Wood Elves. Therefore, the corpses of the deceased are also processed into fertilizer here, but with the peculiarity that, depending on the importance for the tribe, the fertilizer of the corpse is used for the common forest or the tree of life, since the elves believe that especially loyal elves nourish the tree particularly well.

## The legends of Silva Nacia

One of the Wood Elves who is a great role model for the Silva Nacia is the Wood Elf Elanor Dolguruk, who fought relentlessly against the Imperial army as part of the <font color="green">[Uprooting](#Unrooting)</font>, killing more of their men than the attackers were able to capture and kill his tribe members. Through particularly sneaky approaches, sneak attacks, and the use of poison, he was able to survive long enough to keep the attackers out of the Silva Nacia Elven forest for a while.

![Elanor Dolguruk - A Drawing Transmission of the Silva Nacia Ancestors [^ErstwhileskySolaufeinPortrait]](Pictures\\Flavor\Elfen\\ElanorDolguruk_Erstwhilesky.jpg)



## Individual properties (rename for each race)


![An ancestor who internalized hatred against other race[^ElfArcherJLazarusEB]](Pictures\\Flavor\Elfen\\ElfArcher_by_JLazarusEB.jpg)





[^ErstwhileskySolaufeinPortrait]: "Solaufein Portrait" by [Erstwhilesky](https://www.deviantart.com/erstwhilesky/gallery). This portrait is available under a Creative Commons Attribution-Noncommercial-Share Alike 3.0 License.

[^ElfArcherJLazarusEB]: "Elf Archer" by [JLazarusEB](https://www.deviantart.com/jlazaruseb/art/Elf-Archer-531525398). This portrait is available under a Creative Commons Attribution-Noncommercial-No Derivative Works 3.0 License.
