
# The Sea People {#Sea People}

The Sea People are a very large, very diverse group. The name "Sea People" is more of a collective term than a faction with political goals or even any form of unity.
Most land dwellers are very skeptical of the Sea People. This is mainly because the Sea People, operating near the coasts, mostly act as pirates, extorting protection money or raiding coastal regions.
However, the Sea People do not only consist of pirates and criminals, many adventurers, explorers and traders also come from the ranks of the Sea People.
What probably surprises no one is the fact that the best sailors in the world come from the Sea People.

The Sea People feed to a large extent exclusively on the algae species Krüll, which grows on almost any material that floats too long in the sea without significant disturbances such as acceleration. This plant is abundant due to the living conditions of the sea people, and although it satisfies hunger, it lacks certain nutrients - which is why many people from the sea people suffer from deficiencies and related diseases.

One of the most important resources for the Sea People is building material for ships - mostly wood - which is used both for maintenance and for building new ships and cities. Due to the chronic shortage of materials, everything that can be reused is reused - which is why surprisingly good prices can be achieved even for material that would be considered scrap on the mainland.

## The History of the Sea People

No one knows exactly where the Sea People came from - but the recorded history is closely related to the history of the Stateships. The Stateships were discovered barely 100 years after the spread of the Rah Kari - initially by the first freedom-seeking slaves addicted to the Asb'Kartes followed years by all sorts of interested people who could muster enough manpower and courage to man these ships.

The first ship of state to be found was discovered by escaped slaves of the Rah Kari who were fleeing from the Rah Kari with stolen ships. The ship of state was relatively close to shore for a ship of state and only two days' journey from the coast. The slaves headed for it believing that it was a large island where they could hide.

But what they thought was an island quickly turned out to be a steerable and resource-rich vehicle, and thus an asset of inestimable value. They named it after their god Asb'Kartes and still control the ship to this day. With the help of

### The State Ships

### The naval war

### The fleet theft at Storm Cape

## Significant subgroups of the sea people


### Kielhaif

Kielhaif is a particularly large water city and probably the largest settlement at sea that is not a ship of state. This hodgepodge of various ships and float-equipped buildings was built directly over the largest battlefield of the naval war, which is why many treasure hunters operate from there and the trade in water-breathing potions and diving bells is more than booming.

### Arkus {#Arkus}

Arkus is the largest known stateship and is under the command of Grand Admiral "".
It is the world's largest cultivation site of the scallop algae and the largest docking and discharge site for ships.

Arkus is often referred to as the Heart of the Sea People and is a huge city consisting of the ship of state and attached water settlements, ships and debris. The city is constantly changing, making it hard to keep track of.
For the past few years, Arcus has barely moved from its location and is run by "" more like a city than a ship. As the center of maritime trade, there is hardly a captain who has not sailed or had to sail to Arkus, and so there are few goods that cannot be bought in the completely unregulated Arkus.

Although "" and his men try to maintain order and control in Arkus, there are many gangs in the winding alleys that in turn try to gain and play out power over various territories. Some of these gangs are also very successful at it.

### Rahla' Asb'Kartes

The first ship of state to be found was discovered by escaped Rah Kari slaves who were fleeing from the Rah Kari with stolen ships. The ship of state was relatively close to shore for a ship of state and only two days' journey from the coast. The slaves headed for it believing that it was a large island where they could hide.

But what they thought was an island quickly turned out to be a steerable and resource-rich vehicle, and thus an asset of inestimable value. They named it Rahla' Asb'Kartes in honor of their god and control the ship to this day.

With the help of the ship of state, the slaves were able to build a very powerful fleet, which, with the support of the Rahla' Asb'Kartes, would be quite capable of endangering or even destroying the Rah Kari fleet.
The former slaves - who call themselves the Sariva - are very aware of this and virtually hunt down all Rah Kari ships, whether warships or merchant vessels, that leave the Setra Delta under the Rah Kari flag and sail out to sea.

Due to the fact that the Sariva are willing to use any means to fight the Rah Kari, they are considered dangerous and shunned by many others. However, they see themselves as heroes of the ninth god, fighting against the evils of slavery and the deterministic structure of Rah Kari society.

Although the Sariva are more than a match for the Rah Kari at sea, they are far inferior to them on land. Many Sariva have been slaughtered trying to take Rah Kari cities or even H'Abunapthra. Nevertheless, the Sariva continue to raise armies to face the Rah Kari and bring the war to them.

Although the Sariva armies pose only a small, at best medium, threat to the Rah Kari, the economic damage caused by the difficult passability and usability of the Setra is immense, and so the Sariva have long been a thorn in the side of the Empire of the South.

### Sirkali

The Sirkali has been run by the Kristof family for generations. It has an escort fleet consisting almost entirely of longboats and is currently north of the Ska'en, where it is rumored to be hunting monsters.

![A painting of the reported monster hunts [^desmonWOOTFlowerInTheOcean]](Pictures/Flavor/Seevolk/FlowerInTheOcean_by_desmondWOOT.jpg)




The Kristof family is a family that has always been associated with piloting ships of state - a knowledge that is carefully passed down within the family. Thus, the current captain of the Sirkali - Erin Kristof - is considered the best helmsman of a ship of state in the world.

In combat, there is hardly a ship of state that is as feared as the Sirkali. The Sirkali earned this reputation in the naval war, when she engaged both the <font color="green">[Fleet of Arkus](#Arkus)</font> and the <font color="green">[Black Flame](#Black Flame)</font> in battle, severely damaging both stateships and inflicting heavy damage on the escort fleets. Thus both ships had to retreat in order not to fall victim to the artillery of the Sirkali.

> "I know you want to earn glory, but as soon as anyone sees the Sirkali approaching give me a signal immediately. This is not a fight we're going to get into again!"
>
> --- Soerf Garaug - Grand Admiral of the Black Flame in the Great War of the Sea



### Black Flame {#Black Flame}

The Black Flame is another ship of state that is centrally controlled - and therefore has a combat power that should not be underestimated. To the dislike of any constructive force on the sea, however, the Black Flame and its accompanying fleet is a pirate faction through and through.

The goal of the Black Flame is to unite all pirates under one banner. However, this does not mean a state or anything similar, but simply the option to collect a tax or some form of tribute from all pirates on the sea.
However, it is not so easy to implement such a big task. And often pirates, who have sworn tribute and obedience a few weeks before, forget their promises the second they are out of the Black Flame's reach.
Despite all this, the Black Flame is a rightly feared force on the sea, and it is better not to mess with it as a rule.
The Black Flame has a huge but very widespread fleet, controls several water cities and has several large galleons as flagships. The Black Flame fleet is probably the largest standing army of the sea nation.

In the territory of the Black Flame, there is also normal trade and commerce, but the tax - or protection money - that you have to pay to the pirates is enormous - and so most businessmen lose about half of their income to the pirates.

The leadership of the Black Flame was taken over three years ago by Grand Admiral Agrin Bost. However, there is constant internal strife over who should preside, and so there have been years when five new Grand Admirals have been chosen. Thus, Grand Admiral Bost is constantly faced with power conflicts that must be fought, and trust in his captains and subordinates is necessarily very low.


### The Tartarus

The Tartarus is a ship of state that is neither centrally controlled nor effectively manned. This ship is considered a battleground. For years, countless factions of the sea nation have tried to claim this ship for their own, and so there is a constant war for every inch. Both on the ship surrounding the sea and on the Tartarus itself, fighting is going on - and the factions are trying to grab every possible advantage.


## The company of the faction

## Economic situation

### The resources of the faction

## Sociopolitical situation

### Domination system/organization

### The relations of the fakion

## Military of the faction

## The religion of the faction

### Cult of the dead

## The legends of the sea people

There are many different legends about the Sea Peoples. Those that are heard on the mainland are very different from those that are told within all the sea peoples themselves.
The life of a pirate has something mystical for the landlubbers. Living into the day, feeling complete freedom and just doing what you want - that's how many hard-working people dream of a better life as a pirate.

### The Pirates of the Sun Triangle

Not much is known about the Pirates of the Sun Triangle. They only recently emerged after escaping slavery from a mining camp on Rouldav Island. Although they are outnumbered, it is their belief that they have the power to save the rest of the enslaved people of Rouldav.  What distinguishes the pirates of the Sun Triangle from other pirates is, above all, the tattoo of a triangle with an eye in the center, which is surrounded by a sun. All slaves of Rouldav wear this tattoo. However, those who escaped their enslavement made a slight modification by adding a ring around the triangle, which stands for the sun. This mark was chosen because the slaves of Rouldav are destined to spend the rest of their lives underground in the mining facility on the island. They have no way to feel the warmth of the sun, and so those who have managed to escape worship the sun as a metaphor for the freedom it represents to them. Because of the constant darkening of the sun, the Triangle Pirates have become accustomed to the darkness of night and experience virtually no disadvantage in fighting under these conditions.

### Loka family

Many names are known on the seas, but one name that makes every sailor envious is the name Loka. Josa Loka was the first member of the Loka family to really make a name for himself. Before Josa was born, the Loka family was only known for their sailing skills, but their skills were nothing out of the ordinary, at least not until Josa was born. Josa was a unique genius who could traverse the seas like no other. Not long after he turned 24, he commanded his own ship and crew.  The real turning point, however, came when he first encountered the blue serpent Fashit. Fashit was chasing a creature that sailors described as a horse-like creature that walked on the waves.  The horse-like creature jumped onto Josa's deck and Josa had no choice but to escape the blue snake. Until that day, many people thought that the blue snake was the ruler of the West North Sea, but that day Josa became the first person to escape its clutches. While Josa and his crew were glad that they had just made it out of this situation alive, another surprise awaited them. After the encounter, the horse creature jumped back into the water and indicated that the sailors should follow it. Out of curiosity, Josa and his crew decided to follow the creature, and eventually they were led to a yet undiscovered island. The island seemed to be the creature's home, but the most important thing was not the mythical creature, but the long-lost vault with an incredible treasure. Since that day, Josa was showered with fame and fortune, and he went on even more crazy adventures. Nevertheless, the name Loka did not disappear with Josa's death, because he had two sons who carried his legacy with them, and generation after generation the members of the Loka family prove to the world that they are among the greatest adventurers and seafarers of the sea.

### The island of the Loka family

As the name suggests, the island has belonged to the Loka family since it was discovered by Josa Loka. It is said that the Loka family keeps there all their favorite treasures and artifacts acquired during their adventures. The location of the island is therefore coveted information, but no one but the family members themselves know how to get to it. Many sailors who call themselves former crew members claim to know the way to the island, but there are as many of these impostors as there are fish in the ocean. While some say that it is a made-up island, others claim that only a real member of the Loka family can find the way to the island.


### The ocean carpenter / joiner ~

In our world there are still many myths, sagas and legends, especially related to the vastness of the ocean and the people who cross it. One of these mysteries is the man many sailors call the Ocean Carpenter. While there is no exact description of the Ocean Carpenter, many people who have seen him over the years describe him as an old man with a long white beard who wears strange clothing that has gears and cogs worked into it. The Ocean Carpenter is known for appearing on battlefields that have long since ended and collecting the parts of destroyed ships. It is said that he then incorporates these parts into his own ship, making it larger and larger as he sails to more and more forgotten battlefields. The Ocean Carpenter first appeared 244 years ago, and since then his ship has only grown larger and more incomprehensible. The ship itself is steered only by the said bearded man like a multitude of constructs. Many sailors have already tried to approach the ship, but before they could reach the ocean carpenter, they were attacked by the constructs aboard the ship. To this day, no one knows how they can control a ship of this size or why it can float at all, as it looks more like a collection of assembled battleships.

### The Island of Silver and Gold

The Island of Silver and Gold is home to the "Murakai" people, which can be loosely translated as "People of the Golden Face." It was originally inhabited by this people, but after the war with the Sea People they were exterminated, but to this day their culture and unique architectural structures can still be found. The island is famous for its gold and silver mines, which the "Murakai" people incorporated into their buildings. However, the island has not seen peaceful days for a long time, with many factions and peoples fighting over the island and its resources.

### The Murakai and "The Green Lagoon

Many people believe that the Sea People were the first people to truly rule the world's sea, but this is not the case. Northwest of the Rahkari land there is a series of islands originally inhabited by a now extinct people. This people went by the name of "Murakai". The "Murakai" people did not accomplish any outstanding technological feats compared to the Empire, but they did manage to build some of the first ships that could cross the sea. Although their ships had a rather peculiar shape, they could keep up with some ships even of our time. However, the "Murakai" people were extremely isolated, which can be seen from the fact that they never attempted to make contact with the mainland. But when they finally came into contact with another people, this was their undoing. In the year "580 B.C." the Sea People finally discovered the Island of Silver and Gold, their homeland. The Sea People quickly learned how valuable the resources on the island were, and not long after their discovery of the island, they began a war with the "Murkai" people. However, the Murakai people were not accustomed to wars and therefore did not even have a proper military. The scattered fighters posed no threat to an organized army and after only 4 months almost the entire Murakai nation was wiped out.
After the war, only one ship remained, which the captain of the "Murakai" state ship, Captain Einarm, made his personal ship and christened it "The Green Lagoon". He equipped it with the best equipment he could find as a famous captain. But after his death, the Green Lagoon changed from one owner to another. Even today, "The Green Lagoon" is a ship that any experienced captain will immediately recognize, because, in addition to its uniqueness, it brings with it many stories and even more sailor's yarn.



## Individual characteristics (rename for jew. race)

Artifacts
Farm animals
Beastman prey animals / mutations



[^desmonWOOTFlowerInTheOcean]: "Flower in the ocean" by [desmondWOOT](https://www.deviantart.com/desmondwoot/art/Flower-in-the-ocean-311247641). This image is available under a Creative Commons Attribution-Noncommercial-No Derivative Works 3.0 License.

