
# The volcano dwarfs

The first and until today best known and largest dwarf kingdom. Some dwarves may claim that their deep city may be on a par with this one, but anyone skilled in the craft knows that due to the natural advantages of the volcano only there truly masterful things are created.

## The history of the faction

![A Dwarf [^NcorvaDwarf]](Pictures/Flavor/Dwarves/dwarf_by_ncorva.jpg)







## The company of the faction

## Economic situation

Bingo

### The resources of the faction

Mountain salt

Food of the lower class Mushrooms and plants that thrive especially under low light.
Upper class Despite their settlement deep in the mountain, some dwarves love foods that thrive in sunlight, these are either imported, grown outside the city, or even grown in the mountain through clever mirror construction. In addition, some farm animals are bred and share their food with the lower class.

Home of the famous dwarven steel even if today hardly any weapons made of this material since it has become so rare, they are still the only ones to work it at all.

## Sociopolitical situation

### Ruling System/Organization

### The relations of the faction
Neutral to most peoples, they have no direct enemies, but are not particularly popular with many due to their tendency to seek financial success from everything.

Although not militarily allied, it can be assumed that the Rah Kari would support the Dwarven clan as it is the main supplier of one of their most important combat utensils, the constructs.

## Military of the faction

Today, a dwarven invasion army is hardly to be found.

The strength lies in the defense

considerable local forces in the large caravans enough to shake any local power structure.



Artifacts
Guardians?
Vigilantes ready to defend their property

## The religion of the faction

### Death cult

## The legends of the faction




## Individual properties (rename for jew. Race)

Artifacts
Dwarven steel



[^NcorvaDwarf]: "Dwarf" by [Ncorva](https://www.deviantart.com/ncorva/art/Dwarf-764102740). This artwork is available under a Creative Commons Attribution-Noncommercial-No Derivative Works 3.0 License.
