# Economy in Orbis Astea

## Economy in the empire

We begin our journey on the economy of the Empire with the most basic food and agriculture that it produces for the formidable Empire.
About 7 out of 10 people in the Empire work in tilling the meadows and fields or in woodwork. In doing so, the peasants, who often own their lands, use their knowledge of nature and what the best blacksmiths of the Empire can provide for them. Since the climate of the Empire is on average very mild and of less extreme than that of the Rahkarian or Animalian lands, it is possible for the peasants to grow a variety of crops. These include grassy crops such as wheat, barley, oats, or occasionally millet in southern Eldria. Plants from which breads are not made, among the vegetables, are onions, carrots, coal, peas, lentils and a variety of herbs.
The herbs, due to the intensity of care, were often taken over by the younger or weaker of the family.

The farmer and most of his sons, unless they found another use in the service of the emperor, worked in the field and took care of the animals. In this regard, the excellent pastures of the northern slopes of the Heaven's Peak Mountains and their valleys are highly sought after but also endangered by monsters. Typically, farmers kept chickens, pigs, a handful of cows and oxen. In addition, in the more favorable areas surrounded by more water, such as Yondalla, occasionally came geese and ducks.

To feed the emperor's soldiers, clergy, artisans, merchants, and servants, vast quantities of food are needed. The Imperial Institute for Yield Improvement regularly conducts experiments to improve agricultural yields. It was found that a special plow used in cooperation with the Muranun Farm could improve the yield of the soil by a few percentage points, whereupon it was promoted by the Empire.

In principle, Yondalla is the granary of the Empire and provides a good part of the food, as well as processed products, such as durable food. The forests off the slopes of the Night Mountains, as well as the diminishing forests around Civis Primae, are the source of the Empire's timber. Exports of wood or food hardly take place between the, justly subordinated, Eldria and the Emperor. Wood is needed in different qualities for various products, ranging from trebouchets, which can hurl boulders over 300 meters, to the milking stools of the peasants, who process the milk into cheese to then supply the loyal troops of the Emperor.

Guilds for higher quality products can be found in the larger cities of the Empire. These produce, for example, bomb bottles or bandages for injured woodworkers.
It is difficult to determine exactly which power owns which guild, as well as counting the number of members. It is estimated that 20-25% of the Empire's population serves in some guild or another. In most cases, the development of new techniques comes directly from the guilds. The advance way is this, that new developments are usually transported to the big cities and are examined there by the guilds. The inventors are fobbed off with smaller amounts and the guilds raise thereupon a monopoly on this technology. Control of the monopoly is officially the responsibility of the Empire, but is rarely strictly enforced in the case of war-unimportant goods. In most cases, the imitator, if enterprising, is simply integrated into the guild. Tough opponents of the guilds, usually called free spirits, are occasionally threatened, but the guilds always deny this.

### The most relevant guilds (income per month in reiks):
Blacksmiths (4400 reiks)
Basket weaver (2000 reiks)
Weaver (2500 reiks)
Cheese dairy (3000 reiks)
Hunting (2000 - 6000 Reiks)
Tanner (3500 Reiks)
Fisherman (3000 Reiks)
Furrier (3500 Reiks)
Carpenter (3500 Reiks)
Painter (4000 Reiks)
Miller (3000 Reiks)
Butcher (3000 Reiks)
Shoemaker (3500 Reiks)
Saddler (4000 Reiks)
Healer (4500 Reiks)
Alchemist (5000 Reiks)
Traveling Merchant (2000-7000 Reiks) [Contrary to assumptions, this guild also includes local merchants for various goods, thus this guild is called "Merchant Guild" or "Merchant Guild", this guild usually has the most accurate overview of all prices in the Empire]

### Guildless Professions:
Simple Soldier in the Empire (2800 Reiks)
Officer of the Imperial Army (4500 reiks)
Centurion of the Imperial Army (10000 reiks)
Imperial Healer (5000 Reiks)
Imperial Alchemist (6000 Reiks)
Day laborer (1200 - 1500 Reiks)
Farmer (2000- 4000 Reiks - 6000 Reiks in Yondalla)
Woodcutter (3700 Reiks)
Keeper of the Rest Yard (3000 Reiks)

Duties are officially none in the Empire. However, it is possible for road and estate owners to charge amounts for the upkeep of the roads. For this you have to pay in the guild

## Economy in Eldria

The economy in Eldria does not differ much from that of the Empire. Here, too, peasants dominate the population class with about seven-tenths. Crafts comprise about Two Tenths of the population, in addition to a somewhat smaller Blacksmith's Association since the capture by the Empire. Earnings are somewhat lower on average, though this is also reflected in a slightly lower price level of goods.
In contrast to the rest of the empire, the guilds, which in Eldria, before the empire were bulky called "vocation association society", are not so cooperative. Also, due to the discord of the principalities, the technological exchange is worse between the guilds. Thus, the achievements of the last decades came mainly from the Empire.  Bomb bottles, large cannons or treatments for various diseases originated in the Empire.

Conjectures of scholars go in the direction that the eldritch intellect is influenced by the war, the proximity to the Misty Grove, dwarven curses or "Grey Gods".  Other, less exciting reasons could be purely economic. The empire has deep pockets, and so can support development in some cases, and so can support decades of development in others. In Eldria, multi-generational research is a rarity, as money and friction with principalities usually wipes out progress when weaponsmiths, alchemists, or mad geniuses are accidentally or intentionally kicked out of cities and subsequently breathe their last on the rusty blade of a hungry bandit.

Customs in Eldria are not levied uniformly, and the practice of city customs has changed only imperceptibly, despite the presence of the Empire in Eldria, resulting in a reduction of economic life.

## Economy in the land of Rahkari

As a layman, one might think that the lands of the Rahkari are far behind the Empire in economic strength due to the vast deserts and steppes. Surprisingly, however, this is not the case, at least according to the somewhat sparse information available to scholars.
In contrast to the only weak floods that occur due to rarer floods of the Reik, the Setra and its smaller tributaries will flow west and south.  In this respect, the Setra flowing westward and into the Southern Sea, together with the southward flow of the Atum River, which flows from the Setra toward Atumpet, is the most important artery.

Both are fed by the Misty Grove and the Sky Peak Mountains and provide water year-round.  In spring, when the temperatures in the fields are still pleasant, come the floods which are carried throughout the tributaries of the two Great Rivers. The farmers use the fertile mud that is deposited and also collect part of the water in water reservoirs.

In this way, an incredible productivity and high quality of fruits are obtained on small areas. At the same time, the dry air also prevents the loss of a significant part of the harvest, as is usually the case in Eldria and in Nors.  This usually allows for 2 harvests by the summer. Over the summer months when the heat is blazing, the fields lie fallow more often, as sandstorms would otherwise quickly destroy crops.
In the fall, when the temperatures drop, the desert flour is grown, from which the cheapest food, the "desert bread" is usually made. The taste is usually slightly bitter, but nutritious.  It serves primarily as food for the slaves.

As in the other civilized areas, farmers cover a large part of the population. They belong to the path of the farmer and serve the goddess Pseptha. About 5 out of 10 people in the Rahkari kingdom are farmers. About 10-15% serve as slaves in the lowest social caste. For this, the mostly humiliating or too dirty work is performed. However, their role is diverse. Bring human excrement to the fields serve farmers, but can be used, if necessary in quarries or to dig latrines in cities. As a result, it occasionally happens that some slaves have seen more of the lands than local peasants.
The craftsman's path is the second largest group of paths next to the peasants. Every fourth serves here. Thereby most different areas fall. Thus, furriers, shoemakers and butchers are united in the path of craftsmen.

The path of the horse breeder is a special class in the realm of the Rahkari, although few people are assigned to it by birth, they earn relatively much money. The Rahkari horses are used for fast communication between the Rahkari molochs.  It is often possible for Sultanhai, when they ride themselves, to ride without interruption along the great rivers day and night.

Unlike the Empire, the Rahkari countryside has an extremely large number of people trained in healing and medicine, and probably one reason why epidemics are rare in the Molochian cities. The path has few financial resources, but enjoys the highest trust among the general population.

The cult of Meliodas dictates the price guidelines in the Rahkari kingdom. Although there are regional differences, these amount to only a fraction along the Atum and the Setra, which is also a difference to the empire, where prices fluctuate much more.

The Paths of the Rah Kari
The path of the warrior, dedicated to the worship of the god Tarkus Rah
The path of the builder, dedicated to the goddess Pseptha
The path of the craftsman - coupled with the worship of Kha'fan
The path of horse breeders with Hestua as the leading goddess
The path of healers and women - the path of Shafra
The path of artists under the patron god Amdju
The path of traders and the worship of Meliodas
The path of the guardians - the path of Unes Utet

The classes, or stages of the Rahkari:

Slaves: Heri
Beginners: Baskad
Journeymen: Ascii
Masters: Jidai
Highestborn: Sulthanai

The dissemination of new technological developments among the Rahkari is centralized. However, technological development has had little to show for the past few decades. Only the transfer and purchase of dwarven constructs indicates development.  Medically, the Rahkari are, due to the size of the cult anyway, clearly ahead of those of Eldria and the Empire. A technologically, meanwhile older speciality, are the irrigation cisterns or wells mechanically operated by constructs or livestock. Here, in favorable conditions by means of constructs of the dwarves, expensive but sustainable deep shafts can be dug, which provide year-round high-purity water for the population.

However, there is no general knowledge about the military strength, the actual wealth of the Rahkari, because this is strictly guarded by the Selikts, the highest of the paths. Estimates vary widely. Rumor has it that the Rahkari have found rich sources of silver and gold in the southern deserts. But according to the same sources, the area is also said to be cursed and hostile to humans, like the Gray Wasteland.

## Economy in Iceland

The eternal tundras of the Ice Country are inhabited mainly by the Animali. Through the trade established over the years with the Empire and some exchanged stories which imperial chroniclers wrote down, we know that an organized and controlled economy does not exist in the Empire in the strict sense.
The Animali and their tribes live mainly from hunting and do not practice any relevant agriculture, since the tundras have few usable fields.  The tribes live mainly by hunting and gathering berries and fruits and occasionally sowing seeds of useful plants. However, they do not explicitly care for the welfare of these plants.

Large plant-eating animals are usually hunted for meat, hides, and bow components. The Animali are also able to make iron weapons themselves, but the fuel they use is unknown. Scholars assume that it must be oils from nature. Like the fuel oils found in the borders of the Empire to the Ice Country in the Naphtanium Special Administrative Region.

The most valuable trade and probably the greatest economic power are found in the tribes that trade with the Empire. The tribes are able to use masterly imperial craftsmanship and at the same time purchase dried bread and various legumes such as beans at low prices. In return, the hairy trading partners usually supply meat at more favorable conditions than farmers and hunters of the Empire can offer. Trade in alchemical ingredients is also a profitable service for both sides.

A not insignificant black market exists in the sale of bomb bottles, which the Animali cannot produce themselves. However, it is believed that the moltovika and foggranatika that can be made from them help in the hunt for the abominations that the All-God has brought into this world against the blasphemers.

## Economy on the Ska'en



## Economy of the dwarves

The economy of the dwarves is completely untypical for the civilized world.  Neither can the dwarves produce their food and wood in sufficient quality, nor do they have economically central registers. As a result, the dwarves do not have a regular group of farmers or clothing manufacturers or foresters.
The largest occupational caste of the Dwarves is miners, who mine ores and gems. The second largest group is the metallurgists, who produce the famous dwarven steel and create prefabrications for dwarven constructions.  Jewelers, armorers and the food miners. Essence prospectors are dwarves who use special, unknown methods to gather essences for the creation of constructs.  These constructs, along with regular guards, are responsible for the transport and defense of the dwarven caravans.

Unlike other humanoids, dwarves have a different social structure:

The main occupational groups include, in ascending income level:
Mushroom Cultivators - The dwarves' cheapest food in their underground cities consists of a variety of different mushrooms. While these are not very tasty and shorten life if consumed as the main food source, they are significantly cheaper than imported food.
Prospectors - general miners and explorers of underground unknown passages.
Craftsmen - a diverse group of workers, some of them highly specialized, who, among other things, create constructions or ensure the statics of dwarven cities.
Guards - take on the role of military and guards
Essence Hunter - Secondary occupation, often of Upperworld Dwarves is collecting the energies of deceased humanoids. This profession is punishable in the Empire and in the land of Rahkari, exclusive of collecting slave souls.
Merchants - cunning and silver-tongued dwarves who specialize in selling various goods


There is generally no social security among the dwarves. Since even mothers sell their children for an adequate fee and parents charge them for raising their children, little social warmth can be discerned from imperial scholars. Accordingly, the entire dwarf society is bustling and opportunistic. Wherever profit can be made without losing one's head, profit is made. As a result, dwarves are generally distrustful and often harbor resentment even among themselves when someone feels monetarily disadvantaged.  Their religion, mockingly referred to as "all-money" has as its unifying points the life task of a dwarf to create as large a fortune as possible. Because this philosophy permeates dwarven societies, dwarven cities and tribes are usually among the most well-heeled humanoids.
The high financial purchasing power is also needed, however, because dwarven cities are often dependent on the food supply of the surrounding countries. As a result, there are hardly any regular farmers in the economic systems of the dwarves. Also the healer or alchemist school is weaker developed than with the Rahkari or the Imperial.
A large part of the profit, on the part of the Volcanic Dwarves in the west of the Sky Peak Mountains, is made from the sale and maintenance contracts of constructs. The Rahkari in return provide the dwarves with food and also the sale of essences for the constructs, for which the Rahkari slave caste is used.

Economically, the primary trade, after an alleged unpaid debt on the part of the Empire, is primarily with the Rahkari, where constructs and good weapons are exchanged for food wood and other goods.


## The sale of war goods:

Conditioned by the abundance of ores, it is possible in the known world adventurers, scavengers and vagabonds to take advantage of the abundance of weapons and armor to make an uncomplicated living. Before large forges under the control of the Rah-Kari and the Empire could feast on the wealth, the amount of iron was also limited. Consequently, not all kinds of vagabonds found themselves in possession of heavy iron armor and war hammers, in order to take their belongings from villages by force.
The "problem" of these vagabonds was then solved by the burgeoning cultures of the Rah-Kari and later the Empire. Suddenly, the hostile communities tried to sabotage others, and so even the worse-off populations, be they the hungry peasants after poor harvests or the slaves of the Rah-Kari, suddenly became armed.
Over the centuries, as the iron smiths improved their craftsmanship, more and more war materials were sent into the world.
This culminated in the great wars between the Rah-Kari and the Empire in a worsening of order within the empires.

This eventually resulted in the specific areas having their own reasons, laws or rites, reducing the amount of war goods.


### Reduction of war goods in the Empire and the Protectorate of Yondallas:

The Empire's solution was achieved through several paths.
The trading class, especially blacksmiths, were required to keep the amount of weapons in their storage facilities low and report any excess capacity to the Empire. Embezzlement of such weapons ownership has led to severe punishments on several occasions. Particularly unreasonable merchants have even been hanged here, though this is the exception.
On average, dealers have only small stocks of weapons in order not to exceed the limits and buy only a fraction from dubious characters, of which there are unfortunately too many in this blessed world. Mostly such quantities, which the dealers themselves can resell extremely quickly, in order to escape the controls.
In addition, blacksmiths are required to leave a seal on their weapons, usually in the form of a metal relief. If this is missing, imperial representatives can also seize weapons, since no proof of proper origin can be provided.
At the same time, thanks to an arithmetic model, the mathematician Hadrian Plebian was able to calculate how many weapons of a blacksmith should be traceable at any time. Although this rule is crude, it is another piece of the Empire's puzzle to stop looters or the hostile activities of the Rah-Kari.

From a moral point of view, it is questionable for a blacksmith if an evil looking person suddenly offers him 5 bloodstained and dented armors including hair remnants for sale.  Here, in addition to the legal obligation enforced by the Empire, it is also relevant that the dead have been properly buried, otherwise the undead in the vicinity will attack the normal population.  Consequently, a clerical representative must be commissioned to certify the proper burial of the dead. At the same time, this cleric is obliged to report the amount of weapons and armor to the Empire. This "peace obolus" thus fulfills, in addition to the moral duty, the removal of the corpses as well as the preservation of the law.

Unfortunately, the export of these weapons of good quality also attracts representatives of the black market. In doing so, these unjust and morally despicable traders try to bring them to the unstable region of Eldria, where the notorious and trained guerrilla fighters of Eldria sell their shirts for a good weapon.

As a result, the empire particularly controls the tubular borderlands toward Eldria. Trade through Silva Nacia is of limited importance anyway due to the dangerous nature of the route.

The Empire itself produces most of its weapons in the huge fortress cities, which reduces the outflow of weapons and allows for better quality control.

### The Empire's handling of war materiel in Eldria:

In Eldria, an area still riddled with guerrilla fighting and over which the Empire still defiantly claims "it has full control," the problem is of the opposite nature.
In Eldria, weapons of all kinds are in high demand and usually a basic requirement for successful guerrilla warfare. Since the smithy is somewhat under imperial control and poor quality weapons are a problem on the much larger and more poorly controlled black market, the Empire tries to put a stop to this with the "Insurrection Rule", which reduces the number of weapons available from a smith.
This insurgency rule prevents the trade of weapons between the Empire and Eldria. Thus, the insurgents in Eldria are usually left with poor quality weapons, or the support of blacksmiths who take the rap for Eldria's unnecessary independence.

### War goods in the land of the Rah-Kari:

The cult of Meliodas, which would correspond to a merchant caste, defines the price of many goods, including armaments.  Generally, this is a high premium on a sold weapon and armor. Since dwarves trade with the Rah-Kari, but iron armor is impractical in the desert, it takes a surcharge to keep the amount of weapons down and not give the slave castes too many options for resistance. As a result, merchants sell their swords for the customer at "normal" prices as in the Empire, but the blacksmith's profit is low because the "tax" is sometimes 2500 Reiks, or 5000 Rah-Kari. As a result, looters and adventurers get only low prices for their captured goods. The cult of Meliodas thereby fills its own pockets, which, however, also fall into the military use and the secret activities of the guardians. Thus, looters, or insurgents finance their own enemies.

### Dwarves and the use of too many weapons:

Dwarves, on the other hand, have a completely different mentality.  The dwarves' rule in their fortresses in the Heaven's Peak Mountains is unrestricted and not relevantly threatened by skirmishes. At the same time, the forges of the dwarves spit out more than sufficient iron, which is far superior in quality compared to the rest of the races. As a result, the iron and steel swords and armor of the other races are often melted down only to be used to create constructs that are many times more valuable and are a specialty of the Dwarven forge halls. Consequently, looters of the vastness of the Heaven's Peak Mountains could also melt down these weapons so that at least an easier transport is possible.
Since the trade routes from the dwarven fortresses are only primarily developed to the Rah-Kari, and steel simply becomes boiling hot in the blazing sun of the desert, there is little return flow of theoretically cheap steel to the Empire, which would desire it hotly. Moreover, most castes are forbidden to own more than iron weapons/armor. Despite official prohibition, however, many better-off individuals buy this right.
The flow of dwarven equipment could thus only be through the realm of Rah-Kari. Only mentally unstable traders take on the arduous journey across the Heaven's Peak Mountains. The fortresses on both sides of the Bonefield Gorge also block the way here. The last route is the Misty Grove.

### The depths of the Misty Grove:

In the Misty Grove, economic activity in general can be described as nonexistent since the Istval Rockfall. The lack of towns or fixed merchants is the problem. Another problem that inhibits the flow of weapons between Eldria and the Rah-Kari is the famous Misty Grove itself. With no infrastructure or secured routes, there is a potential profit margin, but few traders are willing to take the risk. Too often, strange creatures, madness, or simple disorientation have led to the loss of goods.


### The free sea people and their lack of forges:

As is so often the case, the greatest source of weapons and armor in the Sea People is the mainland. The notorious lack of materials and the "wood savers at sea", get the cheapest weapons only indirectly through the black market of the Rah-Kari. Here, illegal traders of the Rah-Kari take advantage of the favorable iron and steel prices of the dwarves in order to sell them to the sea people in the southern sea. However, since neither blast furnaces nor iron ore mines are very successful in the water, and the eternal battles of the sea people at the sea probably tear every third sword into the blue-black abyss of the ocean, there is a problem in the South and North Seas, despite the actual favorable price of the weapons in the South Sea. The weapons are becoming rarer and rarer from the South Sea towards the North Sea, and of poorer and poorer quality.
At the same time, the Empire has no official trade relations with the Sea People because these "pirates do not want to abide by any treaties".
Probably it is also because there is no real structure in the sea people and pirates do not necessarily have good business relations with their victims.
Consequently, there is only the black market price and what pirates get by looting salt merchants or fishing villages in the empire.
In total, the price is similar to that of the empire, but the quality and price fluctuates significantly.
