# The teaching of Zamrak


### Here everything still needs to be formatted and aligned with the other RMDs

## The Origins of Zamrak
In the early days of man, monsters and abominations caused chaos everywhere and devastated the lands of the human races.
As a result, the people of Orbis Asteas grew increasingly desperate, hoping for redemption through their prayers.
Eventually their prayers were answered and the answer was called Zamrak, a deity for hunting against the monsters.
To spread the word of Zamrak throughout Orbis Astea, the people of Orbis took up arms to become known as the Warriors of Zamrak.

In the old days, these warriors spread out across the globe, fighting every living animal they could find.

## The training of the warriors

Although they were successful at first, they eventually faced great obstacles.
Despite the blessings of their god, there was one important factor that caused the lives of many Zamrak warriors to be short-lived - their training.
Many of these people were simple folk who never received any serious training, whose priority was to protect their fellow man and push back the monsters that terrorized their land.
Therefore, some fighters formed their own groups in order to mold these ordinary citizens into real soldiers and train them.
However, the demand for this training was so high that it far exceeded the capacity of the training groups.
Although all warriors did their best to train as many citizens as possible, most of Zamrak's warriors would meet their end between the fangs of a beast capable of fighting them.
With heavy hearts, the warriors realized that their numbers were dwindling.
They developed a plan to keep the monsters at bay -- the creation of a second generation of warriors.
In order to successfully implement this plan, however, they first had to confront the lingering shadow of Ga'ar, the deity of the monsters, as it creeped like mist over the warriors' ranks, progressively destroying them.
Thus, the last soldiers decided to divide into two groups, one of which would set out for the Berma Valley and one of which would start building the second generation of warriors.
When the god Zamrak, who was well known at that time, received the news of this plan, he decided to use the power at his disposal to lead his disciples.
At that time, the Ice Land was an icy wasteland where no intelligent life could be found.
Moreover, a large number of monsters lived there, since no other race inhabited this land and would therefore have to hunt them.
Deep in the caves of the Ice Land, however, there was a forgotten artifact that dated back to the times of the Prerunners.
The few men who remained of the second group of Zamrak warriors managed to spread the word of their god one last time.
This gave Zamrak enough power to influence the sailors so that they would be stranded in the Ice Country.
There they found the artifact, which was still radiating heat because it was never turned off after the original user disappeared.
Next to the artifact, they found strange cave writings that they could not interpret properly because they did not know the language in which they were written.
These difficulties resulted in translation errors, which led the stranded sailors to interpret and understand Zamrak as a god of transformation.
This image of Zamrak and the belief in it led to Zamrak himself transforming into a god similar to the image the modern Animali have of him.
The mistranslation of the cave writings led the disciples to see the object of the artifact as a sacred symbol which they received from their god, and, because of the mistranslation, called it the "Staff of Molak." This, now sacred, staff was henceforth taken to all major battles to boost the morale of the second generation soldiers in battle. These fighters, today's Animali, did not know that this artifact was intended as a tool for terraforming the territory of the Ice Country. The Prerunners planned to use this machine to reshape the Ice Country so that they could use the land for mass construction. So it happened that the Animali took the staff of Molak when they pursued the World Worm. They managed to use the staff in their favor and kill the monster with it. However, since the Animali did not know how to use the terraformer, it was destroyed during the battle. When the first warriors of Zamrak turned their efforts towards the Bermatal, the Blood God of the monsters Ga'ar did not see this as a threat, but rather as an opportunity. Because she could exert a powerful influence over the lands chosen by Zamrak's warriors to make their last stand there, she was able to manipulate them so that in time they would become her own followers and loyal minions. Not long after their arrival, the warriors felt a strange urge to protect the land , and by extension, the monsters living there. This urge sprang from a collaboration between Ga'ar and the Goddess of Illusions, who worked together to manipulate Zamrak's disciples. The Berma Valley is known to only a few people. Those who do discover it die a quick death at the hands of the new reformed Zamrak warriors who now serve the Goddess of Monsters. These warriors henceforth surround the land of Bermatal and, like the second generation of Zamrak warriors, undergo a transformation to pay homage to their newfound goddess. In the process, they take on a more bestial form. Zamrak's form is described as a giant animalus with three constantly changing heads, his body covered in thick fur and chitinous armor. He wields the great obsidian halberd of Tomtrik and the amber bow Sitrak. Despite his changing heads, one feature always remains constant. The left eye of his middle head is always blood red. This is a scar he got in the Capef against the Frost Giant King Bolwark, whose corpse turned into Mount Surr, which can be seen in the Ice Country today. In his right hand is a silver orb, with which he can change the structure of his people and other beings in his power. Zamrak is the god of transformation and represents a symbol of the way Animali should live. He is constantly changing and transforming to ensure that he and his people never stagnate and become weak and predictable. In order for this to happen, Zamrak gave his people the ability to transform and acquire skills that are best suited to become strong and overcome any hurdles his warriors face. For this reason, the Animali consider transformation a sacred act and a secret that should always be kept, no matter the cost. The Animali believe that Zamrak communicates with his people through the Northern Lights, with each color and color combination having a specific meaning. One of the most revered Northern Lights is the White Light of Vocation. This is said to be Zamrak's way of asking for help in battle, which is to prevent another wave of monsters. During this event, the tribes of the Ice Country sacrifice the bodies of their greatest warriors in a ceremony. In addition, the Animali believe that a perfectly green northern light represents a signpost that indicates the direction in which a tribe should travel in order to experience good fortune. An amber and purple light means that a tribe has angered its god. A completely brown light means that there is a great beast that needs to be killed.

-   Artifact was considered something sacred due to translation errors!
-   As a sacred symbol, it was taken as a morale booster!
-   Animali never knew how to use it/ they never knew what it was!
-   Give the artifact a cool name, it will be a deep lore, it should just be an artifact they found!
-   The artifact, as long as it wasn't being used, was still on, and because of that it radiated heat, allowing the sailors to survive!
-   The artifact was destroyed during the battle of Nebelham!
-   The island in Nebelham, where there is a question mark, will be the place where the monster was defeated by the Animali. There will be a shrine there, built by the Animali of Nebelham.
-   God cannot speak, but can influence people!
-   God manipulated the way the people who read the text understood it
-   The first wave of warriors managed to spread the word of their god to give him enough power to manipulate the sailors to become the second wave!
-   The Goddess of Illusions helped Ga'ar manipulate the first wave. Ga'ar herself could not do that because she is not the Goddess who manipulates people!
-   By the misinterpretation of the text the god was also changed into a new/different kind of god and by this and also by the transformation of the Animali his known as such!
-   Both the first and the second generation of the warriors undertook a transformation to become stronger and more like monsters. The ritual that the first generation undertook was influenced by the Goddess of Illusions, which meant that Ga'ar would be able to manipulate them to her will!
