# The teaching of the All God


## Structure of the teaching of Allgod

### Preserver of Silence or Pontifex Silens

The Keeper of Silence is always male. He is elected for life. All keepers of the silence courts, colloquially priests or parish priests, are eligible to vote. The election actually takes place in the Citadel of Earth below the Monument of Men (west of Civis Primae). For several decades, where the Citadel was damaged by an earthquake, the election has been held in the Inn of the Allgod in Civis Primae. Depending on the state of the Empire, more or less Religious Entities of the Doctrine of Allgod come to participate in the election.  The Concordat of 32 n. Riga ("Guardian Concordat of Nors") has narrowed the real possibility of election to barely two dozen clergymen, who can only appoint a replacement for themselves. This group is called the Guardians of the Seal Stone. In the event of their demise or expulsion by an Overwhelming Majority

### Guardians of the Seal Stone
24 mandatory male members of the Doctrine of the All-God who, along with the Keeper of the Silence, hold the second highest responsibility and power in the faith community. The Guardians of the Seal Stone can only appoint their own successors and elect the Keeper of the Silence. An increase or decrease of the 24 members is forbidden since the Concordat of 32.n Riga "Guardian Concordat of Nors". The Guardians of the Seal Stone, unlike other faith communities, are highly trained in hand-to-hand combat, and their ceremonial garb is gold-embellished heavy armor.

### Keepers of the Resting Places - Priests of the Doctrine of the All-God
The Keepers of the Resting Places are referred to by the general population as "padres" or western regions of the Empire as "priests".  Their task, besides the obligatory physical exercises and ensuring the fragment stones, is to take care of the spiritual well-being and piety of the village or community. They are obliged not to take wives and must train the guards of the resting places. Furthermore, the book "The Life of the Righteous Keepers of the Resting Places" describes in it also the obligation to provide protection to the community in difficult times, as well as to take care paternally of the mostly young and strong keepers of the resting places.

### Guardians of the resting places
Mostly young men who spend their time doing physical exercises as well as burying the deceased and reading the teachings of the All-God. In addition to the possibility of advancing to the position of guardian of the resting places, provided that the training in Civis Primae, which is called "The Inner Contemplation", is completed. However, the election can also be made by the Guardians of the Seal Stone and, according to rumors, can also be achieved with generous donations to the community.


### The Inquisition
Is elected from the ranks of the Keepers and Guardians of the Resting Places (Fathers/Pastors). These are the most pious and sometimes dogmatic representatives of the faith community. Inquisitors are not necessarily male. They receive training in the doctrines of the Forbidden Gods and other terrorists considered heretical (blood cults) and learn to recognize and combat them. Inquistors enjoy great legal liberties and can sometimes approach the now weakened nobility and imprison them with sometimes thin evidence.  Executions or hearings by the guardians of the sealstone are rare, however, and reserved for the approximately 300 high inquistors.
The Inqusition maintains its own information services, as well as logistics centers, and is the strongest military grouping in the Empire, along with the Imperial Army.


## The symbols of the community
The most important symbol is the representation of the seal stone in different colors as well as that of a shovel shining in the sun.
The representation of the seal stone is mostly seen on the colored window panes in the towers of the ecclesias.  The symbol of the shining shovel is found on the robes and armor of the Keepers and Guardians of the Courts of Rest.  However, the Keepers of the Courts of Rest also display the insignia of the Seal Stone on their backs.



## Relics
The most important relic is the extremely heavy seal stone. This is an ancient relic that dates back to the founding of the denomination and has been stored in various cities in the current empire. The location is usually in the immediate vicinity of the Keeper of Silence or the Pontifex Silens.

The Hammer of the Damned is another relic. A hammer with a handle made of dwarven steel and the striking head made of a piece of the Insignia Stone. The original bearer of this weapon was Pontifex Silens "Augur of Untheide". According to the reports, in 376 b. Riga he smashed the skull of 1000 undead and buried them with his shovel "Ewig' Ruh'" and blessed their graves. However, the shovel "Ewig' Ruh'" has been lost since the grinding of Riga.

The body of "Silens Magnifans": a wrapped pile of bones of Silens Magnifans called the Keeper of Silence.  His unnaturally long life (It is said that he was killed by a burning house in 127 winters) and the burning of his body gave him an eternal memory. The bones are stored in the citadel of the earth.  Since the destruction of the latter, however, they lie in the Citadel of Light in Civis Primae and are a tourist attraction. Believers hope for healing of their parents or diseases.


## Origins of the Faith Community
The origins of the faith community are highly disputed.  Few records of the time, which are stored in the libraries of Athumpet, suggest that the founding of the religion was done by a murderer.
According to the Rahkari, before the founding of the Doctrine of the All-God, corpses were disposed of by the elves to become fertilizer for their forests. An unknown person, who is called "The Madman of the Reik" in the records, is said to have tried to hide a murder and buried it deep in the ground. Afterwards he put a stone of the rock face on this grave below a rock fall.  The corpse did not rise again to the life. At the latest from here on, the historian only talks about the "white noses" and disparages their unshavenness, boniness and their stench.
"The lunatic of the Reik" let himself be called a prophet and promised the "dead the eternal rest to make possible". In doing so, he buried these corpses in the same place, but less deeply.
The "white-skinned fleabaggers" believed him.  The burial method was successful. According to the reports of the Rahkari, this only caused disinterest, because their burial rites were already established.
In the following centuries, alleged transcripts were finally found, which point to a similar story. These stories also mention a rockfall and the first "eternal resting place". After a rockfall, a huge boulder of the cliff was mentioned as a religious symbol, which the prophet said "should enable all people of the teachings of the All-God to bury and mourn their loved ones in peace".

Who exactly this "prophet" was is not clear. The representatives of the Doctrine of God deny that their prophet was a murderer and punish all those who do so under the aspects of heresy. The official line of the rock fall and the creation of the Insignia Stone is presented as a "gift" from Heaven, where The All-God was concerned about the welfare of the believers.
The insignia stone, after being significantly reduced in size and fragments were cut off, finally moved to the citadel of the Earth under the Monument of Men, west of Civis Primae.

## Handling of the faith community

Theft or "moving" of insignia stones is subject to severe penalties under "disturbing the peace of the dead".
To contradict the keepers of the silence in matters of faith is usually punished as heresy.

Members of the faith community must pay a "shovel debt" or "silent debt" as soon as they are born or enter the community. This money is used to manage the community's properties and to provide members with the Allgod Drink.
If the shovel debt cannot be paid, the member loses their family name and the inheritance passes to the Pontifex Silens/ Keeper of Silence. Provided repentance is shown or service to the community, it is possible for the Keeper of the Silence, or by proxy the Guardians of the Seal Stone, to return this inheritance and name back to the Faith member.
Regardless of the rights of the "Doctrine of All-God" a settlement of the debt usually leads to a strong social ostracism of this person or even the expulsion from the community. Lynch actions are reported here over all the centuries again and again.



## Attitude toward other religions

### Religion and Customs of the Wood Elves
The religion of the Wood Elves, even though it may be an exaggeration to call it a religious community, partly contradicts the teachings of the All-God.
For example, the burial of the dead in the manner of the Wood Elves, i.e. the use of the corpses for fertilizer, is not appreciated and is usually punished with fines and flogging.

The goal that the whole world should be covered with forest and the public advocacy of this plan, on the other hand, cannot be punished. Here reference is made to the imperial decree of 344 B.C. before Riga, according to which foresters could then also be punished. Thus followed just 344 before Riga the exception from the blasphemy decree. Rituals related to this topic, which due to the inconsistency of these, can be punished with penalties or fines. The juristication of these, however, is usually incumbent on the local keeper of the resting places.


## Curiosities:
### Crusade against the Devil:
The Inquisition, with military support from the Imperial Army, launched a systematic destruction of all cults and places heretical in nature. The crusade ended in ignominy, however, when an army of undead near Steingarten massively reduced the number of participants.
Other crusades against the devil have occurred on a much smaller scale again and again over the centuries, but never with such a large participation of the Imperial Army. Mostly, representatives of blood cults and followers of heretical gods (popularly known as blood gods) were hunted down and hanged or burned and then buried.


### Enabling the Allgottstrunk:
The journey which enables the terminally ill or dying to bid a dignified farewell to the carnal world. Here, pain-relieving substances are used to make life bearable. The demise of these dying takes place at the latest in 1 to 1.5 weeks.

#### Ekklesia:
Prayer building with adjoining cemetery as well as the dwellings and herb gardens stored in the building for the keepers and guardians of the resting places. Usually offer smaller libraries and study rooms for pilgrims.

#### High Inquistor:
Like an Inquistor only with the legal basis to execute or hang suspected persons. There are only just under 300 High Inquisitors in the entire Empire, according to official figures.

#### Fragment Stones:
Stones which, like the Seal Stone in Civis Primae, represent a sacred symbol of the teachings of the All-God and, according to folklore, ensure that the dead find their rest and do not return.

#### Seal Stone:
Stone weighing several oxen, most sacred reliq of the teaching of the All God.  Glows faintly bluish at night when sprinkled with holy water. It is stored in or near the chamber of the Pontifex Silens.


#### The Inn of the All-God:
The Inn of the All-God is the second largest building in Civis Primae and, in addition to a huge library, has a roof made of copper tiles where the symbol of the teachings of the All-God is formed with gold tiles.

#### Inner Retreat:
Training of the guardians of the resting places to become full-fledged keepers of the resting places. In the vernacular, this is usually referred to as "patermaking". The training lasts about 8 years and ends with a solemn ceremony as well as the solemn presentation of a heavy armor. The training includes, in addition to learning and understanding the most important book "The Doctrine of the Allgod", a training of several weeks in the striking down of Awakened as well as the treatment of the diseases which they cause by bites. Once the training or "calling" to the Inner Retreat takes place, these people can no longer be called to the military of the Empire.









### OLD/ OBSOLETE
If scholars are to be believed, the worship of the Allgod originated in the more primitive times of the Heartland and long before the formation of the Empire. Some sources even report that the friendship and cultural similarity between Nors and the Heartland can be explained in large part by missionaries of the Ekklesia of the All-God.

The Doctrine of Allgod is - after the Rah Kas - the largest faith community in Orbis Astea and is ubiquitous in the Empire, but also more prevalent in northern Eldira.

## Organization {#Ekklesia}

The Ekklesia has existed longer than the Empire itself. Already when the relations between Nors and the Heartland began, the Ekklesiarchy started missions, which in the end led to a monotheistic position of the faith of the Allgod.

The Ecclesia also manages to be politically very relevant. Its chairman - the Pontifex Maximus - is considered the second most influential person in the entire Empire. The guiding opinions of the Ekklesia partially direct day-to-day politics and have often brought about social changes. Due to its great political control, the Ecclesia managed to have other faiths banned in the Empire and to be granted its own armed force with far-reaching authorizations.

The Ekklesia is responsible for burying the dead and spreading and preserving the faith. Its priests perform blessings, confessions and masses.

Furthermore, the Ekklesia funds many research teams that are leaders in all scientific fields - but especially in the study of the <font color="green">[blood gods](#blood cult)</font>.

Each year, each church takes in a number of young men and women - so-called god servants - and trains them to become priests, inquisitors, or - in most cases -



## Symbolism

Not a follower of these witchy Rah Kari who can only delay the process of revival because their gods are not true and they must surely use blasphemous witchcraft

and of course the burning helps what is not there can not resurrect a child could have recognized this connection a joke for the so highly praised intelligence of the dwarves

they should have realized that only he the all god gives us the possibility to give peace to friends and family through the simple act of blessed burial

He alone is powerful to do this

This one hears the word of the one

It is said that he began to bury corpses in deep holes because he did not trust the words, but when they did not come up again, the word spread like wildfire and the graves became more and more shallow without a revenant appearing.

the following grew and he the prophet preached that there can be only one. At one point he had convinced the people to break the pact with the elves and stopped the delivery of their dead

Soon followed the subjugation of the elven tribes that had been so faithful to the pact and eliminated the undead because they did not believe in the true word

Many died and even more were sent into slavery to have the words of the one burned into their bodies

it is said that to this day the still wild elf tribes bear it to the people and remind them of the old pact in a macabre way by throwing corpses into wells to poison the water

(and to show the poor villagers the torment of the undead from which only they can protect them.

But this is not true so we see it day in and day out)



