# The teaching of Rah' Kas

Although the Rah' Kas is listed here under religions, it is more than just that. The Rah' Kas is a form of government and society lived in southern Astea - by the <font color="green">[Rah' Kari](#RahKari)</font> named after it. The Rah' Kas is a rigid as well as strict set of rules and assigns people already at their birth an area - the so-called cult - within which a person is allowed to perform cult-conforming activities throughout his life and can also rise within the organization of the cult.

Important in considering the cults is the role of women, who are brought into their own cult at birth and raised there away from their parents. This special cult is the cult of Shafra - the healer cult.

In general, it is impossible to say where the Rah' Kas begins and the actual politics and history of the <font color="green">[Rah' Kari](#RahKari)</font> begins, which is why interested people are recommended to study both entities holistically.

## Organization {#HighCults}

The organization of the Rah' Kas can be described more as the organization of the individual cults, although there is the high council of cult leaders - the Council of the Rah' Kari - but most of the administration is handled in the individual cults. Since this article is not about politics, but about religious practice, it is mainly about this.

In the Rah' Kas there are eight legitimate cults or paths, these are:

-   The Path of the Warrior, with the worship of the god Tarkus Rah
-   The path of the builder, dedicated to the goddess Pseptha
-   The path of the craftsman - coupled with the worship of Kha'fan
-   The path of horse breeders with Hestua as the leading goddess
-   The path of healers and women - the path of Shafra
-   The path of artists under the patron god Amdju
-   The path of traders and the worship of Meliodas
-   The path of the guardians - the path of Unes Utet

Each of these paths has its own administration and represents, so to speak, a separate state in the state of Rah' Kari. The cults have their own punishments and laws - so an action that is legal in one cult can lead to enslavement or even the death penalty in another cult. For example, the warrior cult is highly regulated, while the guardian cult has hardly any rules. In addition to their own laws and administrations, the sizes of the cults also vary - the largest cult is probably the healer cult, followed by the craftsmen and farmers. The cult of the guardians and the artists are the smallest cults.

As with their own states, there are also plenty of examples of certain cults having disputes among themselves. Thus, one of the leading theories for why the Rah' Kari did not play a role in global politics for a long time is that various cults had power struggles among themselves. It was not until the external threat of the Empire and the Path of the Ninth that unity was restored among the cults.

### Head

Each cult has its high priest - the Selkite - who leads it both religiously and politically. The assembly of all Selkites then also leads the nation of Rah' Kari, which is a federation of the various cults.

While on paper all cults are equally important and their Selkites have equal say, in reality there are cults that are significantly more influential than others. The most powerful cults are the cult of Pseptha - the peasant cult, the cult of Shafra - the healer and women's cult, and the most powerful cult, the cult of Unas Utet. These three cults are the political heavyweights of the Rah' Kari - but not necessarily the cults that carry the most religious weight.

All cults are hierarchically structured, and promotion is only possible through promotion from the top - a tradition that has strongly favored the development of rope networks in some cults.

## History

The history and mythology of the Rah' Kas coincides with the <font color="green">[History of Rah' Kari](#RahKari)</font>

## Beliefs

## Commandments and prohibitions

## Important places

## Rites

### Cult of the dead

## Symbolism
