# The teaching of the light of Darcy

The Church of Darcy - often called the Church of Light - is the most influential religion in northern and central Eldria. The Church of Darcy and the Principality of Darcy are inseparable and both entities are also led by the "Advocate of Light".

However, the Church of Darcy is more than just a church, Darcy is a power apparatus and both because of the production of riddin oil and its distribution, as well as from the diplomatic power that the influence over believing and educating nobles gives a factor in the Eldrian patchwork that should not be underestimated

## Organization {#ChurchDarcy}

The Church of Darcy is organized hierarchically. Unlike classical Eldrian society, however, one does not have to be a member of the nobility to rise in Darcy. Each Eldrian region has various churches and their leaders - the priests and a high priest, the highest position one can reach in the church in Darcy.

Any person educated in Darcy can - if there is a recommendation from his teachers - start an assistancy at a church - that is, help the priest with ceremonies, anointings and other religious festivities. After several years of assistantship, he may - if the priest and the local high priest allow it - become a priest himself.
After at least 10 years in the priesthood, a priest may advance to high priest. For this to happen, however, the current high priest must die or resign. The new high priest is then elected by all the priests in the region and proposed to the council of high priests, each of whom has a veto.  
The high priests consult in a body called the Council of High Priests, which is chaired by the so-called Advocate of Light.

Since it is relatively normal for noble families of all major principalities to have at least one child educated in Darcy - usually the second born - there are also some nobles among the priests. And although actually everyone - even bourgeois - can become a high priest, nobles are overrepresented in these positions. On the one hand, this is due to the fact that bribery, worldly power and acquaintances play a major role, and on the other hand, many people in Eldria simply consider the nobility to be "naturally more exalted".

### Head

If one serves as a High Priest of the Church for at least 10 more years, one can be elected "Advocate of Light" by the Council of High Priests. The Advocate's term is 10 years, at which time the High Priest is additionally given the title of Advocate and assumes leadership over Darcy's principality and church - though most often the High Priest is elected Advocate by Darcy himself. A High Priest may be elected Advocate any number of times.


## History

The Church of Darcy is a relatively young religion, founded and introduced by the enlightened Lord James Wilton of Darcy, who founded the church in the form it exists today in the year 12 before Riga. According to legend, Lord Wilton's Ordal appeared to him and explained the way of light - whereupon Lord Wilton used all his life and the resources of his principality to found and advance the Church of Darcy. At that time, however, the Principality and the Church were still two separate entities, and the Advocate of Light was not the same person as the Prince of Darcy.

The teachings of the Church quickly spread throughout Eldria and soon the Church of Darcy became a diplomatically powerful faction through trade in Riddin oil and the founding of the School of Darcy. However, there was soon strife between the Church's apparatus, who continued to demand resources from the principality, and Lord Wilton's grandson - Henry Wilton, the then reigning Prince of Darcy, who did not share his grandfather's piety.
After several years of dispute between the Church of Darcy and the Principality of Darcy, it came to the so-called light punishment. After another dispute escalated between the Advocate of Light and the Prince of Darcy over the execution of a prisoner, the young Lord Wilton had the dignitaries of the Church arrested and expelled from the Principality of Darcy.
However, the young Lord Wilton had not reckoned with the now existing power of the church. The Advocate of Light quickly managed to unite the principalities of Austen, Calvert, Hasting and Aerlham behind him and move towards Darcy. Although Ghent sent troops to assist, Darcy was quickly overrun by the alliance of principalities. The young Lord Wilton was sentenced to death and the Principality of Darcy was handed over to the Church, which from then on merged the status of Prince with that of Advocate of Light.

## Beliefs

According to the doctrine of the Church of Darcy, man consists of a fleshly shell and the soul - the very seat of existence. The eternal soul is the personality of man, while the perishable body is the carrier of memories and learning experiences.
In Darcy's belief, earthly existence is equivalent to hell. Through good deeds that are in accordance with religion and moral values, there is the possibility of reaching the immaterial afterlife - paradise, which is called the world of light. The alternative to this is rebirth on the earthly world - that is, reliving hell.
In theory, each person can be reborn so many times until he is worthy of paradise, however, after the demise of the <font color="green">[ceremony of liberation](#ZeremonieDerBefreiung)</font> - so the equivalent of the funeral - has to take place. If this does not take place and the person becomes an Awakened One, the soul of the person is forever trapped in hell and can never reach paradise. It can only be destroyed by killing the awakened one - an act that is seen as a sad mercy. Through liberation, the soul can escape the body after death, and this prevents the body from being awakened - since the soul is no longer in the body. Instead, the soul can be born with a new body or escape to paradise - should its Ordal deem it worthy.
Darcy's teaching speaks of an individual Ordal that accompanies each person throughout his or her life. This ordal decides the happiness or unhappiness that befalls a person in life. A priest of Darcy assigns this ordal to the anointed person during a ceremony called "anointing" - whoever dies without an assigned ordal will be reborn.

## Commandments and prohibitions

> "If you are good and honorable, do not lie and are selflessly there for other believers, spread the faith, attend mass and do not say bad words, your Ordal will always be favorable to you and happiness will follow you
>
> --- Excerpt from a sermon for children

## Important places

## Rites

In the church of Darcy there are ordinary and extraordinary rites. The ordinary ones include mainly the masses and sermons of the priests, the extraordinary rites are the anointing and the deliverance.

### Anointing

The rite of anointing is the second most important in the religion of Darcy, since it is here that a believer becomes his Ordal, who watches over and judges one from that moment on.

It must be performed by a priest of Darcy. It is usually performed shortly after a person's birth, but can be performed on anyone and represents joining the Church of Darcy.

During the anointing, the symbol of light is drawn with charcoal on the forehead of the anointed, which was then washed away with Riddin oil. This completes the anointing and the person thus belongs to the Church of Darcy and has been assigned an Ordal. This gives the person a chance to reach the light world.

### Liberation {#CeremonyOfLiberation}

Liberation refers to the equivalent of burial in the Empire or the final journey in the Rah' Kas. With the help of this ritual, revival is prevented by releasing the soul and allowing it to be reborn. Liberation is by far the most important ritual in Darcy's teachings - as it ensures that the soul is not stuck on the earthly world.
During the liberation, consecrated Riddin oil in the form of the light symbol is applied to the forehead of the dead person, asking his Ordal to judge him justly.

In return for the anointing, anyone can perform the deliverance with Riddin oil and the citation of the correct prayer, no priest of the Light of Darcy is needed.

> "I call you, unknown Ordal, judge righteously and guide this soul to the world of light or back to the earthly being."
>
> --- the prayer of liberation

The rite of liberation is the only possibility to come into the world of light, if someone was buried according to the rites of other gods - and thus does not arise as an awakened one - according to Darcy's teaching he will be reborn normally and has no chance to come into the world of light.

## Symbolism

The main symbol - and also the only relevant symbol - of the Church of Darcy is the So-called Light Symbol, which also adorns the coat of arms of the Principality of Darcy. The symbol distinguishes churches, believers and pilgrims, and many wear it as a necklace around their necks.
