---
editor_options:
  markdown:
    wrap: sentence
---

# The awakened

As the one time one, every child on Orbis knows that a dead person does not stay peaceful for a long time, usually this peace of a dead person lasts 3 to 4 days until he again of inexplicable thirst for action throws himself on everything humanoid and that without any care for the old body and the newly gained life, which is not surprising since these usually do not have any personality or mind but act purely instinctively.
They also lose some of the strength they had in life.

This can be delayed or prevented entirely by various folk burial rites.
Thus, the dead retain their peace.

Awakened are often found in small to larger groups, even if some undead strolls alone through the world so you should always assume that if you see an undead, others can not be far away.

This reanimation is triggered by a virus that every inhabitant carries since birth, but only after the death of the host in action.
The concentration point of the virus is located in the head, from there it also controls the host body.
This allows the easy elimination of Awakened by destroying the head.
if the head is too badly damaged before the awakening, the virus is forced to alternative and mutates the host body.
These mutations make Awakened significantly more dangerous, as they increase the strength of the Awakened while its only weak point, the head, disappears.

### Combat Behavior

Which target is attacked by the logical can simply be rolled.

Combat: Grapple, Bite, Weapon

Scwache Gließmaßen / Head, Massive Body

No blocking

Weaknesses: Fire (can't extinguish themselves), Holy Water, Light of the Allgod

### Subclasses of the Awakened

In addition to these Normal and Mutated Awakened, there are also several subclasses to be wary of.

These subclasses follow a hierarchy, which is reflected in how many normal Awakened are usually in their entourage.
It should be noted that no Mutated Awakened can be found in these retinues.

The first group of special classes is distinguished from the other Awakened by one fact.
Because even after the demise, they have retained some limited congnitive abilities.
Although what is left seems to differ from person to person.

#### Headless / Mutated Awakened

The creation of these Awakened is considered a capital crime due to the difficulty of eliminating them.
Due to the mutation, the skin of the affected hardens and becomes a natural armor, the arms become dangerous weapons and the head replaces itself with a long worm with blade-like tips spread along its length.
The weak point of the Awakened is still the head, but it is now much more stable and can additionally retract into the torso.
The head can now only be targeted if either the protective chest plate is destroyed beforehand or the head is lured by a person to wrap around it and another person attacks the exposed head.

#### Awakened Knight:

Lime cool may not be this opponent's forte but he is not an opponent you want to face in combat, so he still retains some fighting skills from his former life.
So it is possible for this heavily armored creature to block.
It seems that this reaction is deeply ingrained.
Usually Awakened Knights are accompanied by 3-8 normal Awakened.
In rare cases, they are even accompanied by their trusty undead steed.
Animating a mount seems to be a special ability of Awakened Knights that is not found in any other sub-class.

#### Awakened Alamers:

These pesky contemporaries, are able to summon normal awakened to their aid upon enemy contact.
The number of undead that appear varies greatly and can also occur in waves, which suggests shutting the screamer up as quickly as possible, secretly murdering them before they can call for help, or bypassing them altogether.

#### Awakened Bait:

The cognitive abilities of this devious mostly female specimen allow it to act as a decoy, calling loudly and miserably for help.
As a rule, a handful of awakened people stand around the bait in ambush.
As much as it may seem at first glance that one is facing an intelligent Awakened, this impression quickly evaporates at second glance.
Because the cognitive abilities usually only extend to exactly the sentence of the call for help.

### Chosen Awakened:

These powerful as well as rare Awakened are capable of large amounts of

#### deceivers:

This sly creature specializes in deception, covert movement and usually leads a large group of Awakened.
Due to their high congnitive abilities, they behave strategically and can also hold normal conversations without any problems.
Often they are part of the group or army fighting against the undead and the latter are completely unaware of the enemy in their midst.

#### Bold:

Unlike the Deceiver, this Colossus prefers to command his army from the front.
Heavily armored and equipped with the strength beyond any human, this is not an opponent you want to find yourself in front of in the thick of it.
As difficult as it may be to kill him, it is important, because with his death ends the strategic approach of his army.

### Awakened Champion:

Like an apocalysis, this force of nature moves through the land with hundreds to thousands of Awakened.
With an army that is quickly built and just as easily renewed, these chosen by their blood god roam the world spreading death.
Death is their friend as much as they bring it to everyone else as little as they want to welcome the champions in their arms.
These beings are immortal and can only be defeated by dismembering their bodies and sealing these parts in all directions with the rites of the Allgod.
The religion of the Allgod is especially important because in this religion the dead are only sealed and no final solution is found.
If the individual parts are brought together again, the champion resurrects.

There are rumors that control over some awakened by using limbs of a champion (finger etc) is possible.
Each application costs sanity specifically each recut - 5, while between 3 and 5 awakened can follow a person at the same time.

The Blood Goddess allows this ability, as each application increases her influence, allowing her to have the parts of her champion collected for his resurrection by her Insane followers.
