# The heartland

! map of the heartland](Pictures/Maps/Herzland.jpg)

## Villages of the region

#### **Civis Primae** {.unnumbered}

Capital of the Heartland and the Empire. Bureaucratic, military and financial heart of the Empire. Seat of the emperor with the Villam autem Caesar. Headquarters of the ecclesia. Extreme disparity of wealth. Lower city as the largest inhabited cavern system. Seat of several gangs. Lower Town is characterized by the black market and offers all the dark sides of human civilization. Civis Primae has about 300 churches and temples of the Ekklesia. In the north of the city is the largest known leather tannery.

Population: about 2.000.000

#### **Riga** {.unnumbered}

Largest city on the Reiksee, lost much of its importance after the <font color="green">[Schleifung Rigas](#SchleifungRiga)</font> . Famous for competition arenas and black market businesses. Origin of many of the best soldiers of the Empire.

Population: about 30,000

#### **Wagenfurt** {.unnumbered}

Customs, trade, lumber industry, armament manufacture

Unofficially run entirely by a dwarf. Massively corrupt. Officially, the armory in Wagenfurt is under Civis-Primae.

Population: 7,000

#### **Agiontum** {.unnumbered}

Headquarters of the noble family Thrax. Largest explosives manufactory. Imperial steel plate armor manufactory. Extremely wealthy city. Retained autonomy rights for the most part. Owns its own army of 3000 men. Second largest seat of the Ekklesia. Main residence of the head of the ecclesia (Pontifex Maximus). Largely free of corruption. Headquarters of the Inqusitatore scholae.

Population: about 170,000

#### **Farriontum** {.unnumbered}

Metal manufactory for muskets and large cannon manufactory and heavy armor - heavily guarded with imperial fortress.

Population: 11,000

#### **Meantum** {.unnumbered}

Mine and settlement with the highest yielding copper and iron mines in the Heartland. Supply the purest copper and ore deposits. Supply about 10% of all the iron and copper ore in the Empire. Large pitch mines in the adjacent forest/swamp.

Largely metalworking and logging for further processing in Farriontum

Population: 9800

#### **Arstior-Farm** {.unnumbered}

Cultivation wheat, barley and grazing livestock

Population: 1300

#### **Licinius Farm** {.unnumbered}

Growing wheat, barley and grazing livestock. Largest cheese dairy in the Heartland.

Recently developed farm in honor of Emperor Licinius Proximus

Population: 1800

#### **Castellum-Reik** {.unnumbered}

Largest military camp of the empire. The whole city is a military one. Outside the wall lives the general population with an extensive red light milieu which is a thorn in the side of representatives of the Allgod.

Population: 123,000

#### **Hadrius-Farm** {.unnumbered}

Wheat, barley, hops, grazing animals, poultry. Military organized agriculture which is directly responsible for the supply of the military camp Castellum-Reik.

Population: 23,000

#### **Minor-Civis** {.unnumbered}

Famous for woven fabrics, carpentry and leatherworking, and the crossbowmen's guild. Most influential jeweler's guild. Seat of the alchemist family Chantius - largest potion maker in the service of the Emperor, away from Civis Primae. Popular black market hub.

Population: 64,000

#### **Lirundum** {.unnumbered}

Trade, healing springs and bathhouses

Lirundum is considered a significant healing place where hot thermal waters and in the adjacent forests grow some rarer medicinal plants. Its location as a link between Vaichatum, Orantium and Minor-Civis depends on the collected duties of the products. The extensive thermal baths are accessible to all classes of the population.

Population: 10000

#### **Orantium** {.unnumbered}

Wood processing industry. Hunting rights for the lands between Grimgrod and Orantium. Export of durable meat and sausage. Trade with Grimgrod - gems, meat, beer, weapons and strong potions.

Population: 11.000

#### **Vaichatum** {.unnumbered}

Largest timber producer south of the Reik. Extensive herbs and plant gardens to supply Civis Primae and the army. Family seat of the Ancira noble family. Fishing monopoly of the Vaichatum Lake. Would formerly over the now empty gold mines of the Vaichberg Empire and owed its influence to the Ancira family. The diverse microclimates between the Reik Lake of Vaichatum, the adjacent forest of the swamp and the plain bring floristic richness.

Prohibition of plant collecting in administrative areas of Vaichatum.

University publica in areas of wood craft, alchemy, stone craft and building.

Population: 89.000

#### **Vaichatum Farm** {.unnumbered}

The farm and mountain quarry which stands in the administrative area of Vaichatum. Fish, barley, marble, wheat, herbal farm with alchemically valuable plants. Breeding of horses.

Population: 6400

#### **Thraxium** {.unnumbered}

Retreat of the noble Thrax family. Lives on the business relations of the Thrax families and vyrnwood mining (non-combustible extremely stable wood for special uses).

Population: 1500

#### **Meapontenum** {.unnumbered}

Fishing, minor ore mining, most significant route between Civis-Primae and Yondalla, black market and hospitality.

Population: 8500

#### **Viscutum** {.unnumbered}

Fishing, lumbering, wine production, woven fabrics, siege weapons.

In Viscutum, another bridge over the Reik River has been under construction for about 60 years to better connect Castellum-Reik to the northern half of the Empire with the Protectorate in Yondalla. The bridge will be completed in the course of the next few years.

Population: 13,000 (+ 1000 bridge builders)

#### **Piscaim Farm** {.unnumbered}

Wheat, honey, dried/fruit, dried/fish, manure, grazing animals.

By Lake Piscaim more prosperous farm by selling fish products and by the excellent soils around the lake high yields.

Population: 1100

#### **Tantum Farm** {.unnumbered}

Craft, fruits, honey, wheat, grazing animals, ore mining (, lumbering, quarries, gems, uraninan plantations.

Most important farm in the Heartland due to mild climate, sufficient rain and protected from northern storms by Tantum Mountain. Under the Uraninan noble family for 300 years continuously growing and small town character. Significant in many respects. Only place in the Heartland where uraninan leaves (antidote to blue tongue plague) are commercially planted.

Population: 7500 (+3000-4000 harvesters in summer)

#### **Great Tantium** {.unnumbered}

Craft, stonemason guild, timber construction, wood craft, trade, art smiths

Connecting city between the northern foothills of the Heartland and the Empire.

Population: 48,000

#### {.unnumbered}

#### **Muranum Farm** {.unnumbered}

Formerly: timber farming, grazing livestock, barley, oats, hops, wheat.

Abandoned since raid of hellspawn abominations in 417 CE. Source of countless awakened.

Population: 0

#### {.unnumbered}

#### **Grimgrod** {.unnumbered}

Game meat, monster ingredients, orc soldiers, gems, potions.

Formally subordinate to the Empire largest known orc settlement in the Empire. Orcs themselves occasionally murder hunters from Orantium and Vaichatum. Orcs from Grimgrod are often used as heavy infantry for the Imperial Army. The sale of gems by the orcs is extremely lucrative for the Empire, and the profits are sometimes turned into compensation for murdered hunters from the above-mentioned settlements.

Population: 1000 - 15000

### Infrastructure

The Heartland probably has the best known infrastructure with Nors. Roads are maintained by designated guilds and the central roads are often free of major threats, as the Imperial Army takes care of this. It is mostly possible to travel between major cities without sleeping in the open. Drinking water supply is mostly clean and provided by viaducts or deep wells. Healers and alchemists help against most injuries, as long as the purse is coherent.

## The history of the region

The history of the Heartland is closely tied to the teachings of the All-God and the subsequent founding of the Empire. Civis-Primae is, according to historians, the cradle of civilization and has been inhabited since writing existed. The surrounding areas were put under human care by the growth of the human population and were deforested and/or put in the service of agriculture. The settlements gave rise to small principalities which developed and passed away in constantly changing alliances and enmities. Ruins and former rich principalities met their end through war, disease or misfortune, while elsewhere the chance of life was kinder. Because of the low population density, it was far more difficult to combat <font color="green">[monsters and other abominations](#monsters)</font>. These, imprinted themselves in the culture and rhythm of life of the resident people, as in other early cultures. The spread of the Animali as monster hunters was thereby proven in some cultures in the form of good spirits. However, the better the villages and principalities developed, the more likely the Animali were to interfere with agriculture or hunting, so that even over the centuries before the war between the Animali and the Empire, no consistent view can be found. The monsters, on the other hand, are consistently referred to as evil spirits or demons and, according to oral tradition, often led to the abandonment of settlements. Another problem of the earliest settlements were awakened which transported livestock and even people themselves into the afterlife.

It took a long time until the doctrine of the All-God with his burial rites prevailed, because the unsteady organization and the constant skirmishes thwarted this. Over the centuries, the doctrine of the All-God with the burial rites finally prevailed and was able to lay the foundation for more productive agriculture.

Civis-Primae is here the Moloch from which most stories take their beginning. Thus emperors crowned themselves, princes and the nobility allied themselves or secret agreements were closed. Extremely militaristic, this is still felt today for partly rigid bureaucratic processes and in the omnipresence of the emperor and the imperial army. The emperor was served by the brightest minds that the country has produced over the centuries and so, despite various plagues and wars, it was never completely freed from the resident imperial culture. As a result, deeply rooted and influential guilds established themselves in all areas, whereby progress, despite some setbacks, always originated in the heartland and Civis-Primae.

## Economic situation

The Heartland is one of the richest areas of the Empire, due to various monopolies of power and law. Civis-Primae and Agiontum represent the economic monoliths of the Heartland. Militarily the strongest is, unsurprisingly, Castellum-Reik. A large city where militates of various types are trained. Be it specialists of artillery or nimble troops of horsemen or heavy infantry in the form of men and orcs as strong as oxen. This results in the legendary reputation of the imperial army as perfectly corrdinated. Since only a few landscapes in the service do not serve under the flag of the emperor, the heartland is self-sustaining with less military. Since the annexation of Yondalla and the occupation of Eldria, however, the economic situation has tightened considerably, and it is the central hub for ore and war supplies from Nors and food from Yondalla with the intellectual and bureaucratic center in the Heartland.

### The resources of the region

Self-sufficient in wood and largely in food. Ores and special woods are in short supply and are supplied through Nors and the Silva-Nacia borders and from the Borderlands. Food shortages are alleviated by Yondalla. Attempts to mine ore in the orc-dominated northeastern foothills of the Heaven's Peak Mountains failed a few decades ago, but continue to be actively pursued.

Special needs such as gems, rare ores, and <font color="green">[Alchemical Plants](#DrugPlants)</font> are met primarily through imports.

## Sociopolitical situation

### Ruling system/organization

## Climatic conditions

The Heartland is characterized by mild and rainy weather. Winters are somewhat milder than in Nors. Cold and heat deaths are limited to the homeless and servants.

### The flora and fauna

In the Heartland, the most common and relevant animals are: deer, wild boars, various birds, wolves and bears in the forests, badgers, Heartland foxes

The flora of the Heartland is relatively rich in medicinal plants, as they have been cultivated for a long time and thus spread. As a result, 40 different commonly used medicinal plants can now be found in the Heartland. Commercially, the almost untouched remnant forests consist of a great diversity of trees. Commercially, the sugar maple and various hardwoods are planted.

Food crops in many places do not provide Yondalla's yields per hectare, but have long been sufficient to support the Empire's population. Widespread are the regular food crops such as barley, wheat, oats, and rye.

The diversity of non-alchemical plants is described by scholars as mediocre and sufficient for extravagant decorations of banquets and noble weddings.

#### Monsters in the region

The most common are the Kathakan, Werewolf, Gravis, Flesh Sucker and Awakened. However, the list of monsters is not complete and in rare events you can find Usukate, some Foedukuli and at least 2 reports of small bone skulls.

## Rumors of the region

**The Purification of Muranum Farm**: A Gravis gone berserk by a mercenary company kills his own company and most of the resident guards and soldiers. Two days later, several Awakened and "The Man-Eaters", presumably a group of Usucates, strayed into the farm area and massacred the population which could not flee in time. The cause of both events is unknown. The awakened Gravis is included in children's stories as a giant in the forest. However, he has not been seen for a long time.

**The Treasure in Lake Vaichtum**:

Allegedly, a chest of precious stones was transported across Lake Vaichtum in the summer of 143 A.D. Riga. Due to a storm the boat was captured and the crew lost their lives. Allegedly, the merchants on board illegally traded large quantities of weapons with orc tribes of the Heaven's Peaks and received in return a chest full of emeralds, garnet stones, amethysts and diamonds. The chest has not been found to this day, but the missing weapons from the imperial arsenal and the finding of some of them from orc tribes were consistent with it.

## Sights

Lake Vaichatum

Reik Lake

Monument of the people

Lake Piscaim

Mines of Meapontenum

Monument of the fallen
