# Wandia {#Wandia}

> Oh child, do not forget Wandia, do not forget our shame. Never forget where it leads when the wrong one follows. Do not forget to distrust and bring it back to us. For from the child of this tree there is always only one piece. And if you get it, never give it back, for the people and the small ones, they betrayed us before. And if you get it, never give it back again, because the people and the little ones, they betrayed us before."
>
> --- A lullaby for children from Silva Nacia

Wandia is a sanctuary that is important to the orcs, the elves of Silva Nacia, the Eldrians, as well as the dwarves.

Wandia has had many roles. As the former capital of the <font color="green">[Eldrian Kingdom](#Eldria)</font> and the <font color="green">[Thunder Guardians](#Thunder Guardians)</font>, Wandia was a giant metropolis that would easily dwarf any city known today.
In Wandia's heyday, the <font color="green">[Elves of Silva Nacia](#SilvaNacia)</font> managed to plant and flourish the only seedling of their sacred tree there to this day. This miracle has made Wandia and the recovery of the seedling one of the main goals of the elves - a mission that has cost countless lives to date.

Wandia consists of above-ground city ruins, divided into quarters that are heavily contested by different races. The few inhabitants of the ruins live there partly under very bad conditions.
In addition, there is an underground city whose corridors are largely unmapped because they are too extensive and the strutkur is always changing - either by the intervention of the fighting races or by that of the <font color="green">[true dragon](#TrueDragon)</font> Nuninox.

Both the Upper City and the Lower City, however, are only partially dominated by Orbis Aesta's races. The main part is probably dominated by <font color="green">[Ga'ar](#Ga'ar)</font>, because the further one gets into the ruined desert of Wandia the greater the danger of encountering its monsters in all shapes and colors. Various monsters stubbornly hold the central quarters in the Upper City and especially the royal palace of the old Eldric Empire. In the Deep City they are even more widespread.

> "In search of Honoria, we came to Wandia, we soon made our way to the inner areas - but it is like being cursed. Left and right we are losing our warriors to monsters, and more and more are coming. It almost seems like the monsters are guarding Wandia's center. In the deep city, the plague is even greater. We've even fought walking armor."
>
> --- Arien Tyssen, Eldric Knight and Adventurer

For the orcs, Wandia only became significant when Nuninox appeared.

## The history of the region

### The fall of Wandia

Originally, Wandia was a settlement where humans and dwarves lived together - the dwarves mostly in the underground part and the humans in the above-ground part. After several hundred years of fruitful cooperation, the humans colonized the surrounding area and established Hasting, Calvert and the other eldritch principalities.
Wandia was the heart of the eldritch kingdom and a jewel of civilization. The Thunder Guardians had a safe haven there and the city grew and prospered and was arguably the most impressive city that ever existed.

The strong position of Wandia also attracted the elves in the long run. They created their own quarters in the huge city and thus joined the alliance of the Thunder Guardians and the Kingdom of Eldria.

In the center of Wandia, the seat of the Thunder Guardians and the royal palace are arranged vertically one above the other. Where the dwarven seat of power is located in the Deep City, there is also the royal palace - or today its ruins. At this very point, the elves planted the sapling of their sacred tree, which grew quickly and spanned both seats of power. A symbol of the coexistence of three races.

> "To this day, the elves believe that their tree still stands there, bearing a seedling itself. However, no expedition has ever returned from there to confirm or disprove the story. Nevertheless, the elves see almost any sacrifice as appropriate to get the seedling of the tree or to recapture this tree itself.
>
> --- from "The Chronicles of Wandia" by Wilhelmina Trayne

The idyll of early Wandia was abruptly interrupted when the infamous true dragon Nuninox struck.

> "No one knows where he came from, but the combined forces of men and dwarves proved powerless against the forces of the true dragon. His fire reduced whole armies to ashes in a few minutes, destroying houses, walls and fortresses."
>
> --- Rheymos Earth, an escaped guard of Wandia

With Nuninox came those monsters that populate Wandia today. Only a few could survive. Whom the dragon did not incinerate was caught by a marauding monster.
The hasty escape from Wandia ensured that a great deal of dwarven material in particular - artifacts of the Thunder Guardians - remains in Wandia to this day. This potential loot ensures that again and again fortune seekers try to find great booty in Wandia. Most of them succumb to the dangers of Wandia, but every now and then someone manages to find something - with the sale value one is then usually provided for life.

For the next 400 years, Wandia could not be approached due to the omnipresent danger of the dragon Nuninox. He destroyed everything that came too close to the city. This reign of terror continued until the event that went down in history as the "Battle of the Colossi".

### The Battle of the Colossi

About 400 years after the fall of Wandia, the so-called Battle of the Colossi took place. The few remaining Thunder Guardians had worked tirelessly to finalize their final weapon - <font color="green">[a Titan class construct](#missing)</font>.

> "The Titan construct was originally built for the last 300 years for the Civil War. However, when we lost Wandia we knew it was our best chance. Normally 450 years would be enough for such a project, but since there were only a few of us left, it took considerably longer. But now it is ready. Today we send him to fight and destroy a dragon!"
>
> --- Dhakri Meren, leader of the Thunder Guards, ca 750 before Riga

The dwarves launched their collosal weapon in the embattled Istval. The construct immediately marched to Wandia and was attacked there by Nuninox, as expected. The two collosses engaged in such a monumental battle that those who witnessed it spoke of it for decades to come. Eventually, both disappeared into the depths of the city, and it was unclear which colossus prevailed, but Nuninox no longer terrorized the Wandia region, and was mistakenly assumed dead.

Shortly after the battle of the colossi, the Thunder Guards sent the last of their large missions to Wandia - a large group of the now rare Thunder Guards - none of whom returned.

Today it is known that Nuninox survived the battle - but was so injured by it that he can no longer leave the central quarters of Wandia. He seems to be unable to fly for a long time, but for those who come within his reach, he is still one of the greatest dangers Wandia - and perhaps all of Orbis Astea - has to offer.
What has become of the Titan construct, no one knows for sure, no wreckage has been sighted, nor does it appear to be still in active operation.

## Climatic conditions

### Flora and fauna

#### Monsters in the region

Probably the biggest monster that can be found in Wandia is a dragon. A true dragon, it flies around the underground city and feeds on the awakenings that result from fighting in the underground cities, as the corpses cannot be properly buried.
This fire-breathing dragon is one of the few known and suspected <font color="green">[true dragon](#TrueDragon)</font>
_
## Legends of the region

### The legend of Üräid the Wise

This event, which is difficult to date, occurred sometime between 1150 and 750 BC in Wandia. Due to the lack of written records from credible chroniclers, there are three varying stories from the orcs, elves, and dwarves about the elven matriarch Üräid the Wise and her giant spider.

Üräid the Wise, ruled over her tribe of wood elves on the slopes between the Heaven's Peak Mountains and Wandia. Her tribe numbered tens of thousands, with a distinct group of the Path of the Paw. Orc lore has it that their spiders were particularly large and tasty. Dwarven caravans coveted the tribe's armor, as their chitinous armor had excellent workability.

The actual legend begins with the matriarch colliding with the expansive policy of the dwarves in Wandia, as dwarves cut down a young tree of Saritaäs, the sacred elven tree in Silva Nacia supposedly for firewood. As a result, Üräid the Wise wandered towards Wandia with her spider Golmiäd, supposedly with a leg span of 200 meters, to finally drive the dwarves out of Wandia. So far, apart from the size, this is the undisputed part of the legend.

More controversial are the following events. In the dwarven tales, it is said that thousands of elves on spiders led by Üräid, "the Cruel" headed towards Wandia to exterminate the Thunder Guardians. In the process, the elves slaughtered their way through armies of dwarves, and the spider Golmiäd simply tore apart constructs or broke them like branches under its legs. A slaughter of the thus almost defenseless dwarves followed. Then, out of nowhere, the Twins of the Abyss, giant bone skulls, suddenly appeared from the mountains, which in turn simply wiped out the elf army, and a final battle between Uraeid the Wise and her spider Golmiäd ensued. The twins simply tore open the 20 meter high steel door of the entrance to Wandia and used it as a shield, while the chunks of flesh of the twins of the Abyss began to live and climbed up on the spider Golmiäd or simply fell on it until Uraeid the Wise, at some point was simply torn apart by the descendants of the twins. The spider was shortly thereafter struck down by the twins, whereupon they simply moved into Wandia and wiped out "all civilized life" in Wandia.
The history of the elves itself also speaks of the slaughter of the Forest Destroying Dwarves in Wandia, but does not mention that the Twins of the Abyss fought against Golmiäd and Üräid, but that a true dragon brought the slaughter to an abrupt end by burning everything in its path. The elves considered this a win, since the nimbleness of the spiders were much harder to burn. Üräid herself lost her flawless countenance and died shortly thereafter from the dragon's burns. Golmiäd is said to have then fled into the forest and since then has been eating dwarves who so much as laid a hand on a woodcutter's axe.
The elves saw the power of the dragon and found it was enough punishment for dwarves and took revenge on the orc tribes that devastated their homeland.

According to orc stories, the battle took place between elves and dwarves, because the latter proudly plundered the elven settlement and ate everything carnal and wanted to build a new orc settlement there. Thereupon orcs found the battle in Wandia and took part, until after several decades the camps in and around Wandia were so far destroyed that the twins of the Abrgund "fell from the sky" and thereupon were so enraged about the arte landing that they tore the doors of the entrance out of Wandia and since then try to find the architect of Wandia, who is said to have drained the former lake here.
The True Dragon came sometime later, when it was already a tradition for orcs of the Steel Bone tribe in Wandia to hunt the spider Golmiäd and torture elves to find the spider. However, the dragon did not burn anyone, but a great feast on the surface ended the war between elves and dwarves.

Remaining members of the Steel Bone Tribe were mostly recruited over the centuries, moved away, or lived in the depths of Wandia, so the trail is lost here. Also, no more reports have been found of a hundred meter spider where there were actual losses of military units.
It is also unclear whether the true dragon still rules in Wandia. It is also technically disputed that the Twins of the Abyss ever existed.


## Places of interest

