---
editor_options:
  markdown:
    wrap: sentence
---

# (PART) Deep Lore {.unnumbered}

# Forerunners and blood gods

<big> Caution this is deep lore that is not game relevant but is relevant to understanding.
While it is useful for DM's to understand it, for players it may reveal background and causalities that affect game enjoyment.

So read at your own "risk".
</big>

> "Not much is known about the race we call the Forerunners. Except for their ruins and some of their mechanisms, not much is known about them. We do know that they populated the world before us and were probably powerful of magic. In league with evil gods and with foul magic, their world had to perish to make way for a better, purer world. So we see how God works and rules, and how good always wins, no matter how hard evil tries to kick."
>
> --- Paniac Larren, High Priest of Darcy

This species of intelligent developers and researchers went mad after a time due to complacency and decadence.
This led to the loss of these special abilities as a species of developers.
The "last" of their kind were no more than children who could handle weapons.
It was not possible for them to specifically improve their weapons here or even to develop new ones, so the actions of the "Blood Gods" can rightly be considered insane by mortal humanoids.
The abilities of the individual blood gods are accordingly manifold, since everyone tried to use his "captured technologies" and to optimize them.
This is a very wide range of technologies, which of course can become weapons with malevolent intentions.
This resulted in a ruthless slaughter of this once wise species, shrinking the number of their kind to a small pile.
Consequently, the survivors of these barbarians are neither the most prudent nor the kindest.
As a result, the entire planet on which the world known to man lies has become a shadow of its former self.

### Precursors

Forerunners still possess their physical bodies.
They are able to be almost immortal, since their internal organs and brains can be rejuvenated again and again, but they suffer from the fact that the global ability to regenerate the skin was impaired when their war broke out.
As a result, they constantly feel pain but are unable to stop it or regenerate their skin themselves.
One of the fewer regeneration stations is located a few meters below the surface of the Sulphur Trench and is accordingly a "trap" of the non-material Blood Gods.
The Forerunners are still endowed with, for humans, god-like abilities, but cannot be in all places at once, limiting their capabilities compared to the Blood Gods.
However, these Forerunners are still in a more livable state than their, pre-war, richer counterparts.

### Blood Gods

Blood gods, precisely these richer humanoids in the society of the time, on the other hand, live as metaphysical beings for humans.
They possess no regular body and walk the known world of Orbis Astea as stored consciousnesses of their former bodies on the network infrastructure.
This former material wealth of these children of the ingenious developers and the centuries of malice among themselves lead to paranoid behavior patterns, paranoia and massively erratic behavior.
It would be possible for the blood gods themselves to inhabit real bodies, but it is no longer their original one.
This blurs the sense of authenticity and reality for these gods -- a consequence of imagination being on par with reality.

In this war were created as weapons, tools or slaves, the known humanoid races of dwarves, humans, elves, orcs, halflings.

### A better place for placeless

Saarth Valar, creator of the dwarves, gathered the survivors of their war and wanted to create a new, better, more peaceful world from them.
To do this, he was able to work out a vision with the help of the Blood Goddess of Illusions, Ciresh, the Goddess of Monsters, Ga'ar, the Cold Blood God, Hartemus, and several others to create this new world.
In order to make the heavily radioactively contaminated world easier to use again, Saarth Valar asked Ga'ar to create monsters that could utilize these radioactive substances.
From this, an ecosystem could be created that would allow the Blood Gods to safely change into physical form.
Ga'ar could actually then create self-replicating beings that could accomplish this task.
These monsters are known as Stone Worms, Asworms, and World Worms.
Based on this, thousands of species established themselves, which were also able to use these energy sources.
Hartemus provided the clout of his weapons and troops to allow Saarth Valar to implement these plans without the other blood gods being able to stop him.

However, Thanif, the goddess of the Awakened, that is, the creator of the parasites that afflict all humanoids, was dissatisfied with the power of this alliance and feared losing her "weapons", the Awakened, as soon as peace would come.
Together with Ciresh, she was able to unite the remaining Blood Gods and motivate them to betray Saarth Valar.
Jiraad, the burning blood god, already thought little of Saarth Valar's ideas, but Jiraad's creations were capable of living in this radiant world.
He joined the attempted coup.

H'abunaptra, the mountain in the Rahkari desert, was probably the most important remaining powerhouse of the Forerunners and Blood Gods.
Saarth Valar resided with his attention primarily there.
During the time of the development of the monsters Ga'ars on site in H'abunaptra, Hartemus was there with his weapons.
In the phase where Saarth Valar wanted to devote himself completely to this ancient power plant, to understand and develop it, Ciresh noticed that a spark of distrust towards Saarth Valar was still there.
She disrupted the connection.
Saarth Valar lost access to most of his abilities during the transfer process as a result.
Hartemus then tried to take revenge on Ciresh.
This led to a new conflict between the Blood Gods.
The attempted subversion was successful in the narrow sense.
Saarth Valar's possibilities to realize or form from the network from reality was massively weakened thereupon.
Hartemus, as the executor of Saarth Valar, also suffered bitter losses.
He could not keep up with the mental abilities of the united other blood gods and ended up as one of the weakest blood gods

Saarth Valar's transfer to the powerhouse, however, allowed him to curtail the abilities of the other Blood Gods, simply by cutting the power to the transmission networks.

Asb'cartes, a Forerunner, wanted to use the keys invested in certain humanoids to throttle the power plant in H'abunaptra in order to limit the influence of his richer and crazier kin.
Ciresh, however, wanted the exact opposite from Asb'cartes.
Asb'cartes had been entrusted with the task of gathering and using the keys to keep the power plant in H'abunaptra running at maximum capacity.
Asb'cartes, with his residual sanity, eventually realized that more power never solved a problem for the Blood Gods and decided to destroy the keys.
He was able to destroy one key before Ciresh and the other keys "freed" it from its physical form and transferred it to the realm of the void, since Ciresh did not tolerate betrayal and the keys themselves had some power.

## The Awakening

The Awakened in Orbis Astea are formed from the dead of all known humanoids.
Partly also the natural animal world is affected.
The cause is a failed bioweapons experiment by blood gods.
A combination of a parasite and a virus sleeps inactive in all humanoids.
If the affected host organism dies, the virus begins to become active.
This triggers the parasite to remodel the body.
There are two relevant different outcomes.
If the head of the dead person is destroyed, an altered variant of an awakened person develops from the body found in the remodeling and decomposition.
Here a tentacle or eel-like head area is formed, which protrudes from the body to a different extent.
This forms a sensory nexus that is difficult to hit, similar to a head.
It is not possible to be bitten by this mutated Awakened, but the "head", i.e. this small area protruding from the shoulders, secretes contact poisons.
These poison humanoids and even blood gods.
This makes these Awakened more difficult to fight, since the entire torso must now be destroyed.
If the deceased keeps his head, the parasite forms its sensory center in the head and can thus be eliminated more easily with a decapitation.
The food supply of the awakened is provided by symbiotic fungi, which settle in the rotting body.
Coupled with highly throttleable metabolism of the parasite itself, it allows them to live extremely long without actually "starving".
The fact that Awakened humanoids partially eat is due to the genetic self-optimization of the parasite.
Here, the feeding Awakened, i.e. the parasites in humanoid shell, spread themselves further.
Thus, the most effective hunters continuously improve.

The Awakening can be prevented or temporarily suppressed, provided that it is anointed with Riddin oil, the corpse is burned, or burial under seal stones takes place.
The latter only impede the neuronal and immunological communication of the parasite, leaving it brain dead and far more susceptible to infection.
If the soil organisms degrade the corpse, or the parasite, far enough, resurrection no longer occurs.

## The Gray Wasteland

The gray wasteland forms the northern desert-like area adjacent to the Rahkari's deserts.
It is characterized by extreme temperature fluctuations, which make it impossible for normal mortals to stay long in this area.
This climatic peculiarity is due to blood god activity.
This wasteland is hardly inhabited by living organisms.
However, there are several "oases" inhabited by the pale orcs.
These are very light-skinned, sun-bleached orcs.
This "race" lives by the benevolence of blood gods and their artifacts.
Their form of society is egalitarian, peaceful and non-interventionist.
Thus, they have little interest in spreading into Rahkari territories.
Especially since their gods do not allow them to leave the Grey Wasteland.

Energy sources unknown to humans:\
Some organisms in Orbis Astea use radioactive minerals to draw energy away from the sun.
Many fungi, and stone worms in particular, utilize these to simply feed off of.
These passages of the stone worms form here many explorable and easily passable mountain tunnels.
The feces of the stone worms is primarily sandy material and easy to move/work.
Rich in metals.
Contain toxic substances.

## The eastern frontiers of the known world -- the burning lands

East of Eldria and the borderlands and night mountains surrounding Yondalla are lands virtually unexplored by humans and goblins.
It is called the Burning Lands by the humans.
The name was taken from the Sulphur Rift, which lies to the east of Eldria and the Borderlands.
On the side of the Sulphur Rift there is a little stable plateau, about 200-300 meters above the ground level of the Sulphur Rift.
On the part of the goblins on and in the Night Mountains, occasional expeditions were launched.
The result, however, was death shortly after the invasion or after the return, if the burning lands were entered for a short time.

They are called the Black Lands or the Burning Lands by the goblins.
Expeditions there are becoming rare due to these legends of the curse.
Humans have not yet been able to successfully explore the Night Mountains due to the impassable terrain and raids by goblins.

The Burning Lands themselves are directly ruled by the Blood God Jiraad.
Jiraad resides there most of the time with his attention.

He tries to create his own intelligent and controllable species there.
This amorphous mass, which has consciousness, but Jiraad has not yet succeeded in creating useful minions against other blood gods, especially Ga'ar, the mother of monsters.

Ga'ar uses worlds and worms himself, and as an uncontrolled species, stone worms to utilize the radioactivity of the elements, generating energy from it to create "fuel" for the worms to gradually "cleanse" the areas, reducing Jiraad's options.
The Wormfall region is the active example here, where worms cleanse the area by burning radioactive elements.
Consequently, the areas inhabited by humans are completely limited to these purified areas.

Jiraad himself thereupon also tries to acquire humans for his purposes.
His visions, which he plants in the heads of people, lead to the fact that some roam the sulfur trenches and then get stuck on the plateau or freeze to death or are eaten in the adjacent fog mountains or night mountains.

The burning lands have long served as a retreat for the blood god Jiraad.
Jiraad seeks to create his own creations of monsters and more intelligent beings in these lands to counter the Blood Goddess Ga'ar and her incarnations of Ashworms and Worldworms.
The burning lands are highly radioactively contaminated, making it impossible for ordinary organisms to survive or gain a foothold there in the long term.
Due to the higher mutation rate of the organisms, which can eke out an existence by Jiraad itself or via strong selection, much more abstruse life forms have evolved, which would be considered grotesque or unnatural by humans.
Since monsters and wild animals are hardly suitable to fight against Aschwürmer or world worms Jiraad tried to create his own variants of intelligent living beings, which was only partly successful.
These gelatinous, boneless organisms can barely move upright outside of their special armor.
Without these armors, these "Witnesses of Jiraad" or "Jiraadites" crawl along at a leisurely pace, feeding on radiation via symbiotic fungi.
These fungi give pitch black or purple colors to most of the organisms of the burning lands.
The peculiarity of these witnesses of Jiraad is the ability to unite with other witnesses of Jiraad, in order to carry out an alignment of the collected knowledge.
Jiraad wanted to achieve that the knowledge about the most effective methods of fighting the ash- and worldworms of Ga'ar would spread as fast as possible.
The plan worked conditionally.
Individual groups of Jiraad's witnesses (also called "Zeujards") can become dangerous to the worms.

However, the possibility for the knowledge adjustment has the consequence that these gelatinous creatures forged an own will and own plans.
Other creations quickly perished due to the chaotic geological conditions.
Jiraad tries, somewhat in vain, to lure humanoids with visions of the Burning Lands or the Sulphur Rift into his realm, where he would have greater influence.
However, due to the unfamiliarity of the lands, extremely few humans find their way to the Sulphur Rifts or would survive long enough to be biologically adapted by Jiraad.

Zeujards organize themselves through union festivals where a larger number of Zeujards share their accumulated knowledge and organize resources for armor and weapons.
Technically superior to humans, but dependent on the support of their creator, they do not leave the burning lands.

### Ga'ar's biological children -- the greatest abominations

Usually, Ga'ar retains some control over her made creations.
Thus, monsters of the Hellspawn class are at least familiar with Ga'ar's general desires and can still occasionally respond directly to commands.\

Ga'ar's own children, however, are too large and independent for Ga'ar to control.
Their minds and organisms have become too complex for Ga'ar's influence to be sufficient.

The Earth Devourer -- the monster under the volcano: A gigantic monstrosity under the volcano of the dwarves in the northern Sky Peak Mountains.
The dwarves were created by Saarth Valaar to keep this monster at bay, or rather to maintain the mechanisms that keep the monster in check.
The Earth Devourer uses the surface magma deposits to extract energy from them.
At the same time, this also prevents major eruptions of the volcano.
The Thunderkeepers are the remaining group of dwarves who still roughly know about this task.

### The Deep Lord and Nightmare of the Sea - Leviathan

The Leviathan is a gigantic sea monster hunted by the Sirkali ship of state.
Although it is the weakest child of Ga'ar, its 250,000 tons of body weight alone are enough to rule the depths of the seas undisturbed.
The Leviathan itself is designed to prevent precursors from traveling across the seas, thus limiting their influence.
Humans are familiar with the Leviathan from legends, but it has not been seen in full form.
With thousands of tentacles about a hundred meters long springing from the ventral side of its worm-like body, these are the only part visible to humans should the Leviathan attack.
Like many of Ga'ar's creations, it draws its energy from radioactive elements, which it absorbs from the sea and the ocean floor.
Here, the non-muscularly controlled "hairs" on the belly serve the function of filters for radioactive elements.
Worms living on the leviathan eat these "hairs" and then bury themselves in the soft underside of the belly, where they die and are digested.

#### Bone skinner

The Bone Skullers are not a single monster in the strictest sense, but are, in origin, a bodily child of Ga'ar, but can reproduce on their own.
This makes it impossible for Ga'ar to control them.
The bone skinners among themselves see themselves more as a family.
They can communicate with each other, share common values, and reproduce asexually from within themselves.
They are characterized by a mixture of tentacles, gray armor plates, endless growth, and a dislike of orcs and elves.
Bone skinners are clean in the true sense of the word and fear the spread of disease from humanoids to their own.
Especially orcs and elves, who still carry "natural" diseases.
Bone skinners secrete mucus on their skin layers, which serves to keep diseases away.
Therefore, for the good of the group, infected people are always cast out.
If they survive and find enough food, a new tribe of bone pests can emerge.
With the time new characteristics evolved here, like further arms, color change or other rites, languages and customs.
The parasites that infect all humanoids and cause the awakening, when transmitted to bone pests, lead to a miserable and long-lasting death.
These infected and moribund bone skulls roam around killing humans, Awakened, and other parasite-infected mammals in order to serve the originating tribe.

Since bone skinners do not age in the true sense of the word, death itself is all the more frightening an example, and all the more painful when a family or tribe member, after 400 years of close bonding, is subjected to a gruesome martyrdom by a two-legged screaming worm.
