# (PART) DM section {-}

# For DM's and those who want to become one

The most important thing for being a good DM is a deep knowledge of the rules and the correct interpretation of the values. Of course, there are many other qualities as well, but these two are specific to our system.

## How to interpret values and throws {#gradations}

A Value is a quality criterion of a throw - no matter if sample, save or other - and is reported back by the DM-App for almost all actions. The interpretation of values is not very easy, especially at the beginning, a value of 2 for example indicates that the action was average. To be able to interpret values easily, you have to develop a feeling for them, but there are certain classifications that you can consider.

| Value | Interpretation |
|:------:|:---------------------------------------------------:|
| \< 1 | Very badly run attempt to achieve something |
| \< 2 | bad attempt to achieve something |
| \< 2.5 | poor to medium attempt to achieve something |
| \< 3 | medium attempt to achieve something |
| \< 3.5 | medium to good attempt to achieve something |
| \< 4 | good attempt to achieve something |
| \< 5 | very good attempt to achieve something |
| \< 6 | incredibly good attempt to achieve something |

There is also the [Value Estimator](https://svalv.shinyapps.io/ValueEstimator/), an online app that simulates more than 20 million casts with different attributes and skill levels, so you can get a better and faster overview of the value system. First select the correct data set, if you play the less lethal variant with damage cap at 550 and value cap at 13, you have to select "limited values" under settings. Otherwise the unlimited ones. For the rare case that monsters are important to you, there is the dataset Monstervalues, where attributes up to 80 were simulated.

### What do critical throws do

For critical successes/failures, a D20 die is rolled in the background. The DM app reports critical successes back to you with red (for Nat 20s) or yellow text. Critical failures are reported back with blue (Nat 1) or green. With modifiers like this, DMs often have the option to introduce additional rewards/punishments.

## Quest levels

| quest level | description | reward |
|:----------:|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:---------:|
| 1 | No big consequences and only a pet-peeve for order givers | 500 |
| 2 | Small orders, possibly dangerous, little to no impact | 1000 |
| 3 | Medium orders, somewhat dangerous, no impact on standing with large factions, little local impact | 2500 |
| 4 | Medium orders, somewhat dangerous, mostly no impact on standing with large factions, medium local impact | 6000 |
| 5 | Medium orders, small regional/large local impact, dangerous, affects standing with factions (especially with smaller ones) | 14000 |
| 6 | Medium orders, medium regional impact, dangerous, influences standing with factions (especially with smaller ones) | 28000 |
| 7 | Large orders, large regional impact, influences standing with factions | 50000 |
| 8 | Large Orders, Light Global Impact, Changes Standing with Factions | 100000 |
| 9 | Large Orders, Global Impact, Strongly Changes Standing with Factions                                                                                                                                  | 600000 |
| 10 | Quests with enormous dangers, politically serious consequences and extreme long-term consequences for characters and world. BSP: Kill emperor, take over country etc, can destroy factions completely | 3.000.000 |
