# Die Rasse der Orks

> "Man versklavt Orks nicht. Orks gibt man einen Grund warum Sie etwas machen und belohnt Sie mit reichlich Bier und unmenschlichen Mengen an Essen. Dann sind Sie die treuesten und besten Soldaten welche sich ein Kaiser wünschen kann!"
>
> ---  Lucillus Proximus

Orks sind im Erscheinungsbild von grob menschlicher Statur. Im Allgemeinen sind Orks etwas größer als Menschen. Sexueller Dimorphismus ist weniger stark ausgeprägt als bei Menschen.
Prinzipiell kommen sie in unterschiedlichen Hautschattierungen vor:
Orks, welche primär Untertage aktiv sind, sind meist in grau und braun Tönen anzutreffen.
Orks grünerer Gebiete, wie in Wäldern und auch im Nebelhain, sind meist mit dunkelgrünen Hauttönen anzutreffen.
Die Körperlich größten Orks sind in der Eisenwüste anzutreffen. Ihre Körpergröße ist im Durchschnitt bei knapp unter zwei Metern. Orks der Eisenwüste sind entsprechend rostbraun bis rot-braun.

Die körperliche Stärke von Orks ist die höchste bei allen Rassen. Selbst in der Stadt aufgezogen Orks haben meist bereits die körperliche Kraft von hartgesottenen Soldaten.

Orks sind im Allgemeinen sprachlich wenig gewandt, was auch auf ihre bescheidenere Intelligenz zurückzuführen ist. 

Orks ernähren sich primär von erlegten Beutetieren oder ihren eigenen Toten. Obwohl Orks kurzsichtig sind und demenstprechend keine Fernkampfwaffen effektiv benutzen können, sind diese allerdings, aufgrund ihrer unheimlichen körperlichen Stärke, in der Lage selbst große Ebern mit ihren Knochenspeeren auf mehreren dutzend Metern zu erlegen.

Berüchtigt sind Orks für ihre, im Gegensatz zu allen anderen Rassen, stark ausgeprägten Eckzähnen. Hierbei sind vor allem die Unteren Eckzähne meist bei ausgewachsenen männlichen Exemplaren groß genug um teils die Aussprache zu behindern.

> Aufgrund ihres "wilden" Lebenstils, was für einen kaiserlichen Missionar wie mich, tatsächlich eher eine Untertreibung darstellt, sind Orks gegenüber herkömmlichen Krankheiten beinahe immun. Orks waren auch die einzige Rasse, welche nicht von der großen Seuche - der Irae Omnideus - befallen wurde.
>
> --- Aus "Das Tagebuch eines reisenden Missionars" von Stephanus Arnelius


## Die Geschichte


## Die Gesellschaft


Die Gesellschaft der Orks ist im allgemeinen einfach gegliedert.
Den Orkstamm führt für gewöhnlich ein Stammesoberhaupt, welches in allen Orkgesellschaften, außer den Orks der Eisenrotenwüste, männlich ist.  Das Stammesoberhaupt hat alleine jedoch wenig Entscheidungsgewalt und Orks leben im Allgemeinen in einem partizipatorischen System. Jeder Ork hat ein, entsprechend seines Alters und Rufes ein Stimmrecht Entscheidungen welche Lindwürmer wann wo erlegt werden, welche Beute wem gehört sind im allgemeinen schnell getroffen da die Nutzungsteile und die Nahrung für gewöhnlich fair verteilt wird. Insofern ist es, entgegen der Ordnung des Allgottes, allen Orks erlaubt ihre Fähigkeiten zu bilden wie diese das möchten.
Allerdings sollte hier erwähnt werden, dass dies nur für den Stamm relevante Aufgaben gilt. Künstler, Literaten oder sonstiges Gesocks sucht man bei Orks dementsprechend vergebens.
Allerdings beteilgen sich, an etwaigen Zeichnungen oder Errichtungen von "Gebäuden" meist alle Orks gleichermaßen.

Die für Orks als anerkannte Aufgaben sind Jagen, Sammeln, Trainieren der Kinder für Kämpfe und Jagden - also Lehrer, Heiler - welche ausschließlich männlich sind, Jagd-Priester und Handwerker (wobei diese Gruppe äußerst fluid ist).
Orks betreiben für gewöhnlich keine Landwirtschaft und errichten selten hohe Gebäude, da ihnen das architektonische und Bauherrenwissen fehlt. Folglich verlassen sich Orks beinahe ausschließlich auf natürliche Nahrungsquellen, welche weitaus diverser sind als menschliche Mägen verkraften würden.
So sind Orkfestmahle meist mit barbarischen Mengen Fleisch, Nüssen und Früchten als auch, für Menschen giftige, stärkehaltige Wurzeln gedeckt. Kochtechnische Spezialitäten weisen Orks, unüberraschender Weise, keine auf und ihre Gerichte sind meist im oder am Feuer gegart/geröstet.

Orks sind den meisten anderen Rassen, exklusive Halblinge welche gerne zu Feierlichkeiten verspeist werden, neutral gesonnen, sofern ihre Jagdgründe und ihre Gebiete nicht eingeschränkt werden. 

Die Jagd der Orks erfolgt prinzipiell mit, für Menschen zu schwere, Speere wobei hier auch teils wilde Eber, des Kampfes willen ohne Waffen erlegt werden. Dies zählt zu den, teils wahllosen, Initiationriten, um als fähiges Stammesmitglied anerkannt zu werden.

Interessanterweise findet sich der Kampf gegen Eber, oder eberartige Tiere, in allen bis jetzt untersuchten Orkkulturen wieder, was auf eine ehemals gemeinsame Abstammung hindeutet.

Die Waffen bestehen meist, sofern kein Handel mit höheren Zivilisationen besteht, aus den Knochen diverser Monster. Hierbei sollten die aus Steinwurmzähnen geschliffenen Schwerter erwähnt werden, welche bei richtiger Bearbeitung durchaus mit den Stahlschwertern der Legionen mithalten.  Orks können, aufgrund ihrer überlegenen körperlichen Stärke, jedoch auch häufig mit teils absurd schweren Steinhämmern in den Kampf ziehen.
Natürlicherweise besitzen Orks, abgesehen von Lindwurmhäuten und Knochenrüstungen, keine Metallrüstungen. Allerdings sind Lederrüstungen der  Orks von Menschen meist begehrt, vor allem wenn diese mit Lindwurmhäuten verstärkt wurden.

Stellt man Orks in den Dienste des Kaiser und des Allgottes, so kann man die Nutzung von schwerer Rüstung besonders empfehlen. Aufgrund ihrer Stärke können Orks weitaus dickere Rüstungen tragen, was diese quasi  unverletzbar gegenüber Armbrüsten oder Bogen macht. Orks sind aufgrund der Kurzsichtigkeit in nur sehr seltenen Fällen dazu in der Lage Fernkampfwaffen zu nutzen, wodurch ihre Kultur nie den Bogenbau erlernt hat.
Orks benötigen allerdings, sofern diese zur Fernsicht in der Lage sind, spezielle Bögen und Pfeile da häufig der Bruch des Bogens in Kampfsituationen  erfolgt.

Die Erziehung der Orkkinder erfolgt ohne eine spezifische Schule. Die Orkkinder entscheiden relativ frei, welche Aktivitäten diese ausführen. Meist sind dies, wie Erwachsene Orks, jagen, fressen und rumtollen/kämpfen. Erwähnt wird allerdings zusätzlich zum rumtollen und den Rangeleien der Kinder, wo auch, entgegen des Allgottes, die Mädchen mitkämpfen, die Jagd und Kampfausbildung, welche bereits früh erfolgt. Abgesehen von Bewegungsübungen gegen Lindwürmer und dem Erklären des Kämpfens dagegen, wird der Umgang mit Axt, Schwert, Steinwurf, Speerwurf und tödlicher Faustkampf meist mit Erwachsenen Orkfrauen erlernt.

Der Handel mit dem Kaiserreich brachte einigen wenigen Orkstämmen die Vorzüge der zivilisierten Gesellschaft näher. Hierbei setzten sich vor allem der Verkauf von Bier, Salz und Eisen/Stahl durch. Das Kaiserreich erhält im Gegenzug die für Orks quasi wertlosen Edelsteine welche diese auf ihren Lindwurmjagden finden. Vielfach rekrutiert das Kaiserreich auch direkt aus den Orkstämmen Erwachsene, für die Auffrischung der Truppen in Kriegszeiten.



## Die Religion

Orks beten, zum Leidwesen der Missionare der Ekklesia, diverse Naturgötter an.
Hierbei ist zu erwähnen, dass Orks, aufgrund ihrer etwas komplexen stammesartigen Kultur, meist von Orkgemeinschaft zu Orkgemeinschaft verschiedene Götter anbeten.
Im Kern sind sich all diese Götter allerdings sehr ähnlich, was mich vermuten lässt, dass Orks früher ein geeintes Volk gewesen sein könnten.

Orks in Grimgrod - der größten Orksiedlungs am Fuße des südöstlichen Himmelspitzengebirge, beten zu Akunmaahn.
Hierbei handelt es sich um einen riesigen Lindwurm, welcher, entsprechend ihren Geschichten, nach gewissen Zeiten alles Leben frisst und beim Neubeginn einer neuen Zeit aus seinen Ausscheidungen dann neues Leben entsteht. Für die Orks in Grimgrod, welche grau-braun von der Körperfarbe her sind, ist ihre Hautfarbe ein Beweis dafür.

Zu Ehren Akunmaahns werden regelmäßig Opferfeste, wobei hier meist alte und schwache Orks geopfert werden, abgehalten. Bei diesen Festen tanzen Orks in einem sehr kampfähnlichen Stil und fressen und koopulieren immer wieder zwischendurch, scheinbar wahllos.
Diese Orgien sind für Menschen ein Grauß und vermutlich auch nicht gesund und gehen, Geschichten zu Folge, meist bei Menschen mit Knochenbrüchen einher.

Akunmaahn will, so ihr Glaube, dass ein jeder Ork die Haut eines Lindwurms trägt und nur dann ist er bereit für das ewige Festmahl. Das ewige Festmahl, was eben zugleich ihre Art von "Himmel" darstellt, wird zu mehreren, nicht am Kaiserlichen Kalendar fixierten Daten, abgehalten.

Um Verwirrungen meiner Leser zu vermeiden nenne ich das wiederkehrende Festessen nicht mehr "das ewige Festmahl", sondern nenne es die Völlerei.
Bei den Völlereien danken die Orks Akunmaahn dafür, dass sie auf die Welt gebracht wurden - in ihren Worten "geschissen". Die Völlereien starten meist mit vorhergehenden Jagden und anschließenden echten waffenlosen Kämpfen.
Auch dies dient ihrem "Gott" Akunmaahn, da sie seine Stärke als die wichtigste Tugend ansehen.

Neben der "Völlerei" ist ein weiterer wichtiger relgiöser Akt, die Jagd nach Lindwürmern. Hierbei  ist beinahe der gesamte Stamm in den Bergketten der Himmelsspitzen, südlich der Knochenfeldschlucht, unterwegs.
Die Größe der erlegten Lindwürmer spiegelt hierbei die Zufriedenheit des Gottes Akunmaahn wider. Akunmaahn ermöglicht jedem, der durch den Lindwurm verspeist wird,  nach ihrem Glauben, die Wiedergeburt als noch mächtigerer Krieger, welcher bei der nächsten Lindwurmjagd dessen Haut erwerben wird, was ihm beim "nächsten" Tod den Eintritt zum "ewigen Festmahl" ermöglicht.


Andere Ork Stämme haben nicht unbedingt einen Lindwurm, als "Gott", sondern vielfach bekannte große Kreaturen ihrer Umgebung.

So beten die Orks der Eisenrotenwüste die riesigen erdfressenden Würmer an und versuchen diese, während die Würmer noch nicht ausgewachsen sind, zu töten. Der Gedanke der Wiedergeburt ist auch hier, beim Verschlungen, bzw. Zerquetscht werden, ebenfalls vorhanden.

So bieten die diversen Orkstämme ihre eigene Erklärung an. Orgien, Völlereiein und Kämpfe gehören hierbei allerdings zu fast allen Stämmen.

Der einzige Orkstamm, über den beinahe nichts bekannt ist, welcher aus diesen Mustern eklatant ausschert, sind die blassen Orks aus der Grauen Ödnis.
Über die Orks der Grauen Ödnis ist wenig bekannt, da es lediglich dem Missionar Justanian Hertesin gelang diesen Orkstamm zu finden.

Justanian selbst konnte lediglich über sein unvervollständigtes Werk, welches man in der Nähe von H'abunaptra - dem Heiligen Berg der Rah Kari- fand, sein Wissen Mitteilen.

> "Ein jeder kennt Orks. Grau, grün oder rot. Alle Stark im Körper und schwach im Geiste. Nun sind diese Orks anders. Sie scheinen eine Kultur zu besitzen, welche davon ausgeht, dass ihre Schaffung Absicht war und ihr Gott im Kampf mit dem Tod seine Macht verlor. Hierbei sei angemerkt, dass ihr Gott keine Gestalt hatte und auch nichts von ihnen verlangte. 
Man möge hierbei Staunen, dass diese bleichen Orks, welche sich als Urk-Shum-Toks bezeichnen in weitestgehendem Frieden leben und wenig von den barbarischen Verhalten zeigen, das die anderen Orks aufweisen. Ihre Gottheit ward verschwunden und habe den Orks selber aufgetragen ihrem Leben zu dienen.
Dadurch lebten die Orks in weitestgehender Harmonie. Ressourcen wurden fair aufgeteilt, der ganze Stamm, welcher einem polyamörsen Unzuchthaus gleichte, zeigte auch mir gegenüber keinerlei Gewalt, obwohl ich scheinbar der erste hellhäutige Mensch wart, den diese Orks erblickten. Ihre Intelligenz und auch ihr Charisma wart gleichwertig einem gebildetem Bürger des Kaiserreiches und doch Grund verschieden.
Ein Wunder welche Freiheit ihr Gott diesen Ungläubigen gegeben hat."
>
> ---  Justanian Hertesin in "Die bleichen Orks"




## Die Legenden


## Individuelle Eigenschaften der Orks (Umbennen für jew. Rasse)


## Die Eigenbegriffe der Orks

## Ausrüstung



## Jagdstrategien



## Die Orks untereinander



