---
editor_options: 
  markdown: 
    wrap: sentence
---

# Die Goblins

> "Diese kleinen und irgendwie hässlichen Wesen, sind weder robust noch stark, doch all diese Unfähigkeiten gleichen sie durch ihre agile und hinterhältige Natur aus. Goblins brillieren, wo andere Rassen verzweifeln - nachts und in dunklen Tunneln. Nur jene, die noch nie auf eine Horde Goblins getroffen sind, halten Elfen für die Könige der Nacht. Denn im Unterschied zu den Elfen gibt es vor den Goblins kein Verstecken."
>
> Travius Tandemus Sekundus Geistllicher der Ekkletia

Auf den Reisen durch Orbis Astea trifft man allerlei Bewohner. Zu den haarlosen Vertretern gehören die Goblins. Diese in Stämme organisierten humanoiden leben zumeist Untertage in riesigen Stämmen. Ist man an der Oberfläche unterwegs, hat man zumeist wenig von Goblins zu befürchten. In den Städten haben Goblins meist keine höheren Positionen inne und dienen eher als Aufklärer oder Tagelöhner. Sei es das Reinhalten von Kanalisationen, Spähtruppen oder schlicht als Händler für Absurditäten. Sollten man sich doch feindlich gesinnten Goblins gegenüberfinden, so kann man sich auf Hinterhalte, vergiftete Pfeile und Bolzen und durchgeschnittene Kehlen in der Nacht einstellen. Dank ihrer Thermalsicht sind diese schmächtigen grau-grünen Humanoiden für Hinterhalte auch physiologisch bestens ausgestattet. Zur Bekämpfung der Goblins empfehlen sich Turmschilde, schwere Rüstung und die Verwendung von guten Antipyretika Tränken. Letztere machen den Trinkenden für Goblinaugen deutlich schwerer sichtbar.


Die Gesellschaft – das soziale Untereinander der Goblins
Goblinstämme sind die hauptsächliche Organisationseinheit. Der Stammesschamane bildet das religiöse und seelische Oberhaupt eines Stammes, während sich der Stammeshäuptling hauptsächlich um die organisatorischen Aufgaben kümmert. Als Besonderheit bei Goblins gilt die Faasksitaar, die Stammesmutter, welche alleinverantwortlich für das Gebären von Goblineiern ist. Aufgrund ihres schmerzhaften Verwandlungsprozesses, ist allerdings von ihr nur mehr der basalste Rest eines Vernunftbegabten verstanden vorhanden, wodurch die Geschicke zwischen Schamanen und Häuptling defakto gelenkt werden. Untertage sind Goblinstämme meist deutlich größer als an der Oberwelt. Megastämme, allen voran um die Nachtberge beherbergen teils etliche Stammeshäuptlinge und Stammesschamanen und werden dadurch auf mehrere hunderttausenden Mitglieder geschätzt.

Diese äußerst dünne Schicht an „Königen“ werden allerdings von den einfach arbeitenden Goblins getragen. Der Grundstock, bei Menschen häufig als Pöbel bezeichnet bilden bei den Goblinstämmen den Sammlern, Erntern und Faask Versorgern. Die niederste Gruppe sind die Minenarbeiter, häufig Dreckschaufler genannt.

### Sammler – Die Sucher in der Finsternis
Eine Mischung aus Schatzsucher und Jäger werden die Sammler ausgesandt um außerhalb der etablierten Bereiche des Stammes nach wertvollem zu Suchen. Seien dies die Jagd nach Tieren, das Stehlen von Zwergenwaffen, das Ernten besondere alchemistische Zutaten oder die Erbeutung wertvoller Kleidung – all dies wird explizit von den Sammlern besorgt. Dabei sind Sammler, im Gegensatz zu den Erntern größeren Bedrohungen ausgesetzt und verzeichnen teils große Verluste in der eigenen Gruppe. Sich selbst bezeichnen Sammler häufig als „Näher an Gob, als der Schamane“, insbesondere wenn gefährliche Aufträge erledigt oder Gegenstände gefunden werden müssen.

### Ernter – Bauern der Goblins
Einer der sichersten Gruppen bei den Goblins ist die der Ernter. Diese versorgen die Zinoberpilz-Farmen, halten Vielschreiwürmer. Neben diesen Aufgaben kümmern sich die Ernter um frisch geschlüpfte Goblins, bis diese nach 3-5 Jahren selbständig durch das Leben schreiten können. Dabei wird nicht zwangsläufig eine enge Bindung zu den Ziehkindern aufgebaut, da das Aufziehen als Gruppenaufgabe gesehen wird. Weiters stellen die Ernter den regulären Nährschleim für die Eier her.

### Faask Versorger – Versorgung des Nachwuchses
Da im Durchschnitt ein Ei 2 Jahre benötigt, um zu schlüpfen und in dieser Zeit wöchentlich der Nährschleim erneuert werden muss, während eine Faasksitaare bis zu einem Dutzend Eier am Tag legt, ergeben sich unvorstellbare Mengen an Eiern. Diese müssen nicht nur mit frischen nährschleim versorgt werden. Der alte nährschleim muss entsorgt werden, Pilzbefall verhindert und Eier im Idealfall umgeschlichtet und untersucht werden, um beschädigte zu entfernen.
Dezidiert versorgt werden die besonderen Eier, welche mit Faasksitaarengelee ernährt werden. Hier sind sowohl der Stammesschamane als auf die Diener Gobs Willen gelegentlich involviert und fachsimpeln über die besten Methoden.

### Dreckschaufler – Minenarbeiter
Die unterste Gruppe eines Stammes bilden die Minenarbeiter. Neben der körperlich schweren Arbeit von Wohnhöhlen in den bloßen Felsen zu schlagen, ist auch das Errichten neuer Stollen oder das beistigen des sandigen Steinwurmkotes ihre Aufgabe. Dadurch meist an der vordersten Front unterwegs und mit oft wenig Begleitschutz verzeichnet diese Gruppe die höchste Sterblichkeit, bedingt durch die Felsstürze oder Abscheulichkeiten und auch den geringsten Respekt in der Gruppe. Hierbei werden meist körperlich schwache Goblins oder mit anderen Nachteilen, wie schwacher Thermosicht oder Taubheit der Gruppe zugeordnet.

### Die Krieger
Einfach erklärt ist die Kriegergruppe. Das Bekämpfen feindlicher Stämme, feindlicher Faasksitaaren, Monstern, Lindwürmern oder zu gierigen Zwergen wird von den Kriegern vollführt. Die Kriegergruppe wird aktiv, sofern der Stamm selbst direkt bedroht wird, oder der Schamane und der Häuptling im Einklang Aufgaben erteilen. Meist mit Fernkampfwaffen und Giften bewaffnet, ziehen diese dann durch die Höhlen oder die Oberwelt, um größere Bedrohungen zu bewältigen.

## Die höheren Positionen in den Stämmen
Die wichtigsten Positionen in einem Goblinstamm sind die der Faasksitaare, des Stammesschamanen und des Häuptlings. Die sonstigen höheren Gruppen in den Stämmen setzen sich aus den Wachen der Faasksitaare, Sammler der Faasksitaaren, Schamanenhelfer und den Kriegern zusammen.

### Sammler der Faasksitaaren
Entgegen der Vermutung, sammelt diese Goblingruppe keine Stammesmütter ein, sondern sucht im Auftrag des Stammesschamanen nach den besonderen Zutaten für das Faasksitaarengelee. Diese Aufgabe ist meist gefährlich und führt Goblins immer wieder an die Oberfläche. Ihre Lebensdauer ist im Schnitt kürzer als die anderer Goblins, jedoch können diese sich den höchsten Ehren in den Stämmen zuteilwerden lassen, wenn ihre Suche von Erfolg gekrönt ist.

### Schamanenhelfer – Diener von Gobs Willen
Ein Schamane alleine kann nicht die religiösen Bedürfnisse von mehrere tausend Goblins befriedigen. Die Suche nach Gob, die Ehrung von Gob wie auch die Einhaltung der Festtage und der Riten gehören zu den Aufgaben der Schamanenhelfer. Als Gegenstück zum Allgott der Kaiserlichen, findet sich Gob im Alltag der Goblins wieder. So werden spenden an Gob, die Wartung der Kultstätten oder das Verbreiten der Lehren der Religion „Gobs Wille“ von dieser Gruppe übernommen.

### Die Wachen der Faasksitaare
Die Elitewache, vergleichbar mit den Wachen der Hohepriester der Rahkari, dient dem Schutz der Faasksitaare. Ihre Aufgabe besteht zum allergrößten Teil die Faasksitaare zu beobachten, Auffälligkeiten dem Stammeschamanen zu melden, und all jene fernzuhalten, welche der Faasksitaare Schaden wollen.
Die Faasksitaarenwachen werden immer aus den Eiern, welche mit Faasksitaarengelee versorgt wurden, gezogen. Dieses gibt den darin wachsenden Goblins deutlich mehr kämpferische und regenerative Fähigkeiten als dies von normalen Goblins zu erwarten wäre.

### Die Stammesmutter- Faasksitaar
Die Faasksitaare, als meist einzig Verantwortliche für die Produktion des Nachwuchses steht theoretisch an der Spitze eines Stammes. Obwohl ihre intellektuellen und sprachlichen Fähigkeiten nicht hilfreich sind, um einen Stamm zu leiten, ist es die Produktion der teilweise ein Dutzend Eier pro Tag, welche ihre Rolle im Stamm zementiert. Für die Goblins selbst, welche die Faasksiaare nur äußerst selten überhaupt sehen, hat diese einen hohen emotionalen Wert. Als Zeichen der Hingabe für den Stamm die schrecklichen Schmerzen über Jahre hinweg zu ertragen, wird versucht ihr Geschenke zu machen, welche der Stammesschamane entgegennimmt. Diese Trennung des gemeinen Fußvolkes von der Faasksitaar, dient eher zum Festigen der des Glaubenskonstruktes der Goblins. Defakto ist deren „Heilige“ ein übel gelauntes etwas, auf welches der Stamm und insbesondere der Stammesschamane angewiesen ist.



## Stämme mit und ohne Faasksitaare – Gob Saiks und VrakSaiks.

### Gob Saiks
Für das Überleben eines Goblinsstammes sind die gebärenden Faasksitaare unerlässlich. Stämme, welche es sich leisten können, eine oder mehrere Faasksitaare zu halten werden Gob Saiks genannt. Im Gegensatz zu den faaskstiaarlosen Vrak Saiks können Gob Saiks teils eine Million Mitglieder umfassen. Die häufigste Stammesgröße ist allerdings eher mit einer Faasksitaar. Die Gob Saiks sind dementsprechend mit den allgemein bekannten Goblinstammestrukturen ausgestattet. 

### Vrak Saiks
Fehlt die Faasksitaare werden Stämme als Vrak Saiks bezeichnet, was so viel wie „Mutterlose“ bedeutet. Dies ist zwar im regulären Sinne nicht korrekt da Goblins über die Faaskitaare geboren werden, jedoch obliegt die Kontrolle nicht dem Stammesschamanen. Die häufigste Variante ist ein Handel mit oder Diebstahl der Eier von anderen Stämmen. 
Obwohl das Verhältnis häufig neutral ist sind insbesondere Vrak Saiks an der Erdoberfläche bekannt für ihr brutales Vorgehen gegen ihre sonnenarmen Zeitgenossen.
Als Splittergruppen, welche sich an der Oberwelt niedergelassen haben, spüren diese Gruppen den Hass der Unterweltstämmen. Manche Goblinschamanen verfluchen die Vrak Saiks im Allgemeinen als Verräter und Ketzer, da diese Gob im Lichte oder ohne „Mutter“ nicht ehren können. Die Vermischung mit den anderen Spezies führt auch zum Ausplaudern von Geheimnissen der Goblins und bedrohe das Überleben der Stämme. Andere sehen es differenzierter und sehen diese als nützliche Vorposten und potentielle Verbündete, oder zumindest als nicht zu fütternde Tunnelgräber.
Die Vrak Saiks selbst sind meist kleine Gruppen von Goblins welche als Opportunisten durch die Welt streifen und so jenen dienen welche ihnen die beste Bezahlung bieten. 
Das Vorgehen ist hierbei äußert brutal. So Jagen die Vrak Saik explizit die Faasksitaaren Sammler, foltern diese, um wichtige Informationen über die Stämme zu erhalten. Als grotesker Schlüssel nutzen diese dann die getöteten Faasksitaaren Sammler Goblins als tickende Zeitbombe, welche nach 2-3 Tagen aufersteht und so durch die Tunnel streift. Hierbei werden die Köpfe der armen Seelen abgeschlagen, was diese deutlich schwerer zu töten macht. Für die körperlich schwachen Goblins ist dies eine besondere Herausforderung, da die Erwachten sowohl Eigelege vergiften als auch normale Goblins mit Krankheiten anstecken können.
Der Tumult mit den Erwachten wird von den Vrak Saik Goblins ausgenutzt, um weitere Goblins zu meucheln oder Eier, Faasksitaarengelee oder andere Gegenstände zu stehlen.

Je nach Vraik Saik ist auch das Verhältnis zu den anderen Humanoiden, friedlich, gleichgültig oder territorial, was dementsprechend zu keinen größeren machtpolitischen Verwerfungen führt, aber zu früheren Ableben mancher Menschen, welche die kleinen Wesen nicht mit ausreichend Respekt begegnet.

> "Wir hatten uns an ihr Nest angeschlichen. Wir würden sie überraschen, dachten wir, das wird einfach, dachten wir. Als wir umzingelt waren und die Bolzen von allen Seiten aus der Finsternis kamen wussten wir, dass nicht wir die Jäger waren."
>
> --- Die letzten Gedanken von Brago Tachus, Abenteurer


## Ablauf eines Tages eines typischen Goblins:

Durch das Leben Untertage haben die meisten Goblins andere Rhythmen, welche nicht durch den Wechsel von Tag Nacht oder Winter/Sommer geprägt sind. Vielmehr besteht das Leben aus einem, idealerweise freiwilligen Wechsel von Schlafenzeiten, Ruhezeiten und Arbeitszeiten. Zumeist erfordert allerdings die Arbeit straffere Organisation. Diese wird in Schichten geführt und von der Fackelfarbe in der Haupthöhle bestimmt. Wenn die Farbe der Fackel der Farbe des Schultertattoos übereinstimmt, ist Arbeit angesagt. Dadurch kann, solange kein Goblin sein Tattoo übermalt, gut überprüft werden, wer wann zu Arbeiten hat. So beginnt, nach dem Aufwachen der „Tag“ meist mit einem einfachen Frühstück und dann dem Weg zur Arbeit der Gruppe, sei dies nun das Leben eines Ernters oder das eines Dreckschauflers. Dort wird über etliche Stunden die Arbeit verrichtet, bis die Müdigkeit oder Erschlaffung einsetzt. Ob die Arbeitsleistung reicht, entschließt meist die der Häuptling oder sein Gefolge.. Hierbei sind die Goblins untereinander erstaunlich ehrlich und betrügen selten ihre eigenen Gruppen.

In diesen Pausen finden auch die Wechsel der Arbeitsgruppen statt. Nach der Arbeit, kehren die Goblins zurück zu den Haupthöhlen, waschen sich in den Steinpools und kehren für kurze Zeit in Schlafbereiche zurück, wo diese dösen. Anschließend folgt in der Kultstätte „Lotrat“, was ähnlich ist zu dem Tempel und Kirchen der Rahkari und Lehre des Allgotts, ein „Abendgebet“. Daraufhin ziehen sich die Goblins für den richtigen Schlaf zurück in ihre Schlafhöhle. In dieser Schlafhöhle, welche eine rund 4 Meter Tiefe Ausbuchtung in den Felsen darstellt, schlafen die Goblins dann mit ihren engsten Mitgoblins. Hierbei handelt es sich immer um dieselben Mitglieder der eigenen Arbeitsgruppen.
Schlechter gestellte Goblins, welche die Regeln brachen, oder den Stammesschamanen oder Häuptling nicht dienten, verlieren häufig das Anrecht auf Schlaf in den Kojen und schlafen auf Nackten Boden, meist an der äußeren Grenze der Stammeshöhle.

Feierlichkeiten, trotz des Lebens in ewiger Finsternis, sind auch Goblins nicht fremd. So wird häufig der Tag an welchem eine Neue Faasksitaar ihr erstes Ei gelegt oder der erste Goblin einer neuen Stammesmutter schlüpft, gefeiert.  Neben etlichen unfixierten Festen sind die sonstigen Taktgeber oder das Ansteigen der Pegel der unterirdischen Flüsse und Seen, was durch Starkregenereignisse oder in den nördlicheren Höhlen, durch die Schneeschmelze ausgelöst wird wie auch das Erlegen manch großer Bestien Untertage.  Überlieferungen zufolge werden auch Feste gefeiert, wenn die Bewegungen von Weltenwürmern wahrgenommen werden, womit meist die Erkundung neuer Bereiche einfacher ermöglicht wird. Die religiösen Anwandlungen, dass gewisse Würmer als Reinkarnationen oder heilige Vertreter Gobs gelten, unterstreichen diesen Feierlichen Aspekt und in Ekstase haben sich schon so manche Goblinstämme vor ihre Heiligen geworfen.
Ebenfalls religiös ist das Fest, an dem die Pilger der Goblins, auf der Suche nach ihrem verlorenen Gott „Gob“ mit Wärmefarbe markiert werden und in die weite Unterwelt entlassen werden.


## Physiologie der Goblins
Als Besonderheit im Gegensatz zu den anderen Rassen, ist die Kombination der Sinnesorgane für ihre Weltwahrnehmung. So nutzen Goblins ergänzend zur normalen menschlichen Sicht neben der Thermalsicht auch Klicklaute und Fackeln und die schwachen Lichtquellen der weit verbreiteten Brent-Würmer, welche sich an von Steinwürmern gegrabenen Rändern der Höhlen niederlassen. Obwohl sich Goblins an das merklich stillere Leben untertage gewöhnt haben, sind Goblins allerdings nicht lärmempfindlicher als die anderen Humanoiden.
Damit ist es Goblins möglichst in der schwärzesten Höhle auch sicheren Trittes an ihr Ziel zu kommen.

Der Durchschnittliche Goblin ist etwa so groß wie ein Jugendlicher Mensch. Neben der humanoiden Grundform enden aber hier bereits die Ähnlichkeiten. Der Kopf der Goblins, von der Farbe her wie der restliche Körper meist in Grün- und Grautönen gehalten, weist große, spitz zusammenlaufende Ohren auf, welche die Wahrnehmung von Geräuschen vermutlich verbessert. Ihre Zähne sind eine wilde Mischung aus Spitzen Vorderzähnen und flachen Kauzähnen im hinteren Teil des Gebisses. Ihre Augen wirken fremdartig aufgrund ihrer dunkelgrauen bis schwarzen Färbung.
Der restliche Körper ist schmächtig dünn und weist leicht verlängerte Zehen auf.
Das auffälligste Merkmal oder besser gesagt die Ermangelung dessen ist die unglaubliche Ähnlichkeit innerhalb der Goblins. Die sich nicht auf ein „für mich sehen alle Orks gleich aus“ beschränkt, sondern schlicht den Tatsachen entspricht. Jedoch wird dies ausgeglichen durch den Hang der Körpermodifizierung, welche fast alle Goblins pflegen, seien es nun Schmuck oder Tattoos oder sogar Narben und andere Verzierungen in der Haut.
Ein besonderes Merkmal ist die „Geschlechtslosigkeit“ des überwiegenden Teils der Goblins. Bei Menschen kommt im Schnitt auf eine Frau ein Mann. Bei Goblins ist dieses Verhältnis gravierend anders. So sind fruchtbare Goblinweibchen äußerst selten und vermutlich jede 1000 oder 5000ste Goblin wird tatsächlich zu einer gebärenden Frau oder Stammesmutter.
Hier darf sich der gewiefte Leser allerdings keine Frau im eigentlichen Sinne vorstellen, sondern eine groteske Monster Variante, welche wage an einen Goblin erinnert.
Die „Stammesmutter“ oder in der Sprache der Goblins genannte „Faasksitaar“ ist mehrere Meter groß. Ihre Oberarme sind in Länge und Muskelmasse weit über jenem was selbst die stärksten Orks zu bieten haben. Ihr Kopf erinnert noch von der Form her an Goblins, wenn auch deutlich gewachsen und von stark gedehnter Haut bedeckt. So wie die restlichen Goblins sind die Faasksitaars am Kopf kahl.
Die Beine sind im Verhältnis zu den Oberarmen beziehungsweise dem Brustbereich schmächtig und können alleine den monströs aufgedunsenen Körper kaum längere Zeit stützen. Dadurch kann die Faasksitaar zwar theoretisch aufrecht laufen, jedoch, bedingt durch die niedere Deckenhöhe vieler Höhlen eher nur wie ein beinloser Mensch robben. Auf dem Rücken befindet sich die stark geschwollenen Organe zur Produktion von Eiern. Im „Erntereifen“ Zustand erinnert der Rücken an gelb-grüne Pestbeulen, welche tatsächlich aber die lederartig umhüllten Faask, also Goblineier, sind.
Die Zentnerschwere geschwollenen Eiorgane am Rücken der Faasksitaar sind in einem grau-rötlichen Ton gefärbt und meist von Narben übersäht. Von der Konsistenz her ist dieses Eiorgan an Fettgewebe eines untrainierten Menschen erinnernd.
Die Stammesmutter verliert im schmerzhaften Prozess der „Formung“ von einem Goblin zur Faasksitaar viele ihrer „menschlicheren“ Eigenschaften. Ihr Aggressionslevel nimmt im selben Maße zu, wie ihr Intellekt abnimmt. Der Vergleich mit einem viel zu starken halbstarken 15 Winter alten Menschen liegt da Nahe. Triebe lassen die Faasksitaar die meiste Zeit nur fressen, rumliegen, Eier gebären oder sich zwecks der Fortpflanzung mit Goblins Vergnügen.
Das Gebären der Kinder ist, wie bereits zu erahnen nicht in Lebendform, wie dies bei Menschen der Fall ist, sondern in Form von den Faask genannten Eiern welcher mit einer lederartigen Haut überzogen sind. Diese Eier produziert die Faasksitaar auf ihrem stark verlängerten Rücken, wo diese von den Goblins „Faask“ genannten Eier dann von einer dezidierten Goblin Berufsgruppe mittels Werkzeugs und Krafteinsatz herausgezogen werden.
Für die Faasksitaar ist dieser Prozess unangenehm im besten Fall und sehr schmerzhaft im schlechtesten.
Die geernteten Eier werden dann zu Bruthöhlen gebracht. Dort lagern die Eier dann für rund 2 Jahre und werden wöchentlich mit einer Art blauem Nährschleim versorgt. Dieser ist notwendig, dass die Eier nicht verhungern, beziehungsweise austrocknen. Der Lebenszyklus einen Goblins beginnt vom Schlüpfen aus dem rund 40-70 cm großen Ei. Goblins sind beim Schlüpfen, je nach Ernährung Status und Glück rund 90 bis 100 cm. Im Laufe von 5-10 Jahren wachsen die Goblins langsam auf eine Körpergröße von rund 130 bis 150 Zentimeter, wobei der Durchschnitt eher im unteren Bereich dieser Skala angesiedelt ist.
Bereits 3-4 Jahre nach der Geburt beginnen die jungen Goblins damit Aufgaben im Stamm zu übernehmen. Sei es die Reinhaltung der Wohnhöhlen, das Sammeln und Ernten von Nahrung in sicheren und etablierten Bereichen der Höhlen oder das Versorgen von älteren oder erkrankten Goblins. Nach dieser Zeit Arbeiten die Goblins meist in den dezidierten Gruppen und bleiben diesen in den meisten Fällen treu. Die Zuordnung erfolgt nicht auf den eigenen Wunsch des Goblins hin, sondern nach Zuordnung des Goblinhäuptlings oder seinen Untergebenen.

Die Herstellung des Nährschleims für die Eier wird über die Vermengung mehrerer Pilze und Steinwurmfleisch, also Grundzutaten, welche man in Höhlen einfacher findet, sichergestellt. Diese Bottiche beziehungsweise aus dem Boden geschlagenen Steinpools werden gut bewacht und gewartet, hängt doch das Überleben des Stammes davon ab, dass dieser Nährschleim die wehrlosen Eier mit Energie versorgt, da diese ansonsten nach runden 2 Monaten verkümmern.

Für den kontinuierlichen Nachschub an frischen Eiern sorgt die Faasksitaare, welche sich mit von ihr oder dem Stammesschamanen auserwählten „Geschlechtslosen“ Goblins verpaart. Dieser Prozess besitzt auch nichts anmutiges, sondern gleicht eher einer animalischen Begattung: kurzes Bespringen vollführen des Aktes und Rückkehr in den Alltag.

Die wenigsten erzeugten Eier haben allerdings das Potential, eine Faasksitaare zu werden. Der geringe Prozentsatz an Eiern, welche die Mutation aufweisen, um daraus eine Faasksitaare zu gestalten muss mit einem besonderen „Faasksitaarengelee“ versorgt werden, anstatt des normalen Nährschleims. Dieser löst dann biologische Veränderungen dieser speziellen Goblins aus. Bei dem Schlüpfen aus dem Faask ist allerdings noch immer nicht zu erkennen, ob nun eine Faasksitaar daraus geformt werden kann. Erst nach 5 Jahren lässt sich erkennen, anhand einer Y-förmigen roten Narbe auf dem Bauch, wodurch der Goblin über Jahre dann zu einer Faasksitar gezogen wird.
Dieser Prozess, welcher vom Stammesschamanen geleitet wird, ist für den Goblin selbst schmerzhaft. Unter der Gabe von betäubenden Pilzen werden Knochen gebrochen. Zuerst werden die Obermarmknochen gebrochen und auseinandergezogen, dass Stück für Stück die Oberarme länger werden. Selbiges wird alllerdings weniger häufig an den Beinen durchgeführt. Dies führt, was als „Knackzeit“ bekannt, zu Vernarbungen, Infektionen und etlichen durch Schmerzen bewusstlosen Nächten zu dem typischen Arm und Beinform der Faasksitaare. Der Rücken wird mit speziellen Wurmsalben dazu gebracht erneut zu Wachsen. Diese Würmer fressen sich in die Haut und Knochen des Rüclens der Goblins und verursachen das Weichwerden der Wirbelsäule des Goblins. In dieser Phase kann der Goblin sich kaum mehr bewegen und liegt häufig nur herum. Nach Monaten der Dehnung und dieser Wurmkur ist der Rücken massiv länger als die natürlicherweise der Fall wäre. Die teils bis auf den Muskel eingerissene Haut wird mit der Haut von geopferten Goblins ergänzt, was häufig zu neuen Infektionen führt. Die Y-Förmige Narbe auf dem Bauch wird mit einem Messer geöffnet und im Bauch des Goblins das reifende Eiorgan abgesehen von den Blutgefäßen unter den weichen Rippen aufgeteilt und durchgeschoben, wodurch die einzelnen „Eileiter“ dann am Rücken Enden, wo dieser erneut vernäht werden. Nach einer Verheilungsphase von mehreren Monaten steht am Ende eine fruchtbare und furchtbare Faasksitaar. Dieser schmerzhafte und unschöne Prozess führt zur geistigen Verkümmerung und allgemeiner schlechter Laune der Faasksitaaren.


Daraus ergeben sich für Goblinstämme Probleme. 
Zum einen kann diese anfangs zwangsgefütterte Faasksitaare enorme Mengen an Nahrung verschlingen, welches für kleine Stämme ein logistisches Problem sein kann, zum anderen führt die schlecht gelaunte Faasksitaare schnell zu ein paar toten Goblins. Weiters ist das deuten der Wünsche der geistig verarmenden Faasksitaare über die Zeit zunehmend schwerer. Häufig ist die Interpretation dem geistigen Anführer eines Stammes, dem Goblinschamanen überlassen. Gleichzeitig legen aber ältere Faasksitaaren aber größere Eier, woraus körperlich stärkere Goblins heranwachsen können. Dies wiederum verleitet manche Schamanen die Faasksitaaren so lange am Leben zu lassen, oder diese gar zu fesseln um damit die Faasksitaaren nicht unnötig viele Goblins töten. Problematisch ist dies insbesondere, wenn eine wütende Faasksitaare dann beschließt, dass der Stamm ihrer Anmut nicht würdig ist und zunehmend mehr Goblins tötet, da diese nicht genug oder nicht die richtige Nahrung heranschaffen, oder das kopulieren unzufriedenstellend ist. Dann braucht es mehrere dutzend Goblins, um die Faasksitaare zu überwältigen oder im Notwendigen Fall zu töten.

Es kommt äußerst selten vor, dass ein größerer Stamm mehrere Faasksitaaren zu versorgen hat. Dies ist, sofern die Logistik, welche der Stammesführer zentral steuert, kein Problem, solange ausreichend gute Nahrung für die Faasksitaare bereitgestellt werden können. Ist dies nicht mehr der Fall können sich auch Faasksitaaren gegenseitig bekämpfen. Zum Unterbinden dieser Kämpfe werden teils hunderte Goblins geopfert, was den Wert dieser monströsen „Mütter“ für einen Stamm vermittelt.
Da wie oben erwähnt nicht alle Eier, welche mit Faasksitaarengelee versorgt werden tatsächlich Faasksitaaren werden, können sich die restlichen Ungeborenen Goblins auf ein Lebens als „Elitewache“ der Faasksitaare freuen. Die im Durchschnitt etwas größeren Goblins, sind von der Statur her kräftiger und kämpfen dadurch besser und vehementer.
Das Faasksitaarengelee selbst gilt auch bei den bereits geschlüpften Goblins als Delikatesse, wenn es in kleinen Mengen genossen wird. Zwar wie der normale Nährschleim für andere Rassen auch giftig, befähigt dieser Schleim angeblich die Fertigkeiten eines Goblins für rund eine Stunde. Gewarnt werden sollte allerdings davor, zu viel von diesem Faasksitaarengelee zu essen, da dann Effekte wie bei Missbrauch von Madnika auftreten können. Verlust des Realitätsbezugs, Aggression, Idiotie seien hier warnend erwähnt.

Da Goblins zwar für andere humanoiden Rassen sich alle gleichen, aber für Goblins sehr wohl Unterschiede zwischen den Individuen bestehen, ist es weniger verwunderlich, dass jeder einzelne Goblin auch seine eigenen Ziele Pläne, Hoffnungen und Träume hat.

> „Natürlich würde ich gerne eine schönere Höhle haben, oder die Lichtwelt sehen. Nur wie soll ich das Anstellen? Sowohl meine Sammlerkollegen brauchen mich wie auch die Mutter und der Schamane selbst. Soll ich allein durch diese Höhlen wandern, nur dass Gob mich verschlingt? Oder ich an der Oberfläche von einem von euch dann aufgespießt werde? Oder gar als Erwachter dann meinen Stamm ins Unglück stürze? Nein. Ich denke, hier ist zwar nicht alles perfekt, aber besser als das Ungewisse da draußen.“
>
> - Goblin aus dem Tiefenstamm der Dunstspitzen

Dadurch ist es möglich, dass sich einzelne Gruppen von Goblins abspalten und versuchen ihren eigenen Stamm zu gründen - Sei dies unter der Erde, oder von höhlen bewohnenden Goblins gehassten Oberweltstammgoblins. Diese Stämme sind häufig deutlich kleiner und Aufgrund des Fehlens der Stammesmutter nicht in der Lage sich zu reproduzieren.
Während Untertagesplitterstämme, Gob-Saiks genannt, häufig mit den anderen Stämmen Handel treiben, um Eier zu erhalten, müssen die Oberweltstämme, Vrak-Saiks genannt auf plündern, Hinterhalte, Erpressung oder sonstiges zurückgreifen um an frische Eier zu kommen. 

## Religion – Gobs Wille
Der Ursprung der Religion der Goblins ist ihren Überlieferungen zufolge in der Verdrängung von der Oberfläche zu finden. Laut dem wichtigsten Schriftwerk der Goblins „Gobs Wille“ zwang die Verdrängung durch andere Humanoide die Goblins dazu Untertage auskommen zu müssen. Dies war, Anfangs ein äußerst schweres Unterfangen. Neben einer gänzlich unbekannten Welt war die Dunkelheit ein großes Problem. Fackeln brachten einen nur so lange voran, wie die Fackel brannte, war diese einmal erloschen war man verdammt. Als leichte Mahlzeit für zwischendurch war ein Goblin eine willkommene Abwechslung für Lindwurmer und Höhlenspinnen.
Als ritueller Ort für verzweifelte Stämme um ihre Opfer an Goblins darzulegen war die schwärzeste und tiefste Höhle „Gob“ ausgewählt. kranke Goblins, schwache Goblins wie auch gesunde wurden von den Schamanen geopfert, damit die alten Götter die Oberflächen Bewohner von der Erde fegten.

Laut den Überlieferungen von „Gobs Wille“ wurden die geopferten Goblins „immer wieder von der Höhle verschluckt und sie ertranken in dem sauren und warmen Wasser der schwärzesten Höhle. So war es die Aufgabe der Goblins in den Himmel von Gob zu starren und so endlich wieder zwischen den Sternen zu sein, um die Seele dort hinzuverfrachten“.
Die wenigsten Goblins, die von besonderem Herz überlebten das verschlungen werden der Höhle mit einem Geschenk von Gob. Sie konnten in der Finsternis sehen. Sie konnten andere Goblins in der schwärzesten Nacht vernehmen.
Sie konnten auch die wahren Ausmaße von Gob besser vernehmen. Es handelte sich um keine Höhle, sondern um einen gigantischen Wurm und welchen Verdauungssäften sie badeten. Für diese neuen Goblins, laut den Stammesschamanen gezeichnet durch die Fähigkeit der Wärmesicht und dem Mangel an Frauen, brach ein neues Zeitalter an. Plötzlich war durch Gob die Beherrschung der Höhlenwelten möglich. 
Allerdings hatte dies einen Preis. Die allerwenigsten Goblinfrauen überlebten das verschlungen werden von Gob. Die wenigen welche den sauren See überstanden waren für den Erhalt des Stammes verantwortlich. Erst durch die Entdeckung des Faasksitaarenschleims konnten die wenigen Frauen ausreichend Kinder gebären. Für den Stamm waren diese unersetzlich und ihnen wurde jeder Wunsch von den Augen abgelesen, damit diese möglichst viele Kinder gebären.

Eine grausame Wendung nahm die Geschichte der Goblins und Gobs in den Nachtbergen. In grauer Vorzeit wurden Goblins, nach der Veränderung von Gob versklavt und wie Vieh gehalten umso für die gierigen Zwerge wichtige Ressourcen zu ernten und die Seelen der Goblins zu schänden. Die Zwerge kreuzten die Goblins wie Vieh und probierten Goblinfrauen zu schaffen welche mehr und mehr Kinder gebären. Der Goblinführer der versprengten freien Goblins wollte diese Untat der Zwerge nicht hinnehmen und überrannte und überwältigte die Zwergenenklave in den Nachtbergen. Er tötete alle Goblins welche mit den Zwergen kooperierten und nahm auch notgedrungen die gebärfreudigen Faasksitaare in den Stamm auf, waren doch diese überlebenswichtig für die Goblins.
Die geschundenen Faaasksitaare wurden dem Stammesschamanen überlassen, damit dieser für das geistige Wohlbefinden sorgen konnte.
So wie damals sind auch heute noch die Stammesschamanen dafür verantwortlich die Faasksitaaren bei Laune zu halten, um so noch mehr Kinder zu gebären.

Nach dem Verschlingen durch Gob und der Geburt der ersten Kinder der Verschlungenen, begann die neue Ära. Sie nannten sich fortan Goblins, oder Kinder Gobs.

Seit dessen ist es für einen Stamm Pflicht, sobald eine Faasksitaare das erste Ei legt, eine Höhle zu Gobs Ehren „Lotrat“ genannt zu errichten. Diese Höhlen sind immer ähnlich aufgebaut. Ein dutzende Meter langer und tiefer künstlicher Gang wird in den Felsen gehauen. Leuchtende Brentwürmer werden gesammelt und an den Decken der Höhle, insbesondere über dem extra angelegten See, angesiedelt. Die Wände werden mit schwarzer Farbe ausgemalt. Der Eingang markiert von schwarzen spitzen dolchförmigen Steinen ist ebenso in schwarz gehalten. Hinter dem künstlichen Teich ist ein langer sich windender Pfad mit kleinen Vertiefungen, wo die Augen der verstorbenen Goblins hineingeworfen werden. Dies symbolisiert den Verlust und den Gewinn des Augenlichtes.

Der Ausgang der Höhle ist eine zentrale Vertiefung der Haupt- und Schlafhöhle der Goblins und windet sich von unten nach oben. Der Zugang zu der Höhle der Faasksitaare wird am höchsten Punkt der Höhle angelegt, um die Wichtigkeit der überlebenden Mutter des Stammes zu signalisieren und diese vor Wasser zu schützen welches häufig von unten nach oben gedrückt wird.

Die Leichen der Goblins werden, sobald die als das einzigartigste Goblinmerkmal angesehen Augen entnommen wurden und die engsten Gruppenmitglieder Abschied genommen haben und die „Wurmgrube“ geworfen, wo Prudak-Würner die Leichen verzehren. Die Prudakwürmer können so täglich mehrere verstorbene Goblins verschlingen. Die Prudakwürmer selbst werden von den Diener von Gobs Wille regelmäßig eingefangen und zu alchemistische Zutaten, Öl, Medizin oder Nahrung verarbeitet. Aus dem Öl, welches für Außenständige als Goblinöl bezeichnet, werden rauchfreie Fackeln erstellt. Diese rauchfreien Fackeln, so Überlieferungen der Goblins, wurden auch von Menschen geschätzt, welche daraufhin begannen, Goblins explizit für Fackeln und Kerzen zu töten und zu verarbeiten. Im Jahre 426 n. Riga sind allerdings keine Rezepte für Ölgewinnung aus Goblins mehr bekannt, wodurch nicht klar ist, ob Goblinöl von Nicht-Goblins tatsächlich verwendet wurde.

Die Goblins selbst glauben nicht mehr an ein Paradies im eigentlichen Sinne, sondern hoffen, dass Gob ihnen ein weiteres Mal die Goblins verbessert, so dass Sie endlich besser Untertage leben können. Daraus ergab sich auch ein von dem Stammesschamanen „Kult“ der Körpermodifiaktionen, welchen den Wachen der Faasksitaare im direkten Sinne vorbehalten ist. Reguläre Goblins, welche nicht am Faasksitaaren Gelee genährt wurden, beläuft sich die Modifikationen auf Schmuck, Tattoos und verschiedene Körperliche Veränderungen in unterschiedlichsten Varianten, von kunstvollen Narben bis zu kleinen Gegenständen unter der Haut.

Die Trauer um die Toten hält sich meist kurz. Die Dankbarkeit zwischen den einzelnen Goblins auch während ihrer teils kurzen Lebensspanne ist stark ausgeprägt, denn jeder Goblins weiß alleine hätten man keine Chance zu überleben. Weiters haben die meisten Goblins eines Stammes dieselbe Faasksitaare als Mutter, welche deutlich älter wird als die normalen Goblins. Die Akzeptanz des eigenen Ablebens ist insbesondere bei den Krieger- und Dreckschauflergruppen stark ausgeprägt, da diese die mitunter gefährlichsten Aufgaben im Stamm vollführen.
Aufgrund des Ritus der Beseitigung der Kadaver in den Prudakwürmergruben haben Goblinstämme auch nur geringe Probleme mit Erwachten. Allerdings ist es für die körperlich schwachen Goblins schwer die körperlich kühlen Erwachten immer rechtzeitig zu erspähen, um zu verhindern in einen Nahkampf mit der Schattenseite des Lebens zu führen.

Die familiären Ziele sind aufgrund der Struktur mit der Faasksitaare, den Schamanen und dem Stammeshäuptling häufig eng mit den religiösen Zielen verflochten. So ist die Aufzucht der Eier, die Suche nach dem verschwundenen Gob wie auch das Wohl der Faasksitaare an vielen Tagen ein und dasselbe Ziel.
Die Religiösen Feste ehren dementsprechend die einzelnen Arbeitsgruppen oder das führende Trio des Stammes, den Tag der Verschlungenen.

Einflussnahmen des Blutkults oder Blutgötter sind im Verhältnis zur Oberwelt doch deutlich seltener. Die Ursachen liegen womöglich im religiösen Eifer oder der kurzen Lebensdauer oder einer geringeren biologischen Anfälligkeit gegenüber derartigen Phänomenen.


## Beziehungen zu den anderen Rassen
Goblinstämme senden, sofern Sie nah genug an der Oberfläche sind gelegentlich Gesandte an die Menschen und Halblinge. Für viele tiefer gelegene Goblinstämme ist dies aber ein seltenes Ereignis. Eine besondere Rolle nehmen die Handvoll Mega-Stämme (Blaufeuerhüter, Gomraks, Die Erben Gobs und die Allsehenden), welche aufgrund ihrer Hundertausenden Individuen großen Goblinstämme häufige Gäste bei Vertretern des Kaiserreichs oder der Rahkari sind.
Aufgrund ihres Hangs zu dunklen Orten und ihrer Neigung zu Hinterhalten sowie zum Einsatz von Giften, werden sie oft von anderen Völkern für Ungeziefer gehalten, das es zu entfernen gilt. Jedoch scheitern diese Versuche nicht selten. Insbesondere der Hass des Yondalles'schen Volks gegenüber den Goblins ist groß und auf Goblins ist in Yondalla ein allgemeines Kopfgeld ausgesetzt.

Seit der Besetzung durch das Kaiserreich ist dieser Hass abgeebbt, da Goblins, nach herberen Verlusten, sich nicht gegen die schwerbewaffnete Kaiserliche Armee zu kämpfen trauen und sich wieder in tiefere Höhlensysteme zurückzogen.

Besonders erwähnt werden sollte, dass einige Orkstämme Goblins als Nahrung ansehen und diese wie Halblinge auf ihren Festen verzehren. Gelegentlich treffen dann Orkstämme auf Goblin Erkundungstrupps. Für Orks und Goblins sind die jeweils anderen nicht mehr als Gegner, welche man sobald möglich beseitigt.

Speziell hingegen ist der Hass welchen Zwergen entgegengebracht wird. Expansiv wie Zwergenstädte sind, ist es in den Höhlensystemen welche von Weltenwürmer, Aschwürmern oder Steinwürmern gegraben wurden, so dass nicht genug Platz für alle Seiten ist. So sind die Zwerge zwar oft zahlenmäßig unterlegen, jedoch aufgrund ihrer Konstrukte, welche Goblins schlecht sehen können, meist im Kampf überlegen. Zwerge selbst geben keine Gründe bekannt warum diese häufig Goblinstämme versuchen auszurotten oder immer wieder in ihrer Anzahl stark reduzieren.
Goblins selbst, sagen das Zwerge Blasphemische Dinge anstellen und die Leichen schänden.

>„Während die Goblins still andächtig beten und nach einigen Minuten wieder zurück an ihr Werk dem Schaufeln und Hämmern gehen, hört man mit dann hinter den Spitzhaken und Meißeln der Goblins weitaus kräftigere Spitzhaken. Wie ein Donnerschlag auf Stein. Plötzlich bricht im Staub ein Stahlungetüm durch die Wand und von Schräg unten strömt das blaue Licht der Zwergenlampen. Die metallischen Kolosse mit den Spitzhaken weichen zurück und schon fliegen in den Staubschichten die ersten Bolzen der riesigen Ballisten der Konstrukte.  Etliche Goblins werden von dem Bolzen halbiert, ihre Innereien als feiner Nebel versprüht, während die Kriegergruppe auf die Ungetümer zustürmen. Wie Ameisen versuchen diese den riesigen sechsbeinigen Metallkäfer zu überwältigen. Vergeblich. Kleinere Konstrukte, Zwerge gekleidet in fürstlichen Zwergenstahlrüstungen rücken organisiert mit Schilden vor und picken mit den Lanzen die Goblins, welche die Konstrukte auseinander nehmen wollen. Schreie von Goblins, welchen die Beine von den zweiten Bolzen der Konstrukte abgetrennt wurden Hallen durch die Höhle. Das blaue Licht leuchtet nun tiefer in die Stollen der Goblins. Die Zwerge lachen und marschieren weiter und im Hintergrund eine tiefe Zwergenstimme mit den Worten „Ich bezahl euch nicht fürs lachen.“.“
>
> - Bericht von Valus Rinten Elfischer Gelehrter im Auftrag von Calvert während seines Aufhalts bei einem Goblinstamm

