# Mischlinge

Obwohl es nur selten vorkommt, schaffen es immer wieder Wesen unterschiedlicher Rasse Nachkommen zu zeugen. Diese Kinder stellen für die Eltern jedoch nur selten ein Grund zur Freude dar, da an den meisten Orten in Orbis Astea gemischtrassige Familien nicht sonderlich akzeptiert sind. Ein schwer nachvollziehbares Faktum, da sexuelle Verbindungen weitestgehend als unproblematisch empfunden werden. 
Da eine erfolgreiche Befruchtung zwischen den Rassen unwahrscheinlicher ist als eine gleichrassige Befruchtung ist die grundlegende Zahl an Mischlingen schon eher selten. Diese Zahl wird noch weiter verringert, da viele Mischlingskinder als Folge sozialer oder Körperlicher Misshandlung entweder durch sich selbst, ihre Eltern oder ihre Mitmenschen sterben bevor sie voll ausgewachsen sind. 

Nicht alle Rassen sind in der Lage Mischlinge zu zeugen, so sind Zwerge und Orks beispielsweise absolut nicht in der Lage sich mit anderen Rassen fortzupflanzen. Ebenso wurden noch keine Mischlinge gezeugt, die selbst Fortpflanzungsfähig gewesen wären - die Mischlingslinie stirbt also immer mit dem Mischling selbst. Menschen und Elfen scheinen am kompatibelsten zu sein, da die meisten Mischlinge Halbelfen sind. 