# Wirtschaft in Orbis Astea


Waffen Problem:
Kaiserreich & Yondalla: 
Das Kaiserreich will die Anzahl Waffen reduzieren, um Stabilität aufrecht zu erhalten und weniger Waffen an Eldria zu liefern.  Schmiede außerhalb der Kaiserlichen Festungen dürfen maximal 5 Schwerter/Waffen bei sich haben, da es ansonsten als „Organisation zum Aufstand“ angesehen wird, was ein Straftatbestand im Kaiserreich ist.   Folglich können einzelnen Plünderer oder Schwarzmarkthändler kaum ihre Waffen verkaufen oder in größeren Mengen kaufen. Dies führt zu einer gewissen Schwarzmarktnachfrage, was den Export in unstabilen Regionen wie Eldria lukrativer machen würde. Allerdings verhindert ein verpflichtendes Schmiedeemblem, welche meist unheimlich elegant sind und folglich äußerst diffizil zum Herstellen, das billige Unfertigen. Schmiede sind selbst für die den Einsatz ihres Schmiedesiegel verantwortlich und haben dadurch öfters Probleme mit den Behörden des Kaiserreiches falls plötzlich mehr Schwerter unter seinem Siegel auftauchen.
Aus moralischer Sicht ist es für einen Schmied Fragwürdig, wenn ein böser dreinschauender Mensch ihm plötzlich 5 Blutverschmierte und eingedellte Rüstungen samt Haarresten feilbietet.  Hierbei ist es neben der Gesetzlichen Pflicht, welche durch das Kaiserreich durchgesetzt wird, auch relevant, dass die Toten ordentlich beerdigt wurden, da sonst die Untoten in der Nähe die normale Bevölkerung angreifen.  Folglich muss ein geistlicher Vertreter beauftragt werden die korrekte Beerdigung der Toten zu bescheinigen. Gleichzeitig ist dieser Geistliche verpflichtet die Menge an Waffen und Rüstungen dem Kaiserreich zu melden. Dieser „Friedensobolus“ erfüllt also nebst der moralischen Pflicht, die Beseitigung der Leichen sowie der Wahrung des Rechts.

In Eldria, einen noch immer von Guerilla Kämpfen durchzogenen Gebiet, über welches das Kaiserreich noch immer trotzig behauptet „es habe die volle Kontrolle“ ist das Problem umgekehrter Natur.
In Eldria sind Waffen jeder Art heiß begehrt und meist eine Grundbedingung für einen erfolgreichen Guerilla Kampf. Da die Schmiede einigermaßen unter Kaiserlicher Kontrolle stehen und Waffen in schlechter Qualität auf dem weitaus größeren und schlechter kontrollierten Schwarzmarkt ein Problem darstellen, versucht das Kaiserreich mit der „Aufstandregel“ welche die Anzahl der erhältlichen Waffen bei einem Schmied reduziert, dem einem Riegel vorzuschieben. 
Dadurch wird der Handel zwischen dem Kaisserreich und Eldria unterbunden.  Zum einen begrenzt das Gebiet von Silva Nacia den direkten Transport, zum anderen verhindert die gut Kontrollierte östliche Schlauchförmige Region des Grenzlandes einen überbordenden Austausch der Waffen in beide Richtungen.

Rahkari: Monopol über den Waffen/Rüstungspreis.  Der Kult der Meliodas (Händlerkaste) definiert den Preis.  Im Allgemeinen ist dies ein hoher Aufpreis auf eine Verkaufte Waffe. Da Zwerge zwar mit den Rahkari handeln, Eisenrüstungen aber in der Wüste unpraktisch sind, braucht es einen Aufpreis, um die Menge an Waffen niedrig zu halten und nicht die Sklavenkasten zu viele Möglichkeiten für den Widerstand zu bieten. Dadurch verkaufen Händler zwar ihre Schwerter für den Kunden zu „normalen“ Preisen wie im Kaiserreich, allerdings ist der Profit des Schmiedes gering, da die „Steuer“ teils 2500 Reiks, bzw. 5000 Rahkari beträgt. Dadurch bekommen Plünderer und Abenteurer nur geringe Preise für ihr erbeutetes Gut.

Zwerge:
Zwerge hingegen haben eine völlig andere Mentalität.  Die Herrschaft der Zwerge in ihren Festungen im Himmelsspitzengebirge ist uneingeschränkt und nicht relevant durch Scharmützel bedroht. Gleichzeitig spucken die Schmieden der Zwerge Zwergenstahl aus, welche von der Qualität her im Vergleich zu Stahl oder Eisen weitaus überlegen ist, werden die Schwerter aus Eisen und Stahl häufig nur eingeschmolzen, um Daraus Konstrukte zu erstellen, welche ein vielfacher Wertvoller ist und eine Besonderheit der Schmiedehallen der Zwerge darstellt. Da der Handelsweg von den Zwergen weg nur primär zu den Rahkari erschlossen sind, und Stahl in der glühenden Sonne der wüste einfach nur kochend heiß wird, gibt es kaum einen Rückfluss aus theoretisch billigem Stahl in das Kaiserreich, welches diesen heiß begehren würde.

Nebelhain:
Im Nebelhain sind die ökonomischen Aktivitäten im Allgemeinen irrelevant. Der Mangel an Städten oder fixen Händlern ist das Problem. Ein weiteres Problem welche den Waffenfluss zwischen Eldria und den Rahkari hemmt ist der berühmte Nebelhain selbst.  Da weder Infrastruktur noch gesicherte Wege vorhanden sind, ist zwar eine mögliche Gewinnspanne da, allerdings sind die wenigsten Händler bereit dieses Risiko einzugehen.


Seevolk:
Die Primäre Quelle von Waffen und Rüstungen im Seevolk ist wie so oft das Festland. Der berüchtigte Materialmangel und die „Holzsparer zu See“, bekommen die günstigsten Waffen nur indirekt über den Schwarzmarkt der Rahkari. Hierbei nutzen illegale Händler der Rahkari die günstigen Eisen und Stahlpreise der Zwerge aus, um diese dann an das Seevolk im Südmeer zu verkaufen. Da allerdings weder Hochöfen noch Eisenerzminen im Wasser großartig sinnvoll sind, und die ewigen Kämpfe des Seevolks am Meer vermutlich jedes 3 Schwert in den blauen Abgrund des Ozeans reißt, besteht trotz des eigentlichen günstigen Preises der Waffen im Südmeer, im Süd und Nordmeer ein Problem. Die Waffen werden vom Südmeer Richtung Nordmeer immer seltener und von der Qualität immer schlechter.
Gleichzeitig hat das Kaiserreich keine offiziellen Handelsbeziehungen zum Seevolk da diese „Piraten sich an keine Verträge halten wollen“.  Folglich gibt es nur den Schwarzmarktpreis und das was Piraten bei dem Plündern von Salzhändlern oder Fischerdörfern erbeuten.
In der Summe ist der Preis dadurch ähnlich zu dem des Kaiserreiches, allerdings in der Qualität und dem Preis her deutlich schwankender.


## Wirtschaft im Kaiserreich 

## Wirtschaft im Land der Rahkari

## Wirtschaft in Eldria

## Wirtschaft in Eisland

## Wirtschaft der Zwerge

## Wirtschaft ...



