
# Die Elfen von Silva Nacia {#SilvaNacia}

## Die Geschichte von Silva Nacia

Die Geschichte der Silva Nacia Elfen ist ebenso durch die <font color="green">[Entwurzelung](#Entwurzelung)</font> geprägt, wie die aller Waldelfen in Orbis Astea. Besonders ist jedoch der Status, mit welchem sie aus diesen Kriegen hervorgingen. Seitdem die Versklavung der Elfen ein weiteres Mal abgeschafft wurde, gilt der Wald der Fraktion als unbedingt zu vermeiden. 

## Die Gesellschaft von Silva Nacia

Die Elfen der Silva Nacia Fraktion gelten das die arrogantesten Waldelfen, die in den Wäldern Orbis Asteas leben. 

Die oberste Instanz der gesellschaftlichen Struktur bildet der Rat. Dieser setzt sich aus den ältesten Frauen der oberen sozialen Klasse des Stammes zusammen und besetzt die Gesandten-Stellen des Stammes. 

* Gesandte der Klauen = Krieger
* Gesandte des Zweiges = Öko-System Pflege (Pflanzen, Gräber, Dünger)
* Gesandte des Blicks = Späher 
* Gesandte des Hammers = Handwerker
* Gesandte der Pfoten = Tierhaltung
* Gesandte der Lupe = Forschung

Wird eine neue Gesandte im Silva Nacia berufen, ist es die letzte Pflicht der alten Gesandten, die Geschichte ihrer "Regentschaft" mithilfe der Leuchtquallen-Flüssigkeit an die Felswände unter dem heiligen Baum zu schreiben.

Die Gesellschaft besteht so aus spezialisierten Gruppen, die sich lediglich ihrem Bereich widmen und ihr Wissen und ihre Fähigkeiten dort weiter vertiefen. Diese Stellen werden jedoch nicht zufällig vergeben und auch wird kein Elf in seine Stelle geboren. Anders als es von anderen Rassen und deren Gesellschaften bekannt ist, erhalten die Nachkömmlinge der Elfen die Möglichkeit jeden Bereich kennenzulernen, sodass sie Präferenzen für mögliche Stellen angeben können. Diese werden ebenfalls von den Gesandten der einzelnen Bereiche bewertet, was dazu führt, dass es zu einer Übereinstimmung zwischen Interessen und Fähigkeiten bei der Zuteilung der Stellen kommt.

Eine Gesandte des Zweiges zu sein stellt eine besondere Ehre dar, weil diese unmittelbar die Forderungen ihrer Götter erfüllen dürfen, indem sie die Wälder pflegen und mit den Leichen ihrer Stammesmitglieder die Götter nähren. 

## Wirtschaftliche Lage

### Die Ressourcen von Silva Nacia

## Soziopolitische Lage 

### Herrschaftsystem/Organisation

### Die Beziehungen von Silva Nacia

## Militär von Silva Nacia

Einen wesentlichen Vorteil, gegenüber den anderen Waldelf-Stämmen, stellen die <font color="green">[Pflanzen des Waldes ](#SilvaNaciaWald)</font> dar. 

## Die Religion von Silva Nacia

Wie alle Waldelfen betet auch Silva Nacia zu den Waldgöttern. Das besondere ist jedoch der große Baum des Lebens, welcher sich in Mitten des Waldes befindet und das Zentrum des Glaubens darstellt. Die Bedeutung dieses Baumes für die Elfen Silva Nacias ist weitreichend bekannt, weshalb es verschiedenste Abwehrmechanismen gegen Eindringlinge gibt.  

### Totenkult

Der Totenkult der Silva Nacia orientiert sich am allgemeinen Glauben der Waldelfen. Daher werden auch hier die Leichen der Verstorbenen zu Dünger verarbeitet, jedoch mit der Besonderheit, dass je nach Bedeutung für den Stamm, der Dünger der Leiche für den gemeinen Wald oder den Baum des Lebens genutzt wird, da die Elfen glauben, dass besonders treue Elfen den Baum besonders gut nähren. 

## Die Legenden von Silva Nacia

Einee der Waldelfen, der ein großes Vorbild für die Silva Nacia ist, ist der Waldelf Elanor Dolguruk, welcher im Rahmen der <font color="green">[Entwurzelung](#Entwurzelung)</font> unerbitterlich gegen die kaiserliche Armee kämpfte und mehr ihrer Männer tötete als die Angreifer seine Stammesmitglieder fangen und töten konnten. Durch besonders hinterlistige Vorgehensweisen, Schleichattacken und den Einsatz von Gift konnte er lange genug überleben, um die Angreifer für eine Weile aus dem wald der Silva Nacia Elfen fernzuhalten. 

![Elanor Dolguruk - Eine Zeichnungsübermittlung der Silva Nacia Vorfahren[^ErstwhileskySolaufeinPortrait]](Pictures\\Flavor\\Elfen\\ElanorDolguruk_Erstwhilesky.jpg)



## Individuelle Eigenschaften (Umbennen für jew. Rasse)


![Eine Vorfahrin, die den Hass gegen andere Rasse verinnerlicht hat[^ElfArcherJLazarusEB]](Pictures\\Flavor\\Elfen\\ElfArcher_by_JLazarusEB.jpg)





[^ErstwhileskySolaufeinPortrait]: "Solaufein Portrait" von [Erstwhilesky](https://www.deviantart.com/erstwhilesky/gallery). Dieses Portrait steht unter einer Creative Commons Attribution-Noncommercial-Share Alike 3.0 License zur Verfügung.

[^ElfArcherJLazarusEB]: "Elf Archer" von [JLazarusEB](https://www.deviantart.com/jlazaruseb/art/Elf-Archer-531525398). Dieses Portrait steht unter einer Creative Commons Attribution-Noncommercial-No Derivative Works 3.0 License zur Verfügung.
