
# Das Seevolk {#Seevolk}

Das Seevolk ist eine sehr große, sehr diverse Gruppe. Der Name "Seevolk" ist mehr ein Sammelbegriff als eine Fraktion mit politischen Zielen oder gar irgendeiner Form von Einigkeit. 
Die meisten Landbewohner sind dem Seevolk gegenüber sehr skeptisch. Das liegt vor allem daran, dass das Seevolk, dass nahe den Küsten operiert zumeist als Piraten agiert, Schutzgeld erpresst oder Küstenregionen überfällt.
Allerdings besteht das Seevolk nicht nur aus Piraten und Kriminellen, auch viele Abenteurer, Erforscher und Händler kommen aus den Reihen des Seevolks. 
Was wahrscheinlich niemanden Überrascht ist die Tatsache, dass die besten Seemänner der Welt aus dem Seevolk stammen. 

Das Seevolk ernährt sich zu großen Teilen ausschließlich von der Algenart Krüll, die an fast jedem Material wächst, welche zu lange im Meer ohne signifikante Störgrößen wie Beschleunigung treibt. Diese Pflanze ist anhand der Lebensumstände des Seevolks im Übermaß vorhanden, und obwohl sie den Hunger stillt fehlen ihr gewisse Nährstoffe - weswegen viele Leute aus dem Seevolk an Mangelerscheinungen und damit verbundenen Krankheiten leiden. 

Eine der wichtigsten Ressourcen für das Seevolk ist Baumaterial für Schiffe - meistens Holz - was sowohl für die Wartung als auch für den Bau neuer Schiffe und Städte verwendet wird. Aufgrund der chronischen Materialknappheit wird alles wiederverwendet was wiederverwendbar ist - weswegen man auch für Material welches man auf dem Festland als Schrott bezeichnen würde erstaunlich gute Preise erzielt werden können.

## Die Geschichte des Seevolks

Niemand weiß so genau wo das Seevolk herkommt - aber die aufgezeichnete Geschichte ist eng verwandt mit der Geschichte der Staatenschiffe. Die Staatenschiffe wurden knapp 100 Jahre nach der Ausbreitung der Rah Kari entdeckt - anfangs von den ersten Freiheitssuchenden Sklaven, die dem Asb'Kartes verfallen waren folgenden Jahren von allen möglichen interessierten, die genug Manneskraft und Mut aufbringen konnten um diese Schiffe zu bemannen. 

Das erste Staatenschiff das gefunden wurde, wurde von geflohenen Sklaven der Rah Kari entdeckt die mit gestohlenen Schiffen auf der Flucht vor den Rah Kari waren. Das Staatenschiff war relativ Ufernah für ein Staatenschiff und nur zwei Tagesreisen von der Küste entfernt. Die Sklaven steuerten es an im Glauben dass es sich um eine große Insel handelt, auf der sie sich verstecken könnten.

Doch das, was sie für eine Insel hielten entpuppte sich schnell als ein steuerbares und ressourcenreiches Vehikel, und damit als Asset von unschätzbarem Wert. Sie nannten es nach ihrem Gott Asb'Kartes und beherrschen das Schiff bis zum heutigen Tag. Mithilfe 

### Die Staatenschiffe

### Der Seekrieg

### Der Flottendiebstahl zu Sturmkap

## Bedeutsame Untergruppen des Seevolks 


### Kielhaif

Kielhaif ist eine besonders große Wasserstadt und die wohl größte Siedlung auf See, die kein Staatenschiff darstellt. Dieses Sammelsurium verschiedener Schiffe und mit Schwimmkörpern ausgestatter Gebäude wurde direkt über dem größten Schlachtfeld des Seekrieges gebaut, weswegen viele Schatzjäger von dort aus operieren und der Handel mit Wasseratmungstränken und Tauchglocken mehr als boomt.

### Arkus {#Arkus}

Arkus ist das größte bekannte Staatenschiff und untersteht Großadmiral "".
Es ist der weltweit größte Anbauplatz der Krüllalge und der größte Anlauf und Ablaufplatz für Schiffe. 

Arkus wird oft als das Herz des Seevolks bezeichnet und ist eine riesige Stadt, die aus dem Staatenschiff und daran angebauten Wassersiedlungen, Schiffen und Trümmern besteht. Die Stadt ändert sich ständig und ist daher kaum zu überblicken.
Die letzten Jahre hat sich Arkus kaum von der Stelle bewegt und wird von "" mehr wie eine Stadt geführt als wie ein Schiff. Als der Mittelpunkt des Seehandels gibt es kaum einen Kapitän, der Arkus noch nicht angesteuert hat oder ansteuern musste, und so gibt es nur wenige Güter die man im vollkommen unregulierten Arkus nicht kaufen kann.

Obwohl "" und seine Männer versuchen die Ordnung und Kontrolle in Arkus aufrecht zu erhalten gibt es viele Gangs in den verwinkelten Gassen die ihrerseits versuchen die Macht über verschiedene Territorien zu erlangen und auszuspielen. Manche dieser Gangs sind auch sehr erfolgreich dabei.

### Rahla' Asb'Kartes

Das erste Staatenschiff das gefunden wurde, wurde von geflohenen Sklaven der Rah Kari entdeckt die mit gestohlenen Schiffen auf der Flucht vor den Rah Kari waren. Das Staatenschiff war relativ Ufernah für ein Staatenschiff und nur zwei Tagesreisen von der Küste entfernt. Die Sklaven steuerten es an im Glauben dass es sich um eine große Insel handelt, auf der sie sich verstecken könnten.

Doch das, was sie für eine Insel hielten entpuppte sich schnell als ein steuerbares und ressourcenreiches Vehikel, und damit als Asset von unschätzbarem Wert. Sie nannten es ihrem Gott zu ehren Rahla' Asb'Kartes und beherrschen das Schiff bis zum heutigen Tag.

Mithilfe des Staatenschiffs war es den Sklaven möglich eine sehr schlagkräftige Flotte aufzubauen, die mit Unterstützung von Seiten der Rahla' Asb'Kartes durchaus in der Lage wäre die Flotte der Rah Kari zu gefährden oder sogar zu vernichten. 
Die ehemaligen Sklaven - die sich selbst die Sariva nennen - sind sich dessen sehr bewusst und machen geradezu Jagd auf alle Schiffe der Rah Kari, egal ob Kriegs- oder Handelsschiffe, die unter der Flagge der Rah Kari das Setra-Delta verlassen und aufs offene Meer hinaussegeln.

Aufgrund der Tatsache dass den Sariva jedes Mittel recht ist, um gegen die Rah Kari vorzugehen, werden sie von vielen anderen als gefährlich angesehen und gemieden. Sie selbst sehen sich alllerdings als Helden des neunten Gottes, die gegen das Übel der Sklaverei und der deterministischen Struktur der Gesellschaft der Rah Kari kämpfen. 

Obwohl die Sariva auf See den Rah Kari mehr als ebenbürtig sind, sind sie ihnen auf Land weit unterlegen. Schon viele Sariva sind beim Versuch Städte der Rah Kari oder gar den H'Abunapthra einzunehmen abgeschlachtet worden. Dennoch stellen die Sariva immer wieder Armeen zusammen um sich den Rah Kari zu stellen und den Krieg zu ihnen zu tragen.

Obwohl die Armeen der Sariva nur eine kleine, bestenfalls mittlere, Bedrohung für die Rah Kari darstellen ist der wirtschaftliche Schaden durch die schwere Passierbarkeit und Nutzbarkeit der Setra immens, und so sind die Sariva schon seit längerem ein Dorn im Auge des Reichs des Südens. 

### Sirkali

Die Sirkali wird seit Generationen von der Familie Kristof geführt. Sie hat eine Begleitflotte, die fast ausschließlich aus Langbooten besteht und befindet sich momentan nördlich der Ska'en, wo sie gerüchten Zufolge auf Monsterjagd ist.

![Ein Gemälde über die berichteten Monsterjagden[^desmonWOOTFlowerInTheOcean]](Pictures/Flavor/Seevolk/FlowerInTheOcean_by_desmondWOOT.jpg)




Die Familie Kristof ist eine Familie die schon seit jeher mit dem Steuern von Staatenschiffen assoziiert wird - ein Wissen, welches innerhalb der Familie sorgsam weitergegeben wird. So gilt der momentane Kapitän der Sirkali - Erin Kristof - als der beste Steuermann eines Staatenschiffes auf der ganzen Welt. 

Im Kampf gibt es kaum ein Staatenschiff, dass ähnlich gefürchtet ist wie die Sirkali. Diese Reputation hat sich die Sirkali im Seekrieg redlich verdient, als sie sowohl die <font color="green">[Flotte der Arkus](#Arkus)</font> als auch die <font color="green">[Schwarzflamme](#Schwarzflamme)</font> im Kampf stellte, beide Staatenschiffe stark beschädigte und den Begleitflotten schweren Schaden zufügte. So mussten sich beide Schiffe zurückziehen um nicht der Artillerie der Sirkali zum Opfer zu fallen.

> "Ich weiß dass ihr euch Ruhm verdienen wollt, aber sobald irgendeiner sieht, wie sich die Sirkali nähert gebt mir sofort ein Zeichen. Das ist kein Kampf auf den wir uns nochmal einlassen!"
>
> --- Soerf Garaug - Großadmiral der Schwarzflamme im großen Seekrieg



### Schwarzflamme {#Schwarzflamme}

Die Schwarzflamme ist ein weiteres Staatenschiff, das zentral gesteuert wird - und daher eine nicht zu unterschätzende Kampfkraft aufweißt. Zum unlieben jeder konstruktiven Kraft auf dem Meer ist die Schwarzflamme und ihre Begleitflotte allerdings durch und durch eine Piratenfraktion. 

Das Ziel der Schwarzflamme ist es, alle Piraten unter einem Banner zu vereinigen. Damit ist allerings kein Staat oder ähnliches gemeint, sondern einfach nur die Option von allen Piraten auf dem Meer eine Steuer oder eine Form von Tribut einzutreiben.
Allerdings ist es gar nicht so einfach, eine derartig große Aufgabe umzusetzen. Und oftmals vergessen Piraten, die einige Wochen davor Tribut und Folgsamkeit geschworen haben, ihre Versprechen in der Sekunde, in der sie sich nicht mehr in Reichweite der Schwarzflamme befinden. 
Trotz alledem ist die Schwarzflamme eine zurecht gefürchtete Macht auf dem Meer, mit der man sich im Regelfall besser nicht anlegen sollte. 
Die Schwarzflamme hat eine riesige, aber sehr weit verbreitete Flotte, kontrolliert mehrere Wasserstädte und hat mehrere große Galeonen als Flaggschiffe. Die Schwarzflammen-Flotte ist das wahrscheinlich größte stehende Heer des Seevolks.

Im Machtgebiet der Schwarzflamme gibt es auch normales Handwerk und normalen Handel, allerdings ist die Steuer - bzw das Schutzgeld - welches man den Piraten zahlen muss enorm - und so verlieren die meisten Geschäftstreibenden circa die hälfte ihres Einkommens an die Piraten. 

Die Führung der Schwarzflamme wurde vor drei Jahren von Großadmiral Agrin Bost übernommen. Allerdings gibt es ständig inneren Streit darüber wer den Vorsitz haben sollte, und so hat es schon Jahre gegeben, in denen fünf neue Großadmiräle gekürt wurden. So sieht sich Großadmiral Bost immer wieder Machtkonflikten ausgesetzt die es zu bekämpfen gibt, und das Vertrauen in seine Kapitäne und Untergebenen ist notgedrungen sehr klein.


### Die Tartarus

Die Tartarus ist ein Staatenschiff, das weder Zentral gesteuert wird noch effektiv bemannt ist. Dieses Schiff gilt als Schlachtfeld. Seit Jahren versuchen unzählige Fraktionen des Seevolks dieses Schiff für sich zu beanspruchen, und so herrscht ein konstanter Krieg um jeden Zentimeter. Sowohl auf dem das Meer umgebene Schiff als auch auf der Tartarus selbst wird gekämpft - und die Fraktionen versuchen sich jeden möglichen Vorteil zu ergattern.


## Die Gesellschaft der Faction

## Wirtschaftliche Lage

### Die Ressourcen der Faction

## Soziopolitische Lage 

### Herrschaftsystem/Organisation

### Die Beziehungen der Fakion

## Militär der Faktion

## Die Religion der Fraktion

### Totenkult

## Die Legenden des Seevolks

Über das Seevolk kursieren ganz unterschiedliche Legenden. Jene, die man auf dem Festland hört unterscheiden sich doch sehr von denen, die innerhalb aller Seevölker selbst erzählt werden. 
Das Leben eines Pirats hat für die Landratten etwas mystisches. Das Leben in den Tag hinein, die völlige Freiheit zu spüren und einfach das tun, was man möchte - so erträumen sich viele hart Arbeitende ein besseres Leben als Pirat. 

### Die Piraten des Sonnendreiecks

Viel ist nicht bekannt über die Piraten des Sonnendreiecks. Sie tauchten erst kürzlich auf, nachdem sie aus der Sklaverei eines Minenlagers auf der Insel Rouldav entkommen waren. Obwohl sie zahlenmäßig unterlegen sind, ist es ihre Überzeugung, dass sie die Kraft haben, den Rest der versklavten Menschen von Rouldav zu retten.  Was die Piraten des Sonnendreiecks von anderen Piraten unterscheidet, ist vor allem die Tätowierung eines Dreiecks mit einem Auge in der Mitte, was von einer Sonne umgeben ist. Alle Sklaven von Rouldav tragen diese Tätowierung. Doch diejenigen, die ihrer Versklavung entkommen konnten, haben eine leichte Abwandlung vorgenommen, indem sie einen Ring um das Dreieck herum hinzugefügt haben, der für die Sonne steht. Dieses Zeichen wurde gewählt, da die Sklaven von Rouldav dazu bestimmt sind, den Rest ihres Lebens unter der Erde in der Bergbauanlage auf der Insel zu verbringen. Sie haben keine Möglichkeit, die Wärme der Sonne zu spüren und so verehren diejenigen, denen die Flucht gelungen ist, die Sonne als Metapher für die Freiheit, die sie für sie darstellt. Aufgrund der ständigen Verdunkelung der Sonne haben sich die Dreieckspiraten an die Dunkelheit der Nacht gewöhnt und erfahren so gut wie keine Nachteile im Kampf unter diesen Bedingungen.

### Familie Loka

Viele Namen sind auf den Meeren bekannt, aber ein Name, der jeden Seemann neidisch macht, ist der Name Loka. Josa Loka war das erste Mitglied der Familie Loka, das sich wirklich einen Namen gemacht hat. Bevor Josa geboren wurde, war die Familie Loka lediglich für ihre Segelfähigkeiten bekannt, aber ihre Fähigkeiten waren nichts Außergewöhnliches, zumindest nicht, bis Josa geboren wurde. Josa war ein einzigartiges Genie, welcher die Meere wie kein anderer durchqueren konnte. Nicht lange nachdem er 24 Jahre alt geworden war, befehligte er sein eigenes Schiff und seine eigene Mannschaft.  Der eigentliche Wendepunkt kam jedoch, als er zum ersten Mal auf die blaue Schlange Fashit traf. Fashit jagte eine Kreatur, die die Seeleute als ein pferdeähnliches Wesen beschrieben, das auf den Wellen lief.  Das pferdeähnliche Wesen sprang auf Josas Deck und Josa hatte keine andere Wahl, als der blauen Schlange zu entkommen. Bis zu diesem Tag dachten viele Menschen, dass die blaue Schlange der Herrscher der West-Nordsee sei, doch an diesem Tag wurde Josa der erste Mensch, der ihren Fängen entkam. Während Josa und seine Mannschaft froh waren, dass sie es gerade noch lebend aus dieser Situation herausgeschafft hatten, erwartete sie eine weitere Überraschung. Nach der Begegnung sprang das Pferdewesen zurück ins Wasser und deutete an, dass die Seeleute ihm folgen sollten. Aus Neugierde beschlossen Josa und seine Mannschaft, dem Wesen zu folgen, und schließlich wurden sie zu einer noch unentdeckten Insel geführt. Die Insel schien die Heimat des Wesens zu sein, doch das Wichtigste war nicht das Fabelwesen, sondern das lange verschollene Gewölbe mit einem unglaublichen Schatz. Seit diesem Tag wurde Josa mit Ruhm und Reichtum überschüttet, und er begab sich auf noch mehr verrückte Abenteuer. Dennoch verschwand der Name Loka nicht mit Josas Tod, denn er hatte zwei Söhne, die sein Erbe mit sich trugen und Generation für Generation beweisen die Mitglieder der Familie Loka der Welt, dass sie zu den größten Abenteurern und Seefahrern des Meeres gehören.

### Die Insel der Familie Loka

Wie der Name schon sagt, gehört die Insel der Familie Loka, seit sie von Josa Loka entdeckt wurde. Es heißt, dass die Familie Loka dort alle ihre beliebtesten Schätze und Artefakte aufbewahrt, die sie im Laufe ihrer Abenteuer erworben hat. Die Lage der Insel ist daher eine begehrte Information, doch niemand außer den Familienmitgliedern selbst weiß, wie man zu ihr gelangt. Viele Seeleute, die sich selbst als ehemalige Besatzungsmitglieder bezeichnen, behaupten, sie wüssten den Weg zur Insel, doch gibt es von diesen Schwindlern so viele wie Fische im Ozean. Während die einen sagen, dass es sich um eine erfundene Insel handelt, behaupten andere, dass nur ein echtes Mitglied der Loka-Familie den Weg zur Insel finden kann. 


### Der Ozean Zimmermann / Schreiner ~

In unserer Welt gibt es noch viele Mythen, Sagen und Legenden, vor allem in Bezug auf die weiten des Ozeans und den Menschen, die ihn durchqueren. Eines dieser Mysterien ist der Mann, den viele Seefahrer den Ozean-Zimmermann nennen. Es gibt zwar keine genaue Beschreibung des Ozean-Zimmermanns, aber viele Menschen, die ihn im Laufe der Jahre gesehen haben, beschreiben ihn als einen alten Mann mit einem langen weißen Bart, der seltsame Kleidung trägt, in die Zahnräder und Rädchen eingearbeitet sind. Der Ozean-Zimmermann ist dafür bekannt, dass er auf längst beendeten Schlachtfeldern auftaucht und die Teile der zerstörten Schiffe einsammelt. Man sagt, dass er diese Teile dann in sein eigenes Schiff einbaut und es dadurch immer größer macht, während er zu immer mehr vergessenen Schlachtfeldern segelt. Der Ozean-Zimmermann tauchte vor 244 Jahren zum ersten Mal auf, und seither ist sein Schiff nur noch größer und unverständlicher geworden. Das Schiff selbst wird nur von dem besagten bärtigen Mann wie einer Vielzahl an Konstrukten gesteuert. Viele Seeleute haben bereits versucht, sich dem Schiff zu nähern, doch bevor sie den Ozeanzimmermann erreichen konnten, wurden sie von den Konstrukten an Bord des Schiffes angegriffen. Bis heute weiß niemand, wie er ein Schiff dieser Größe kontrollieren kann oder warum es überhaupt schwimmen kann, da es eher einer Ansammlung von zusammengebauten Schlachtschiffen ähnelt.

### Die Insel aus Silber und Gold 

Die Insel des Silbers und des Goldes ist die Heimat des "Murakai"-Volkes, was lose mit „Menschen des Goldenen Antlitz“ übersetzt werden kann. Ursprünglich war sie von diesem Volk bewohnt, doch nach dem Krieg mit dem Seevolk wurden sie ausgerottet, doch bis heute sind ihre Kultur und ihre einzigartigen architektonischen Strukturen noch zu finden. Die Insel ist berühmt für ihre Gold- und Silberminen, die das "Murakai"-Volk in seine Gebäude einbaute. Die Insel hat jedoch seit langem keine friedlichen Tage mehr erlebt, da viele Fraktionen und Völker um die Insel und ihre Ressourcen kämpfen.

### Die Murakai und "die Grüne Lagune"

Viele Menschen glauben, dass das Seevolk das erste Volk war, das wirklich das Meer der Welt beherrschte, doch das ist nicht der Fall. Nordwestlich vom Land der Rahkari gibt es eine Reihe von Inseln, die ursprünglich von einem inzwischen ausgestorbenen Volk bewohnt wurden. Dieses Volk trug den Namen "Murakai". Das "Murakai"-Volk hat im Vergleich zum Imperium keine herausragenden technologischen Leistungen vollbracht, aber es ist ihm gelungen, einige der ersten Schiffe zu bauen, die das Meer durchqueren konnten. Obwohl ihre Schiffe eine recht eigenartige Form hatten, konnten sie mit einigen Schiffen selbst unserer Zeit mithalten. Das "Murakai"-Volk war jedoch extrem isoliert, was man daran erkennen kann, dass es nie versuchte, mit dem Festland in Kontakt zu treten. Doch als sie schließlich mit einem anderen Volk in Kontakt kamen, wurde ihnen dies zum Verhängnis. Im Jahr "580 v. R." entdeckte das Seevolk schließlich die Insel aus Silber und Gold, seine Heimat. Das Seevolk lernte schnell, wie wertvoll die Ressourcen auf der Insel waren, und nicht lange nach ihrer Entdeckung der Insel begannen sie einen Krieg mit dem Volk der "Murkai". Das Volk der Murakai war jedoch nicht an Kriege gewöhnt und verfügte daher nicht einmal über ein richtiges Militär. Die versprengten Kämpfer stellten so keine Bedorhung für eine geordnete Armee dar und nach nur 4 Monaten war fast das gesamte Volk der Murakai ausgelöscht. 
Nach dem Krieg blieb nur ein einziges Schiff übrig, das der Kapitän des "Murakai"-Staatenschiffs, Kapitän Einarm, zu seinem persönlichen Schiff machte und es „Die Grüne Lagune“ taufte. Er stattete es mit der besten Ausrüstung aus, die er als berühmter Kapitän finden konnte. Doch nach seinem Tod wechselte die grüne Lagune von einem Besitzer zum nächsten. Selbst heute ist „die Grüne Lagune“ ein Schiff, das jeder erfahrene Kapitän sofort erkennt, da es, nebst der Einzigartigkeit, viele Geschichten und noch mehr Seemannsgarn mit sich bringt. 



## Individuelle Eigenschaften (Umbennen für jew. Rasse)

Artefakte
Nutztiere
Beastman Beutetiere / Mutationen



[^desmonWOOTFlowerInTheOcean]: "Flower in the ocean" von [desmondWOOT](https://www.deviantart.com/desmondwoot/art/Flower-in-the-ocean-311247641). Dieses Bild steht unter einer Creative Commons Attribution-Noncommercial-No Derivative Works 3.0 License zur Verfügung.

