# Wirtschaft in Orbis Astea

## Wirtschaft im Kaiserreich 

Wir beginnen unsere Reise über die Wirtschaft des Kaiserreichs bei dem grundlegensten Nahrungsmitteln und der Landwirtschaft welche dieses für das formidable Kaiserreich herstellt.
Rund 7 von 10 Menschen des Kaiserreichs arbeiten in der Bestellung der Wiesen und Äcker oder in der Holzarbeit. Hierbei nutzen die Bauern, welche häufig Eigentümer ihrer Länderein sind ihr Wissen über die Natur und das was die besten Schmieden des Kaiserreiches für Sie an Gerätschaften bereit stellen. Da das Klima des Kaiserreiches im Schnitt sehr mild ist und von weniger extremen als das der Rahkarischen oder Animalischen Ländern, ist es den Bauern möglich eine Vielzahl von Feldfrüchten anzubauen. Dazu gehören gräserartige Früchte wie Weizen, Gerste, Hafer oder im südlichen Eldria gelegentlich Hirse. Pflanzen aus welchen kein Brote hergestellt werden, zu den also zu Gemüsen zählend, sind die Zwiebeln, Karotten, Kohle, Erbsen, Linsen und eine Vielzahl an Kräutern.
Die Kräuter wurden, aufgrund der Pflegeintensität häufig von den jüngeren oder schwächeren der Familie übernommen.

Der Bauer und die meisten seiner Söhne, sofern diese nicht in den Dienst für den Kaiser eine andere Verwendung finden, arbeiten am Felde und kümmerten sich um das Getier. Hierbei sind die hervorragenden Weiden der Nordhänge der Himmelsspitzengebirge und deren Täler sehr begehrt aber auch von Monstern gefährdet. Typischerweise halten sich Bauern Hühner, Schweine, eine Hand voll Kühe und Ochsen. Dazu kamen gelegentlich in den günstigeren und von mehr Wasser umgebenen Gebieten wie Yondalla auch Gänse und Enten.

Um die Soldaten, Geistlichen, Handwerker, Händler und Diener des Kaisers zu ernähren, werden Unmengen von Nahrungsmitteln benötigt. Das kaiserliche Institut für Ertragssteigerung stellt hierzu regelmäßig Versuche an um Erträge in der Landwirtschaft zu verbessern. So konnte festgestellt werden, dass ein besonderer Pflug welche in Kooperation mit der Muranunfarm die Erträge der Boden um einige Prozentpunkte verbessern konnte, woraufhin, diese Seitens des Kaiserreichs gefördert wurden.

Prinzipiell ist Yondalla die Kornkammer des Kaiserreichs und stellt einen guten Teil der Nahrung, sowie weiterarbeiteter Produkte, wie haltbare Speisen. Die Wälder vor den Hängen der Nachtberge, sowie die kleiner werdenden Wälder um Civis Primae stellen hier die Quelle für das Holz des Kaiserreichs dar. Exporte an Holz oder Nahrung findet zwischen dem, gerechterweise dem Kaiser unterstellten, Eldria kaum statt. Holz wird, in unterschiedlichen Qualitäten für diverse Produkte benötigt, angefangen von Trebouchets, welche Felsbrocken über 300 Meter schleudern können, hin zu den Melkschemeln der Bauern, welche die Milch zu Käse verarbeiten, um daraufhin die treuen Truppen des Kaisers zu versorgen.

Zünfte für höherwertige Produkte findet man in den größeren Städten des Kaiserreichs. Diese stellen, dann beispielsweise Bombenflaschen her, oder Verbände für verletzte Holzarbeiter.
Genau festzustellen welche Macht welche Zunft besitzt ist ebenso wie die Zählung der Mitglieder schwer. Geschätzt dienen 20-25% der Bevölkerung des Kaiserreichs in irgendwelchen Zünften. Hierbei geht meist die Entwicklung neuer Techniken von den Zünften direkt aus. Des Vorangehens weise ist diese, das neue Entwicklungen meist in die Großstädte transportiert werden und dort von den Zünften untersucht werden. Die Erfinder werden mit kleineren Beträgen abgespeist und die Zünfte erheben daraufhin ein Monopol auf diese Technologie. Die Einhaltung der Kontrolle des Monopols obliegt offiziell dem Kaiserreich, wird aber, bei Kriegsunwichtigen Gütern selten streng vollstreckt. In den meisten Fällen wird der Nachahmer, so er geschäftstüchtig ist einfach in die Zunft integriert. Harte Gegner der Zünfte, meist Freigeistler genannt, werden gelegentlich auch bedroht, was die Zünfte allerdings immer bestreiten.

### Die relevantesten Zünfte (Einkommen im Monat in Reiks):
Schmiede (4400 Reiks)
Korbflechter (2000 Reiks)
Weber (2500 Reiks)
Käserei (3000 Reiks)
Jagd (2000 – 6000 Reiks)
Gerber (3500 Reiks)
Fischer (3000 Reiks)
Kürschner (3500 Reiks)
Zimmerer (3500 Reiks)
Maler (4000 Reiks)
Müller (3000 Reiks)
Metzger (3000 Reiks)
Schuhmacher (3500 Reiks)
Sattler (4000 Reiks)
Heiler (4500 Reiks)
Alchemist (5000 Reiks)
Reisende Händler (2000-7000 Reiks) [Entgegen der Annahmen sind in dieser Zunft auch Ortsgebundene Händler für diverse Güter inkludiert, dadurch wird diese Zunft als „Händlergilde“ oder „Handelsgilde“ bezeichnet, diese hat meist den exaktesten Überblick über sämtliche Preise im Kaiserreich]

### Zunftlose Berufe:
Einfacher Soldat im Kaiserreich (2800 Reiks)
Offizier d. Kaiserlichen Armee (4500 Reiks)
Zenturio d. Kaiserlichen Armee (10000 Reiks)
Kaiserlicher Heiler (5000 Reiks)
Kaiserlicher Alchemist (6000 Reiks)
Tagelöhner (1200 - 1500 Reiks)
Bauer (2000- 4000 Reiks - 6000 Reiks in Yondalla)
Holzfäller (3700 Reiks)
Bewahrer des Ruhehofs (3000 Reiks)

Zölle fallen im Kaiserreich offiziell keine an. Allerdings ist es Weg und Gutsbesitzern möglich  Beträge zum Erhalt der Wege zu verlangen. Dafür müssen in der Zunft 

## Wirtschaft in Eldria

Die Wirtschaft in Eldria unterscheidet sich nicht wesentlich von der des Kaiserreiches. Auch hier prägen Bauern mit rund Sieben Zehntel die Bevölkerungsschicht. Handwerke umfassen, neben seit der Einnahme durch das Kaisereich einer etwas kleineren Schmiedevereinigung, rund Zwei Zehntel der Bevölkerung. Die Verdienste sind im Schnitt etwas schlechter, was sich allerdings auch in einem leicht geringeren Preisniveau von Gütern niederschlägt. 
Im Gegensatz zum restlichen Kaiserreich sind die Zünfte, welche in Eldria, vor dem Kaiserreich sperrig „Berufungsvereinigungsgesellschaft“ genannt, nicht derartig kooperativ. Auch ist aufgrund der Zerstrittenheit der Fürstentümer der Technologische Austausch schlechter zwischen den Zünften. So kamen die Errungenschaften der letzten Jahrzehnte vorwiegend aus dem Kaiserreich.  Bombenflaschen, Großkanonen oder Behandlungen für verschiedene Krankheiten fanden im Kaiserreich ihren Ursprung. 

Vermutungen von Gelehrten gehen in die Richtung, dass der eldrische Intellekt durch den Krieg, die Nähe zum Nebelhain, Zwergenflüche oder „Graue Götter“ beeinflusst wird.  Andere, weniger aufregende Gründe könnten rein wirtschaftlicher Natur sein. Das Kaiserreich besitzt tiefe Taschen und kann so teils Entwicklungen unterstützen und damit teils Jahrzehntelange Entwicklungen unterstützen. In Eldria ist eine Forschung von mehreren Generationen eine Rarität, da Geld und Reiberein mit Fürstentümern meist Fortschritte zunichtemachen, wenn Waffenschmiede, Alchemisten oder verrückt Geniale, versehentlich oder absichtlich aus den Städten geworfen werden und anschließend ihr Leben an der rostigen Klinge eines hungrigen Banditen aushauchen.

Zölle in Eldria werden nicht einheitlich erhoben und die Praxis von Stadtzöllen hat sich, trotz der Anwesenheit des Kaiserreichs in Eldria nur unmerklich geändert, was zu einer Reduktion des wirtschaftlichen Lebens geführt hat.

## Wirtschaft im Land der Rahkari

Man möge als Laie meinen, dass die Länderein der Rahkari in wirtschaftlicher Stärke aufgrund der ausgedehnten Wüsten und Steppen weit abgeschlagen der des Kaiserreichs liegen. Erstaunlicherweise ist dies jedoch nicht der Fall, zumindest laut den etwas spärlicheren Informationen welche Gelehrten vorliegen.
Im Gegensatz zu den nur schwachen Überschwemmungen die durch seltenere Hochwässer der Reik auftreten, wird die Setra und ihre kleineren Nebenflüsse Richtung Westen und Süden.  Insofern ist die Richtung Westen und ins Südmeer fließende Setra gemeinsam mit dem Richtung Süden Fluss Atum, der von der Setra Richtung Atumpet fließt, die wichtigste Verkehrsader.

Beide werden aus dem Nebelhain und den Himmelsspitzengebirge gespeist und liefern ganzjährlich Wasser.  Im Frühling, wenn die Temperaturen auf den Feldern noch angenehm sind, kommen die Überflutungen welche in die ganzen Nebenärme der beiden Großen Flüsse getragen werden. Die Bauern nutzen den Fruchtbaren schlamm der sich ablagert und sammeln auch einen Teil des Wassers in Wasserstätten.

Dadurch wird auf geringen Flächen eine unheimliche Produktivität und hohe Qualität an Früchten erzielt. Gleichzeitig verhindert die Trockene Luft auch den Verlust eines signifikanten Teil der Ernte, wie es sonst in Eldria und in Nors der Fall ist.  Dies ermöglicht bis zum Sommer meist 2 Ernten. Über die Sommermonate bei Gluthitze liegen die Felder öfter brach, da Sandstürme Ernten sonst rasch vernichten würden.
Im Herbst wenn die Temperaturen sinken wird das Wüstenmehl angebaut, aus welchem meist die billigste Nahrung, das „Wüstenbrot“ hergestellt wird. Der Geschmack ist meist leicht bitter, jedoch Nährreich.  Es dient primär als Nahrung für die Sklaven.

Wie auch in den anderen zivilisierten Gebieten decken Bauern einen großen teil der Bevölkerung ab. Sie gehören dem Pfad des Bauers an und dienen der Göttin Pseptha. Rund 5 von 10 Menschen im Reiche der Rahkari sind Bauern. Rund 10-15% dienen als Sklaven in der niedrigsten sozialen Kaste. Hierfür wird die meist erniedrigenden oder zu schmutzigen Arbeiten ausgeführt. Ihre Rolle ist allerdings divers. Bringen Sie menschliche Exkremente auf die Felder dienen Sie zwar den Bauern, können aber, bei Notwendigkeiten in Steinbrüchen oder zum Ausheben von Latrinen in Städten verwendet werden. Dadurch kommt es gelegentlich vor, dass manche Sklaven mehr von den Ländereiengesehen haben, als Ortsgebundene Bauern.
Der Pfad des Handwerkers ist neben den Bauern die zweitgrößte Gruppe der Pfade. Jeder vierte dient hier. Dabei Fallen unterschiedlichste Bereiche an. So sin Kürschner, Schuhmacher und Metzger im Pfad der Handwerker vereint.

Der Pfad des Pferdezüchters ist eine Sonderklasse im Reiche der Rahkari, obwohl diesem wenige Menschen per Geburt zugeteilt sind erwirtschaften diese Verhältnismäßig viel Geld. Die Rahkari Pferde dienen der schnellen Kommunikation zwischen den Molochen der Rahkari.  Für Sultanhai ist es oft möglich, wenn diese selbst reiten, ohne Unterbrechung entlang der großen Flüsse Tag und Nacht zu reiten.

Im Gegensatz zum Kaiserreich, sind im Lande der Rahkari extrem viele Menschen in Heilung und Medizin ausgebildet, und vermutlich ein Grund warum Seuchen in den molochhaften Großstädten selten auftreten. Der Pfad besitzt zwar wenig finanzielle Mittel, genießt aber in der allgemeinen Bevölkerung das höchste Vertrauen.

Der Kult der Meliodas diktiert im Reiche der Rahkari die Preiserichtlinien. Zwar gibt es regional Unterschiede, jedoch belaufen sich diese entlang des Atum’s und der Setra nur auf einen Bruchteil, was ebenso einen Unterschied zum Kaiserreich darstellt, wo die Preise deutlich stärker fluktuieren.

Die Pfade der Rah Kari
Der Pfad des Kriegers mit der Verehrung des Gottes Tarkus Rah
Der Pfad des Bauers, gewidmet der Göttin Pseptha
Der Pfad des Handwerks - gekoppelt an die Verehrung des Kha’fan
Der Pfad der Pferdezüchter mit Hestua als Leitgöttin
Der Pfad der Heiler und Frauen - der Pfad der Shafra
Der Pfad der Künstler unter dem Schutzgott Amdju
Der Pfad der Händler und die Verehrung von Meliodas
Der Pfad der Hüter - der Pfad des Unes Utet

Die Klassen, oder Stufen der Rahkari: 

Sklaven: Heri
Anfänger: Baskad
Gesellen: Ascii
Meister: Jidai
Höchstgeborenen: Sulthanai

Die Verbreitung von neuen technologischen Entwicklungen bei den Rahkari erfolgt zentralistisch. Die Technologische Entwicklung hatte allerdings in den letzten Jahrzehnten wenig vorzuweisen. Lediglich der Transfer und Kauf von Zwergenkonstrukten zeigt eine Entwicklung an.  Medizinsch sind die Rahkari, aufgrund der Größe des Kultes ohnehin deutlich vor denen Eldrias und des Kaiserreichs. Eine technologisch, mittlerweile ältere Besonderheit, sind die mechanisch von Konstrukten oder Nutztier betriebenen  Bewässerungszisternen oder Brunnen. Hierbei können, in günstigen Bedingungen mittels Konstrukte der Zwerge, teure, aber nachhaltige tiefe Schächte gegraben werden, welche ganzjährlich hochreines Wasser für die Bevölkerung zur Verfügung stellen.

Über die Militärische Stärke, den tatsächlichen Reichtum der Rahkari gibt es allerdings kein allgemeines Wissen, da diese von den Selikten, den obersten der Pfade, streng gehütet wird. Schätzungen divergieren stark. Gerüchtenzufolge sollen die Rahkari in den Südwüsten ergiebigste Silber und Goldquellen gefunden haben. Aber laut selben Quellen soll die Gegend auch verflucht und als menschfeindlich, wie die Graue Ödnis bezeichnet werden.

## Wirtschaft in Eisland

Die ewigen Tundren des Eisland werden vorwiegend von den Animali bewohnt. Durch den über die Jahre etablierten Handel mit dem Kaiserreich und einigen ausgetauschten Geschichten welche kaiserlichen Chronisten schriftlich niederschrieben wissen wir, dass eine organisierte und kontrollierte Wirtschaft im Kaiserreich im engeren Sinne nicht existiert.
Die Animali und ihre Stämme leben hauptsächlich von der Jagd und betreiben keine relevante Landwirtschaft, da die Tundren wenig nutzbare Äcker aufweisen.  Die Stämme ernähren sich überwiegend durch die Jagd und das Sammeln von Beeren und Früchten und gelgentliche gezielte aussähen von Samen von Nutzpflanzen. Sie kümmern sich allerdings nicht explizit um das Wohlergehen dieser Pflanzen.

Große Pflanzenverzehrende Tiere werden für gewöhnlich für Fleisch, Felle und Bogenbestandteile gejagt. Den Animali ist auch möglich Eisenwaffen selbst herzustellen, jedoch ist das Brennmaterial, welches Sie dafür verwenden nicht bekannt. Gelehrte vermuten, dass es sich um Öle aus der Natur handeln müsste. So wie die gefundenen Brennöle in den Grenzen des Kaiserreichs zum Eisland im Sonderverwaltungsgebiet Naphtanium.

Der wertvollste Handel und vermutlcih die größte Wirtschaftskraft finden sich in den Stämmen, welche mit dem Kaiserreich handeln. Diese können dadurch auf meisterliche kaiserliche Handwerkskunst zurückgreifen, gleichzeitig Trockenbrot und diverse Hülsenfrüchte wie Bohnen günstig erstehen. Im Gegenzug liefern die haarigen Handelspartner meist Fleisch zu günstigeren Konditionen als es Landwirte und Jäger des Kaiserreichs bieten können. Der Handel mit Alchemistischen Zutaten ist ebenso ein für beide Seiten einträglicher Dienst.

Ein nicht unbedeutender Schwarzmarkt besteht im Verkauf von Bombenflaschen, welche die Animali selbst nicht herstellen können. Jedoch, so die Vermutung helfen di daraus herzustellenden Moltovika und Nebelgranatika deutlich bei der Jagd auf die Scheusale welche der Allgott gegen die Blasphemiker in diese Welt gebracht hat.

## Wirtschaft auf den Ska'en



## Wirtschaft der Zwerge

Die Wirtschaft der Zwerge ist komplett untypisch für die ziviliserte Welt.  Weder können die Zwerge ihre Nahrung und ihr Holz in ausreichender Qualität herstellen, noch Verfügen diese über Wirtschaftlich Zentrale Register. Dadurch besitzen die Zwerge keine Regulräe Gruppe an Bauern oder Kleidungsherstellung oder Förster. 
Die größte Berufskaste der Zwerge ist Minenarbeiter, welche Erze und Edelsteine zutage fördern. Die Zweitgrößte Gruppe sind die Metallurgen, welche den berühmten Zwergenstahl herstellen und Vorfertigungen für Zwergenkonstruke erstellen.  Juweliere, Rüstungschmiede und die Essenzschürfer. Essenzschürfer sind Zwerge welche mit speziellen, unbekannten Methoden Essenzen für das Erschaffen von Konstruken sammeln.  Diese Konstrukte, sind neben regulären Wachen für den Transport und die Verteidigung der Zwergenkarawanen zuständig.

Zwerge besitzen im Gegensatz zu anderen Humanoiden eine andere Gesellschaftstruktur:

Zu den Hauptberufsgruppen gehören in aufsteigender Einkommensstufe:
Pilzbewirter – Die günstigste Nahrung der Zwerge in ihren unterirdischen Städten besteht aus einer Reihe unterschiedlicher Pilze. Diese sind zwar wenig schmackhaft und verkürzen das Leben, sofern diese als Hauptnahrungsquelle verzehrt werden, sind jedoch bedeutend günstiger als die importierte Nahrung.
Schürfern – allgemeine Minenarbeiter und erkunder von unterirdischen unbekannten Gängen.
Handwerker – eine diverse Gruppe aus verschiedenen, teils hochspezialisierten Arbeitern, welche unter anderem Konstrukte erstellen oder die Statik der Zwergenstädte sicherstellen.
Wächter – Übernehmen die Rolle des Militärs und der Wache
Essenzjäger – Nebentätigkeit, häufig von Oberweltzwergen ist das Sammeln der Energien der verstorbenen Humanoiden. Dieser Beruf stehen im Kaiserreich und im Lande der Rahkari, exklusive des Sammelns von Sklavenseelen, unter Strafe.
Händler - gewiefte und silberzüngige Zwerge welche sich auf den Verkauf diverser Waren spezialisieren


Bei den Zwergen gibt es im Allgemeinen keine soziale Absicherung. Da selbst Mütter ihre Kinder für einen adäquaten Beitrag verkaufen und Eltern die Aufzucht ihrer Kinder ihnen in Rechnung stellen, kann von kaiserlichen Gelehrten wenig soziale Wärme ausgemacht werden. Dementsprechend umtriebig und opportunistisch ist die gesamte Zwergengesellschaft. Wo auch immer Profit gemacht werden kann ohne, dass man den Kopf verliert, wird auch Profit gemacht. Dadurch sind Zwerge im allgemeinen misstrauisch und hegen auch untereinander häufig Groll, wenn sich jemand monetär benachteiligt fühlt.  Ihre Religion, spöttisch als „Allgeld“ gezeichnet hat als vereinenden Punkte die Lebensaufgabe eines Zwerges ein möglichst großes Vermögen zu erzeugen. Dadurch dass diese Philosophie sich durch Zwergengesellschaften zieht, gehören Zwergenstädte und Stämme meist zu den am besten betuchten Humanoiden. 
Die hohe finanzielle Kaufkraft wird allerdings auch benötigt, da Zwergenstädte häufig auf die Nahrungsversorgung der umliegenden Länder angewiesen sind. Dadurch sind in den Wirtschaftsystemen der Zwerge kaum reguläre Bauern Vertreten. Auch der Heiler- oder Alchemistenschule ist schwächer ausgeprägt als bei den Rahkari oder den Kaiserlichen.
Ein großer Teil des Gewinns wird, seitens der Vulkanzwerge im Westen des Himmelspitzengebirges, aus den Verkauf und Wartungskontrakten von Konstrukten erzielt. Die Rahkari versorgen im Gegenzug die Zwerge mit Nahrung und auch den Verkauf von Essenzen für die Konstrukte, wozu die Sklavekaste der Rahkari verwendet wird.

Wirtschaftlich ist der primäre Handel, nach einer angeblich unbeglichenen Schuld seitens des Kaiserreichs vorwiegend mit den Rahkari, wo Konstrukte und gute Waffen gegen Nahrung Holz und sonstige Güter getauscht wird. 


## Der Verkauf von Kriegsgütern:

Bedingt durch den Reichtum an Erzen ist es in der bekannten Welt Abenteurer, Plünderern und Vagabunden möglich die Häufigkeit an Waffen und Rüstungen zu nutzen, um so unkompliziert ein Auskommen zu finden. Bevor sich große Schmieden unter Kontrollen der Rah-Kari und des Kaiserreichs an dem Reichtum ergötzen konnten, war auch die Menge an Eisen beschränkt. Folglich fanden sich nicht allerlei Vagabunden im Besitz von schweren Eisenrüstungen und Kriegshämmern, um damit Dörfern unter Gewalt ihr Hab und Gut abzuknöpfen.
Das "Problem" dieser Vagabunden wurde dann durch die aufkeimenden Kulturen der Rah-Kari und später des Kaiserreichs behoben. Plötzlich versuchten die verfeindeten Gemeinschaften andere zu sabotieren und so wurden auch die schlechtgestellten Bevölkerungsgruppen, seien es die hungrigen Bauern nach schlechten Ernten oder die Sklaven der Rah-Kari, plötzlich bewaffnet.
Im Laufe der Jahrhunderte, in welchen die Eisenschmiede ihre Handwerkskunst verbesserten, wurde so immer mehr an Kriegsgütern in die Welt geschickt. 
Dies gipfelte in den großen Kriegen zwischen den Rah-Kari und dem Kaiserreich in einer Verschlimmerung der Ordnung innerhalb der Reiche.

Daraus erfolgten schlussendlich in den spezifischen Gebieten eigene Gründe, Gesetzte oder Riten, wodurch die Menge an Kriegsgütern reduziert wurde.


### Reduktion der Kriegsgüter im Kaiserreich und dem Protektorat Yondallas:

Die Lösung des Kaiserreichs wurde über mehrere Pfade erreicht.
Die handelnde Klasse, insbesondere Schmiede, wurde verpflichtet die Menge an Waffen in ihren Lagerstätten gering zu halten und allfällige Überkapazitäten an das Kaiserreich zu melden. Das Unterschlagen solcher Waffenbesitzungen führte schon mehrmals zu harten Strafen. Besonders uneinsichtige Händler wurden hier sogar gehängt, wobei dies jedoch die Ausnahme darstellt.
Im Durchschnitt haben Händler dadurch nur noch geringe Waffenbestände lagernd, um nicht über die Grenzwerte zu kommen und kaufen so dubiosen Gestalten, wovon es in dieser gesegneten Welt leider zu viele gibt, nur mehr einen Bruchteil ab. Meist solche Mengen, welche die Händler selbst äußerst rasch weiterverkaufen können, um so den Kontrollen zu entgehen.
Zusätzlich sind Schmiede verpflichtet ein Siegel auf ihren Waffen zu hinterlassen, meist in Form eines Metallreliefs. Fehlt dieses, können kaiserliche Vertreter auch Waffen in Beschlag nehmen, da kein Nachweis für eine ordentliche Herkunft erbracht werden kann.
Gleichzeitig konnte der Mathematiker Hadrian Plebian dank eines arithmetischen Modells errechnen wie viele Waffen eines Schmieds jederzeit Auffindbar sein müssten. Obwohl diese Regel grob ist, ist es ein weiteres Puzzlestein des Kaiserreichs, um so Plünderern oder den feindlichen Aktivitäten der Rah-Kari Einhalt zu gebieten.

Aus moralischer Sicht ist es für einen Schmied fragwürdig, wenn ein böser dreinschauender Mensch ihm plötzlich 5 blutverschmierte und eingedellte Rüstungen samt Haarresten feilbietet.  Hierbei ist es, neben der gesetzlichen Pflicht, welche durch das Kaiserreich durchgesetzt wird, auch relevant, dass die Toten ordentlich beerdigt wurden, da sonst die Untoten in der Nähe die normale Bevölkerung angreifen.  Folglich muss ein geistlicher Vertreter beauftragt werden die korrekte Beerdigung der Toten zu bescheinigen. Gleichzeitig ist dieser Geistliche verpflichtet die Menge an Waffen und Rüstungen dem Kaiserreich zu melden. Dieser „Friedensobolus“ erfüllt also nebst der moralischen Pflicht, die Beseitigung der Leichen sowie der Wahrung des Rechts.

Der Export dieser Waffen von guter Qualität lockt leider auch Vertreter des Schwarzmarktes an. Hierbei versuchen diese unrechten und moralisch zu verachtenden Händler in die instabile Region Eldrias zu bringen, wo die berüchtigten und ausgebildeten Guerillakämpfer Eldrias ihr letztes Hemd für eine gute Waffe verkaufen.

Das Kaiserreich kontrolliert das schlauchförmige Grenzland Richtung Eldria dadurch besonders. Der Handel durch Silva Nacia ist durch die Gefährlichkeit der Route ohnehin nur beschränkt bedeutend.

Das Kaiserreich selbst stellt die meisten Waffen in den riesigen Festungsstädten her, wodurch der Abgang an Waffen geringer ist und die Qualität besser kontrolliert werden kann. 

### Der Umgang des Kaiserreichs in Eldria mit Kriegsgütern:

In Eldria, ein, noch immer von Guerillakämpfen durchzogenen, Gebiet, über welches das Kaiserreich noch immer trotzig behauptet „es habe die volle Kontrolle“, ist das Problem umgekehrter Natur.
In Eldria sind Waffen jeder Art heiß begehrt und meist eine Grundbedingung für einen erfolgreichen Guerillakampf. Da die Schmiede einigermaßen unter kaiserlicher Kontrolle steht und Waffen in schlechter Qualität auf dem weitaus größeren und schlechter kontrollierten Schwarzmarkt ein Problem darstellen, versucht das Kaiserreich mit der „Aufstandregel“, welche die Anzahl der erhältlichen Waffen bei einem Schmied reduziert, dem einem Riegel vorzuschieben. 
Diese Aufstandsregel unterbindet den Waffenhandel zwischen dem Kaiserreich und Eldria. Somit bleiben den Aufständischen in Eldria meist nur Waffen schlechter Qualität, oder die Unterstützung von Schmieden, welche den Kopf für die unnötige Unabhängigkeit Eldrias hinhalten.

### Kriegsgüter im Land der Rah-Kari:

Der Kult der Meliodas, was einer Händlerkaste entsprechen würde, definiert den Preis für viele Güter, unter anderem auch Rüstungsgüter.  Im Allgemeinen ist dies ein hoher Aufpreis auf eine verkaufte Waffe und Rüstungen. Da Zwerge zwar mit den Rah-Kari handeln, Eisenrüstungen aber in der Wüste unpraktisch sind, braucht es einen Aufpreis, um die Menge an Waffen niedrig zu halten und nicht die Sklavenkasten zu viele Möglichkeiten für den Widerstand zu bieten. Dadurch verkaufen Händler zwar ihre Schwerter für den Kunden zu „normalen“ Preisen wie im Kaiserreich, allerdings ist der Profit des Schmiedes gering, da die „Steuer“ teils 2500 Reiks, bzw. 5000 Rah-Kari beträgt. Dadurch bekommen Plünderer und Abenteurer nur geringe Preise für ihr erbeutetes Gut. Der Kult der Meliodas füllt dadurch seine eigenen Taschen, welche aber auch in die militärische Nutzung und die geheimen Aktivitäten der Hüter fallen. Dadurch finanzieren Plünderer, oder Aufständische ihre eigenen Feinde.

### Zwerge und der Umgang mit zu vielen Waffen:

Zwerge hingegen haben eine völlig andere Mentalität.  Die Herrschaft der Zwerge in ihren Festungen im Himmelsspitzengebirge ist uneingeschränkt und nicht relevant durch Scharmützel bedroht. Gleichzeitig spucken die Schmieden der Zwerge mehr als hinreichend Eisen aus, welche von der Qualität her im Vergleich zu den restlichen Völkern weitaus überlegen ist. Dadurch werden die Schwerter und Rüstungen aus Eisen und Stahl der anderen Völker häufig nur eingeschmolzen, um daraus Konstrukte zu erstellen, welche ein vielfaches wertvoller sind und eine Besonderheit der Schmiedehallen der Zwerge darstellt. Folglich könnten Plündern der weiten des Himmelsspitzen Gebirge diese Waffen auch einschmelzen damit zumindest ein einfacherer Transport möglich ist. 
Da die Handelswege von den Zwergenfestungen nur primär zu den Rah-Kari erschlossen sind, und Stahl in der glühenden Sonne der Wüste einfach nur kochend heiß wird, gibt es kaum einen Rückfluss aus theoretisch billigem Stahl in das Kaiserreich, welches diesen heiß begehren würde. Außerdem ist es den meisten Kasten verboten mehr als Eisenwaffen/Rüstungen zu besitzen. Trotz offiziellen Verbots, erkaufen sich allerdings viele besser gestellte Personen dieses Recht.
Der Fluss an zwergischen Ausrüstungen könnte dadurch nur über das Reich der Rah-Kari erfolgen. Die beschwerliche Reise über das Himmelsspitzengebirge nehmen nur geistig labile Händler auf sich. Die Festungen auf beiden Seiten der Knochenfeldschlucht blockieren hier ebenso den Weg. Als letzte Route bleibt der Nebelhain.

### Die Tiefen des Nebelhain:

Im Nebelhain sind die ökonomischen Aktivitäten im Allgemeinen seit dem Felssturz von Istval als nichtexistent zu bezeichnen. Der Mangel an Städten oder fixen Händlern ist das Problem. Ein weiteres Problem, welche den Waffenfluss zwischen Eldria und den Rah-Kari hemmt, ist der berühmte Nebelhain selbst. Da weder Infrastruktur noch gesicherte Wege vorhanden sind, ist zwar eine mögliche Gewinnspanne da, allerdings sind die wenigsten Händler bereit dieses Risiko einzugehen. Zu oft haben merkwürdige Kreaturen, Wahnsinn oder schlichtweg Desorientierung zum Verlust von Waren geführt.


### Das freie Seevolk und sein Mangel an Schmieden:

Die größte Quelle von Waffen und Rüstungen im Seevolk ist wie so oft das Festland. Der berüchtigte Materialmangel und die „Holzsparer zu See“, bekommen die günstigsten Waffen nur indirekt über den Schwarzmarkt der Rah-Kari. Hierbei nutzen illegale Händler der Rah-Kari die günstigen Eisen und Stahlpreise der Zwerge aus, um diese dann an das Seevolk im Südmeer zu verkaufen. Da allerdings weder Hochöfen noch Eisenerzminen im Wasser großartig erfolgreich sind, und die ewigen Kämpfe des Seevolks am Meer vermutlich jedes dritte Schwert in den blau-schwarzen Abgrund des Ozeans reißt, besteht trotz des eigentlichen günstigen Preises der Waffen im Südmeer, im Süd und Nordmeer ein Problem. Die Waffen werden vom Südmeer Richtung Nordmeer immer seltener und von der Qualität immer schlechter.
Gleichzeitig hat das Kaiserreich keine offiziellen Handelsbeziehungen zum Seevolk da diese „Piraten sich an keine Verträge halten wollen“.
Vermutlich liegt es auch daran, dass es im Seevolk keine wirkliche Struktur besteht und Piraten nicht unbedingt mit ihren Opfern gute Geschäftsbeziehungen führen.
Folglich gibt es nur den Schwarzmarktpreis und das was Piraten bei dem Plündern von Salzhändlern oder Fischerdörfern im Kaiserreich erbeuten.
In der Summe ist der Preis dadurch ähnlich zu dem des Kaiserreiches, allerdings in der Qualität und dem Preis her deutlich schwankender.
