# Die Lehre des Allgottes


## Struktur der Lehre des Allgott

### Bewahrer der Stille oder Pontifex Silens

Der Bewahrer der Stille ist immer männlich. Er wird auf Lebenszeit gewählt. Wahlberechtigt sind alle Bewahrer der Ruhehöfe, umgangssprachlich Priester oder Pfarrer. Die Wahl findet eigentlich in der Zitadelle der Erde unterhalb des Denkmals der Menschen statt (westlich von Civis Primae). Seit einigen Jahrzehnten, wo die Zitadelle durch ein Erdbeben beschädigt wurde, findet die Wahl in der Herberge des Allgotts in Civis Primae statt. Je nach Zustand des Kaiserreiches kommen mehr oder weniger Religiöse Entitäten der Lehre des Allgotts um sich an der Wahl zu beteiligen.  Das Konkordat von 32 n. Riga („Wächterkonkordat von Nors“) hat die reelle Möglichkeit zur Wahl auf knapp zwei Dutzend Geistliche eingeengt, welche lediglich selbst einen Ersatz für sich bestimmen können. Diese Gruppe wird als Wächter des Siegelsteins bezeichnet. im Falle ihres Ablebens oder der Verstoßung durch eine Überwältigende Mehrheit 

### Wächter des Siegelsteins
24 obligatorisch männliche Mitglieder der  Lehre des Allgottes welche neben dem Bewahrer der Stille die zweithöchste Verantwortung und Macht in der Glaubensgemeinschaft besitzen. Die Wächter des Siegelsteins können nur ihre eigenen Nachfolger bestimmen und den Bewahrer der Stille wählen. Eine Vergrößerung oder Verkleinerung der 24 Mitglieder ist seit dem Konkordat von 32.n Riga „Wächterkonkordat von Nors“ verboten. Die Wächter des Siegelsteins sind, im Gegensatz zu anderen Glaubensgemeinschaften hervorragend im Nahkampf ausgebildet und deren Zeremonielle Kleidung ist eine Goldverzierte Schwere Rüstung.

### Bewahrer der Ruhehöfe – die Priester der Lehre des Allgotts
Die Bewahrer der Ruhehöfe werden von der Allgemeinen Bevölkerung als „Pater“ oder westlichen Regionen des Kaiserreichs auch als „Pfarrer“ bezeichnet.  Deren Aufgabe besteht neben den obligatorischen Leibesübungen und dem Sicherstellen der Fragmentsteine darin für das seelische Wohl und die Frömmigkeit des Dorfes oder der Gemeinschaft zu sorgen. Sie sind verpflichtet keine Frau zu nehmen und müssen die Wächter der Ruhehöfe ausbilden. Weiters beschreibt das Buch „Das Leben der gerechten Bewahrer der Ruhehöfe“ darin auch die Verpflichtung der Gemeinde Schutz in schwierigen Zeiten zu gewähren, so wie sich väterlich um die meist jungen und kräftigen Wächter der Ruhehöfe zu kümmern.

### Wächter der Ruhehöfe
Meist Junge Männer welche mit Leibesübungen so wie am Vergraben der Verstorbenen und dem Lesen der Lehre des Allgottes ihre Zeit verbringen. Neben der Möglichkeit zum Bewahrer der Ruhehöfe aufzusteigen, sofern die Ausbildung in Civis Primae welche „Die innere Einkehr“ genannt wird, abgeschlossen wird. Die Wahl kann allerdings auch von den Wächtern des Siegelsteins erfolgen und ist, Gerüchten zu Folge, mit Großzügigen Spenden an die Gemeinschaft ebenfalls zu erreichen.


### Die Inquisition
Wird aus den Reihen der Bewahrer und Wächter der Ruhehöfe (Pater/Pfarrer) gewählt. Hierbei handelt es sich um die frömmsten und teils dogmatischsten Vertreter der Glaubensgemeinschaft. Inquisitoren sind nicht zwangsläufig männlich. Sie bekommen eine Ausbildung welche sich mit den Lehren der Verbotenen Götter und anderer, als ketzerisch angesehen Terroristen (Blutkulte) auseinandersetzen und lernen diese zu erkennen und zu bekämpfen. Inquistoren genießen rechtlich große Freiheiten und können teils auch an den mittlerweile geschwächten Adel herankommen und diese mit teils dünner Beweislage inhaftieren.  Exekutionen oder Anhörung durch die Wächter des Siegelsteins sind allerdings selten und den rund 300 Hochinquistoren vorbehalten.
Die Inqusition unterhalt eigene Informationsdienste, sowie Logistikzentren und stellt neben der Kaiserlichen Armee die militärisch stärkste Gruppierung im Kaiserreich dar.


## Die Symbole der Gemeinschaft
Das wichtigste Symbol ist die Darstellung des Siegelsteins in unterschiedlichen Farben sowie die das einer in der Sonne glänzenden Schaufel.
Die Darstellung des Siegelsteins ist meist auf den Farbigen Fenstergläsern in den Türmen der Ekklesien zu sehen.  Das Symbol der glänzenden Schaufel findet sich auf den Gewändern und Rüstungen der Bewahrer und Wächter der Ruhehöfe.  Die Bewahrer der Ruhehöfe zeigen jedoch am Rücken auch die Insignien des Siegelsteins.



## Reliquien
Das bedeutendste Relikt ist der extrem schwere Siegelstein. Hierbei handelt es sich um ein altes Relikt welche an die Gründung der Glaubensgemeinschaft zurückreicht und schon in diversen Städten im heutigen Kaiserreich gelagert wurde. Der Lageort ist meist in unmittelbarer nähe zum Bewahrer der Stille bzw. dem Pontifex Silens.

Der Hammer der Verdammten ist ein weiteres Relikt. Ein Hammer mit Griff aus Zwergenstahl und dem Schlagkopf aus dem Stück des Insigniensteins. Der Ursprüngliche Träger dieser Waffe war Pontifex Silens „Augur von Untheide“. Laut den Berichten schlug dieser 376 v. Riga so 1000 Untoten den Schädel ein und begrub dieser mit seiner Schaufel „Ewig‘ Ruh‘“ und segnete deren Gräber. Die Schaufel „Ewig‘ Ruh‘“ ist allerdings seit der Schleifung von Riga verloren gegangen.

Der Leib von „Silens Magnifans“:  Eine eingehüllter Haufen Gebeine des Silens Magnifans bezeichneten Bewahrer der Stille.  Sein unnatürlich langes Leben (Angeblich wurde er 127 Winter und im Winter von einem Brennenden Haus erschlagen.)  und die Verbrennung seiner Leiche bescherten ihn eine ewige Erinnerung. Die Gebeine werden der Zitadelle der Erde gelagert.  Seit der Zerstörung dieser liegen diese allerdings in der Zitadelle des Lichtes in Civis Primae und sind eine Touristenattraktion. Gläubige erhoffen sich davon Heilung ihrer Eltern oder Krankheiten.


## Ursprünge der Glaubensgemeinschaft
Die Ursprünge der Glaubensgemeinschaft sind äußerst umstritten.  Wenige Aufzeichnungen dieser Zeit welche  in den Bibliotheken von Athumpet lagern, legen den Schluss nahe, dass die Gründung der Religion durch einen Mörder erfolgte.
Den Bericht der Rahkari zufolge wurden Leichen vor der Gründung der Lehre des Allgottes von den Elfen entsorgt um zu Dünger für deren Wäldern zu werden. Ein Unbekannter welcher in den Aufzeichnungen „Der Irre der Reik“ genannt wird, soll hierbei versucht haben einen Mord zu verstecken und vergrub dieses Tief in der Erde. Anschließend legte er unterhalb eines Felsturzes einen Stein der Felswand auf dieses Grab.  Die Leiche erstand nicht wieder zum Leben. Spätestens ab hier, lässt der historiker aber sich nur über die „Weißnasen“ aus und verunglimpft deren Unrasiertheit, Boniertheit und deren Gestank. 
„Der Irre der Reik“ ließ sich als Prophet bezeichnen und versprach den „Toten die Ewige Ruhe zu ermöglichen“. Hierbei begrub er diese Leichen am selben Platz, allerdings weniger tief. 
Die „Weißhäutigen Flohschleudern“ glaubten ihm.  Die Beerdigungsmethode war erfolgreich. Den Berichten der Rahkari zu folge, löste das nur Desinteresse aus, da deren Bestattungsriten bereits etabliert waren.
In den folgenden Jahrhunderten fanden sich schließlich angebliche Niederschriften, welche auf eine ähnliche Geschichte hindeuten. In diesen Geschichten wird ebenfalls ein Felssturz und der erste „ewige Ruhehof“ genannt. Nach einem Felsbruch wurde ein riesiger Felsbrocken der Klippe als Religiöses Symbol genannt, welches der Prophet „Allen Menschen der Lehre des Allgotts ermöglichen soll ihre Liebsten in Ruhe zu bestatten und zu betrauern“.

Wer genau dieser „Prophet“ war ist nicht klar. Die Vertreter der Lehre Des Allgotts bestreiten, dass ihr Prophet ein Mörder war und bestrafen alle jene die es tun unter den Aspekten der Ketzerei. Die offizielle Linie des Felssturzes und der Entstehung des Insigniensteins wird als „Geschenk“ des Himmels dargestellt, wo der Allgott um das Seelenwohl der Gläubigen besorgt war.
Der Insignienstein, nachdem er deutlich verkleinert wurde und Fragmente abgeschlagen wurden, wanderte Schlussendlich in die Zitadelle der Erde unter dem Denkmal der Menschen, westlich von Civis Primae.

## Handhabung der Glaubensgemeinschaft

Der Diebstahl oder die „Verbringung“ von Insigniensteine ist unter „Störung der Totenruhe“ mit harten Strafen bedacht. 
In Glaubensfragen den Bewahrer der Stille zu widersprechen, wird meist als Ketzerei geahndet.

Mitglieder der Glaubensgemeinschaft müssen eine „Schaufelschuld“ oder „Stille Schuld“ begleichen, sobald diese geboren werden oder in die Gemeinschaft eintreten. Dieses Geld wird verwendet, um die Liegenschaften der Gemeinschaft zu verwalten und den Mitgliedern den Allgottstrunk zu ermöglichen.
Kann die Schaufelschuld nicht bezahlt werden verliert das Mitglied seinen Familiennamen und das Erbe übergeht an den Pontifex Silens/ Bewahrer der Stille. Sofern reue gezeigt oder der Dienst an der Gemeinschaft gezeigt wird, ist es möglich, dass der Bewahrer der Ruhe, oder in seiner Vertretung die Wächter des Siegelsteins, dieses Erbe und den Namen wieder zurück an das Glaubensmitglied geben.
Unabhängig von den Rechten der „Lehre des Allgotts“ eine Begleichung der Schuld meist zu einer starken sozialen Ächtung dieser Person oder gar dem Verstoßen aus der Gemeinschaft. Lynchaktionen werden hierbei über all die Jahrhunderte immer wieder berichtet.



## Einstellung gegenüber anderen Religionen

### Relgion und Gebräuche der Waldelfen
Die Relgion der Waldelfen, auch wenn es möglicherweise eine Übertreibung ist, diese als Glaubensgemeinschaft zu bezeichnen, steht teils im Widerspruch zu den Lehren des Allgotts. 
So ist beispielweise die Bestattung der Toten in waldelfischer Manier, sprich die Verwertung der Leichen zu Dünger, ungern gesehen und wird meist mit Geldbußen und Auspeitschung geahndet.

Das Ziel, dass die ganze Welt mit Wald bedeckt werden soll und das öffentliche Befürworten dieses Planes kann hingegen nicht unter Strafe gestellt werden. Hierbei wird auf das kaiserliche Dekret von 344 vor Riga verwiesen, wonach dann auch Forstwirte bestraft werden könnten. Dadurch folgte eben 344 v. R. die Ausnahme aus dem Blasphemieerlass. Mit diesem Thema verwandte Rituale, welche Aufgrund der Uneinheitlichkeit eben dieser, können allerdings mit Zuchtstrafen oder Geldbußen belegt werden. Die Juristikation dieser obliegt allerdings meist dem lokalen Bewahrer der Ruhehöfe.


## Kuriositäten:
### Kreuzzug gegen den Teufel:
Die Inquisition  startete mit militärischer Unterstützung der Kaiserlichen Armee eine Systematische Zerstörung sämtlicher Kulte und Orte ketzerische  Natur. Der Kreuzzug endete allerdings in einer Schmach, als eine Armee aus Untoten in der Nähe von Steingarten die Anzahl der Beteiligten massiv reduzierte.
Weitere Kreuzzüge gegen den Teufel gab es in weitaus kleinerer Manier immer wieder über die Jahrhunderte, jedoch nie mit einer derart großen Beteiligung der Kaiserlichen Armee. Meist werden hier Vertreter von Blutkulten und Anhänger von ketzerischen Göttern ( Im Volksmund als Blutgott bezeichnet) gejagt, und erhängt oder verbrannt und anschließend begraben.


### Den Allgottstrunk ermöglichen:
Die Reise welche Totkranken oder Sterbenden ermöglicht einen würdigen Abschied von der fleischlichen Welt zu nehmen. Hierbei wird mit schmerzlindernden Substanzen das Leben erträglich gemacht. Das Ableben dieser sterbenden erfolgt spätestens in 1 bis 1,5 Wochen.

#### Ekklesia:
Gebetsgebäude mit anschließenden Friedhof sowie den im Gebäude gelagert Wohnstätten und Kräutergärten für die Bewahrer und Wächter der Ruhehöfe. Bieten meist kleinere Bibliotheken und Lernstuben für Pilger.

#### Hochinquistor:
Wie ein Inquistor nur mit der rechtlichen Grundlage zur Exekution oder Erhängung von verdächtigen Personen. Es gibt im gesamten Kaiserreich nach offiziellen Angaben nur knapp 300 Hochinquisitoren.

#### Fragmentsteine:
Steine welche wie der Siegelstein in Civis Primae, eine heiliges Symbol der Lehre des Allgottes darstellen und, laut dem Volksmund sicherstellen, dass die Toten ihre Ruhe finden und nicht zurückkehren.

#### Siegelstein:  
Mehrere Ochsen schwerer Stein, heiligstes Reliq der Lehre des Allgottes.  Leuchtet Nachts schwach bläulich wenn dieser mit Weihwasser beträufelt wird. Ist im oder nahe der Kammer des Pontifex Silens gelagert.


#### Die Herberge des Allgottes:
Die Herberge des Allgottes ist das zweitgrößte Gebäude in Civis Primae und hat neben einer riesigen Bibliothek ein Dach aus Kupferziegeln wo mit Goldziegeln das Symbol der Lehre des Allgotts geformt ist.

#### Innere Einkehr: 
Ausbildung der Wächter der Ruhehöfe zu vollwertigen Bewahrer der Ruhehöfe. Im Volksmund wird hier meist von „Patermachung“ gesprochen. Die Ausbildung dauert rund 8 Jahre und endet mit einer feierlichen Zeremonie sowie der Feierlichen Überreichung einer schweren Rüstung. Die Ausbildung beinhaltet neben dem Lernen und Verstehen des wichtigsten Buches „Die Lehre des Allgotts“ auch ein mehrwöchige Ausbildung im Niederstrecken von Erwachten sowie der Behandlung der Krankheiten welche diese durch Bisse verursachen. Sobald Die Ausbildung oder die „Berufung“ zur Inneren Einkehr erfolgt, können diese Menschen nicht mehr zum Militär des Kaiserreiches Berufen werden.









###  OLD/ OBSOLETE
Wenn man den Gelehrten glauben kann, entstand die Verehrung des Allgottes in den primitiveren Zeiten des Herzlandes und noch lange vor der Formierung des Kaiserreiches. Manche Quellen berichten sogar davon, dass sich die Freundschaft und kulturelle Ähnlichkeit zwischen Nors und dem Herzland zu großen Teilen durch Missionare der Ekklesia des Allgottes erklären lässt.

Die Lehre des Allgotts ist - nach dem Rah Kas - die größte Glaubensgemeinschaft in Orbis Astea und ist im Kaiserreich allgegenwärtig, jedoch auch im Norden Eldiras stärker vertreten.

## Organisation {#Ekklesia}

Die Ekklesia existiert schon länger als das Kaiserreich selbst. Bereits als die Beziehungen zwischen Nors und dem Herzland anfingen startete die Ekklesiarchie Missionen, die im Endeffekt zu einer monotheistischen Stellung des Glaubens des Allgottes führten.

Die Ekklesia schafft es auch politisch sehr relevant zu sein. Ihr Vorsitzender - der Pontifex Maximus - wird als die zweiteinflussreichste Person im ganzen Kaiserreich gehandelt. Die Leitmeinungen der Ekklesia leiten zum Teil die Tagespolitik und haben schon häufiger gesellschaftliche Veränderungen mit sich gebracht. Durch die große politische Kontrolle schaffte es die Ekklesia andere Glaubensrichtungen im Kaiserreich verbieten zu lassen und eine eigene Streitmacht mit weitreichenden Berechtigungen zugesprochen zu bekommen.

Die Ekklesia ist verantwortlich für die Bestattung der Toten und das Verbreiten und Bewahren des Glaubens. Ihre Priester nehmen Segnungen, Beichten und Messen vor. 

Des weiteren finanziert die Ekklesia viele Forschungsteams, die in sämtlichen wissenschaftlichen Bereichen - vor allem aber in der Erforschung der <font color="green">[Blutgötter](#Blutkult)</font> führend sind.

Jedes Jahr nimmt jede Kirche eine Reihe junger Männer und Frauen - sogenannte Gottesdiener - auf und bildet sie zu Priestern, Inquisitoren oder - in den meisten Fällen - zu 



## Symbolik

Kein Anhänger dieser hexerischen Rah Kari die den Prozess der der Erweckung nur hinhaus zögern können da ihre Götter keine Wahren sind und sie sicher lästerlicher Hexerein bedienen müssen

und natürlich hilft das verbrennen was nicht da ist kann nicht wiederauferstehen ein kind hätte diesen zusammenhang erkennen können ein scherz für die so hoch gepriesene intelligenz der zwerge

hätten sie doch erkennen müssen das nur er der Allgott uns die möglichkeit gibt Freunden und Familie Frieden zu geben durch den einfach Akt des Gesegneten Begrabens

Nur ER allein ist mächtig dazu

Dieser eine hört das wort des einen

Man sagt er begann damit leichen zu vergraben in tiefen tiefen löchern weil er den worten nicht traute, doch als sie nicht wieder nach oben kamen verbreitete sich das wort wie ein lauffeuer und immer oberflächlicher wurden die Gräber ohne das ein Wiedergänger erschien.

die Anhängerschaft wuchs und er der Prophet predigte das es nur den einen Geben kann. Ab einem Punkt hatte er die Menschen überzeugt sie fingen an den Pakt mit den Elfen zu brechen und stoppten die Lieferungen ihrer Toten

Als bald folgte die Unterwerfung der Elfenstämme die sich bisher so treu an den Pakt hielten und die untoten beseitigten da sie nicht an das wahre Wort glaubten

Viele starben und noch mehr wurden in die Sklaverei geschickt um ihnen die Worte des einen in die Körper zu brennen

man sagt bis heute tragen es die noch wilden Elfenstämme den Menschen nach und erinnern sie an den alten Pakt auf makabere Weise in dem sie Leichen in Brunnen werfen um Wasser zu vergiften

(und den armen Dorfbewohnern die Qual durch die Untoten vor Augen zu führen vor der nur sie sie schützen können.

Doch dies ist nicht wahr so sehen wir es Tag ein Tag aus)



