# Die Lehre von Zamrak


### Hier muss noch alles formatiert und an die anderen RMDs angeglichen werden 

## Die Ursprünge Zamraks
In der Frühzeit der Menschen verursachten Monster und Abscheulichkeiten allerortens Chaos und verwüsteten die Länder der menschlichen Rassen.
Dies hatte zur Folge, dass die Menschen Orbis Asteas zunehmend verzweifelten und auf Erlösung durch ihre Gebete hofften.
Schließlich wurden ihre Gebete erhört und die Antwort darauf hieß Zamrak, eine Gottheit für die Jagd gegen die Monster.
Um das Wort Zamraks in Orbis Astea zu verbreiten, griffen die Menschen Orbis' zu den Waffen, um als die Krieger des Zamraks bekannt zu werden.

In den alten Tagen verteilten sich diese Krieger über den ganzen Globus und bekämpften jedes lebende Tier, das sie finden konnten.

## Die Ausbildung der Krieger

Obwohl sie anfangs erfolgreich waren, sahen sie sich schließlich großen Hindernissen gegenübergestellt.
Trotz des Segens ihres Gottes gab es einen wichtigen Faktor, der dazu führte, dass das Leben vieler Zamrak-Krieger nur von kurzer Dauer war - ihre Ausbildung.
Viele dieser Menschen waren einfache Leute, die nie eine ernsthafte Ausbildung erfuhren, deren Priorität es war ihre Mitmenschen zu schützen und die Ungeheuer, die ihr Land terrorisierten, zurückzudrängen.
Einige Kämpfer bildeten daher eigene Gruppen, um aus diesen einfachen Bürgern richtige Soldaten zu formen und sie zu trainieren.
Die Nachfrage nach dieser Ausbildung war jedoch so hoch, dass sie die Kapazitäten der ausbildenden Gruppen bei weitem überstiegen.
Obwohl alle Krieger ihr Bestes taten, um so viele Bürger wie möglich auszubilden, so würden doch die meisten Krieger Zamraks ihr Ende zwischen den Reißzähnen einer Bestie finden, diese zu bekämpfen vermochten.
Mit schwerem Herzen erkannten die Krieger, dass ihre Zahl zunehmend schrumpfte.
Sie entwickelten einen Plan, um die Monster weiter in Schach halten zu können -- die Schaffung einer zweiten Kriegergeneration.
Um diesen Plan erfolgreich umsetzen zu können, mussten sie jedoch zunächst dem verweilenden Schatten Ga'ars, der Gottheit der Monster, gegenübertreten, da sich dieser schleichend wie Nebel über die Reihen der Krieger legte und diese fortschreitend vernichtete.
Somit fassten die letzten Soldaten den Entschluss, sich in zwei Gruppen aufzuteilen, von welcher eine sich auf den Weg ins Bermatal machen sollte und eine mit dem Aufbau der zweiten Generation von Kriegern beginnen sollte.
Als der, zu diesem Zeitpunkt wohlbekannte, Gott Zamrak die Nachricht von diesem Plan erhielt, beschloss er, die ihm zur Verfügung stehende Macht zu nutzen, um seine Jünger zu führen.
Zu diesem Zeitpunkt war das Eisland eine eisige Einöde, in der kein intelligentes Leben zu finden war.
Zudem lebte dort eine große Anzahl von Monstern, da keine andere Rasse dieses Land bewohnte und sie daher jagen müsste.
Tief in den Höhlen des Eislandes gab es jedoch ein vergessenes Artefakt, welches aus den Zeiten der Prerunner stammt.
Den wenigen Männern, die der zweiten Gruppe der Zamrak-Krieger noch geblieben waren, gelang es, ein letztes Mal das Wort ihres Gottes zu verbreiten.
Dies gab Zamrak genug Macht, um die Seeleute so zu beeinflussen, dass diese im Eisland stranden würden.
Dort fanden sie das Artefakt, welches noch immer Hitze ausstrahlte, da es nach dem Verschwinden des ursprünglichen Benutzers nie abgeschaltet wurde.
Neben dem Artefakt fanden sie seltsame Höhlenschriften, die sie nicht richtig interpretieren konnten, da sie die Sprache, in der sie geschrieben waren, nicht kannten.
Aus diesen Schwierigkeiten ergaben sich Übersetzungsfehler, welche dazu führten, dass die gestrandeten Seeleute Zamrak als Gott der Transformation interpretieren und verstehen würden.
Dieses Bild von Zamrak und der Glaube an dieses führte dazu, dass Zamrak selbst sich in einen Gott verwandeln sollte, der dem Bild entspricht, wie es die heutigen Animali von ihm haben.
Die Fehlübersetzung der Höhlenschriften veranlasst die Schüler dazu, den Gegenstand des Artefakts als heiliges Symbol zu sehen, welches sie von ihrem Gott erhalten haben, und, aufgrund der fehlerhaften Übersetzung, „Stab des Molak" nannten. Dieser, nun heilige, Stab wurde fortan zu allen großen Schlachten mitgenommen, um die Moral der Soldaten der zweiten Generation im Kampf zu stärken. Diese Kämpfer, die heutigen Animali, wussten nicht, dass dieses Artefakt als Werkzeug für die Terraformung des Territoriums des Eislandes gedacht war. Die Prerunner planten mit dieser Maschine das Eisland so umzugestalten, dass sie das Land für den Massenbau nutzen konnten. So kam es, dass die Animali den Stab von Molak mitnahmen, als sie den Welt-Wurm verfolgten. Es gelang ihnen hierbei den Stab zu ihren Gunsten einzusetzen und damit das Monster zu töten. Da die Animali jedoch nicht wussten, wie sie den Terraformer einsetzen sollten, wurde er während der Schlacht zerstört. Als die ersten Krieger von Zamrak ihre Bemühungen in Richtung des Bermatals umsetzten, sah der Blutgott der Monster Ga'ar dies nicht als Bedrohung, sondern eher als Chance. Da sie einen starken Einfluss auf die Länder nehmen konnte, die von den Kriegern Zamraks gewählt wurden, um dort ihren letzten Widerstand zu leisten, war es ihr möglich, diese so zu manipulieren, dass sie mit der Zeit zu ihren eigenen Anhängern und loyalen Schergen werden würden. Nicht lange nach ihrer Ankunft verspürten die Krieger einen seltsamen Drang, das Land , und damit auch die dort lebenden Monster, zu beschützen. Dieser Drang entsprang einer Zusammenarbeit Ga'ars mit der Göttin der Illusionen, welche gemeinsam die Manipulation der Schüler Zamraks durchführten. Das Bermatal ist nur wenigen Menschen ein Begriff. Jene, die es dennoch entdecken ereilt ein schneller Tod durch die Hand der neuen reformierten Zamraks-Krieger, die nun der Göttin der Monster dienen. Diese Krieger umgeben fortan das Land des Bermatals und nehmen, wie die zweite Generation der Zamrak-Krieger, eine Verwandlung vor, um ihrer neu gefundenen Göttin zu huldigen. In diesem Prozess nehmen sie eine bestialischere Gestalt an. Die Gestalt Zamraks wird als riesenhafter Animalus mit drei ständig wechselnden Köpfen beschrieben, dessen Körper mit dickem Fell und einer Chitin-Rüstung bedeckt ist. Er schwingt die große Obsidian-Hellebarde von Tomtrik und den Bernsteinbogen Sitrak. Trotz seiner wechselnden Köpfe bleibt ein Merkmal immer konstant. Das linke Auge seines mittleren Kopfes ist immer blutrot. Die ist eine Narbe, welche er sich im Kapf gegen den Eisriesenkönig Bolwark zuzog, dessen Leichnam sich in den Berg Surr verwandelte, welcher heute im Eisland zu sehen ist. In seiner rechten Hand befindet sich ein silberner Reichsapfel, mit dem er die Struktur seines Volkes und anderer Wesen in seiner Gewalt verändern kann. Zamrak ist der Gott der Verwandlung und stellt ein Symbol für die Art und Weise, wie Animali leben sollten. Er verändert und verwandelt sich ständig, um sicherzustellen, dass er und sein Volk niemals stagnieren und schwach und berechenbar werden. Damit dies geschehen kann, gab Zamrak seinem Volk die Fähigkeit, sich zu verwandeln und Fähigkeiten zu erwerben, die am besten geeignet sind, um stark zu werden und alle Hürden zu überwinden mit denen sich seine Krieger konfrontiert sehen. Aus diesem Grund sehen die Animali die Transformation als einen heiligen Akt und ein Geheimnis an, das immer gewahrt werden sollte, koste es, was es wolle. Die Animali glauben, dass Zamrak über die Nordlichter mit seinem Volk kommuniziert, wobei jede Farbe und Farbkombination eine bestimmte Bedeutung hat. Eines der meist verehrtesten Nordlichter ist das weiße Licht der Berufung. Diesem wird nachgesagt, dass Zamrak auf diese Weise um Hilfe im Kampf bittet, die eine weitere Welle an Monstern verhindern soll. Während dieses Ereignisses opfern die Stämme des Eislandes die Körper ihrer größten Krieger in einer Zeremonie. Darüber hinaus glauben die Animali, dass ein vollkommen grünes Nordlicht einen Wegweiser darstellt, der die Richtung angibt, in welche ein Stamm reisen sollte, um Glück zu erfahren. Ein bernsteinfarbenes und violettes Licht bedeutet, dass ein Stamm seinen Gott erzürnt hat. Ein vollständig braunes Licht bedeutet, dass es eine große Bestie gibt, die es zu töten gilt.

-   Artefakt wurde aufgrund von Übersetzungsfehlern als etwas Heiliges angesehen!
-   Als ein heiliges Symbol wurde es als Moralapostel mitgenommen!
-   Animali wussten nie, wie man es benutzt/ sie wussten nie, was es war!
-   Geben sie dem Artefakt einen coolen Namen, es wird eine tiefe Überlieferung sein, es soll einfach ein Artefakt sein, das sie gefunden haben!
-   Das Artefakt war, solange es nicht benutzt wurde, immer noch an, und dadurch strahlte es Hitze aus, wodurch die Seeleute überleben konnten!
-   Das Artefakt wurde während des Kampfes von Nebelham zerstört!
-   Die Insel in Nebelham, auf der es ein Fragezeichen gibt, wird der Ort sein, an dem das Monster von den Animali besiegt wurde. Dort wird es einen Schrein geben, der von den Animali von Nebelham errichtet wurde.
-   Gott kann nicht sprechen, aber kann Menschen beeinflussen!
-   Gott manipulierte die Art und Weise, wie die Menschen, die den Text lasen, ihn verstanden
-   Die erste Welle von Kriegern schaffte es, das Wort ihres Gottes zu verbreiten, um ihm genug Macht zu geben, die Matrosen so zu manipulieren, dass sie zur zweiten Welle wird!
-   Die Göttin der Illusionen half Ga'ar, die erste Welle zu manipulieren. Ga'ar selbst konnte das nicht tun, weil sie nicht die Göttin ist, die die Menschen manipuliert!
-   Durch die Fehlinterpretation des Textes wurde der Gott auch in eine neue/andere Art von Gott verwandelt und dadurch und auch durch die Verwandlung der Animali sein er als solcher bekannt!
-   Sowohl die erste als auch die zweite Generation der Krieger unternahmen eine Verwandlung, um stärker und mehr wie Monster zu werden. Das Ritual, dass die erste Generation unternahm, wurde von der Göttin der Illusionen beeinflusst, was bedeutete, dass Ga'ar in der Lage sein würde, sie nach ihrem Willen zu manipulieren!
