# Die Lehre des Rah' Kas

Obwohl das Rah' Kas hier unter Religionen aufgelistet ist, ist es mehr als nur das. Das Rah' Kas ist eine Staats- und Gesellschaftsform, die im Süden Asteas - von den danach benannten <font color="green">[Rah' Kari](#RahKari)</font> gelebt wird. Das Rah' Kas ist ein ebenso rigides wie strenges Regelwerk und weißt den Menschen bereits bei ihrer Geburt einen Bereich - den sogenannten Kult - zu, innerhalb desem ein Mensch sein Leben lang kultkonforme Tätigkeiten ausführen darf und auch innerhalb der Organisation des Kultes aufsteigen kann.

Wichtig bei der Betrachtung der Kulte ist die Rolle der Frauen, die bei der Geburt in ihren eigenen Kult gebracht und dort fernab ihrer Eltern erzogen werden. Dieser Spezielle Kult ist der Kult der Shafra - der Heilerkult.

Im allgemeinen ist unmöglich zu sagen, wo das Rah' Kas anfängt und die tatsächliche Politik und Geschichte der <font color="green">[Rah' Kari](#RahKari)</font> anfängt, weswegen interessierten empfohlen wird beide Entitäten holistisch zu studieren.

## Organisation {#HoheKulte}

Die Organisation des Rah' Kas kann man eher als Organisation der einzelnen Kulte beschreiben, zwar gibt es den hohen Rat der Kultführer - den Rat der Rah' Kari - doch der größte Teil der Verwaltung wird in den einzelnen Kulten abgehandelt. Da es in diesem Artikel nicht um die Politik geht, sondern um die Religiöse Praxis, wird vor allem auf diese eingegangen.

Im Rah' Kas gibt es acht legitime Kulte oder Pfade, diese sind:

-   Der Pfad des Kriegers mit der Verehrung des Gottes Tarkus Rah
-   Der Pfad des Bauers, gewidmet der Göttin Pseptha
-   Der Pfad des Handwerks - gekoppelt an die Verehrung des Kha'fan
-   Der Pfad der Pferdezüchter mit Hestua als Leitgöttin
-   Der Pfad der Heiler und Frauen - der Pfad der Shafra
-   Der Pfad der Künstler unter dem Schutzgott Amdju
-   Der Pfad der Händler und die Verehrung von Meliodas
-   Der Pfad der Hüter - der Pfad des Unes Utet

Jeder dieser Pfade hat eine eigene Verwaltung und stellt sozusagen einen eigenen Staat im Staat der Rah' Kari dar. Die Kulte besitzen eigene Strafen und Gesetze - so kann eine im einen Kult legale Handlung in einem anderen Kult zur Versklavung oder gar zur Todesstrafe führen. Beispielsweise ist der Kriegerkult stark reguliert, während im Hüterkult kaum Regeln vorhanden sind. Neben eigenen Gesetzen und Verwaltungen sind auch die größen der Kulte unterschiedlich - der größte Kult ist wohl der Heilerkult, gefolgt von den Handwerkern und Bauern. Der Kult der Hüter und der Künstler stellen die kleinsten Kulte dar.

Wie bei eigenen Staaten gibt es auch genügend Beispiele dafür, dass gewisse Kulte Streitigkeiten untereinander hatten. So ist eine der führenden Theorien dafür, dass die Rah' Kari lange Zeit lang keine Rolle in der globalen Politik gespielt haben jene, dass verschiedene Kulte untereinander Machtkämpfe geführt haben. Erst die externe Bedrohung durch das Kaiserreich und den Pfad des neunten sorgte wieder für Einigkeit unter den Kulten.

### Oberhaupt

Jeder Kult hat seinen Hohepriester - den Selkiten - der ihm sowohl religiös als auch politisch führt. Die Versammlung aller Selkiten führt dann auch die Nation der Rah' Kari, die eine Föderation der verschiedenen Kulte darstellt.

Während auf dem Papier alle Kulte gleichbereichtigt sind und ihre Selkiten gleich viel zu sagen haben, gibt es in der Realität Kulte die deutlich einflussreicher sind als andere. Die mächtigsten Kulte hierbei sind der Kult der Pseptha - der Bauernkult, der Kult der Shafra - der Heiler und Frauenkult und der wohl machtigste Kult, der Kult des Unas Utet. Diese drei Kulte sind zwar die poltischen Schwergewichte der Rah' Kari - jedoch nicht unbedingt die Kulte, die religiös am meisten Gewicht haben.

Sämtliche Kulte sind hierarchisch aufgebaut, aufstieg ist nur möglich durch Beförderung von oben - eine Tradition, welche bei manchen Kulten das entstehen von Seilschaften stark begünstigt hat.

## Geschichte

Die Geschichte und Mythologie des Rah' Kas deckt sich mit der <font color="green">[Geschichte der Rah' Kari](#RahKari)</font>

## Glaubenssätze

## Gebote und Verbote

## Wichtige Orte

## Riten

### Totenkult

## Symbolik
