# Das Grenzland

Das Grenzland ist die Außengrenze des Kaiserreichs mit Eldria und damit eine der Regionen, die mit der blutigen Vergangenheit eines Kriegsgebietes mithalten können. Aufgrund der vergangenen Konflikte sind Erwachte dort häufiger als im Herzland und lokale Garnisionen müssen oft Kräfte mobilisieren um Friedhöfe, Gruften und ehemalige Schlachtfelder so weit abzuschirmen, dass die Transportwege sicher sind. 

![Karte des Grenzlandes]

Die eben genannten Transportwege sind eine der wichtigsten Eigenschaften des Grenzlandes. Das Grenzland stellt nämlich den sichersten Weg nach Eldria dar, da der kürzere Weg durch den <font color="green">[Silva Nacia](#RegionSilvaNacia)</font> geht, der bekannterweise aufgrund der elfischen Aktivitäten nicht der sicherste Weg ist - vor allem nicht für die Logistik des Kaiserreiches. 

## Ortschaften der Region 

### Infrastruktur

## Die Geschichte der Region

Das Grenzland hat seinen Anteil an blutigen Konflikten und Kriegen, da es oft das Schlachtfeld für viele Zusammenstöße zwischen dem Kaiserreich und den Mächten von Eldria war. Einer dieser Zusammenstöße war die "Rote-Schock-Schlacht" im Jahr 188. Die Fürsten von Eldria bereiteten sich darauf vor, ihre Streitkräfte ins Grenzland zu verlegen, um ihre Vorherrschaft in der Region zu stärken, doch das Kaiserreich hatte Spione in die Reihen Eldrias eingeschleust, die ihre Pläne verrieten. 
Mit diesen Informationen schickte das Imperium eigene Truppen in die Region, um die rivalisierenden Armeen in einen Hinterhalt zu locken und die Kontrolle über die Region an sich zu reißen. In dieser Schlacht enthüllte das Kaiserreich eine der geheimen Waffen, die "Hammerer von Alt-Greifenstadt". Es war das erste Mal, dass die Armeen Eldrias auf diese Streitkräfte trafen, und folglich hatten sie einen massiven Einfluss auf die Schlacht, da sie darauf spezialisiert waren, die Ritter Eldrias effektiv auszuschalten. Die Schlacht endete mit einem entscheidenden Sieg für das Kaiserreich. Auch wenn dies nicht die letzte Schlacht zwischen den beiden Mächten war, so war es doch diejenige, die den Krieg zu Gunsten des Reiches entschied. 

Eine weitere berüchtigte Schlacht, die zu einer der schrecklichsten Zeiten im Grenzland führte, war die Schlacht bei den Qirrik-Hügeln. Auch hier standen sich die Streitkräfte Eldrias und des Kaiserreichs gegenüber, doch diese Schlacht war keineswegs einseitig.
Beide Mächte hatten große Verluste zu beklagen, doch am Ende ging Eldria als Sieger hervor. Trotz ihres Sieges befanden sie sich in feindlichem Gebiet und hatten nur noch eine Handvoll Soldaten, die ohne Kommandanten dastanden. Traurigerweise mussten die Soldaten die unehrenhafte Entscheidung treffen, das Schlachtfeld zu verlassen, ohne sich um die Toten zu kümmern. Diese Entscheidung führte zur Entstehung dessen, was heute als die "Verfallenen Hügel von Qirrik" bekannt ist.  Nach nicht allzu langer Zeit wurde das Grenzland von einer ganzen Armee von Untoten heimgesucht, und viele Wochen lang war das Leben der Grenzlandbewohner durch die Untoten bedroht. Es bedurfte der vereinten Kräfte der 7. Legion und der im Grenzland stationierten Truppen, um die Untotenarmee zu besiegen. Untote waren im Laufe der Geschichte des Grenzlandes ein großes Problem, da unzählige Schlachten in der Region stattgefunden haben und viele Leichen unbeaufsichtigt gelassen wurden. 


## Wirtschaftliche Lage

### Die Ressourcen der Region

Das felsige und hügelige Gelände des Grenzlandes macht den normalen Ackerbau sehr schwierig,  weswegen die Region vor allem von der Viehzucht lebt. Infolgedessen produziert das Grenzland jedes Jahr eine große Menge an Fellen und Pelzen. Die Felle reichen von Nerzfellen bis hin zu Ziegenfellen. Wer das Grenzland durchstreift, wird höchstwahrscheinlich auf mehrere Pelzproduzenten treffen, die sich auf bestimmte Tiere spezialisiert haben.

Eine weitere Ressource, die im Grenzland weit verbreitet ist, ist Holz, genauer gesagt Brennholz. Aufgrund des eigenartigen Klimas und der wechselnden Temperaturen im Grenzland ist das meiste Holz in der Region nicht stark genug, um in großen Gebäuden oder Schiffen verwendet zu werden, weshalb sich die Menschen im Grenzland dafür entschieden haben, Geschäfte mit Brennholz und Holzkohle zu machen. Das Geschäft mit der Holzkohle ist so bedeutend geworden, dass über die Hälfte der Holzkohle von Herzland aus dem Grenzland importiert wird. Das einzige Ressourcenproblem, mit dem Grenzland konfrontiert ist, sind Erze und Salz. Zwar gibt es im Grenzland einige seltsame Erze, die meisten davon sind jedoch nutzlos.


## Soziopolitische Lage 

Aufgrund der eher desolaten Lage des Grenzlandes migrieren viele junge Erwachsene in Richtung des Herzlandes, da die wirtschaftlichen Chancen in den Großstädten deutlich besser und aussichtsreicher sind als die, die die kleinen und mittleren Städte des Grenzlandes biesten können. Dieser Mangel an jungen Menschen macht sich sowohl wirtschaftlich als auch militärisch bemerkbar. 

### Der Orden der Säuberung

Der Orden der Reinigung wurde mit dem einzigen Ziel gegründet, die Ländereien des Grenzlandes von den Untoten zu säubern, die wie eine Plage sind. Der Orden wurde kurz nach dem Sieg über die untote Armee der Qirrik-Hügel gegründet. Das Imperium wusste, dass es, wenn es die Region übernehmen und eine Infrastruktur aufbauen wollte, dafür sorgen musste, dass die Untoten kein Problem mehr darstellen würden. Der Orden setzt sich aus Soldaten zusammen, die sich auf die Vernichtung von Untoten spezialisiert haben. Als solche tragen sie stets Ausrüstung für die Bestattung der Toten bei sich. Sie sind an ihrem Symbol zu erkennen, das eine Blume unter einer strahlenden Sonne darstellt. Der Orden hat sogar besondere Beziehungen zur Kirche, da er eine Unterabteilung der Ekklesia ist. Eines der größten Probleme des Ordens ist jedoch, dass er einfach nicht über genügend Truppen verfügt, um größere Gruppen von Untoten zu bekämpfen (z. B. nach einer großen Schlacht), weshalb er seine Reihen oft mit Veteranen aus der Söldnergilde aufstockt. Natürlich bezahlen sie diese mit Geld, aber ihre Hauptbezahlung besteht darin, dass sie ihren politischen Einfluss, der von der Kirche ausgeübt wird, nutzen, um Mitglieder der Gilde vor rechtlichen Konsequenzen zu schützen.  


### Herrschaftsystem/Organisation

## Klimatische Bedingungen

### Die Flora und Fauna

#### Monster in der Region

## Geschichten der Region

### Der Köpfer von Pikliven

Die Geschichte hat uns gezeigt, dass sich in Zeiten von Konflikten und Kriegen Nachbarn, Freunde und sogar Familienmitglieder aufgrund der Krise, in der sie sich befinden, oft gegeneinander wenden. Manche Menschen sehen diese Krisen sogar als Gelegenheit, ihre eigenen bösartigen Absichten zu verfolgen. Eine solche Person war der Köpfer von Pikliven.  Niemand kennt seine wahre Identität oder weiß, woher er kommt. Viele spekulieren, dass er ein ehemaliger Zenturio des Kaiserreichs ist, der einen großen Hass auf Eldria hegt. Manche sagen, er sei ein vom Allgott gesandter Vergeltungserfüller, der uns für die unzähligen Kriege zwischen uns bestrafen soll. Der Köpfer wird als ein großer, grau gekleideter Mann mit einem modifizierten Menschenfänger dargestellt, der selbst die besten Ritter enthaupten kann. Der Köpfer von Pikliven wurde erstmals 207 nach der Schlacht von Krissweg gesichtet, als er die Köpfe der toten Soldaten einsammelte. Es heißt, dass man die Schreie der enthaupteten Seelen hören konnte, die an seiner Hüfte hingen und um Hilfe riefen. 7 Jahre nach seinem ersten Auftauchen berichtete ein Bauer in Pikliven, dass er unter der Erde Menschen in Todesangst schreien hörte. Später stellte sich heraus, dass es sich um die enthaupteten Köpfe handelte, die vermutlich vom Enthaupteten von Pikliven in den Boden gesteckt worden waren. Auch heute noch kann man die Schreie der Opfer des Enthaupteten hören, wenn man durch die Landschaft von Pikliven fährt.

## Die verlorene Stadt Ferinstill

Die Geschichte von Ferinstill beginnt mit seinem Gründer, der Familie Kishiv. Die Kishiv-Familie erlangte nach dem Niedergang der ""-Familien in Eldria große Bedeutung. Obwohl sie zuvor mehrere Bauernhöfe in Eldria verwaltet hatten, stiegen die Kishivs nach dem Machtverlust der ""-Familie auf, indem sie neue Technologien im landwirtschaftlichen Bereich einführten. Im Jahr "" schließlich ernannte der Führer von Aerlham das Oberhaupt der Familie Kishiv, Hostus Sai Kishiv, offiziell zur Speerspitze des landwirtschaftlichen Fortschritts in der relativ neuen Region Eldrias, dem Grenzland. Die seltsame Fauna und das Ökosystem des Grenzlandes faszinierten Hostus, und so beschloss er, sein neues Hauptquartier inmitten der Wälder und Berge des Grenzlandes zu errichten, das schließlich zur Stadt Feringstill wurde. 

Obwohl es für die Familie anfangs schwierig war, sich im Grenzland niederzulassen und eine Wirtschaft aufzubauen, die auf den verschiedenen Produkten der Region basierte, war der schwierige Teil ihrer Geschichte noch nicht zu Ende.  Nach einigen Jahren kamen zahlreiche Migranten in der Hoffnung auf neue Möglichkeiten ins Grenzland, und folglich mussten Tausende von neuen Mündern in der Region ernährt werden, eine Aufgabe, die die Familie Kishiv auf sich nahm. Diese Aufgabe erwies sich jedoch als besonders schwierig, da die Familie mit ihrer derzeitigen Technologie und Infrastruktur einfach nicht in der Lage war, genügend Getreide und Vieh zu ernähren. Sie versuchten alles, was ihnen einfiel, auch wenn es in einer moralischen Grauzone lag. Sie versuchten, neue essbare Pflanzen und Nahrungsquellen zu entdecken, was dazu führte, dass viele Bürger an Vergiftungen starben. Sie versuchten, verschiedene Gemüsesorten und Pflanzen zu kreuzen, was dazu führte, dass mehrere Ernten ungenießbare Lebensmittel erbrachten.

Schon bald wurde die Familie mit der harten Realität der Situation konfrontiert.  Trotz aller Bemühungen war es ihnen nicht möglich, die vielen Menschen im Grenzland zu ernähren. Im Jahr 189, nicht viele Tage nach einer weiteren Missernte, kam ein Brief aus Aerlham. Die Fürsten von Eldria rüsteten sich für einen neuen Krieg, und Kishiv wurde damit beauftragt, genügend Nahrung für die Truppen zu beschaffen.

>Wisset, dass ihr Grenzen habt, meine Söhne. Am Ende des Tages sind wir Menschen. Nicht mehr und nicht weniger. Obwohl Gott uns seine Gestalt und seine Gaben gegeben hat, sind wir nicht er. Unser Volk sieht uns zwar als eine Familie ohne Grenzen, aber das sind wir nicht. Auch wenn wir in der Vergangenheit Großes erreicht haben, können wir dies nicht immer tun. Merkt euch das, meine Söhne, und wenn der Tag kommt, an dem ihr mit unserer lächerlichen Realität konfrontiert werdet, werdet ihr nicht so leiden wie ich.
>
> --- Hostus an seine 2 Söhne

In dieser schlimmen Zeit, in der Kishivs strahlende Gnade schwand, kam die Erlösung in Form ihres zweiten Sohnes Atin Curius Kishiv. Denn Atin wurde für eine Reise in die Wildnis des Grenzlandes gefunden, die noch viele Geheimnisse barg, die darauf warteten, von Eldria entdeckt zu werden. Da er außerdem der zweite Sohn war, wurden viele Aufgaben der Familie auf seinen älteren Bruder abgewälzt, so dass Atin viel Zeit für sich selbst hatte. Als er eines Abends von seiner Reise in die Berge zurückkam, schien er noch erschöpfter und ausgelaugter zu sein als sonst, und eilte mit guten Neuigkeiten zu seinem Vater. Offenbar hatte er einen Weg gefunden, mehr zu ernten, als sie jemals erhoffen konnten. Er hatte einen Weg gefunden, die Ehre und den Ruhm ihrer Familie wiederherzustellen. Am nächsten Tag wagten sich beide in Begleitung ihrer Leibwächter in die Wildnis und kehrten nach vielen Stunden zu ihrem Landsitz zurück, doch seltsamerweise fehlte dem Vater ein Auge, und trotzdem war sein anderes Auge mit etwas gefüllt, das sein älterer Sohn als einen sterbenden Mann beschrieb, der einen Winkel sah. Am nächsten Tag wurde der älteste Sohn Martin Vetious Kishiv beauftragt, nach Aerlham zu reiten und persönlich einen Brief an die Familie zu überreichen, in dem verkündet wurde, dass genug Nahrung für die Armee des Fürsten und zwei weitere bereitstehen würden. Nach vielen Monaten ritt Martin, begleitet von vielen Beamten der Armee, zurück ins Grenzland, doch irgendetwas war nicht in Ordnung. Nachdem sie die Hauptstraße, die nach "" führte, verlassen hatten, sahen sie immer mehr Moos und Straßenrand, wohin sie auch blickten. Martins Herzschlag stieg und mit ihm die Angst um seine Familie, und diese Angst war nicht unberechtigt. Als sie in Ferringstill ankamen, war keine Menschenseele zu sehen, aber es gab auch keine Anzeichen für irgendwelche Kämpfe. Jedes Gebäude war von der Flora des Grenzlandes überwuchert. Es war, als ob die Stadt seit Jahrzehnten sich selbst überlassen worden war. Die Gruppe versuchte, nach Hinweisen auf das Geschehene zu suchen, doch es war nichts zu finden. Nirgendwo war eine menschliche Spur zu finden, außer den Werkzeugen der Menschen, die auf dem Boden lagen, und den Tellern und Tassen, die auf den Tischen standen.

Bis heute ist es keinem Historiker gelungen, herauszufinden, was sich in Ferringstill wirklich zugetragen hat, und es gibt nur Theorien ohne soliden Beweis. Martin Vetious Kishiv, der einzige Überlebende der Stadt, hat jedoch sein ganzes Leben lang nach Antworten gesucht. Obwohl er keine Beweise für die Geschehnisse fand, versuchen seine Nachkommen bis heute, die Wahrheit über die verschwundene Stadt Ferringstill herauszufinden.


## Sehenswürdigkeiten

## Besonderheiten der Region

### Die Hammerer von Alt-Greifenstadt

Diese Einheiten der kaiserlichen Armee hat sich frühzeitig auf rüstungsbrechende Waffen spezialisiert, um die eldrischen Ritter effektiver zu bekämpfen. Die Hammerer von Alt-Greifenstadt 


## Notes

Lore session Notes.

Red shock battle:
•	Small battle against the empire (3 legion), were Eldria won and took over the region, but the surviving soldiers splitten up in multiple groups and after time (with the help of locals) many resistance groups were form. A surviving soldier fled the battle with banner of the 3 legion and he became the leading symbol. They were finance from the empire and Hüter Cult in secret. The plague (irae omnideus) came in 198. Afterwards they retreated back to eldria but they were ambush and it led to the red shock battle. The remaining remnants formed what is nowadays known as the 3 legion, which is officlaly recognized by the Empire. Today they are the ones, which patrol and safeguard Grenzland. Since the Rahkari part had no real tides to the Rahkari, they make their own faction. This eventually led to a civil war in Grenzland. During the war the resistance faction created the city of Arx libertas. Arx libertas was founded close to yondalla because it blocked the second route from yondalla to the empire. It led to a sign contract with the Empire and the resistance fighter, were the Empire was given Grenzland but the Resistance were made into lords with great autonomy. They were allowed to keep their soldiers in their armies and raise their own taxes. After this the importance of Arx Libertas grew weaker because it no longer held its important political reach over the empire. After time the mercenary guild was founded in Arx. Nowadays the guild can be found in every mayor town of Grenzland.
•	Battle of Qirrik hills. During the war between the two forces the spies of Eldria found out that the empire was sending the 4 legion to support the war efforts. As such they send in the army of Austen, however in reality it was the battle hardened 8 legion. The battle was tough but in the end the forces of Austen came out on top. Quote. The commander of the legion – Brakus Tertius Servarius - battled on with 7 arrows in his back and killed a lot of people before getting killed himself.
Sein Sohn Decius Primus Sevarus – der spätere Gründer von Kreuzburg – diente als Praefectus in der Armee, die die Armee der Untoten vernichten sollte um die Grenzen des Herzlandes zu schützen. 
