---
editor_options: 
  markdown: 
    wrap: sentence
---

# Die Region Oberreik

## Ortschaften der Region

### Infrastruktur

## Die Geschichte der Region

### Die Geschichte der Region vor der Kolonialisierung

Es ist nur wenig über Oberreik aus den Zeiten bekannt, bevor das Imperium versuchte die Region zu kolonisieren.
Es wird angenommen, dass die Waldelfen den Wald beherrschten, wie es überall auf der Welt üblich ist und dass die Orks ihre Hochburg einige hundert Jahre vor der Gründung der Kreuzburg errichteten.
Die Menschen entdeckten bald die Wunder des Eisenholzes, welches aus dem Zobelwald stammt.
Es dauerte jedoch viele Jahrzehnte, bis richtige Handelslinien geschaffen wurden und Produktion stattfinden konnte.
Im Jahr 209 nR wurde der General Decius Primus Servarius zusammen mit seinem jüngeren Bruder Julianos Secundos Servarius damit beauftragt, eine Garnison in der Region zu gründen, um die vielen Karawanen, die Eisenholz ins Herzland transportierten, vor Elfenüberfällen zu beschützen.

Decius war ein Mann menschlicher Rasse, der im Herzland geboren wurde.
Sein Vater war ein Soldat, der im Krieg gegen Eldria fiel.
Bald darauf trat Decius in die Fußstapfen seines Vaters und stieg schnell in den Rängen des Militärs auf.
Decius versorgte seinen jüngeren Bruder Julianos mit allem, was er brauchte.
Dieser schaffte es somit sich als Assistenz-Professor in Civis Primae durchzusetzen.
Bald nach ihrer Ankunft in der Region gründete das Duo den Außenposten Sulondos, der heute als die Stadt Kreuzburg bekannt ist.
Die Brüder waren sehr erfolgreich in ihren ersten Jahren in Oberreik.
Doch obwohl die Saat für das Wachstum gelegt worden war, hielt Decius seinen Bruder oft davon ab, ihre Operationsbasis zu erweitern.
Doch mit der Zeit entwickelte sich der kleine Außenposten zu einem kleinen Dorf und schließlich zur Stadt Kreuzburg.
Die Stadt hatte, aufgrund ihrer geographischen Lage, ein großes Potential für den Handel und es dauerte nicht lange, bis auch verschiedene Händler dies erkannten.
Trotz der Tatsache, dass Decius der Mann war, der die ganze Operation leitete, bevorzugten viele der Bürger Kreuzburgs den allseits beliebten jüngeren Bruder Julianos, da er der Grund für den Wohlstand der Stadt war.
Doch mit dem Wohlstand kam auch der Unmut.
Denn der ältere Bruder verstand sich darauf sich an seine ursprünglichen Anordnungen zu halten und nicht von ihnen abzuweichen.
Darüber hinaus war er bekannt dafür, dass er jeden diskriminierte, der nicht aus dem Imperium stammte.
Als solcher verabscheute er die Animali, die Menschen aus Ska'en und die Orks, die sich in seiner Stadt bewegten.
Irgendwann hatte Decius die Nase voll von seinem jüngeren Bruder und seinen offenen Ansichten und versuchte, ihn zur Unterwerfung zu prügeln.
Dies sollte sich als der vielleicht größte Fehler herausstellen, den er je begangen hat.
Denn dieser Angriff sollte zu seinem Untergang führen.
Julianos floh aus der Stadt und begab sich auf eine neue Reise nach Civis Primae.
Er war sich des großen Potenzials Kreuzburgs bewusst, jedoch war ihm klar, dass er dieses nie vollkommen ausschöpfen könne, solange sein Bruder den Fortschritt der Stadt aufzuhalten wusste.
Julianos fasste den Beschluss, die Zukunft der Stadt selbst in die Hand zu nehmen und seinen eigenen Bruder zu stürzen.
Als er in Civis Primae ankam, schaffte er es, eine Audienz beim Kaiser selbst zu bekommen und bald darauf erklärte er ihm die Situation um Kreuzburg.
Gemeinsam heckten die beiden einen Plan aus, die Stadt zu übernehmen.
Zwei Monate nachdem Julianos die Stadt verlassen hatte, kehrte er zurück, doch war er nicht allein.
Mit ihm war die Macht einer ganzen Legion und der berühmte General Quintis Egnatius Leddicus.
Viele Menschen würden denken, dass Decius seine Torheit aufgeben und vor der Stärke des Imperiums niederknien würde, doch war dies leider nicht der Fall.
Trotz allem blieb Decius seinen Befehlen treu und er schuf eine gut befestigte Station für sich und seine Männer.
Er hatte es sogar geschafft, einige Kanonen zu beschaffen, für den Fall, dass die Stadt angegriffen werden würde.
Doch wenn ein Mann und seine wenigen treuen Soldaten einer ganzen Legion gegenüberstehen, so fallen die Chancen auf einen Sieg obgleich sehr gering aus.
Schließlich fielen all seine Soldaten und Decius wurde in gewahrsam genommen.
Viele Historiker sagen, dass nach der Schlacht das erste wahre goldene Zeitalter der Region begann, da Julianos nun die Region anführte, ohne von seinem Bruder eingeschränkt zu werden.

## Wirtschaftliche Lage

### Die Ressourcen der Region

## Soziopolitische Lage

### Herrschaftsystem/Organisation

## Klimatische Bedingungen

### Die Flora und Fauna

#### Monster in der Region

## Gerüchte der Region

## Sehenswürdigkeiten

### Die Hauptstadt Kreuzburg

Die Hauptstadt von Oberreik ist Kreuzburg.
Sie ist der wichtigste Handelsplatz der gesamten Region, da verschiedene Wesen vieler Völker in diese Stadt kommen, um Handel zu betreiben.
Kreuzburg gilt als einer der wichtigsten Handelsplätze im Imperium, da auf dem Marktplatz viele exotische Waren zu finden sind.
Es ist nicht nur die Stadt, in die viele der Ska'en-Waren importiert und verkauft werden, sondern auch einer der weihevollen Orte, an dem Händler frische Animali-Waren in die Hände bekommen können.
Die Stadt ist darüber hinaus berühmt für ihre bekannten Tischler, die das Holz des Zobelwaldes zu den vom Imperium geschätzten Holzwaren verarbeiten.

Obwohl es selten ist, Gruppen von Animali im Imperium anzutreffen, so kann man doch Animali-Karawanen begegnen, die nach Kreuzburg ziehen, wenn man etwas Glück hat.
Auch lebt Kreuzburg von den Produkten und Arbeitskräften der Orks, die in Oberreik zu finden sind.
Diese stammen aus der Ork-Hochburg Grurdir.
Kreuzburg ist darüber hinaus einer der einzigen Orte außerhalb von Ska'en, an dem man große Ansammlungen von *"Ska'en's people" (wir haben gerade kein Wort für das Volk)* antreffen kann, da sich in Kreuzburg eine ihrer einzigen Handelszentralen befindet.
Obwohl in der Nachbarregion Nors viele Vorurteile über verschiedene Rassen herrschen, gilt Oberreik als eine der tolerantesten Regionen des Reiches.
Doch diese Einstellung war nicht schon immer so.

## Ein wertvolles Gut - das Eisenholz

Oberreik ist bekannt für sein starkes und widerstandsfähiges Holz, welches aus dem Zobelwald gewonnen wird.
Das Eisenholz ist besonders dann wichtig, wenn es um den Bau großer Gebäude geht.
Das Holz ist aber auch mit einem gewissen Prestige-Status verbunden.
Es bietet darüber hinaus auch viele andere Verwendungsmöglichkeiten, wie z.B.
in der Tischlerei, da die Produkte bei vielen Menschen in Riga und Civis Primae sehr begehrt sind.
Es wurden bis dato viele Theorien aufgestellt, um die besondere Qualität des produzierten Holzes zu erklären.
Eine davon stammt von einem der ersten menschlichen Siedler "Lucius Minicus Melissus", welche besagt, .
Einige Einheimische bevorzugen jedoch eine Theorie, die ursprünglich von den Animali des Eislandes stammt.
Diese besagt, dass das Land, auf dem der Wald steht, nach dem Kampf mit dem Animali-Gott in das Blut des Weltenwurms Aersiqus getaucht wurde.
Man glaubte, dass Aersiqus im Laufe seines Lebens Berge von Erzen verzehrt hatte.
Die verschiedenen darin enthaltenen Mineralien wurden in sein Blut aufgenommen und als der Wurm starb, gab das Blut aus seinem Körper dem Boden wundersame Eigenschaften, die so die Bäume des Zobelwaldes schufen.

## Das Zusammenleben der verschiedenen Rassen

Obwohl die Animali heute friedlich mit dem Imperium Handel betreiben, war das nicht immer so.
Die Animali waren das erste Volk, welches die Ressourcen des Waldes von Zobel erntete.
Als sie entdeckten, dass die Menschen begannen, die Bäume selbst zu ernten, griffen sie diese an.
Viele der ersten Außenposten, die von den Menschen um Zobel herum errichtet wurden, wurden von den Animali angegriffen und niedergebrannt.
Als jedoch der Kontakt zwischen den Menschen und den Animali stetig zunahm, legten viele der Animali ihre Waffen nieder und stoppten ihre Angriffe.
Die Interaktionen mit den Orks verliefen zumeist friedlich, da sie Kreuzburg mit guten und kräftigen Arbeitskräften und interessanten orkischen Waren versorgten und auch heute noch versorgen.
Dementgegen hat das Imperium, auch heute noch, viele Konflikte mit den, in der Region beheimateten, Waldelfen.

## Die Zobel-Fäule

Die Zobel-Fäule ist eine Krankheit, die die Holzfäller des Zobelwaldes befällt.
Wird ein Eisenbaum gefällt und aufgesägt, so setzt der Baum gefährliche Sporen frei.
Diese Sporen sorgen dafür, dass das Fleisch des Baumfällers juckt und mit der Zeit langsam verrottet.
Die Krankheit führt jedoch nicht dazu, dass das Abholzen von Eisenholzbäumen aufhört.
Der Handel mit diesem Gut ist sehr lukrativ.
Und wie viele Leute wissen, ist es besser krank zu sein und Geld zu haben, als Hunger zu leiden oder auf der Straße zu sterben.
Doch nicht nur Menschen, Orks und andere Waldarbeiter werden von den Sporen der Bäume befallen.
Eine vielleicht noch erschreckendere Tatsache betrifft die Monster, die den Zobelwald bewohnen.
Viele Monster, die im Wald heimisch wurden, lernten mit der Zobel-Fäule zu leben und wurden aufgrund ihrer Mutagene, die durch die Anpassung an die Krankheit entstanden, zu grotesken Wesen.

## Die Armee in Oberreik

Die Armee des Imperiums ist hauptsächlich für ihre starke Infanterie bekannt.
Doch aufgrund der Tundra-Landschaft des Oberreiks, hat sie sich für eine Armeezusammenstellung entschieden, die auf leichter Kavallerie basiert, um die landschaftlichen Gegebenheiten der Region besser auszunutzen.
