# Naphtanium

Bis vor 2 Jahrzehnten  war die Region Naphtanium noch ein Teil des Oberreiks und bildete so eine Pufferregion vor den Tundren des Eislandes. Offiziell ist der Grund für die Abspaltung dieses Teiles des Oberreiks mit Bürokratischen Gründen aufgeführt, da die befestigten Verbindungsstraßen ins Oberreik nur mehr über das Herzland laufen (seit rund 3 Jahrzehnten) Defakto gab es allerdings vor rund 3 Jahrzehnten noch eine befestigte Verbindungsstraße an den südlichen Rändern des Zobelwaldes. Diese wurde durch einen großen Murenabgang  im Jahr 394 n. R.  über etliche Kilometer zerstört. Allerdings bot der damalige Regionalkommandant des Oberreiks an diese zu reparieren, wozu es allerdings nie kam. Die Gründe hierfür sind ebenso spekulativ. Klamme Staatskassen, Angriffe von Elfen oder Gerüchte von bösartigen Wesen oder das intervenieren des Kaisers höchstselbst werden unter vorgehaltener Hand diskutiert.
Ein offizielles Schreiben wurdedie Weigerung der Straßesreperatur und daraus resultiertende Umweg über das Herzland genannt, wofür im Oberreik mindere Strafzahlungen fällig wurden.

Für das Herzland und den Moloch namens Civis Primae brachte das einen indirekten Vorteil, da das begehrte Eisenholz aus dem Zobelwald, so wie die Landwirtschaftlichen Güter dadurch günstiger, und sicherer ins Herzland geschafft werden konnten.

Als Regionalkommandant wurde in Naphtanium, welches nach der "schwarzen Stadt" Naphtanium benannt wurde, Hadranius Maximus Woranius eingesetzt, welcher seit dessen die Gebiete verwaltet und dem Kaiser treu ergeben zu sein scheint. Selbst residiert Hadranius Maximus Woranius allerdings nicht in Naphtanium sondern Lignium, wo dieser offiziell die Bürokraten des Herzlandes unterstüzt die kriminiellen Strukturen aufzubrechen.

Naphatnium selbst ist im Verhältnis zu anderen Hauptsädten der Regionen in einer geographischen isolierten Lage. Unabhängig davon sind viele dort explizit stationierte Soldaten , um laut offiziellen Positionen, diese vor Angriffen der Animali zu schützen, mit welchen allerdings vor allem Nachts, auf den Straßen Handel getrieben wird.

Die Hauptprodukte sind offiziell, Holz, Pferde, Kohle, Schwarzfett, Pech, Schwefelbergbau und Zuckerahorn und ein marginaler Landwirtschaftlicher Überschuss, da die regionale Hauptstadt Naphtanium selbst beinahe vollständig auf Nahrungslieferungen angewiesen ist.



## Ortschaften der Region 

### Naphtanium
Schwarzfett, Pech, bedeutende Alchemistenschule.

Durch die Abholzung der letzn großen Wälder nördlich von Civis-Primae wurden der Zugang hinter den Sümpfen von Lignium dort Schwarzfett (Pechschwarze Ölige Substanz zum Schmieren und verwenden von Kerzen/Ölen), Pech und Schwefel gefunden. Dies und gelgentliche Handelsbeziehungen zu Animali und einer großen Spende seitens der Kaiserlichen Armee konnte in diesen kalt-nassen Gebieten an der Grenze zu den Tundren des Nordens eine Alchemistenschule errichtet werden, welche derweil der ÖÄffentlichkeit nicht zugänglich ist und Gerüchten zu Folge an der Erforschung etlicher Alchemistischer Wunder beteiligt ist. Naphatanium ist komplett auf Nahrungslieferungen angewiesen und wird häufig als Schwarze Stadt beschrieben.

Einwohner: 67.000

### Weißstadt

Schwefelbergbau, beginnender Kupfer- und Bleibergbau

Weißstadt liegt an der äußersten Grenze der Region Naphatanium und so wie die schwarze Stadt Naphatnium selbst am Berg Eisblick.
Wurde zuerst nur als Minenstadt für den Schwefelabbau verwendet, wuchs jedoch deutlich an und ist der kleine Zwilling von Naphtanium.

Einwohner: 7.300


### Lignium

Holzbau, Pferdehaltung & Zucht, Holzhandwerk, Kohleabbau, Zuckerahorn

Einst umgeben von dichten Waldgebieten, wurde über den Aufstieg des Kaiserreiches der größte Teil abgeholzt und damit gleichzeitig der Zugang zu den Tundren des Norden gelegt. Grassierende Korruption und hohe Kriminalitätsrate.

Seit 10 Jahren durch direkt vom Kaiser beordertere Bürokraten und hochrangingen Vertretern der Ekklesia verwaltet.

Einwohner: 120.000

### Groß-Waldhack

Holzhandwerk, Holzwirtschaft, Pferdezucht, Weidetierhaltung & Phosphorminen

Abholzen des Waldes führte zur Freilegung Reichsinterner Phosphorminen. Abbau des Phosphors in den letzen Jahren stark Rückläufig.

Einwohner: 7000

### Klein-Waldhack

Holzwirtschaft, Zuckerahorn

Waldarbeitersiedlung welche Hartholz und natürlichen Zuckerahorn über Groß-Waldhack und Groß-Tantum nach Civis-Primae liefert. Hat einen militärischen Außenposten welcher vor Werwölfen, Kathakanen und Fleischsauger Angriffen schützt.

Einwohner: 2500

### Jash-Hurk

Edelsteine

Orksiedlung in der Nähe von der schwarzen Stadt Naphtanium. Orks werden für die Reihen der Kaiserlichen Armeen rekrutiert und leben ansonsten von den Tundren und der Jagd. Rituelle Wettkämpfe und fleischliche-lüsterne Orgien und gelegentliche Scharmützel mit den Animali des Eislandes machen den Großteil ihres Lebens aus. 

Einwohner: rund 8.000

### Infrastruktur



## Die Geschichte der Region

Die Region war geschichtlich an das Oberreik gebunden und war vor allem durch den massiven Holzbedarf des wachsenden Herzlandes erst bewohnbar geworden, als ansässige Elfenstämme Stück für Stück vertrieben wurden. Scharmützel mit den Elfen gehörten bis vor wenigen Jahrhunderten noch zu den täglichen Problemen, sind heute jedoch abseits der größeren Wälder keine Bedrohung für die Stabilität mehr.
Die Dienste von Cirion Demian welcher der Erste Stadthalter von Lignium war verdankt das Gebiet seinen raschen Aufstieg als "sägewerk der Menschheit". Foglich kamen auch viele begabte Handwerker aus diesem Gebiet.
Die Ansäßige Orksiedlung "Jash-Hurk" des "Jash-Hurk" Stammes steht in keinen relevanten Konflikten mit dem Kaisserreich, hat jedoch historisch lange zurückreichende Fehden mit den Animali des Eislandes.


## Wirtschaftliche Lage

Die größte Stadt Lignium kämpft mit massiver Korruption und Kriminalität. Naphatanium und Weißstadt werden derzeit von Civis Primae finanziell untersttützt. Seit der Gründung des unabhängigen Gebietes wurde noch kein allgemein Bekannter Staatshaushalt veröffentlicht. Der Wohlstand der Bevölkerung ist bestenfalls durchschnittlich.
Lediglich Naphatanium hat einen etwas höhere Lebensstandard aufgrund der Geldspenden des Kaisers und der Ansäßigen großen Alchemistenschule, welche der Öffentlichkeit nicht zugänglich ist.


### Die Ressourcen der Region

Holz, Pferde, Kohle, Schwarzfett, Pech, Schwefelbergbau und Zuckerahorn, Alkohol und ein marginaler Landwirtschaftlicher Überschuss

## Soziopolitische Lage 


### Herrschaftsystem/Organisation

Offiziell genießt es die selbe Autonomie wie Oberreik, defakto ist die Region Naphatanium abhängig von der Gunst der Herrscher in Civis Primae.
Derzeitiges rechtliches Oberhaupt: Hadranius Maximus Woranius

Die schwarze Stadt Naphatanium und Weißstadt sind rechtlich ein Sonderprotektorat des Kaisers.

Religion: Allgott-Glaube


## Klimatische Bedingungen

Kalt-feucht. Häufige Regen und Schneeschauer. Sommer Trocken

### Die Flora und Fauna



#### Monster in der Region

Werwölfe, Kathakane, seltener Höllenbrut

## Gerüchte der Region

Die Gründung und der erhalt sind nicht klar und wird als Gutdünken Kaiserlicher Gewalt ausgelegt. Dies ist ein sich bloß hartnäckig haltender, Ehrbeleidigender Dumpfsinn.



## Sehenswürdigkeiten

5 Meter Bronzestatue von Hadranius Maximus Woranius mit Augen aus 2 Opalen.
