# Wandia {#Wandia}

> "Oh Kind vergiss mir Wandia nicht, vergiss nicht unsre Schmach. Vergiss niemals wohin es führt wenn falschen folgt man nach. Vergiss nicht zu misstrauen und hol es uns zurück. Denn vom Kinde dieses Baumes gibt es immer nur ein Stück. Und wenn ihr es erhalten, gebt es niemals wieder her, denn die Menschen und die kleinen, sie verrieten uns vorher. Und wenn ihr es erhalten, gebt es niemals wieder her, denn die Menschen und die kleinen, sie verrieten uns vorher."
>
> --- Ein Schlaflied für Kinder aus Silva Nacia

Wandia ist ein Heiligtum, welches sowohl den Orks, den Elfen von Silva Nacia, den Eldrianern, als auch den Zwergen wichtig ist. 

Wandia hatte viele Rollen. Als ehemalige Hauptstadt des <font color="green">[Eldrischen Königreiches](#Eldria)</font> und der <font color="green">[Donnerwächter](#Donnerwächter)</font> war Wandia eine riesenhafte Metropole, die jede heute bekannte Stadt problemlos in den Schatten stellen würde. 
In der Glanzzeit Wandias schafften es die <font color="green">[Elfen von Silva Nacia](#SilvaNacia)</font> den bis heute einzigen Sätzling ihres heiligen Baumes dort zu pflanzen und gedeihen zu lassen. Dieses Wunder sorgt dafür dass Wandia und das wiederbeschaffen des Sätzlings eines der Hauptziele der Elfen ist - eine Mission, die bis heute unzählige Leben gekostet hat.

Wandia besteht aus oberirdischen Stadtruinen, unterteilt in viertel, die von verschiedenen Rassen stark umkämpft sind. Die wenigen Einwohner der Ruinen leben dort zum Teil unter sehr schlechten Bedingungen.
Zudem gibt es eine unterirdische Stadt, deren Gänge großteils nicht kartografiert sind, da diese zu weitreichend sind und sich die Strutkur immer wieder verändert - entweder durch das Eingreifen der kämpfenden Rassen oder durch das des <font color="green">[wahren Drachen](#WahrerDrache)</font> Nuninox.

Sowohl die Oberstadt als auch die Unterstadt werden allerdings nur zum Teil von den Rassen Orbis Aesta's beherrscht. Den Hauptteil beherrscht wohl <font color="green">[Ga'ar](#Ga'ar)</font>, denn umso weiter man in die Ruinenwüste Wandias reinkommt desto größer wird die Gefahr ihren Monstern in allen Formen und Farben zu begegnen. Verschiedene Monster halten in der Oberstadt störrisch die zentralen Viertel und vor allem den königlichen Palast des alten Eldrischen Reiches. In der Tiefstadt sind sie sogar noch weiter verbreitet.

> "Auf der Suche nach Honoria kamen wir nach Wandia, wir schlugen uns alsbald in die inneren Bereiche vor - aber es ist wie verflucht. Links und rechts verlieren wir unsere Recken an Monster und es werden immer mehr. Es wirkt fast so als würden die Monster Wandias Zentrum bewachen. In der Tiefstadt ist die Plage sogar noch größer. Wir haben sogar wandelnde Rüstungen bekämpft."
>
> --- Arien Tyssen, Eldrischer Ritter und Abenteurer

Für die Orks bekam Wandia erst eine Bedeutung als Nuninox auftauchte.

## Die Geschichte der Region

### Der Fall von Wandia

Ursprünglich was Wandia eine Siedlung, in der Menschen und Zwerge zusammenlebten - die Zwerge überwiegend im unterirdischen Teil und die Menschen im oberirdischen. Nach mehreren hundert Jahren ertragreicher Zusammenarbeit kolonialisierten die Menschen die Umgebung und errichteten Hasting, Calvert und die anderen eldrischen Fürstentümer. 
Wandia war das Herz des eldrischen Königreiches und ein Juwel der Zivilisation. Die Donnerwächter hatten dort einen sicheren Hafen und die Stadt wuchs und gedeihte und war die wohl beeindruckendste Stadt, die jemals existierte. 

Die Starke Position Wandias lockte langfristig auch die Elfen. Sie legten in der riesigen Stadt ihre eigenen Viertel an und schlossen sich so der Allianz aus den Donnerwächtern und dem Königreich Eldria an.

Im Zentrum Wandias sind der Herrschaftssitz der Donnerwächter und der königliche Palast senkrecht übereinander angeordnet. Dort wo in der Tiefstadt der zwergische Herrschaftssitz liegt, liegt auch der königliche Palast - oder heute dessen Ruinen. An genau diesem Punkt pflanzten die Elfen den Sätzling ihres heiligen Baumes, der schnell Wuchs und beide Herrschaftsitze umspannte. Ein Symbol für die Koexistenz dreier Rassen. 

> "Bis heute glauben die Elfen dass ihr Baum dort noch steht und selbst einen Sätzling trägt. Allerdings ist noch nie eine Expedition von dort zurückgekommen um die Geschichte zu bestätigen oder zu widerlegen. Dennoch sehen die Elfen fast jedes Opfer als angemessen an um an den Sätzling des Baumes zu kommen oder diesen Baum selbst zurückzuerobern.
>
> --- aus "die Chroniken von Wandia" von Wilhelmina Trayne

Die Idylle des frühen Wandia wurde Jäh unterbrochen, als der berüchtigte wahre Drache Nuninox zuschlug. 

> "Niemand weiß woher er kam, aber die geeinten Kräfte von Menschen und Zwergen zeigten sich als machtlos gegen die Kräfte des wahren Drachen. Sein Feuer ließ ganze Armeen in wenigen Minuten zu Asche werden, und vernichtete Häüser Mauern und Wehrstätten."
>
> --- Rheymos Erden, ein geflohener Wachmann Wandias

Mit Nuninox kamen auch jene Monster, die heute Wandia bevölkern. Nur wenige konnten überleben. Wen der Drache nicht einäscherte, der wurde von einem marodierendem Monster erwischt. 
Die überstürzte Flucht aus Wandia sorgte dafür, dass gerade sehr viel Zwergenmaterial - Artefakte der Donnerwächter - bis heute in Wandia verbleibt. Diese mögliche Beute sorgt dafür, dass immer wieder Glücksritter versuchen, in Wandia große Beute zu finden. Die meisten davon erliegen den Gefahren Wandias, hin und wieder schafft es jedoch jemand etwas zu finden - mit dem Verkaufswert hat man dann für gewöhnlich lebenslang ausgesorgt.

Die nächsten 400 Jahre konnte man sich Wandia durch die allgegenwärtige Gefahr des Drachen Nuninox nicht nicht nähern. Er vernichtete alles was der Stadt zu nahe kam. Diese Terrorherrschaft hielt so lange an bis es zu dem Ereigniss kam, welches als "Kampf der Kolosse" in die Geschichte einging.

### Der Kampf der Kolosse

Etwa 400 Jahre nach den Fall von Wandia kam es zum sogenannten Kampf der Kolosse. Die wenigen verbleibenden Donnerwächter hatten unermüdlich darauf hingearbeitet ihre finale Waffe - <font color="green">[ein Konstrukt der Titan Klasse](#fehlt)</font> - zu finalisieren.

> "Das Titankonstrukt wurde die letzten 300 Jahre ursprünglich für den Bürgerkrieg gebaut. Als wir Wandia verloren hatten wussten wir aber, dass es unsere beste Chance ist. Normalerweise würden 450 Jahre für ein derariges Projekt reichen, aber da wir nur noch wenige waren dauerte es erheblich länger. Doch nun ist er fertig. Heute schicken wir ihn in den Kampf einen Drachen zu vernichten!"
>
> --- Dhakri Meren, Führerin der Donnerwächter, ca 750 vor Riga

Die Zwerge starteten ihre kollosale Waffe im umkämpften Istval. Das Konstrukt marschierte umgehend nach Wandia und wurde dort erwartungsgemäß von Nuninox angegriffen. Die beiden Kollosse lieferten sich einen derart monumentalen Kampf, dass jene, die ihn beobachten konnten, noch jahrzehnte darüber Sprachen. Schlussendlich verschwanden beide in den Abgründen der Tiefstadt und es war unklar welcher der Kolosse schlussendlich obsiegte, Nuninox jedoch terrorisierte das Umland Wandias nicht mehr, weswegen fälschlicherweise von seinem Tod ausgegangen wurde. 

Kurz nach dem Kampf der Kolosse sendeten die Donnerwächter die letzte große ihrer Missionen nach Wandia - eine große Gruppe der selten gewordenen Donnerwächter - von der keiner zurückkehrte.

Heute weiß man, dass Nuninox den Kampf überlebt hat - allerdings dadurch so verletzt wurde, dass er die zentralen viertel Wandias nicht mehr verlassen kann. Er scheint nicht mehr in der Lage zu sein für lange Zeit zu fliegen, für diejenigen jedoch, die sich in seine Reichweite begeben, ist er immernoch eine der größten Gefahren die Wandia - und vielleicht ganz Orbis Astea - zu bieten hat.
Was aus dem Titan-Konstrukt geworden ist weiß niemand so genau, weder wurde ein Wrack gesichtet, noch scheint es noch aktiv in Betrieb zu sein.

## Klimatische Bedingungen

### Die Flora und Fauna

#### Monster in der Region

Das wohl größte Monster, welches in Wandia gefunden werden kann, ist ein Drache. Ein wahrer Drache, der in der unterirdischen Stadt herumfliegt und sich von den Erwachten ernährt, die durch die Kämpfe in den unterirdischen Städten entstehen, da die Leichen nicht ordnungsgemäß bestattet werden können. 
Dieser feuerspeiende Drache ist einer der wenigen bekannten und vermuteten <font color="green">[wahren Drachen](#WahrerDrache)</font>
_
## Legenden der Region

### Die Legende von Üräid der Weisen

Dieses schwer zu datierende Ereignis trug sich irgendwann zwischen 1150 und 750 v. Riga in Wandia zu. Mangels schriftlicher Überlieferungen glaubwürdiger Chronisten, gibt es seitens der Orks, der Elfen und der Zwerge drei variierende Geschichten über die Elfenmatriarchin Üräid der Weisen und ihrer gigantischen Spinne.

Üräid die Weise, herrschte über ihren Stamm an Waldelfen an den Hängen zwischen den Himmelsspitzengebirge und Wandia. Ihr Stamm umfasste mehrere zehntausend Mitglieder, mit einer ausgeprägten Gruppe des Pfades der Pfote. Orküberlieferungen zufolge sollen deren Spinnen besonders groß und schmackhaft gewesen sein. Zwergenkarawanen begehrten die Rüstungen des Stammes, da die Chitinpanzer eine hervorragende Verarbeitungsfähigkeit aufwiesen.

Die eigentliche Legende beginnt mit der Matriarchin, welche von der Expansiven Politik der Zwerge in Wandia kollidierte, da Zwerge einen Jungbaum des Saritaäs, des heiligen Elfenbaums in Silva Nacia angeblich für Brennholz abhakten. Daraufhin, wanderte Üräid die Weise mit ihrer Spinne Golmiäd, angeblich mit einer Beinspannweite von 200 Metern Richtung Wandia, um die Zwerge endlich aus Wandia zu vertreiben. Soweit, abgesehen von der Größe, ist das der unstrittige Teil der Legende.

Streitiger werden die folgenden Ereignisse. In den Zwergenerzählungen, wird erzählt, dass tausende Elfen auf Spinnen angeführt von Üräid, „der Grausamen“ Richtung Wandia um die Donnerwächter auszurotten. Dabei metzelten sich die Elfen durch Heerscharen an Zwerge und die Spinne Golmiäd riss Konstrukte einfach auseinander, oder zerbrach diese wie Äste unter ihren Beinen. Es folgte ein Gemetzel an den dadurch fast wehrlosen Zwergen. Daraufhin sollen wie aus dem nichts die Zwillinge des Abgrundes, riesige Knochenschädler, plötzlich aus den Bergen aufgetaucht sein, welche dann wiederrum die Elfenarmee einfach ausradierte und ein letzter finaler Kampf von Uräid der Weisen mit ihrer Spinne Golmiäd erfolgte. Die Zwillinge rissen die 20 Meter hohe Stahltüre des Zuganges von Wandia einfach auf und nutzten diese als Schilde, während die Fleischbrocken der Zwillinge des Abgrundes zu leben begannen und auf der Spinne Golmiäd hochkletterten oder schlichtweg drauf fielen bis Üräid die Weise, irgendwann von den Abkömmlingen der Zwillinge einfach auseinandergerissen wurde. Die Spinne wurde kurz darauf von den Zwillingen niedergerungen, woraufhin diese einfach Wandia bezogen und „alles zivilisierte Leben“ in Wandia auslöschten.
Die Geschichte der Elfen selbst, spricht zwar auch von dem Gemetzel der Waldzerstörerischen Zwerge in Wandia, erwähnt allerdings nicht, dass die Zwillinge des Abgrundes gegen Golmiäd und Üräid gekämpft hätten, sondern dass ein wahrer Drache, dem Gemetzel eines jähen Endes bereitete, indem er alles in seinem Pfad verbrannte. Die Elfen werteten dies als Gewinn, da die Flinkheit der Spinnen deutlich schwerer zu verbrennen waren. Üräid selbst verlor ihr makelloses Antlitz und verstarb kurz darauf an den Verbrennungen des Drachens. Golmiäd soll daraufhin in den Wald geflohen sein und seitdem Zwerge fressen, welche auch nur eine Hand an eine Holzfälleraxt legten.
Die Elfen sahen die Kraft des Drachens und befanden es war genug der Strafe für Zwerge und übten Rache an den Orkstämmen, welche ihre Heimat verwüsteten.

Orkgeschichten zufolge fand der Kampf zwischen Elfen und Zwergen statt, da diese stolz die Elfensiedlung plünderten und alles fleischlichen Fraßen und dort eine neue Orksiedlung errichten wollten. Daraufhin fanden Orks die Schlacht in Wandia und nahmen teil, bis nach etlichen Jahrzehnten die Lager in und um Wandia soweit zerstört waren, dass die Zwillinge des Abrgundes „vom Himmel fielen“ und daraufhin über die arte Landung so erbost waren, dass Sie die Türen des Einganges aus Wandia rissen und seitdem versuchen den Architekten von Wandia zu finden, welche hier den früheren See trockengelegt haben soll.
Der Wahre Drache kam irgendwann später, als es für Orks des Stahlknochenstammes in Wandia bereits eine Tradition hatten die Spinne Golmiäd zu jagen und Elfen zu foltern, um die Spinne zu finden. Der Drache verbrannte aber niemanden, sondern ein großes Festmahl an der Oberfläche beendete den Krieg zwischen Elfen und Zwergen.

Verbliebene des Stahlknochenstammes wurden Großteiles über die Jahrhunderte rekrutiert, zogen weg oder lebten in den Tiefen Wandias, wodurch sich die Spur hier verliert. Auch wurden keine Berichte über eine hundert Meter große Spinne mehr gefunden, wo es tatsächlich zu Verlusten an militärischen Einheiten kam.
Auch ist unklar, ob der wahre Drache noch in Wandia herrscht. Auch ist es fachlich umstritten, dass es die Zwillinge des Abgrundes je existierten.


## Sehenswürdigkeiten

