# Das Berma-Tal {#BermaTal}

> Täglich werden Kriege geführt, und es scheint, als würde der Frieden nie den Weg in das abgelegene, scheusliche und neblige Berma-Tal finden.
>
> - Heb Eorri, Expeditionsleiter der Rahkari über das Bermatal

Das Berma-Tal ist jenes Tal welches südöstlich der Dunstspitzen liegt. Es ist durch den Nebelhain, die Dunstspitzen und die Wüsten von Appothis von der restlichen zivilisierten Welt getrennt. Doch wenn man die mysteriösen Dunstspitzen oder die endlosen Wüsten von Appothis überwindet landet man nicht - wie man anhand der Landschaft vermuten könnte - im Paradies, sondern im gefährlichen Bermatal.Viele Regionen der bekannten Welt sind gefährlich und voller Geheimnisse, aber nur wenige kommen an die Region des Berma-Tals heran. Die meisten Menschen wissen, dass die Wüste der Rah Kari für den Reisenden unversöhnlich sein kann, aber der Reisende, der unvorbereitet in das Berma-Tal kommt, wird einen grausameren Tod finden. Es ist nur wenig über diese Region bekannt, da fast alle Expeditionen, die in die Region vorstießen, nie wieder gesehen wurden. 
Die wenigen, die zurückgekehrt sind, haben die Region als einen vom Krieg zerrissenes Gebiet beschrieben, das von Wilden bevölkert ist. Wilden, die sich gegenseitig gnadenlos niedermetzeln und ihre Kinder blasphemischen unbekannten Göttern opfern.

Trotz der Grausamkeit dieser Menschen gibt es mehrere Stämme in der Region, welche sich grundlegend dadurch unterscheiden welches Tier, Monster oder sonstiges Ungeheuer von den Wilden des Stammes gerade verehrt wird. Obwohl es unzählige kleinere und mittelgroße Stämme gibt, gibt es 3 Stämme die das Berma-Tal dominieren: 1, 2, und 3. und kurzbeschreibung

Das Berma-Tal wird auch als das Tal der Monster beschrieben. Die wenigen Reisenden, die dort waren und noch leben, um Geschichten über das Berma-Tal zu erzählen, beschreiben die Region als voll von Monstern und Ungeheuern - welche dort selbst noch grotesk entstellt oder mutiert sind. Geschichten zufolge beherbergt das Berma-Tal sogar Menschen, welche zu Monstern geworden sind. 

## Stämme

Reisende behaupten, dass die Stämme, die im Berma-Tal leben, ein einziges Monster oder eine Monsterart in ihrem Gebiet anbeten. Die Stammesangehörigen gehen weit über Beten, Weihungen und übliche Verehrung hinaus um ihre Götter zufrieden zu stellen. Über dunkle Rituale ist es manchen sogar möglich, die Merkmale ihrer Monstergötter selbst zu bekommen - was die ultimative Gnade dieser Götter darstellen soll. 


Diese Merkmale sind - nach Berichten von Sir Eduard von Haag - in den beobachteten Stämmen immer unterschiedlich. Sie sind davon abhängig welche Götzen oder Abscheulichkeiten vom jeweiligen Stamm als Götter verehrt werden. Zum Beispiel kann eine derartige Veränderung dazu führen, dass eine einzige Hand in eine Art Klaue geformt wird, oder das Wachsen von Flügeln und die dadurch verbundene Fähigkeit zu fliegen. Das sorgt dafür, dass Stamm A gegen Stamm B sich sehr einfach zu wehr setzen kann - da ihre körperliche Veränderung durch das Ritual der Fleischgabe eine verstärkte Haut hervorruft. Durch die Mannigfaltigkeit, so wird angenommen, ist es unmöglich, dass ein Stamm die absolut Herrschaft über das Bermatal übernimmt.

## Die Fleischgabe

Die Fleischgabe, die als eine der schrecklichsten Rituale im Berma-Tal angesehen werden kann, ist die "Tradition", durch die die Stämme ihre Göttern, Dämonen und Ungeheuern am nächsten kommen und die Merkmale und Eigenschaften eines Monsters nach und nach übernehmen.

Bei dem Ritual der Fleischgabe werden die tapfersten oder vielversprechendsten Jugendlichen für die Verschmelzung zu einem "Gro'flaak-Krieger" ausgewählt. Dann werden die Auserwählten mittels Körperteilen von Monstern und unbekannten Substanzen zu grotesken Mischungen aus Mensch und Bestie verschmolzen. Diese Gro'flaak Krieger formen häufig die Elite der Soldaten eines Stammes. 

Die Verschmelzung wird unter den Stammesangehörigen als große Ehre angesehen, da die neuen "Wesen" als Beschützer des Stammes gelten. Doch obwohl die Stämme des Berma-Tals diese Verschmelzung als große Ehre ansehen, haben Menschen aus der zivilisierten Welt beobachtet, dass diese verschmolzenen Wesen große und permanente Schmerzen und Qualen erleiden. So winden sich diese während der des Schlafes ständig oder üben selbstverletzendes Verhalten aus. Auch scheinen die Gro'flaak Krieger meist von schlechter Laune zu sein, da diese häufiger in Streits und Schlägereinen mit anderen Stammesmitgliedern sind. Ebenso werden häufig klaffende Wunden an Monstermenschen gesehen und des Nachts lässt sich häufig das Wimmern der frisch erschaffenen Gro'flaak Krieger vernehmen.
Weniger aggressiv gesonnene Stämme, geben zwar zu, dass es eine schmerzhafte Bürde sei, als Gro'flaak Krieger für den Stamm zu dienen, allerdings nichts anderess als den ganzen Tag auf einem Pferd oder in schwerer Rüstung herumzulaufen. Gro'flaak Krieger bestätigen durchaus, dass Schmerzen da sind, aber auch, dass diese nach einiger Zeit nicht mehr als schlimm wahr genommen werden.

Diese veränderten Kireger erinnern zwar noch immer an Menschen, jedoch ist es in etwa so wie mit Erwachten. Es waren oder sind Menschen, aber Sie sind "fremd". In den ersten 10-15 Jahren bewahren diese "Wesen" einige Aspekte ihrer Menschlichkeit und werden als menschliche Waffen gegen die anderen Stämme oder nicht verehrte Monster eingesetzt - in einer Rolle ähnlich zur schweren Infanterie aus Eldria. Sie sind ausgebildete Krieger, hervorragend im Kampfe und ihrem Stamm Treu ergeben. Zum  ihrem eigenen "Glück" werden die meisten Gro'flaak Krieger einige Jahre nach der Verwandlung im Kampf gegen andere Stämme oder Monster getötet. Diejenigen armen Sellen, welche die häufigen Stammeskonflikte überleben, verlieren jedoch aufgrund der andauernden Schmerzen, welche sie ertragen müssen, völlig den Verstand. 

Es wird angenommen, dass das körperliche Leiden mit der Zeit nur noch schlimmer wird. Auch verhalten sich die unveränderten Stammesmitglieder mit der Zeit immer zurückhaltend gegenüber ihnen, da sie immer weniger Mensch werden. Der Mangel an Zuneigung - das "fremde" in diesen Kriegern - welches nichteinmal eine Mutter übersehen kann, ist hier noch eine zusätzliche Belastung. Zwar werden diese Krieger zwar immer für ihre Heldentaten gefeiert, jedoch ohne den Helden selbst in der Feier zu inkludieren.

Wenig verwunderlich verlassen die meisten dieser Wesen - absichtlich oder unbewusst - ihren Stamm und ziehen in die Wildnis, um den Rest ihres Lebens als einzelgängerirsche Nomanden zu leben. Dabei verkommen diese immer mehr zu Monstern, welche alles und jeden zu töten, der ihnen über den Weg läuft. Wenig überraschend ist es in einigen Stämmen die Pflicht eines jeden „Verschmolzenen“ sich bei den ersten Anzeichen von Realitätsverlust oder Wahnsinn in einem letzten Kampf gegen echte Monster oder andere Stämme zu stürzen und diese so lange anzugreifen, bis der Stamm oder die Monster von der Erde getilgt sind.

## Die Stämme der Region 

Im Bermatal gibt es eine Unzahl an Stämmen - manche werden neu gegründet, andere lösen sich auf oder werden von größeren Stämmen geschluckt. Die meisten Stämme sind zu klein um große Bedeutung zu erlangen, manche allerdings bestehen aus mehreren Siedlungen und vielen hunderten Mitgliedern. Es gibt allerdings drei dominante Stämme, deren Mitgliederzahlen in den tausenden liegt. Alle drei haben große Einflussgebiete und viele Siedlungen und üben immense Macht aus. Sie haben affiliierte Stämme, die untereinander zum Teil Stellvertreterkriege führen oder auf eigene Art und Weise versuchen sich einen Vorteil in der schwierigen politischen Situation zu sichern. Diese drei Stämme sind die Ulugda - oft auch die braunen genannt, die Vogalta und die roten Rola-Akthir.

### Ulugda

Heb Eorri lieferte bis dato die vollständigsten Berichte über den Stamm der Ulugda, auf welchen sich nachfolgende Beschreibung bezieht.
Der Stamm der Ulugda besiedelt die östlichen Gebirgshänge der Dunstspitzen welche in das Bermatal zeigen. Den Beobachtungen des Rahkariforschers Heb Eorri zufolge, sind keine nennenswerten Gebäude der Ulugda bekannt. Ihr dasein, so scheint es, fristen die Ulugda in Höhlensystemen, welche an den Eingängen mit Bildern von einem riesigen Wurm verziert sind. Laut den Berichten von Heb Eorri sind aus den Höhlen, sofern man sich wagt diesen bis auf wenige Meter zu nähern, Schreie und Gesänge in einer unbekannten sprache zu hören. Die Vermutung liegt Nahe, dass es sich um die lokale Stammesssprache handelt.
Die Wagemutigsten Rahkari des Expeditionstrupp wagten sich in die Höhlen, wurden allerdings in den Höhlen ermordet. Am nächsten Tage konnte allerdings der - auf einer Pieke aufgespießte - Kopf eines Spähersbeim Höhleneingang vermacht werden.

Den Rahkari war es außerdem möglich 5 Gefangene zu machen. Ihre Anatomie war durchwegs normal, abgesehen von diversen Narben auf dem Körper. Diese Narben könnten die Funktion von Hautmalereien erfüllen, allerdings lässt sich dies nicht bestätigen. Bemerkenswerter ist, dass alle 5 Gefangenen nach 2 Tagen in Gefangenschaft verstarben indem diese sich des Nachts mittels Gift suizidiierten.

Was genau die Ulugda anbeten ist schwer zu beschreiben. Neben die Malerein an den Höhleneingängen, ließen sich ähnliche Zeichnungen auf dem unteren Rücken aller 5 Gefangenen nachweisen. Ob dies nun ein Wurm, eine Schlange oder ein kruder Lindwurm ist, lässt isch nicht mit Sicherheit sagen. Die Zeichnungen legen allerdings nahe, dass dieses wurmartige Wesen Schuppen aufweist, welche von den Menschen verwendet werden können. Selbige "Schuppen" ließen sich auf der Kleidung der Gefangenen nachweisen, wodurch die Vermutung nahe liegt, dass es sich um eine Schlange handeln könnte.

### Rola-Akthir

Der Stamm des Nordens - von den Einheimischen Rola-Akthir genannt - ist vielleicht der mächtigste Stamm im Berma-Tal. Es wird angenommen, das die ersten Menschen, die im Berma-Tal ankamen, sich im nördlichen Teil der Region niederließen - wo der Stamm der Rola-Akthir bis heute lebt. Sollte dies stimmen, macht das die Rola-Akthir auch zum ältesten Stamm im Berma-Tal.

Der Name "Rola-Akthir" - was auf Rahkari so viel wie „Blutrünstig“ bedeutet - wurde dem Stamm von dem bekannten Forscher und Entdecker Heb Eorr gegeben. Ihre Siedlung ist an einem dutzende Meter hohem pechschwarzem Felsbrocken zu erkennen, der fast wie ein ritueller Turm aussieht und sich in der Mitte der Siedlung befindet. Laut Heb Eorri ist dieser Stamm der "zeremoniellste" im Berma-Tal und besitzt eine Menge eigener Riten und Zeremonien, die den Alltag der Rola-Akthir stark beeinflussen.
Eines dieser Riten scheint die Jagd auf absichtlich freigelassene Gefangene zu sein. Dabei werden die Gefangenen meist komplett nackt einige Stunden "Vorsprung" gewährt. Daraufhin beginnen die von der Fleischgabe veränderten als auch die normalen Krieger mit der Jagd. Eben jene Menschenjagd mündet in der Erjagung der Geflohenen wo ihre sich noch windenden Körper zu jenem pechschwarzen Felsbrocken in der Mitte der Siedlung gelegt wird. Anschließend bereiten sich alle beteiligten Jäger ein Festmahl, wo sie sich rot anmalen oder kleiden, da Rot die Farbe der Rola.Akthir ist.

Die von der Fleischgabe veränderten Krieger dieses Stammes weisen starke Veränderungen auf. So wächst auf der Rückseite des kahlen Kopfes eine Art von Insektenauge. Die ursprünglichen Arme bleiben zwar unverändert jedoch werden zwei weitere unter den Schultern hinzugefügt, die so aussehen als würden sie aus dem Brustkorb wachsen und nicht krud angenäht sein. Diese Arme münden in Klingen, welche stark an die Klauen von großen Käfern erinnern. Oft werden ihnen rote Linien überall auf die Körper gemalt.

Die Rola-Akthir sind einer der aggressivsten Stämme im Berma-Tal und viele Stämme haben Angst vor den roten Kriegern. Sie sind bekannt dafür, ihre besten Gro'flaak-Krieger in einer Gruppe namens "Ar'Tin" zu organisieren, wo sie sich gegenseitig lehren und fördern. Den Ar'Tin zu begegnen ist eine der sichersten und schnellsten Arten im Berma-Tal zu sterben.

### Vogalta

Der erste Stamm, auf den ein Erforscher höchstwahrscheinlich stößt, ist der Vogalta-Stamm, der sich im Süden von Berma-Tal befindet und häufig in den Dunstspitzen anzutreffen ist. Dieser Stamm ist dafür bekannt, dass er sehr territorial ist. Wenn jemand es wagt, das Land des Stammes zu betreten, wird der Eindringling schnell gejagt, oft ohne Vorwarnung. Alternativ findet der Neugierige sein jähes Ende aus dem Hinterhalt, wenn ein Stammesmitglied plötzlich aus dem Gebüsch springt oder sich von den Bäumen fallen lässt. 

Die Vogalta haben die bis dato am weitesten ausgebaute Siedlung und bauen auch die großen Bäume der Region - welche angeblich aussehen wie verknorrte und sich windende Kiefern - in ihre Siedlung mit ein. Der Stamm ist auch dafür bekannt, dass das Brauen von Tränken oder Drogen von allen Mitgliedern geübt wird. Allerdings fehlt es dadurch oft an Zutaten, um etwas herzustellen, das mit den Tränken anderer Zivilisationen mithalten kann. 
Der Stamm der Vogalta betet eine Abscheulichkeit an, die als riesige Waldschlange beschrieben werden kann. Die Gelehrten der Expedition von Lord Charles von Austen, um 345 vor Riga behaupten sogar, diese Schlange gesehen zu haben, wie sie für die Vogalta Wege durch den Wald und die Berge bereitete.

> Ich pisste über die Klippe bei den Dunstspitzen und dann sah ich so n riesiges Ding in der Ferne. Grün, schlangenähnlich brach es Bäume auseinander, dahinter Zweibeinige Wesen, sollten Menschen oder Orks sein. Wäre ich nicht am Pissen gewesen hätt‘ ich mich wohl angepisst. Das grüne Dinge war locker 50 Meter lang.
>
> - John Edingson, Soldat von Lord Charles von Austen, 345 v. R.

Späher des Stammes welche getötet oder gefangen genommen werden konnten, hatten gelegentlich eine schlangenähnliche, beschuppte Haut. Diese Sonderlinge - vermutlich auch durch das Ritual der Fleischgabe entstanden - konnten ihren Körper auf unmenschliche Weise verbiegen. Sie verstecken sich oft in den Bäumen, in denen sie mit  ihrer grün-braunen Haut schwer zu sehen sind, und warten, bis sich fremde Truppen direkt unter ihnen befanden. Dann sprangen sie herunter, packten ihre Gegner, hielten sie wie eine Würgeschlange fest und bissen in den Kopf oder Schultern der Soldaten. Dank ihren Helmen und Rüstungen fiel es ihnen allerdings schwer tödliche Bisse zu setzen.

> "Diese "Wesen" allerdings in Brand zu setzen war ein Ding der Unmöglichkeit. Ich hatte gute Männer, fähig ausgebildet an der Klinge, Heiler, Bogenschützen. Alle waren entsetzt und verwundert über das, was dieses "Ding" sein konnte. Nichteinmal die Leichen brannten. In der Nacht kamen die dann wieder. Pechschwarze Neumondnächte, trotzdem fanden Sie uns und griffen an als ob Sie sehen konnten. Wir überlebten zwar mit nur wenigen Verlusten, allerdings war die Moral nach wenigen Wochen bereits so schlecht unter den Männern, dass eine tiefere Expedition in das neblige Bermatal nicht möglich schien."
>
> - Lord Charles von Austen, 345 v. R.



## Infrastruktur

Die Region des Bermatals weist keine richtige Infrastruktur, in Form von befestigten Straßen oder Flusshandelswegen auf. Es gibt zwar primitive Wege durch die Wälder und auch simple Holzgebäude innerhalb der Siedlungen der einzelnen Stämme, aber kein Stamm ist mit den anderen wirklich über gesicherte Wege verbunden worauf Wagen von Pferden gezogen werden könnten. Der Quell dieser schäbigen Infrastruktur liegt soweit Heb Eorri daran, dass die Stämme ständig Krieg gegeneinander führen. Der einzige bekannte Stamm welcher mit Steinen gepflasterte Straßen aufweist, ist der "Vogalta"-Stamm. Diese Straßen führen zu rituellen Plätzen oder den größten ihrer Unterjochten Stämme. Angeblich wurden diese Wege von einer riesigen Schlange durch den Wald getrieben. Anschließend wurde die knapp unter der Oberfläche liegende Schotterschicht freigelegt, indem die Erde und das zerstörte Gehölz abgetragen wurde. Dies würde zwar den Transport per Wagen prinzipiell ermöglichen, jedoch wurde dies im Bermatal bis jetzt nicht beobachtet.

## Die Geschichte der Region

Die Geschichte vom Berma-Tal besteht aus einer langen Sammlung von Geschichten, schwarzen Witzen und Sagen, die von verschiedenen, teils betrunkenen, Leuten, erzählt werden.
Das Berma-Tal war einst eine wohl unbewohnte Region, in der eine endlose Zahl an Monstern umherstreifte, weswegen es kaum bevölkert wurde. 

>" Kein auch nur halbwegs vernünftiger Mensch würde sich denken, in dieser mit Krankheiten, Monstern und unwegsamen Dickicht vollgestopften Nebeligen Tal ein Kind in die Welt zu setzen oder überhaupt seine Frau mitnehmen zu können. Da hat man in den Wüsten Appothis' noch bessere Chancen ein langes glückliches Leben zu führen."
>
> - Heb Eorri, über die Lebensbendingungen im ursprünglichen Bermatal

Die meisten Geschichten besagen, dass das Bermatal die Region ist, aus welcher  die Monster unserer Welt ursprünglich stammen, dies lässt sich allerdings notorisch schwer belegen. Chronisten bestätigen zwar, dass an den Rändern der Dunstspitzen seit jeher viele Monster gesichtet wurden, allerdings wird selbiges heute auch noch über den Nebelhain oder das Himmelsspitzengebirge gesagt. Da Monster allerdings, auch heute noch, schwer zu kartieren sind, bleibt die Bermatal-Monsterwiege-Theorie genau was sie ist: eine Theorie.

Die am weitesten verbreitete Meinung über die heutigen menschlichen Bewohner von Berma-Tal ist, dass diese Menschen früher einer Organisation angehörten, welche Monster jagte. Sie nannten sich die „Zamrak-Krieger" oder "Krieger von Zamrack". Diese Krieger sind eine Ansammlung von Menschen, die schon seit Hunderten von Jahren existieren und dafür bekannt sind, Monster zu jagen - vor allem jene, welche es wagen, das einfache Volk terrorisieren.

Die ersten Aufzeichnungen der zamrak-Krieger führt die Kirche von Darcy, während des Zeitalters, in welchem die organisierte Monsterjagd in Eldria für Jung und alt gang und gäbe war. Damals war es üblich, dass sich viele unausgebildete Krieger und Bauern zur Monsterjagd zusammengeschlossen haben. Diese "Masse statt Klasse" Strategie war zwar effektiv im Sinne von der Reduktion der Monster, jedoch weniger wenn man ein Reich zu verwalten hatte, in welchen plötzlich eine große Anzahl der Bauern zu Waffen griffen und sich organisierten und viele davon widerrum bei der Monsterjagd verstarben.

Da der menschliche Einfallsreichtum doch nicht immer der rohen Kraft von Dämonen und Scheusalen überlegen zu sein scheint wurde eine besser ausgebildete Gruppe benötigt. Die Zamrakkrieger wurden "geboren". Und ihre Methoden - der Austausch von Wissen, die Sonderanfertigung von Waffen, das explizite studieren der Monster über Generationen hinweg - führten zu bemerkenswerten Ergebnissen. Nicht nur, dass Eldria bedeutend sicherer wurde, sondern auch dass die Zamrakkrieger selbst immer weniger gebraucht wurden. Sie begannen, einen großen Teil ihrer politischen Allianzen zu verlieren. Ihr eingeschworenes Ziel, die Welt von Scheusalen zu befreien, und der Mangel an Käuflichkeit, schreckte hohe Relgionsvertreter und Lordschaften auf. Ressentiments wurden bewusst gestreut. Die Zamrakkrieger kümmerte dies nicht, war doch ihr Ziel nie die Politik zu beeinflussen. Die Fürstentümer hingegen, beinflussten, was diese beeinflussen konnten und wuchsen dank der kontrollierbareren Umweltbedingungen und wurden immer stärker. Bald wollten sie keine Monsterjäger mehr, die nicht unter ihrer Kontrolle standen vor allem nicht wenn diese bewaffnet, organisiert und zahlreich waren. Anfangs noch deutlich militärisch den geeinten Zamrakkriegern unterlegen, führten die stabilen Bedingungen durch den Monstermangel schließlich zu militärisch starken Fürstentümern und dazu dass den Zamrackkriegern Kost, Logie, Bezahlung oder Würdigung der Krieger verwehrt blieb. Vergrault und geächtet als Krieger, welche gegen Einhörner kämpfen, blieb den Zamrak-Kriegern keine andere Wahl, als sich einen neuen Platz zu suchen. 

Daraufhin zogen diese Krieger in die Dunstspitzen, um von dort aus verächtlich auf die Hochgeborenen in Eldria hinab zu blicken und beim Anbruch der Dämmerung - wenn die Abscheulichkeiten die Menschen erneut tyrannisieren - zurückzukehren und die Menschheit zu retten, wie es ihr Eid verlangte.

In dieser "Zeit des Umzugs" führte ein Feldherr namens Emeric Tholy die Krieger an. Tholy versprach den Kriegern, dass sie ein neues, vielversprechendes Land finden würden, wenn sie ihm durch die Wüsten und vorbei an den Gebirgsketten der Dunstspitzen folgen würden. Tholy war ein hervorragender Krieger und Anführer. Für manche zu gut. Dadurch entstanden Gerüchte, dass Tholy entweder bessessen oder verrückt war. Alternativ wird beschrieben, dass Tholy nie sein Gesicht zeigte, da sich die Menschen kein Bildnis von ihm machen sollten. Dadurch entstand das Gerücht, dass Emeric Tholy eigentlich 3 verschiedene Personen war. Dies lässt sich allerdings nicht zweifelsfrei belegen. Heutzutage ist die Einschätzung der Inqusition, dass Tholy von Ciresh, der Blutgöttin des Verrats und der Illusionen, beherrscht wurde. Sie soll Tholy und die restlichen Krieger von Zamrak absichtlich in diese Region geführt haben.

Manche Inquisitoren glauben, dass Ciresh einen Pakt mit der Blutgöttin Ga'ar schloss, um die Zamrak-Krieger aus Eldria zu holen und sie ins Berma-Tal zu bringen. Dort sollte sie die Krieger zu ihren Marionetten machen. Es ist unbekannt, was Ga'ar Ciresh für diese Aktion versprach. Einige Vertreter spekulieren, dass Ciresh freie Herrschaft über Eldria versprochen wurde, um ihre Opfer auf ihre sadistische Art und Weise zu foltern, ohne von anderen Blutgöttern gestört zu werden. Eine andere Theorie besagt, dass Ga'ar Ciresh eine Zusammenarbeit versprochen hat, bei der sie gegen den Blutgott Hartemus vorgehen würde. Dies lässt sich allerdings schwer belegen, da die Aussagen  auf den Niederschriften eines als verrückt eingestuften ehemaligen Hochinquisitors beruhen, der kurz darauf von der Inquisition selbst exektuiert wurde.

Ciresh, so die verbotene die Niederschrift namens "Der Pakt und Teufeln", hielt sich jedoch nicht an ihr Versprechen, die Krieger an Ga'ar zu übergeben. Als Spott sollten die Zamrak-Krieger verschiedene Monster "anbeten" und als Häme für den mieserablen Einfluss welchen Ga'ar auf die Menschen hat, sich auch mit diesen Monster verschmelzen. 

Es ist nicht bekannt, wie groß der Einfluss von Ciresh auf die Stammesangehörigen von Berma-Tal heute ist, aber die Stämme beten heute alle ihren eigenen Monstergötter an. Einige Leute glauben, dass Ciresh dies aus Bosheit gegenüber Ga'ar getan hat, oder schlichtweg weil es in ihrer Natur liegt.

Die Stämme der ehemaligen Zamrak-Krieger sind jetzt überall im Berma-Tal zu finden, allerdings ist dieses Erbe lang vergessen. Auch der Namen der Organisation wurde abgelegt, oder zumindest keine Stämme welche sich Zamrak nannten gefunden. 

Das macht die Niederschrift des exektutierten Hochinquistors allerdings schwer überprüfbar, so die einhellige Gelehrtenmeinung. Belegt ist nur, dass jeder Stamm darauf aus ist andere Stämme zu unterwerfen oder niederzumetzeln. Lediglich ihrem eigenen Stamm gilt den Bewohnern des Bermatals eine fanatische Treue, womit auch bleibende Paralellen schon enden. 


## Wirtschaftliche Lage

In Bermatal gibt es keine reguläre Wirtschaft, da Stämme kaum miteinander kooperieren oder Handel treiben wollen. Jeder Stamm stellt im Allgemeinen seine eigenen Güter selbst her. Wenn ein Gegenstand von einem anderen Stamm geraubt wird, kämpfen die Stammesangehörigen entweder darum oder er wird den Stammesführern als Tribut übergeben. Was danach mit dem Gegenstand geschieht, entscheidet der Anführer selbst. Bei wertvolleren Gegenstände mischen sich allerdings die jeweiligen Hauptstämme der Ulugda, Rola-Akthir oder der Vogalta ein und bestimmen was Recht ist - Macht gibt auch im Bermatal Recht.
Folglich ist auch kein Handel zwischen dem Berma-Tal und äußeren Mächten - wie Eldria oder den Rah Kari - belegt.

### Die Ressourcen der Region

Die häufigsten Ressourcen im Bermatal sind zweifelsohne Monstermaterialien und ein natürliches sehr reichhaltiges Angebot an Nahrung in Form von Früchten und Pflanzen. Monster sind überall in der Region zu finden, und obwohl jeder Stamm ein bestimmtes Monster verehrt, werden andere "Spezies" an Monstern gejagt um Material für Waffen, Kleidung oder allgemeine Gegenstände zu erhalten. Das Fleisch wird häufig, so der glaube der Stämme verzehrt um die Kraft der anderen Monster zu erhalten.
Viele der "besonderen" Waren, die die Stämme selbst herstellen, sind aus Monsterteilen gefertigt. Trinkbecher, Bögen, Kampfdrogen und Rüstungen finden ihren Ursprung in den Innerein, Sehnen, Knochen und Häuten von den Scheusalen dieser Welt.
Durch das natürlich reichhaltige Angebot an Nahrung verfügt jeder Stamm über einen großen Vorrat an eben dieser. Da ebenso oft große Monster erlegt werden, sammeln sich häufig große Mengen an Fleisch, welche die Stammesmitglieder wenig später essen. Das macht die Stämme in dieserlei Hinsicht nicht unähnlich zu den Orkstämmen der restlichen bekannten Welt. Jeder Stamm hat normalerweise einen Sammelplatz, an dem die gefundene Nahrung im Stammesgebiet gelagert und zubereitet wird um so den Verfall durch Pilze und Fäulnis vorzubeugen.

Holz selbst ist das wichtigste Baumaterial, welches die Stämme verwenden. Aufgrund des dichten Waldes, der geringen Menschendichte herrscht kein Mangel an hervorragenden Bauholz. Die Berma-Idioten, so die abschätzige Bezeichnung für Bewohner des Tals, welche der Zwerg Vrak der Reiche den Menschen dort gab, errichten keine großen Gebäude und bauen nur selten neue, so dass ihnen das Holz vermutlich nie ausgehen wird. Es wären zwar sicher im Rahmen der Möglichkeiten größere Häuser zu errichten, aber vermutlich fehlt schlichtweg der Willen dafür - schließlich ist ausreichend Nahrung vorhanden und Schutz durch die Gro'flaak Krieger gegeben. 

Die Stämme verfügen über keine komplexeren Gegenstände oder Utensilien wie Konstrukte, Wägen, Glocken, Kirchen, Navigationshilfen oder Pergament. Ob dies durch einen beschränkten Intellekt, Krieg oder andere Gründe bedingt ist lässt sich nicht klären.  Einhellig ist lediglich die Meinung, dass es gut ist, dass diese "Wilden" keinen Fuß in die Länder Eldrias oder der Rahkari setzen und auch kein Interesse an anderen Gütern  haben, welche geliefert wurden.

> "Diese Menschen sind mir Suspekt. Bitte, wer würde freiwillig ein Kilogramm Gold ablehnen nur um einen besonderen Krieger zu bekommen? Wer verzichtet auf formidablen Rahkarischnaps zu unschlagbar günstigen Preisen? Wer möchte keine Sklaven kaufen? Bitte, Rahkarische Sklavinnen mit vollem Haar und Busen lassen selbst Orks mal die ihren Vergessen. Es bestand auch keine Interesse meine Geschichten zu hören.
Lediglich die Tränke welche ich mitführte weckten Interesse, welche Sie mir unter Androhung von Gewalt entwandten. Aber 30.000 Reiks an Tränken ist für mich kein Grund mein Leben zu riskieren. Und diese Menschen von meinem Orkbattalion abschlachten zu lassen, wäre nicht meinem Reichtum entsprechend.
Edelsteine, glitzernde Dinge, Stahlrüstungen, nichts außer Drogen beigeisterte diese Wilden. Kein Wunder, dass Sie nicht aus diesem grünen Misthaufen von einem Tal herauskommen. Das Kaiserreich wird seine Schuld begleichen bevor diese Wilden als zivilisiert gelten, so primitiv sind diese."
>
> - Vrak der Reiche, 212 n. Riga aus "Memoiren des Allgeldgesegneten"

## Soziopolitische Lage 

Im Allgemeinen gibts es neben den drei dominierenden Stämmen keine Nennenswerten politischen Intrigen. Die unterschiedlichen Stämme der Menschen kontrollieren das Land, welches nicht von Monstrositäten selbst beherrscht wird. Keiner der drei großen bekannten Clans der Vogolta, Rola-Akthir oder Ugalda scheint jedoch in der Lage zu sein, den anderen in die Knie zu zwingen ohne von anderen Stämmen, oder umherstreifenden Monstergruppen vernichtet zu werden. Diese Pattsituation besteht vermutlich schon seit Hunderten von Jahren, da die Beschreibungen der wenigen Expeditionen an die Ränder des Bermatals seit Jahrhunderten davon berichten, dass es unmöglich ist, Allianzen zu schmieden oder gar Stämme dazu zu bwegen gegen ihre Stammesführung oder zumindest gegen die vorherrschenden Stämme zu agieren.


## Klimatische Bedingungen

Das Berma-Tal genießt zwar ein warmes, von dichtem Wald und ausreichend Regen geprägtes Klima, jeodhch können die Temperaturen in der Region, verbunden mit der hohen Luftfeuchte, oft unangenehm für schwer gerüstete Krieger werden. Allerdings scheint die hohe Luftfeuchte und Temperatur den menschlichen "Ureinwohnern" des Bermatals wenig zu stören. Durch den Mangel an Extremtemperaturen scheint auch das errichten von Unterkünften ein geringeres Bedürfnis zu sein. als es beispielsweise in den kalten Gebieten Nors der Fall ist. 
Wenig überraschend für den Aufmerksamen Leser dieser Niederschriften, ändert sich das Klima im Laufe des Jahres nur selten drastisch und die Region bleibt es fast immer warm und feucht.

### Die Flora und Fauna

#### Monster in der Region

Als vermeindlicher Geburtsort der Monster gilt das Berma-Tal als Heimat der Blutgöttin Ga'ar. Einige Reisende glauben, dass jedes Monster einst von diesem Ort aus in die anderen Regionen der Welt gewandert ist. Eine unbeschreibliche Anzahl und Diversität von Monstern durchstreift die Region, einige dieser Absonderlichkeiten der Natur scheinen keine auch nur annähernd ähnlichen Vetter in der restlichen Welt zu besitzen. Etliche Einzelsichtungen ergeben zwar immer wieder Gruselgeschichten für die späteren Kinder der Reisenden, aber es ermöglicht bis dato nicht auf die Lebenseigenschaften der Monster zurückzuschließen. 

Unabhängig von den zivlisierten Gelehrten des Kaiserreichs, der Rahkari oder Eldrias, kamen die Elfen in alten Legenden zu einem ähnlichen Schluss.
Die Elfenkaste der Pfote aus den Stämmen von Silva Nacia, also der Kaste der Tierzüchter der Elfen, beschreibt die Wurzeln mancher Monster hinter den Dunstspitzen. Auch wird in Überlieferungen beschrieben, dass die Elfen wie auch ihre getreuen Spinnen, früher gemeinsam an der Seite der Menschen gegen diese Abscheulichkeiten kämpften, wofür allerdings in Eldria keine Aufzeichnungen vorliegen. 
Der allgemeine Usus beschreibt - und das ist eines der wenigen Dinge, in welchen sich die Zivilisierten Völker einig sind - dass das Bermatal als Vorhof der Hölle beschrieben werden kann. Der Ort wo Monster geboren werden und wie Krankheiten in die Welt geschleudert werden. Der Ort an dem Menschen zu Monstern im übertragenenen und wortwörtlichen Sinne zu Monstern werden. 
Folglich, wie man in den Armenvierteln den Quell vieler Krankheiten findet, welche an die Hochgeborenen weitergereicht werden können, finden sich natürlicherweise in den Armenvierteln mehr Krankheiten als in den Vierteln der Hochgeborenen.


## Gerüchte der Region

### Der Hass auf die Zivilisation

Mehrere Stämme berichten davon, dass zum Ende der Zeit ein Stamm erscheinen wird, welcher eine riesige feuerspeiende Echse anbeten wird. Sie werden geküsst von der Echse, zerfallen zu Glut und brennen dann alle jene im Bermatal nieder, welche nicht des reinen Herzens für die ihrigen sind. Die Feuerspeiende Echse hatte bereits die ersten Menschen verbrannt und ihre Glutleiber
die restlichen Menschen und jede Spur von einer Zivilisation aus dem Bermatal gebrannt. Seitdem wacht die Echse darauf, dass das Bermatal frei vom scähdlichen Einfluss hinter den Bergen ist und spuckt gelegentlich Feuer im Herzen des Bermatals um die Menschen daran zu erinnern, dass Sie und die Natur eins sind.

### Vrak der Reiche

Als am längsten das Bermatal bereisender Zwerg galt Vrak der Reiche. Er soll Zentnerweise Gold mit sich geschleppt haben. Vor seiner Reise in das Bermatals habe er einen gesamten Orkstamm gekauft, ihnen gesagt, dass Sie selbst Götter werden können und den Kreislauf des gefressen und neugeschaffen werden durchbrechen können, wenn Sie die Wiege der Götter, das Bermatal, von den Monstern reinigen. Er würde ihr leitende Hand sein, nur mussten Sie ihm Folgen.
Neben knapp Tausend Orkkriegern und rund 150 Menschen machte er sich 211 n. Riga auf den Weg in das Bermatal. Dort errichtete er die Festung "Goldblick" die Mine "Des Kaiser's Tasche" und hielt einen "Park" an Monstern. Allerdings ließen sich in den wenigen Folgeexpeditionen keine Spuren von Vrak dem Reichem im Jahr 287 n. Riga mehr nachweisen.

Die letzten Briefe von Vrak kamen auf gestanzten Goldblättern nach Gent und stammen aus dem Jahr 214 n. Riga.
Vrak selbst soll irgendwann die Kontrolle über die Orks verloren haben, da er sich über deren Loyalität ihm gegenüber unsicher wurde, da die Orks nicht zufrieden damit waren eine Festung für ihn zu errichten. Einige wenige Gesandte kehrten 215 nach Riga zurück, wo sich deren Spur verlor.
Vorraussichtlich wurden die Goldbestanzten "Briefe" eingeschmolzen und verkauft. So erlag Vraks Vermächtnis nichteinmal seiner Gier, sondern der Gier der Menschen. 


## Sehenswürdigkeiten

Für Reisende empfiehlt sich, an den höchsten Gipfel der Dunstspitzen umzukehren. So interessant die Hölle sein möge, so sehr sollte man die Verdammten an diesen Orten belassen.

