---
editor_options: 
  markdown: 
    wrap: sentence
---

# (PART) Deep Lore {.unnumbered}

# Die Vorreiter

<big> Achtung hierbei handelt es sich um nicht spiel- aber verständnisrelevante Deep-Lore.
Während es für DM's sinnvoll ist sie zu verstehen kann es für spieler schlecht sein - je nach spielerlebnis.
Lesen also auf eigene "Gefahr".
</big>

> "Nicht viel ist bekannt über die Rasse, welche wir Vorläufer nennen. Außer ihre Ruinen und manche ihrer Mechanismen ist nicht viel über sie bekannt. Wir wissen, dass sie die Welt vor uns besiedelt haben und wahrscheinlich der Magie mächtig waren. Im Bunde mit bösen Göttern und mit fauler Zauberei musste ihre Welt untergehen um Platz für eine bessere, reinere Welt zu machen. So sehen wir, wie Gott wirkt und waltet, und wie das gute immer gewinnt, egal wie sehr das Böse zu strampeln versucht"
>
> --- Paniac Larren, Hohepriester von Darcy

die Vorreiter waren ein Volk, welches lange vor unserer Zeitrechnung existierte.
Aufgrund ihres enormen Fokus im Bereich Wissenschaft und Technik erschufen sie eine Gesellschaft, in der einzelne Individuen eine beinahe unendliche Fülle an Möglichkeiten hatten.
Der technologische Fortschritt machte die Vorreiter unsterblich -- so dass weder Krankheiten noch die Zeit sie vernichten konnten.
Die Gesellschaft der Vorreiter ergab sich dem Luxus -- und so wurden immer weniger Kinder geboren.
Als die Population so verkleinert war, dass es nur mehr 10000 Vorreiter gab.
Sie wurden immer unvernünftiger und in ihrem Wahn sich selbst zu verwirklichen stießen sie immer öfter aufeinander -- allerdings hatte durch die Technologische Macht der Vorreiter jedes einzelne Individuum die Macht, ganze Armeen aus Robotern oder biologischen Abominationen zu schaffen.
Ausgestattet mit dieser macht wurde aus Streit schnell ein Krieg, in den nach und nach jeder der Vorreiter hineingezogen wurde.
Obwohl die Vorreiter selbst kaum kämpften, und das großteils ihren Kreaturen und Schöpfungen überließen waren diese Kriege so riesig, dass bis heute viel von ihnen erkennbar ist.
Die meisten Monster sind Schaffungen von einer Vorreiterin namens Ga'ar, welche sie im Krieg einsetzte - die Erweckung war eine Waffe der Vorreiterin Thanif -- und Vorreiter wie Flos Maschinengott erschufen Konstrukte, die heute Staatenschiffe genannt werden.

## Das Ende der Vorreiterkriege:

Der Krieg der Vorreiter ging viele Jahre und kostete eine Menge an Leben -- viele Teile der Welt wurden zerstört und bis heute sind Zeichen oder Überbleibsel des Krieges eine enorm prägende Seite von Orbis Astea, die viel der Geschichte und Eigenheiten dieser Welt erklären.

## Das Erwachen: 

Die Erwachten in Orbis Astea werden aus den Toten aller bekannter Humanoide gebildet.
Teils ist auch die natürliche Tierwelt betroffen.
Ursache dafür ist ein gescheitertes Biowaffenexperiment von Blutgötter.
Eine Kombination eines Parasiten und eines Virus schläft inaktiv in allen Humanoiden.
Verstirbt der Betroffene Wirtorganismus, beginnt der Virus aktiv zu werden.
Dies triggert den Parasiten den Körper umzubauen.
Dabei gibt es zwei relevante unterschiedliche Ergebnisse.
Wird der Kopf des Toten zerstört, entwickelt sich aus dem sich in der Umformung und Zersetzung findenden Körpers eine veränderte Variante eines Erwachten.
Hierbei bildet sich ein Tentakel/Aalartiger Kopfbereich der Unterschiedlich weit aus dem Körper ragt.
Dieser bildet einen schwer zu treffenden sensorischen Nexus, ähnlich einem Kopf.
Es ist zwar nicht möglich von diesem mutierten Erwachten gebissen zu werden, jedoch sondert der „Kopf", also dieser kleine Bereich, der aus dem Schultern herausragt, Kontaktgifte ab. Diese vergiften Humanoiden und selbst Blutgötter. Dadurch sind diese Erwachten schwerer zu bekämpfen, da hierbei nun der gesamte Torso zerstört werden muss. Behält der Verstorbene seinen Kopf, bildet der Parasit sein sensorisches Zentrum im Kopf und kann so mit einer Enthauptung leichter beseitigt werden. Die Nahrungsversorgung der Erwachten erfolgt über symbiontische Pilze, welche sich im verrottenden Körper niederlassen. Gepaart mit stark drosselbarem Stoffwechsel des Parasiten selbst, ermöglicht es diesen extrem lange zu leben ohne tatsächlich zu „verhungern".
Das Erwachte Humanoide teilweise fressen ist der genetischen Selbstoptimierung des Parasiten geschuldet.
Hierbei verbreiten die fressenden Erwachte, also die Parasiten in humanoider Hülle, sich selbst weiter.
So werden die effektivsten Jäger kontinuierlich besser.

Das Erwachen kann verhindert oder temporär unterdrückt werden, sofern mit Riddinöl gesalbt, die Leiche verbrannt wird oder das Begraben unter Siegelsteinen erfolgt.
Letzteres behindern lediglich die neuronale und immunologische Kommunikation des Parasiten, wodurch dieser Hirntot bleibt und für Infekte weitaus anfälliger wird.
Degradieren die Bodenorganismen den Leichnahm/Parasit weit genug, erfolgt keine Auferstehung mehr.

## Die Graue Ödnis: 

Die graue Ödnis bildet das nördliche Wüstenartige Gebiet, das an die Wüsten der Rahkari's angrenzt.
Es ist geprägt von extremen Temperaturschwankungen, was es Normalsterblichen verunmöglicht lange in diesem Gebiet zu verweilen.
Diese klimatische Sonderheit ist auf Blutgötteraktivität zurückzuführen.
Dieses Ödland ist kaum von lebenden Organismen bewohnt.
Es existieren allerding mehrere „Oasen", welche von den bleichen Orks bewohnt werden. Dies sind sehr hellhäutig, sonnengeblichene Orks. Diese „Rasse" lebt durch das Wohlwollen von Blutgötter und deren Artefakte.
Ihre Gesellschaftsform ist egalitär, friedlich und nicht interventionistisch.
Sie haben also wenig Interesse sich in die Gebiete der Rahkari auszubreiten.
Zumal ihre Götter ihnen auch nicht erlauben die Graue Ödnis zu verlassen.

Den Menschen unbekannte Energiequellen:\
Einige Organismen in Orbis Astea nutzen radioaktive Mineralien, um daraus Energie abseits der Sonne zu ziehen.
Viele Pilze und insbesondere Steinwürmer verwerten diese, um sich daraus schlichtweg zu ernähren.
Diese Gänge der Steinwürmer bilden hierbei viele Erforschbare und leicht begehbare Bergstollen.
Der Fäzes der Steinwürmer ist primär sandiges Material und einfach zu verschieben/bearbeiten.
Reich an Metallen.
Toxische Stoffe enthalten.

## Die östlichen Grenzen der bekannten Welt -- die brennenden Länder:

Bereits im Bookdown in Kursiv: Östlich von Eldria und dem Grenzland und der Yondalla umgebenden Nachtberge befindet sich das den Menschen und Goblins quasi unerforschte Land.
Es wird von den Menschen als Brennenden Länder bezeichnet.
Die Bezeichnung wurde von dem östlich von Eldria und dem Grenzland liegenden Schwefelgraben, übernommen.
Seitens des Schwefelgrabens türmt sich eine wenig stabiles Plateau auf, rund 200-300 Meter über des Boden Niveaus des Schwefelgrabens.
Seitens der Goblins auf und in den Nachtbergen wurden gelegentlich Expeditionen gestartet.
Das Ergebnis war allerdings das Sterben kurz nach dem Eindringen bzw.
nach der Rückkehr, wenn die brennenden Länder kurzzeitig betreten wurden.

Von den Goblins werden Sie als das schwarze Land oder die Brennenden Ländern bezeichnet.
Expeditionen dorthin werden durch diese Legenden des Fluches seltener.
Menschen haben bis jetzt die Nachtberge aufgrund des Unwegsamen Geländes und durch Überfälle von Goblins bis jetzt nicht erfolgreich erkunden können.

Die brennenden Länder selbst sind von dem Blutgott Jiraad direkt beherrscht.
Jiraad residiert dort.
Er versucht dort seine eigene Intelligente und steuerbare Spezies zu erzeugen.
Diese amorphe Masse, welche zwar Bewusstsein aufweist jedoch ist es Jiraad bis jetzt nicht gelungen daraus nützliche Schergen gegen anderen Blutgötter, inbesondere Ga'ar, der Mutter der Monster, zu erzeugen.

Ga'ar nutzt selbst Welten und Aschwürmer und als nicht kontrollierte Spezies, Steinwürmer um die Radioaktivtät der Elemente zu verwerten, daraus Energie zu erzeugen umso den „Treibstoff" für die Würmer zu erzeugen um nach und nach die Bereiche zu „reinigen", wodurch Jiraads Möglichkeiten reduziert werden sollen.

Wurmfall ist hier das aktuelle aktive Beispiel.
Die von Menschen bewohnten Bereiche beschränken sich also folglich komplett auf diese bereinigten Bereiche.

Jiraad selbst versucht daraufhin auch Menschen für seine Zwecke zu akquirieren.
Seine Visionen, welche er in die Köpfe von Menschen pflanzt, führen dazu das manche die Schwefelgräben durchstreifen und anschließend am Plateau feststecken oder in den angrenzenden Nebelbergen oder Nachtbergen erfrieren oder gefressen werden.

Die brennenden Länder dienen seit langem als Rückzugsort des Blutgottes Jiraad.
Jiraad versucht in diesen Ländern seine eigenen Kreationen an Monster und intelligenteren Wesen zu erschaffen, um der Blutgöttin Ga'ar und deren Inkarnationen an Asch- und Weltenwürmern etwas entgegenzusetzen.
Die brennenden Länder sind hochgradig radioaktiv verstrahlt, was es für gewöhnliche Organismen unmöglich macht dort langfristig zu Überleben oder Fuß zu fassen.
Durch die höhere Mutationsrate der Organismen, welche von Jiraad selbst oder über starke Selektion ein Dasein fristen können, haben sich deutlich abstrusere Lebensformen entwickelt, welche von Menschen als grotesk oder widernatürlich empfunden werden würden.
Da Monster und Wildtiere kaum geeignet sind, um gegen Aschwürmer oder Weltenwürmer vorzugehen versuchte Jiraad seine eigenen Varianten von intelligenten Lebewesen zu erschaffen, was nur bedingt erfolgreich war.
Diese gallertartigen Organismen ohne Knochen können außerhalb ihrer besonderen Rüstungen kaum sich aufrecht fortbewegen.
Ohne diese Rüstungen kriechen diese "Zeugen Jiraads" oder "Jiraaditen" in gemächlicher Geschwindigkeit vor sich hin und ernähren sich über symbiotische Pilze von der Strahlung.
Diese Pilze geben den meisten Organismen der brennenden Länder Pechschwarze oder purpurne Farben.
Die Besonderheit dieser Zeugen Jiraads ist die Fähigkeit sich mit anderen Zeugen Jiraads zu vereinen, um so einen Abgleich des gesammelten Wissens durchzuführen.
Jiraad wollte hierbei erreichen, dass sich das Wissen um die effektivsten Bekämpfungsmethoden der Asch- und Weltenwürmer von Ga'ar so rasch durchsetzt.
Der Plan ging bedingt auf.
Zwar können so einzelne Gruppen von Zeugen Jiraads (Auch als "Zeujards" bezeichnet) den Würmern gefährlich werden.

Jedoch hat die Möglichkeit zum Wissensabgleich die Folge, dass diese galertigen Kreaturen einen eigenen Willen und eigene Pläne schmiedeten.
Andere Kreationen gingen an den chaotischen geologischen Bedingungen schnell zugrunde.
Jiraad versucht, etwas vergeblich Humanoide mit Visionen der brennenden Länder oder des Schwefelgrabens in sein Reich zu locken, wo er größeren Einfluss hätte.
Durch die Unbekanntheit der Ländereien finden allerdings nur äußerst wenige Menschen in die Schwefelgräben oder würden lange genug überleben, um von Jiraad biologisch adaptiert zu werden.

Zeujarden organisieren sich über Vereinigungfeste wo eine größere Anzahl der Zeujarden ihr gesammeltes Wissen austauschen und um Ressourcen für Rüstungen und Waffen zu organisieren.
Technisch den Menschen deutlich überlegen, aber angewiesen auf die Unterstützung ihres Erschaffers, verlassen Sie die brennenden Länder nicht.

# Was sind Blutgötter?

Blutgötter sind die letzten Überlebenden der Vorläufer.
Dies ist eine menschenartige Spezies, welche durch enormen technischen Fortschritt quasi gottgleiche Fähigkeiten erlangt, welche für die regulären Menschen nicht erklär- oder logisch verstehbar sind.
Darunter zählen beispielsweise die Fähigkeiten Visionen in den Köpfen von Humanoiden zu setzen oder Körperliche Veränderungen hervorzurufen.

Die Blutgötter und Vorläufer bekriegen sich primär gegenseitig und interagieren im Allgemeinen beiläufig mit Menschen.

## Vorläufer und Blutötter: 

Technische weit fortgeschrittene Spezies an Humanoiden, welche durch die erlangte Macht verrückt wurden.
Sie haben sich gegenseitig stark reduziert da jeder möglichst viel Kontrolle oder Macht haben wollte.
Diese Spezies an intelligenten Entwicklern und Forschern wurde durch Selbstgefälligkeit und Dekadenz nach einer Zeit verrückt.
Dies führte zu dem Verlust dieser besonderen Fähigkeiten als Spezies von Entwicklern.
Die „letzten" ihrer Art waren dadurch nicht mehr als Kinder, welche mit Waffen hantieren konnten. Ihnen war es nicht möglich hier gezielt ihre Waffen zu verbessern oder gar neue zu entwickeln, wodurch die Aktionen der „Blutgötter" von sterblichen Humanoiden zu Recht als verrückt angesehen werden können.
Die Fähigkeiten der einzelnen Blutgötter sind dementsprechend mannigfaltig, da jeder versuchte seine „erbeuteten Technologien" einzusetzen und diese zu optimieren. Es handelt sich hierbei um eine sehr breite Palette an Technologien, welche natürlich mit malevolenten Absichten zu Waffen werden können. Daraus resultierte ein unbarmherziges Gemetzel dieser einst so weisen Spezies, wodurch die Anzahl ihresgleichen auf einen kleinen Haufen zusammenschrumpfte. Die Überlebenden dieser Barbareien sind folglich weder die Besonnensten noch die Gütigsten. Dadurch wurde der gesamte Planet, auf dem die für Menschen bekannte Welt liegt, zu einem Schatten seiner selbst.

Vorläufer besitzen noch ihren physischen Körper.
Sie sind zwar imstande fast unsterblich zu sein, da ihre inneren Organe und Hirne immer wieder verjüngt werden können, leiden jedoch darunter das beim Ausbruch ihres Krieges die globale Fähigkeit zur Regernation der Haut beeinträchtigt wurde.
Dadurch spüren diese ständig Schmerzen sind aber nicht imstande diese zu stoppen oder ihre Haut selbst zu regenerieren.
Eine der weniger Regenerationsstationen befindet sich einige Meter unter der Oberfläche des Schwefelgrabens und ist dementsprechend eine „Falle" der nicht-materiellen Blutgötter. Die Vorläufer sind zwar noch immer mit für Menschen, gottgleichen Fähigkeiten ausgestattet, können aber nicht an allen Orten gleichzeitig sind, wodurch ihre Möglichkeiten im Vergleich zu den Blutgöttern beschränkt sind. Allerdings sind diese Vorläufer noch in einem lebenswerteren Zustand als ihre, vor dem Krieg, reicheren Artgenossen. Blutgötter, eben diese in der damaligen Gesellschaft reicheren Humanoiden, hingegen leben als für Menschen metaphysisches Wesen. Sie besitzen keinen regulären Körper und wandeln als gespeichertes Bewusstsein ihrer ehemaligen Körper auf der Netzwerkinfrastruktur durch die bekannte Welt von Orbis Astea. Dieser ehemalige materielle Reichtum dieser Kinder der genialen Entwickler und die Jahrhunderte lange Boshaftigkeit untereinander führen zu paranoiden Verhaltensmustern, Verfolgungswahn und massiv erratischem Verhalten. Es wäre den Blutgöttern selbst zwar möglich reale Körper zu bewohnen, jedoch ist es nicht mehr ihr ursprünglicher. Dadurch verschwimmt für diese Götter das Gefühl der Echtheit und Realität -- eine Konsequenz daraus, wenn die Vorstellungskraft gleichauf mit der Realität ist.

In diesem Krieg wurden als Waffen und Werkzeuge, oder Sklaven, die bekannten humanoiden Rassen der Zwerge, Menschen, Elfen, Orks, Halblinge erschaffen.

### Nach dem Krieg zwischen den Blutgöttern: 

Saarth Valar, Erschaffer der Zwerge, sammelte die Überlebenden ihres Krieges ein und wollte daraus eine neue, bessere, friedlichere Welt erschaffen.
Dafür konnte er mithilfe der Blutgöttin der Illusionen, Ciresh, die Göttin der Monster, Ga'ar, dem kalten Blutgott, Hartemus, und einigen anderen eine Vision erarbeiten, um diese neue Welt zu erschaffen.
Um die stark radioaktiv verseuchte Welt wieder einfacher nutzbar zu machen, bat Saarth Valar Ga'ar darum Monster zu erschaffen welche diese radioaktiven Stoffe verwerten können.
Daraus ließe sich ein Ökosystem erschaffen welche den Blutgöttern erlauben würde, gefahrlos in eine physische Gestalt zu wechseln.
Ga'ar konnte tatsächlich dann selbst reproduzierende Wesen erschaffen, welche diese Aufgabe vollbringen konnten.
Diese Monster sind als Steinwürmer, Aschwürmer und Weltenwürmer bekannt.
Darauf aufbauend etablierten sich tausende Arten, welche ebenfalls in der Lage waren diese Energiequellen zu nutzen.
Hartemus lieferte die Schlagkraft seiner Waffen und Truppen, um Saarth Valar das Umsetzen dieser Pläne zu ermöglichen, ohne dass die anderen Blutgötter ihn aufhalten konnten.

Thanif, die Göttin der Erwachten, also die Erschafferin der Parasiten, welche alle Humanoiden befällt, war allerdings mit der Machtfülle dieser Allianz unzufrieden und fürchtete ihre „Waffen", die Erwachten zu verlieren, sobald es zu einem Frieden kommen würde. Sie konnte gemeinsam mit Ciresh die restlichen Blutgötter vereinen und Sie motivieren Saarth Valar zu hintergehen. Jiraad, der brennende Blutgott, hielt ohnehin bereits wenig von Saarth Valars Ideen, waren Jiraad'S Kreationen doch dazu in der Lage in dieser strahlenden Welt zu leben. Er schloss sich dem Umsturzversuch an.

H'abunaptra, der Berg in der Wüste der Rahkari, stellte das vermutlich bedeutendste verbliebene Kraftwerk der Vorläufer und Blutgötter dar.
Saarth Valar residierte mit seiner Aufmerksamkeit primär dort.
Während der Zeit der Entwicklung der Monster Ga'ars vor Ort im H'abunaptra war Hartemus mit seinen Waffen vor Ort.
In der Phase wo sich Saarth Valar komplett diesem alten Kraftwerk widmen wollte, um es zu verstehen und auszubauen, merkte Ciresh dass ein Funken Misstrauen gegenüber Saarth Valar noch da war.
Sie störte die Verbindung.
Saarth Valar verlor dadurch während des Übertragungsprozesses den Zugang zu den meisten seiner Fähigkeiten.
Hartemus versucht daraufhin Rache an Ciresh zu nehmen.
Was zu einem neuerlichen Konflikt zwischen den Blutgöttern führte Der Umsturzversuch war daraufhin im engeren Sinne erfolgreich.
Saarth Valars Möglichkeiten sich zu realisieren oder von dem Netzwerk aus der Realität zu formen wurde daraufhin massiv geschwächt.
Hartemus erleidete, als Vollstrecker Saarth Valars ebenso herbe Verluste.
Er konnte mit den geistigen Fähigkeiten der vereinten anderen Blutgöttern nicht mithalten und endete als einer der schwächsten Blutgötter.\
Saarth Valars Übertragung auf das Kraftwerk ermöglichte ihm aber die Fähigkeiten der anderen Blutgötter zu beschneiden, schlichtweg indem er die Energiezufuhr zu den Übertragungsnetzwerken drosselte.

Asb'cartes, ein Vorläufer, wollte die Schlüssel, welche in gewissen Humanoiden angelegt sind nutzen um das Kraftwerk im H'abunaptra zu drosseln umso den Einfluss seiner reicheren und verrückteren Verwandten zu beschränken.
Ciresh wollte allerdings von Asb'cartes genau das gegenteilige.
Asb'cartes war mit der Aufgabe betraut worden die Schlüssel zusammenzutragen und einzusetzen, um das Kraftwerk im H'abunaptra auf höchster Stufe laufen zu lassen.
Asb'cartes, mit seinem Rest an Vernunft, merkte aber schlussendlich, dass mehr Macht noch nie ein Problem der Blutgötter löste und beschloss die Schlüssel zu zerstören.
Er konnte einen Schlüssel zerstören, bevor Ciresh und die anderen Schlüssel ihn von seiner physischen Form „befreiten" und in das Reich der Leere überführte, da Ciresh Verrat nicht duldete und die Schlüssel selbst über einiges an Macht verfügten.

## Ga'ar's leibliche Kinder -- die größten Abscheulichkeiten: 

Für gewöhnlich behält Ga'ar eine gewisse Kontrolle über ihre erschaffenen Kreationen.
So sind die Monster der Klasse der Höllenbrut zumindest mit den Allgemeinen Wünsche Ga'ars vertraut und können gelegentlich auch noch direkt auf Befehle reagieren.\
Ga'ar leibliche Kinder selbst sind hier allerdings zu groß und eigenständig als das Ga'ar diese noch kontrollieren könnte.
Zu komplex wurde deren Verstand und Organismus als das die Einflussmöglichkeiten Ga'ars ausreichen würden.

### Der Erdverschlinger -- das Monster unter dem Vulkan: 

Gigantische Monstrosität unter dem Vulkan der Zwerge im nördlichen Himmelsspitzengebirge.
Die Zwerge wurden von Saarth Valaar erschaffen, um dieses Monster in Schach zu halten bzw.
die Mechanismen, welche das Monster im Zaum halten zu warten.
Der Erdverschlinger nutzt die oberflächlichen Magmavorkommen, um daraus Energie zu gewinnen.
Gleichzeitig verhindert dies auch größere Eruptionen des Vulkans.
Die Donnerwächter sind die Verbleibende Gruppe an Zwergen, welche noch grob um diese Aufgabe weiß.

### Der Tiefenherrscher und Alptraum der See - Leviathan: 

Ein gigantisches Seemonster welches von dem Staatenschiff Sirkali gejagt wird, das schwächste Kind Ga'ars.

## Knochenschädler: 

Die Knochenschädler sind im engeren Sinne kein einzelnes Monster, sondern sind, im Ursprung zwar ein leibliches Kind Ga'ars, können sich aber aus sich selbst heraus reproduzieren.
Dadurch ist es für Ga'ar unmöglich diese zu kontrollieren.
Die Knochenschädler untereinander sehen sich eher als Familie.
Sie können untereinander kommunizieren, haben gemeinsame Wertvorstellungen und reproduzieren sich asexuell aus sich selbst heraus.
Sie zeichnen sich durch eine Mischung aus Tentakel, grauen Panzerplatten, endloses Wachstum und einer Abneigung gegen Orks und Elfen aus.
Knochenschädler sind im eigentlichen Sinne reinlich und fürchten das Überspringen von Krankheiten von Humanoiden auf die Ihren.
Insbesondere Orks und Elfen, welche noch „natürliche" Krankheiten mit sich schleppen. Knochenschädler sondern auf ihren Hautschichten Schleim ab, welcher dazu dient Krankheiten fernzuhalten. Zum Wohle der Gruppe werden daher immer wieder Infizierte verstoßen. Überleben diese und finden diese Genug Nahrung kann daraus ein neuer eigener Stamm an Knochenschädlern entstehen. Mit der Zeit evolvierten sich hier neue Merkmale, wie weitere Arme, Farbänderung oder andere Riten, Sprachen und Gebräuche. Die Parasiten, welche alle Humanoiden Befallen und das Erwachen verursachen, führen bei Übertragung auf Knochenschädlern zu einem jämmerlichen und lang andauernden Zugrunde gehen. Diese infizierten und Todgeweihten Knochenschädler ziehen herum und töten Menschen, Erwachte und sonstige mit Parasiten infizierte Säugetiere, um so dem Ursprungsstamm zu dienen.

Da Knochenschädler im eigentlichen Sinne nicht altern, ist der Tod selbst ein umso erschreckenderes Beispiel und umso schmerzlicher, wenn ein Familien- oder Stammesmitglied nach 400 Jahren enger Bindung von einem zweibeinigen schreienden Wurm ein grausames Martyrum nach sich zieht.

## Jagd auf den Weltenwurm:

## Zamrak -- Gott der Animali:
