---
editor_options: 
  markdown: 
    wrap: sentence
---

# Wer willst du sein?

In Orbis Aestea bietet eine Vielzahl von möglichen Geschichten, Charakteren und Möglichkeiten an.
Die wichtigste Frage für die Erstellung eines Charakters ist "Worauf hast du Lust?"

## Die Charakter Creation

Als erstes ist es wichtig ungefähr eine Ahnung zu haben was und wen man spielen will.
Obwohl sich das vollständige Bild eines Charakters erst am Schluss der Erstellung ergibt ist es dennoch wichtig, dass man weiß wohin man will und was einem Spaß macht.

Oben im Download-Menü liegt ein Vorlage-File, mit dem die Character-Creation in Excel gut und Schnell vorgenommen werden kann.
Das "Status"-Blatt ist besonders wichtig, da es einen schnellen Überblick verleiht und man die größten Teile jeder Session nur über das Status-Blatt Spielen kann.
Hier bitte die Attribute und Skills nicht direkt verändern, sie müssen im Arbeitsblatt "Character Sheet" angepasst werden und werden dann mit Referenzen automatisch in Status aktualisisert.
Das ganze Sheet arbeitet allgemein viel mit Referenzen, daher gut darauf aufpassen was man überschreibt, aber die Logik dahinter wird man schnell verstehen.
Das Sheet ist für einen Beispielcharakter aufgebaut, seine Werte und sein Inventar ist natürlich nach und nach mit den eigenen zu ersetzen.

Auch wichtig ist zu wissen welchen Defensivskill man verwenden will, <font color="green">[Blocken oder Ausweichen](#BlockenAusweichen)</font>, da diese Skillgruppe für Abenteurer unabhängig von der Spielweise eine der wichtigsten ist.

### Rasse und Startwerte

Als erstes wählt man die Rasse aus, die man Spielen möchte, am wichtigsten hierbei ist, dass verschiedene Rassen verschiednene Werte und Attribute haben mit denen man arbeiten kann.
Des weiteren haben manche Rassen gewisse Fähigkeiten - wie zum Beispiel die THermosicht der Goblins - die große Vorteile mit sich bringen können.

mit diesen Base-Stats fängt man an:

<small> <small>

+----------------------+------------+------------+-------------------------------------+-------------+-------------------------+--------------+--------------+-------------------------+
| Wert                 | Mensch     | Waldelf    | Zwerg                               | Ork         | Animalus                | Goblin       | Stadtelf     | Halbling                |
+:====================:+:==========:+:==========:+:===================================:+:===========:+:=======================:+:============:+:============:+:=======================:+
| Strength             | 10         | 8          | 10                                  | 13          | 12                      | 7            | 8            | 7                       |
+----------------------+------------+------------+-------------------------------------+-------------+-------------------------+--------------+--------------+-------------------------+
| Agility              | 10         | 13         | 8                                   | 10          | 12                      | 12           | 13           | 10                      |
+----------------------+------------+------------+-------------------------------------+-------------+-------------------------+--------------+--------------+-------------------------+
| Charisma             | 10         | 11         | 8                                   | 6           | 8                       | 9            | 12           | 13                      |
+----------------------+------------+------------+-------------------------------------+-------------+-------------------------+--------------+--------------+-------------------------+
| Physical             | 10         | 9          | 10                                  | 12          | 11                      | 8            | 9            | 9                       |
+----------------------+------------+------------+-------------------------------------+-------------+-------------------------+--------------+--------------+-------------------------+
| Intelligence         | 10         | 10         | 14                                  | 8           | 9                       | 10           | 10           | 10                      |
+----------------------+------------+------------+-------------------------------------+-------------+-------------------------+--------------+--------------+-------------------------+
| Instinct             | 10         | 12         | 10                                  | 10          | 10                      | 10           | 11           | 10                      |
+----------------------+------------+------------+-------------------------------------+-------------+-------------------------+--------------+--------------+-------------------------+
| Luck                 | 5          | 4          | 4                                   | 6           | 4                       | 7            | 4            | 6                       |
+----------------------+------------+------------+-------------------------------------+-------------+-------------------------+--------------+--------------+-------------------------+
| Glaube               | 5          | 5          | 5                                   | 5           | 5                       | 5            | 5            | 5                       |
+----------------------+------------+------------+-------------------------------------+-------------+-------------------------+--------------+--------------+-------------------------+
| Health               | 200        | 150        | 200                                 | 250         | 250                     | 150          | 150          | 150                     |
+----------------------+------------+------------+-------------------------------------+-------------+-------------------------+--------------+--------------+-------------------------+
| Ausdauer             | 12         | 15         | 9                                   | 12          | 13                      | 14           | 15           | 10                      |
+----------------------+------------+------------+-------------------------------------+-------------+-------------------------+--------------+--------------+-------------------------+
| Startgeld            | 30000      | 28500      | 66000                               | 21000       | 24000                   | 30000        | 25500        | 36000                   |
+----------------------+------------+------------+-------------------------------------+-------------+-------------------------+--------------+--------------+-------------------------+
| Rassenfähigkeiten    |            | Nachtsicht | Geldgeil                            | Kurzsichtig | Mutation                | Thermo-sicht | Nachtsicht   | Unverdächtig            |
+----------------------+------------+------------+-------------------------------------+-------------+-------------------------+--------------+--------------+-------------------------+
| Freie Skillpunkte    | 150        | 150        | 150                                 | 150         | 150                     | 150          | 150          | 180                     |
+----------------------+------------+------------+-------------------------------------+-------------+-------------------------+--------------+--------------+-------------------------+
| Freie Attributpunkte | 25         | 20         | 15                                  | 17          | 17                      | 20           | 20           | 20                      |
+----------------------+------------+------------+-------------------------------------+-------------+-------------------------+--------------+--------------+-------------------------+
| Sprachen             | Herkunft 8 | Elfisch 8  | Zwergisch 8 Rah Kari 5 Kaiserlich 4 | Orkisch 6   | Beastmen 8 Kaiserlich 3 | Gob 8        | Kaiserlich 8 | Kaiserlich 8 Halbling 8 |
+----------------------+------------+------------+-------------------------------------+-------------+-------------------------+--------------+--------------+-------------------------+

</small> </small>

#### Rassenfähigkeiten {.unnumbered}

-   Nachtsicht: Elfen können im Dunklen sehen.
-   Gier nach Reichtum: Zwerge bekommen bei Intimidation-Proben +3 Instinct wenn es um Geld geht.
-   Kurzsichtig: Die Kurzsichtigkeit von Orks macht es ihnen unmöglich Fernkampfwaffen zu verwenden
-   Thermo-sicht: Goblins sehen die Wärmestruktur von Körpern. Normalerweise ist dies ein riesenhafter Vorteil, da sie sowohl im Dunklen als auch durch Wände Bedrohungen ausmachen können. Manche gefährliche Monster haben aber keine Wärmesignatur
-   Unverdächtig: Halblinge werden aufgrund ihres unauffälligen Verhaltens und ihrer Erscheinung meistens nicht verdächtigt gesetzeswidrig gehandelt zu haben.
-   Mutation: Die Mutation ist verbunden mit dem <font color="green">[Übergangsritual der Animali](#Mutation)</font> sie übernehmen physiologische Marker des ersten Monsters, das sie erjagt haben. Davon abhängig ob der Charakter ein Jungtier oder bereits mutiert ist steht die Mutation noch aus, oder er hat mehrere individuelle Perks und schwächen, die zur erjagten Beute passen. Im Falle eines Jungtiers wird die Mutation noch ausgespielt.

### Level und Skillverbesserungen

Folgende Punkte gibt es bei Level-ups oder Character-Creation zu vergeben:

-   Attributpunkte - hiermit verbessert man Attribute, die Health und die Ausdauer
-   Skillpunkte - hiermit verbessert man Skills

Um die Skills und Attribute zu verbessern muss eine gewisse Menge an Attribut- und Skillpunkten vergeben werden.
Höhere Werte kosten Verhältnissmäßig mehr.
Jeder Wert kann Zurückentwickelt werden, bringt aber nur einen Skill/Attributpunkt pro Stufe.
Wichtig ist allerdings, dass sowohl Luck als auch Glaube nicht aufgewertet werden können.

Bei einem Level up bekommt man:

-   vier Attributpunkte
-   Skillpunkte abhängig von der Intelligenz des Charakters nach folgenden Schema:

| Intelligenz | Skillpunkte |
|:-----------:|:-----------:|
|      6      |     14      |
|      7      |     15      |
|      8      |     15      |
|      9      |     16      |
|     10      |     16      |
|     11      |     16      |
|     12      |     17      |
|     13      |     17      |
|     14      |     17      |
|     15      |     18      |
|     16      |     18      |
|     17      |     18      |
|     18      |     19      |
|     19      |     19      |
|     20      |     20      |

Bei der Character-Creation sind Attribute schon mit den Kosten nach dem untenstehenden Schema zu bezahlen.
Skillpunkte können - im Gegensatz dazu - bei der Creation einfach addiert werden und müssen erst bei Level-ups nach dem unten stehenden Schema bezahlt werden.

Sowohl Attribut- als auch Skillpunkte verfallen nicht wenn man im Level aufsteigt, man kann also für spätere Stufen "sparen".
Des weiteren kann man einen Attributpunkt einmal pro Level up zu zwei Skillpunkten umwandeln - dies gehr nicht in die andere Richtung.

Achrung bei der Charakter Creation dürfen Attribute maximal 15 betragen, Skills maximal 45.

#### Kosten Attributverbesserung {.unnumbered}

| Attributes | Kosten/einheit |
|:----------:|:--------------:|
|    0-10    |       1        |
|   10-12    |       2        |
|   12-14    |       4        |
|   14-16    |       6        |
|   16-18    |       8        |
|   18-20    |       10       |

#### Kosten Health-verbesserung {.unnumbered}

| Health  | Kosten/25 einheiten |
|:-------:|:-------------------:|
| 150-200 |         0,5         |
| 200-300 |          1          |
| 300-400 |          2          |
| 400-500 |          4          |
| 500-600 |          6          |
| 600-700 |          8          |

Achtung: Gesundheit wird immer in 25er Chunks erhöht.

#### Kosten Ausdauerverbesserung {.unnumbered}

| Ausdauer | Kosten/einheit |
|:--------:|:--------------:|
|   0-10   |       1        |
|  10-12   |       2        |
|  12-14   |       3        |
|  14-16   |       4        |
|  16-18   |       5        |
|  18-20   |       6        |

#### Kosten Skillverbesserung {.unnumbered}

| Skills | Kosten/einheit |
|:------:|:--------------:|
| 0 -20  |       1        |
| 20-40  |       2        |
| 40-60  |       4        |
| 60-80  |       6        |
| 80-100 |       8        |

## Wissen und Sprachen {#Wissensskills}

Die Welt von Orbis Astea ist gekennzeichnet von Komplexität.
Hierbei haben, so wie in der realen Welt, einzelne Menschen nicht das gesammelte Wissen der Welt.
Besonders schlaue und erfahrene Charaktere haben natürlich auch den einen weiteren geistigen Horizont um mehr ihrer Umwelt zu verstehen.

Um bei der Erstellung eines Charakters auch die Fähigkeiten im Bereich "Wissen der Welt" und Sprachen zu berücksichtigen wird diese durch die Startattribute Intelligenz und Instinkt errechnet.

Die Anzahl verfügbarer Punkte errechnet sich folgendermaßen:

$$Intelligenz \cdot 4 + Instinkt$$

**Beispiel Berechnung der Wissens- und Sprachpunkte:**

Standardmensch: 10 Intelligenz & 10 Instinkt

Berechnung der Verfügbaren Punkte: $10 \cdot 4 + 10 = 50$

Folglich hat der Ersteller dieses Charakters 50 Punkte zur Verfügung.

Diese können nun für Wissens- und/oder Sprachenstufen vergeben werden.

+--------------------------------------------+----------------+----------------------------------+--------------------------------------------+
| Niveau/Stufe der Sprache oder des Wissens: | Kosten Punkte: | Wissensniveau                    | Sprachniveau                               |
+:==========================================:+:==============:+:================================:+:==========================================:+
| Stufe 0                                    | 0              | Kein Wissen im Bereich           | Keine Sprachfähigkeit                      |
+--------------------------------------------+----------------+----------------------------------+--------------------------------------------+
| Stufe 1                                    | 5              | Grundwissen                      | sehr einfache Gespräche möglich            |
+--------------------------------------------+----------------+----------------------------------+--------------------------------------------+
| Stufe 2                                    | 15             | Belesen & Erfahren im Fachgebiet | Verständigung umständlich aber vollständig |
+--------------------------------------------+----------------+----------------------------------+--------------------------------------------+
| Stufe 3                                    | 25             | Ausgewiesener Fachmensch         | Gesetzestext- und Muttersprachenniveau     |
+--------------------------------------------+----------------+----------------------------------+--------------------------------------------+

Diese Werte sind absolute - keine kummulativen Kosten.\

+----------------------------------+----------------------------------------------------------------------------------------------------+
| Auswahloptionen an Wissenskills: | Beschreibung                                                                                       |
+==================================+====================================================================================================+
| Kriegstaktiken                   | Flankierungmanöver, Guerillakrieg, Sabotage, Formationen im Kampf                                  |
+----------------------------------+----------------------------------------------------------------------------------------------------+
| Medizin                          | Erkennen und Behandlen von Krankheiten                                                             |
+----------------------------------+----------------------------------------------------------------------------------------------------+
| Belebte Welt                     | Wissen über die natürliche Tier- und Pflanzenwelt                                                  |
+----------------------------------+----------------------------------------------------------------------------------------------------+
| Religion                         | Riten, Bräuche, Traditionen etc.                                                                   |
+----------------------------------+----------------------------------------------------------------------------------------------------+
| Monster                          | Schwächen und Stärken der Monster und Abscheulichkeiten                                            |
+----------------------------------+----------------------------------------------------------------------------------------------------+
| Geschichte                       | Wissen über wie sich der rote Faden der Ereignisse, vermeintlich durch die Welt zieht              |
+----------------------------------+----------------------------------------------------------------------------------------------------+
| Etiquette                        | Der soziale Kitt jeder Gesellschaft - Gesten, Bräuche, Traditionen                                 |
+----------------------------------+----------------------------------------------------------------------------------------------------+
| Landwirtschaft                   | Unterjochung der Natur um dieser Nahrung oder Materialien abzugewinnen                             |
+----------------------------------+----------------------------------------------------------------------------------------------------+
| Wirtschaft                       | Wissen wer was braucht und wie man soetwas bereitstellt                                            |
+----------------------------------+----------------------------------------------------------------------------------------------------+
| Recht                            | Hilft dem Spieler den Mächtigen in Orbis Astea (nicht) auf die Füße zu treten.                     |
+----------------------------------+----------------------------------------------------------------------------------------------------+
| Schwarzmarkt                     | Elfengesichter, Drogen und Sprengmittel bekommt man nur wenn man Jemanden kennt der Jemanden kennt |
+----------------------------------+----------------------------------------------------------------------------------------------------+
| Seekunde                         | Leben auf dem offenen Meer ist erst möglich wenn man die See kennt                                 |
+----------------------------------+----------------------------------------------------------------------------------------------------+
| Kartografie                      | Wissen wo was ist und wer wo sein könnte                                                           |
+----------------------------------+----------------------------------------------------------------------------------------------------+
| Schriftlehre                     | Stufe 1: Lesen/Schreiben möglich                                                                   |
|                                  |                                                                                                    |
|                                  | Stufe 2: Lesen komplexer Literatur                                                                 |
|                                  |                                                                                                    |
|                                  | Stufe 3: Ermöglicht das Fälschen von Dokumenten                                                    |
+----------------------------------+----------------------------------------------------------------------------------------------------+

| Auswahloptionen Sprachen:                     |
|-----------------------------------------------|
| Gob (Sprache der Goblins)                     |
| Orkisch                                       |
| Kaiserlich (Kaiserreich, Yondalla und Eldria) |
| Rahkari                                       |
| Zwergisch                                     |
| Elfisch                                       |

**Beispiel mit einem normalen Charakter mit 50 Punkten:**

-   15 Punkte für die Sprache Rahkari auf Stufe 2
-   15 Punkte für Medizin auf Stufe 2
-   5 Punkte für Kartographie Stufe 1 der Gebiete der Rahkari Fraktion
-   15 Punkte für Religionskenntnisse Stufe 2 der Gebiete der Rahkari Fraktion

Wichtig ist es für DMs die Skills mit eigenem Gefühl einzubringen was realistisch ist.


Auch nach der Character-Creation kann man seine Wissensskills verbessern. Dies geht über das <font color="green">[sogenannte Studieren](#Studieren)</font>.

### Kontakte

Kontakte sind ein weiteres Stück der Welt - sozusagen das soziale Kapital des Spielers.
Sie helfen an Aufträge, Informationen und andere Dinge zu kommen, für die Vitamin B nun mal nützlich ist oder sein könnte.
Die Punkte, die man für Kontakte vergeben kann berechnen sich aus der Summe: $$(4 \cdot Charisma) + Instinct.$$

Diese Punkte können dann auf die Affection, die ein Kontakt gegenüber eines Charakter empfindet, und die Power, also den sozialen Stand und Einfluss, eines Kontaktes verteilt werden.

Die Kosten beschreiben, wie viele Punkte ein Spieler ausgeben muss, um sich einen Kontakt eintragen zu können.
Diese stellen die Summe der jeweiligen Stufen dar.
Möchte man eine Liebesbeziehung zu einer Person aus dem Hochadel führen, so sind insgesamt 60 Punkte zu entrichten.
30 für die Stufe 7 Power und nochmal 30 Punkte für die Stufe 7 Affection.

Beide Parameter können auf einer Skala von jeweils 1 - 10 vergeben werden.
Die inhaltliche Bedeutung der jeweiligen Skalen-Stufe zeigt die nachfolgende Tabelle:

+-------+-----------------------------------------------------+------------------------+--------+
| Stufe | Power                                               | Affection              | Kosten |
+:=====:+:===================================================:+:======================:+:======:+
| 1     | Unterschicht                                        | Bekanntschaft          | 2      |
+-------+-----------------------------------------------------+------------------------+--------+
| 2     | Normale Person                                      | Gute Bekanntschaft     | 4      |
+-------+-----------------------------------------------------+------------------------+--------+
| 3     | Sozial gut vernetzte Person                         | Kollegen               | 7      |
+-------+-----------------------------------------------------+------------------------+--------+
| 4     | Stadtwache                                          | Gleicher Freundeskreis | 10     |
+-------+-----------------------------------------------------+------------------------+--------+
| 5     | Hohes Bürgertum                                     | Freunde                | 15     |
+-------+-----------------------------------------------------+------------------------+--------+
| 6     | Niederer Adel                                       | Familienmitglied       | 20     |
+-------+-----------------------------------------------------+------------------------+--------+
| 7     | Adel/Militärkommandant/Unterweltboss/Hoher Beamter  | Enge Freunde           | 25     |
+-------+-----------------------------------------------------+------------------------+--------+
| 8     | Hochadel                                            | Liebesbeziehung        | 30     |
+-------+-----------------------------------------------------+------------------------+--------+
| 9     | Höchste Beamte/Minister/Heerführer                  | Beste Freunde          | 40     |
+-------+-----------------------------------------------------+------------------------+--------+
| 10    | Kaiser/Hohepriester/Fürst eines Staatenschiffs/etc. | Wie das eigene Kind    | 45     |
+-------+-----------------------------------------------------+------------------------+--------+

: Kontakte und was sie ausmacht.

## Der Bewegungsradius {#BewRadius}

Der Bewegungsradius stellt die Strecke dar, die ein Charakter in einer Runde zurücklegen kann.
Sie berechnet sich durch den Agility-Wert durch 2 abgerundet.
So kann sich eine normal agile Person 5 Meter pro Runde bewegen.
Mit Reittieren kann dieser Wert natürlich deutlich höher sein.

## Das Inventar

Das Inventar ist der kummulierte Besitz eines jeden Abenteurer, seine Habseligkeiten und seine wichtigen Gegenstände sind gut aufgeführt.
Ein richtig geführtes Inventar ist Grundlage für ein schnelles und reibungslos ablaufendes Spiel.

### Rucksack

Alle Gegenstände, die nicht sofort verfügbar sind, sind im Rucksack.
Ein durchschnittlich starker Mensch (Stärke 10) kann dabei 40kg tragen.
Prinzipiell nimmt man den Durchschnitt aus Stärke und Physical mal 4 um die Traglast zu determinieren.
Diese wird als Rucksackgröße benutzt.

Ein Objekt während einem Kampf aus dem Rucksack holen kostet die Main Action, sollte man sich allerdings nicht im Kampf/unter Zeitdruck befinden kann man problemlos Objekte aus dem Rucksack rauskramen.

### Holster

Da man Waffen in gefährlichen Settings schnell zur Hand haben will - und diese nicht erstmal ewig aus dem Rucksack kramen will wurden Holster erfunden.
Diese Kosten pro Holster bei der Erstellung eines Charakters 1250 Reiks und man kann maximal 5 davon haben.
In verschiedene Holster passen nur bestimmte Waffentypen.
Mehr dazu <font color="green">[hier](#Holster1)</font>.

### Tranktasche

Auch Tränke will man im Kampf schnellstmöglich verfügbar haben.
Dafür wurde die Tranktasche entwickelt.
Für viele Soldaten und Abenteurer ist die Tranktasche nicht wegzudenken - Bomben, Power ups und Heilungen einfach mit einer single Action zu verwenden ist auch ein gutes Argument, denn genau dies erlaubt die Tranktasche.

Es gibt Tranktaschen mit verschiedenen Mengen an Slots:

| Tranktasche | Preis | Slots |
|:-----------:|:-----:|:-----:|
|    Klein    | 2500  |   2   |
|   Normal    | 15000 |   4   |
|    Groß     | 45000 |   6   |

## Ausrüstung

Nach der Charakter-Creation ist die richtige Startausrüstung von Bedeutung.
Was ein Abenteurer unbedingt haben sollte ist eine Waffe, eine Tranktasche und möglicherweise Rüstung, da ohne eine solche die Überlebenschancen deutlich kleiner werden.

Ausrüstung zum kaufen findet ihr hier:

-   Hier findet ihr <font color="green">[Waffen](#Waffen)</font>
-   Hier findet ihr <font color="green">[Rüstung](#Rüstung)</font>
-   Hier findet ihr <font color="green">[Reittiere](#Mounts)</font>
-   Hier findet ihr <font color="green">[Übrige Gegenstände](#AndereGegenstände)</font>
-   Hier findet ihr <font color="green">[Tränke](#Tränke)</font>

Denkt beim Einkaufen aber daran, dass es sinnvoll sein kann sich etwas Geld überzuhalten.
Schließlich bringt das Leben in Orbis Aestea <font color="green">[Lebenshaltungskosten](#Lebenshaltungskosten)</font> mit sich, und auch für Quests ist es immer sinnvoll etwas Geld übrig zu haben.

## Die Rolle des Gewichts

Gewicht Spielt natürlich eine Große Rolle - kein Charakter kann mehr mit sich tragen als seine eigene Tragfähigkeit.
Diese berechnet sich anhand der Stärke mal vier.

### Das Aktive Gewicht {#AktivesGewicht}

Das Aktive Gewicht ist das Gewicht der Dinge, die am Körper getragen werden.
Das besteht aus:

-   Waffen in Holstern
-   Rüstung
-   Schild
-   Wurfwaffen in Holstern

Die Summe des Gewichts dieser Items ist das Aktive Gewicht.
Es wird durch 5 geteilt und danach vom Physical-Wert abgezogen um die <font color="green">[Ausdauerwürfel für den Ausdauersave](#Ausdauersave)</font> zu erhalten.

#### Die Belastungsstufen und ihre Debuffs {#Belastungsstufe}

| Belastung      | Aktives Gewicht | Schleichen | Acrobatics <br>und running |  Aufstehen  |     Reisen     |
|----------------|:---------------:|:----------:|:--------------------------:|:-----------:|:--------------:|
| leicht Beladen |  Gewicht \< 18  |     --     |             --             |     --      |       --       |
| mittel Beladen |  Gewicht \< 30  |  -2 Dice   |          -1 Dice           |     --      | -1 Phy / Länge |
| Schwer Beladen |  Gewicht \> 30  |  -3 Dice   |          -2 Dice           | main Action | -1 Phy / Länge |

### Das passive Gewicht

Das Passive Gewicht ist die Summe des Gewichts der Items die sich im Rucksack befinden.
Zusammen mit dem Aktiven Gewicht darf es die Traglast nicht überschreiten.
Ansonsten gibt es keine spezielle Relevanz

#### Zusätzliches Gewicht {.unnumbered}

Manchmal trägt der Spieler zusätzliches Gewicht - bspw.
eine ohnmächtige Person.
Dies kann mit verchiedenen Nachteilen kommen, welche der DM festlegt.
Ein Beispiel ist die Unfähigkeit auszuweichen oder zu rennen.

## Wo nachschauen?

## Im Spiel

Einige Werte verändern sich dynamisch im Spiel.
Die wichtigen sind hier aufgeführt und erklärt.

### Modifikatoren

Bestimmte Effekte (Tränke, Musik, Kälte, etc.) geben positive oder negative modifikatoren, die nicht wie externe Effekte (Schlechte Sicht) die Thresholds beeinflussen, sondern die Werte eines Characters ändern.
Sie sind mit + oder - in der Spalte "Modifyer" rechts vom jeweiligen Skill einzutragen.

### Glaube

> "Wenn man die Götter erzürnt richten sie einen, wenn man ihnen huldigt belohnen sie einen"
>
> --- Altes Sprichwort

Glaube ist an sich kein Allein fungierendes Attribut, da Proben so gut wie immer zusammen mit Glück geworfen werden.
Das besondere am Glauben ist allerdings dass man ihn mit verschiedenen Aktionen beeinflussen kann.
Wenn man sich im Einklang zu den eigenen Göttern verhält, Epische Taten vollbringt, oder eine aandere Aktion macht bei der der DM denkt man hätte es verdient, steigt der Glaube-Wert.
Bei gegenteiligem Verhalten sinkt der Glaube wert.
Dieser Wert stellt für der DM eine Möglichkeit dar gutes Roleplay zu belohnen.

Dieser Wert soll die Göttliche Gunst in entscheidenden Situationen darstellen.

### Glück

Ebenso wie bei Glaube kann auch das Glück sinken und steigen.
Wenn ein Charakter beispielsweise Aktionen bringt die gegen seine eigenen Werte gehen, sinkt der Glückswert durch Ansage des DM's.
Bei Aktionen auf die ein Charakter besonders Stolz sein kann steigt dieser wieder.
Die stärke von Senkung/Steigung liegt am DM.

Dieser Wert soll das persönliche Wachstum und Wohlbefinden wiederspiegeln.

### Sanity

Sanity bezeichnet die Rate, in der der Charakter noch Zurechnungsfähig ist.
Sie geht vom Maximalwert 100 bis zum Wert Null.
Sanity sinkt jedes Mal, wenn man mit Blutgöttern in Kontakt kommt, Blutgöttern dient oder eine Blutgottwaffe verwendet.
Solange die Sanity über 20 ist gibt es noch nichts zu befürchten.
Sinkt die Sanity unter 20, hat der DM einmal pro Session die Möglichkeit einen Glück/Glaube-Save zu machen und - falls dieser gefailt wird - übernimmt der DM kurzzeitig die Kontrolle über die Figur, die daraufhin Wahrscheinlich horrende Taten vollbringt.
Sinkt die Sanity unter 10, hat der DM zwei mal pro Session die Chance auf die Übername des Charakters.
Sollte die Sanity allerdings auf Null sinken, verliert der Spieler dauerhaft die Rolle über den Charakter - und der Charakter fällt langfristig dem blutigen Treiben eines <font color="green">[bösen Gottes](#Blutkult)</font> anheim.

Bei Interaktionen entscheidet der DM um wie viel die Sanity sinkt.

#### Verfluchte Artefakte

Es gibt ein paar sehr starke Artefakte (allesamt Tier 5), die ihren starken Effekt damit "bezahlen lassen" das man bei jeder Verwendung Sanity verliert.
Dies sind meistens Blutkultrelikte und können von Waffen über Amulette mit gewissen Wirkungen alles sein was einem fähigen DM einfällt.

### Lagern und Ruhen

Es gibt immer die Möglichkeit eine Pause einzulegen und ein Lager aufzuschlagen.
Dabei Regenerieren sich Leben und Ausdauer zum Teil.
Pro Nacht stellt man 5 Punkte Ausdauer wieder her, oder 100 Punkte leben.
Allerdings stellt ein Lager auch ein gutes Ziel für mögliche Gegner dar.

### Längerfristige Verletzungen

Achtung, hier wird entgegen der Konventionen von Orbis Astera ab- statt aufgerundet.

#### Verstümmelung {.unnumbered}

Eine Verstümmelung bedeutet, dass von einem Körperteil nur noch 20% der Gesundheit übrig ist.
In diesem Falle ist es ratsam so schnell wie möglich Ärztliche Hilfe aufzusuchen, um eine Verkrüppelung zu vermeiden.
Der Verstümmelte bekommt einen Attribut-Debuff von 50% auf alle Checks die den verstümmelten Körperteil beinhalten.
Außerdem muss er einen Willpower-Save bestehen, ansonsten fällt er in <font color="green">[Ohnmacht](#Ohnmacht)</font>.

Ein Charakter der einen Survival-Wert von 50 oder höher aufweist kann einen Verband machen, der vorübergehend den "verkrüppelt" Status-Debuff auf 20% verringert.
Dies kann der Charakter auch selbst machen wenn sein Survival hoch genug ist und er den Check um nciht in Ohnmacht zu fallen überstanden hat.
Der Threshold liegt bei 5.

#### Verkrüppelung {.unnumbered}

Eine Verkrüppelung bedeutet, dass die Gesundheit eines Körperteils auf Null gesunken ist.
Damit verliert der Charakter den besagten Körperteil.
Er ist nicht mehr in der Lage Checks auszuführen, die diesen Körperteil beinhalten und muss unbedingt zu einem Arzt.
Die langzeitfolgen einer Verkrüppelung sind nicht zu unterschätzen und viele Abenteurer müssen sich zur Ruhe setzen, wenn ihnen eine Verkrüppelung widerfährt.

Bei einer Verkrüppelung muss ein Charakter einen Willpower-Save bestehen, ansonsten fällt er in <font color="green">[Ohnmacht](#Ohnmacht)</font>.
Der Threshold liegt bei 8.

### Ohnmacht und Tod {#Ohnmacht}

Wenn man in Ohnmacht fällt hat man zwei Optionen - entweder man wartet drei Stunden, oder man bekommt ein <font color="green">[Epinephrinika](#Epinephrin)</font>.

Es gibt mehrere Methoden in Ohnmacht zu fallen, die Wichtigsten sind:

-   Missglückter Toxi-Save
-   Narkotika
-   Health auf Null und bestandener Luck - Save
-   Die Ausdauer erreicht den Wert Null und man hat einen missglückten Ausdauer-Save
-   Willpower-Save bei Verstümmelung oder Verkrüppelung nicht geschafft.

Sterben kann man im Gegenzug dazu nur auf zwei weisen:

-   der Luck-Save wenn man keine Health mehr hat missglückt
-   Man verliert seine Health im Ohnmächtigen Zustand
