# Die Vorreiter

<big> Achtung hierbei handelt es sich um nicht spiel- aber verständnisrelevante Deep-Lore. Während es für DM's sinnvoll ist sie zu verstehen kann es für spieler schlecht sein - je nach spielerlebnis. Lesen also auf eigene "Gefahr". </big>

die Vorreiter waren ein Volk, welches lange vor unserer Zeitrechnung existierte. Aufgrund ihres enormen Fokus im Bereich Wissenschaft und Technik erschufen sie eine Gesellschaft, in der einzelne Individuen eine beinahe unendliche Fülle an Möglichkeiten hatten. Der technologische Fortschritt machte die Vorreiter unsterblich – so dass weder Krankheiten noch die Zeit sie vernichten konnten. Die Gesellschaft der Vorreiter ergab sich dem Luxus – und so wurden immer weniger Kinder geboren. Als die Population so verkleinert war, dass es nur mehr 10000 Vorreiter gab. Sie wurden immer unvernünftiger und in ihrem Wahn sich selbst zu verwirklichen stießen sie immer öfter aufeinander – allerdings hatte durch die Technologische Macht der Vorreiter jedes einzelne Individuum die Macht, ganze Armeen aus Robotern oder biologischen Abominationen zu schaffen.  Ausgestattet mit dieser macht wurde aus Streit schnell ein Krieg, in den nach und nach jeder der Vorreiter hineingezogen wurde. Obwohl die Vorreiter selbst kaum kämpften, und das großteils ihren Kreaturen und Schöpfungen überließen waren diese Kriege so riesig, dass bis heute viel von ihnen erkennbar ist. Die meisten Monster sind Schaffungen von einer Vorreiterin namens Ga’ar, welche sie im Krieg einsetzte - die Erweckung war eine Waffe der Vorreiterin Thanif – und Vorreiter wie Flos Maschinengott erschufen Konstrukte, die heute Staatenschiffe genannt werden.


## Das Ende der Vorreiterkriege

Der Krieg der Vorreiter ging viele Jahre und kostete eine Menge an Leben – viele Teile der Welt wurden zerstört und bis heute sind Zeichen oder Überbleibsel des Krieges eine enorm prägende Seite von Orbis Astea, die viel der Geschichte und Eigenheiten dieser Welt erklären.
